### ISSUE TITLE
Google job store does not validate name prefix

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#1011]
Google imposes naming restrictions on bucket names see 
[https://cloud.google.com/storage/docs/naming#requirements](https://cloud.google.com/storage/docs/naming#requirements)

As it stands the Google job store does not prevent the name prefix in the job store ~~string~~ locator from causing bucket names to violate these restrictions as is the case with name prefixes in the  Azure and AWS job stores and their respective component name restrictions.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-86)
┆Issue Number: TOIL-86

**Comment by hannes-ucsc** [comment]
I don't think I actually addressed this. Reopening.

**Comment by DailyDreaming** [comment]
No longer applicable.  The Google job store is completely different now.
