### ISSUE TITLE
Declare IDs as `Any` in API docstrings

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1018]
… so we can change our mind about their type in the future.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-87)
┆Issue Number: TOIL-87

**Comment by cket** [comment]
@hannes-ucsc just to clarify, this is so we could do something like make job store ID an object?

**Comment by hannes-ucsc** [comment]
Yes.
