### ISSUE TITLE
writeGlobalFileStream should return FileID object with .size

### ISSUE THREAD

**Issue by arkal** [DataBiosphere/toil#1020]
Issue #1014 woks on adding attributes to the return value of writeGlobalFile. This issue concerns setting up the same for writeGlobalFileStream.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-106)
┆Issue Number: TOIL-106

**Comment by adamnovak** [comment]
This is causing me problems now. The documentation claims that writeGlobalFileStream gives the file ID of the file being written, but really it just gives an str. Even when passing it along to successor jobs, it's still not a file ID with a size member, as the documentation suggests it should be. So it's possible to get files in your file store with undeterminable sizes, which in turn interferes with jobs that process files and make sure to reserve the right amount of disk to process the files they are dealing with.
