### ISSUE TITLE
Error when running example: AttributeError: 'module' object has no attribute '__file__'

### ISSUE THREAD

**Issue by vsoch** [DataBiosphere/toil#1026]
I'm testing toil on python 2.7.6, and it bugs out after this line:

```
  from toil.job import Job

  def helloWorld(message, memory="2G", cores=2, disk="3G"):
      return "Hello, world!, here's a message: %s" % message

  j = Job.wrapFn(helloWorld, "woot")
```

Error seems to be getting the **file** attribute from the module:

```
  >>> j = Job.wrapFn(helloWorld, "woot")
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/vanessa/.local/lib/python2.7/site-packages/toil/job.py", line 280, in wrapFn
     return FunctionWrappingJob(fn, *args, **kwargs)
     File "/home/vanessa/.local/lib/python2.7/site-packages/toil/job.py", line 2678, in __init__
     self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
     File "/home/vanessa/.local/lib/python2.7/site-packages/toil/resource.py", line 363, in forModule
     filePath = os.path.abspath(module.__file__)
     AttributeError: 'module' object has no attribute '__file__'
```

This is toil toil-3.2.1, python 2.7.6, on ubuntu. It produces the same error whether I do a local install with --user, or install to system with sudo. Is the example up to date with the current version?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-88)
┆Issue Number: TOIL-88

**Comment by vsoch** [comment]
oh, is it expecting my example job to be the file/module? I'm running this interactively.

**Comment by vsoch** [comment]
yep, just worked when I ran it as a script :)

**Comment by vsoch** [comment]
Is there any way to run a workflow dynamically, without needing a Class defined in a file?

**Comment by jvivian** [comment]
> yep, just worked when I ran it as a script :)

The "Hello World" step asks you to put it in a file, but we should probably explicitly state the reason for that.

> Is there any way to run a workflow dynamically, without needing a Class defined in a file?

Could you expand a bit on your question?  All jobs have to be defined, either as a class or as a function (I usually just define them as functions).  The dynamic element of Toil comes into play when creating the graph that represents the workflow — You can either explicitly lay out which jobs follow what other jobs, or you can use conditionals / loops to run jobs only under certain conditions and N number of times.  

An example of dynamicism in the Toil source code would be the [sort](https://github.com/BD2KGenomics/toil/blob/master/src/toil/test/sort/sort.py), which performs the splitting function an indeterminate number of times based on the input.

We also have a repository (under heavy development) that contains workflows written in Toil for genomic analysis: https://github.com/BD2KGenomics/toil-scripts .  Most of these pipelines take advantage of both static and dynamic job declaration.

**Comment by vsoch** [comment]
As a user testing this out, my first instinct was to define the HelloWorld class in an interactive session (as you would imagine, copy pasting the code into an open terminal) and then run the `Job.wrapFn` also in the same console.

I am happy to close this issue, as the use case I described above is likely not very common, and I'll likely be using TOIL for command line running tools (for example. integration with SLURM would be amazing to add!). Right now I'm trying to figure out if there are tools for generating data structures (eg json or yaml) to hold a workflow, period. I found a bunch of [good examples](https://github.com/common-workflow-language/workflows/tree/master/workflows) but it seems like these are made manually, and [tools](https://github.com/common-workflow-language/workflows/tree/master/tools) can also be made manually for specific software, but I can't seem to find anything that would make it easy for a researcher to say "hey, here is my analysis in a container, it has some script I want to run, and takes some inputs and outputs, make a data structure to define that (and then easily add it to a workflow!)" Do you know of anyone working on this problem?

Once the data structure is down to turn some analysis into a simple data structure to be used by TOIL, then it will be possible to dig into tools for that (which is the TOIL specialty!) :_)

**Comment by fnothaft** [comment]
@jvivian instead of documenting that Toil can't run in an interactive session (a la #1027), I think it'd be better to _make_ Toil usable in an interactive terminal. Anecdotally, Spark's gotten a ton of mileage out of being able to use Spark in a REPL --> while it was originally just a nifty feature, it's become a huge selling point for people who are running ad hoc analyses, or who are prototyping.

Also, I wager that @vsoch is far from the last person who will have this instinct:

> As a user testing this out, my first instinct was to define the HelloWorld class in an interactive session (as you would imagine, copy pasting the code into an open terminal) and then run the `Job.wrapFn` also in the same console.
>
> I am happy to close this issue, as the use case I described above is likely not very common

I disagree that it is likely not very common ;), but that's a question that is open to debate.

As an aside, RE:

> Right now I'm trying to figure out if there are tools for generating data structures (eg json or yaml) to hold a workflow, period. I found a bunch of good examples but it seems like these are made manually, and tools can also be made manually for specific software, but I can't seem to find anything that would make it easy for a researcher to say "hey, here is my analysis in a container, it has some script I want to run, and takes some inputs and outputs, make a data structure to define that (and then easily add it to a workflow!)" Do you know of anyone working on this problem?

Just so I understand the use case a bit better, are you looking for the ability to generate a data structure from a command line invocation of a tool --> e.g., the script is contained in a docker container and I want to generate YAML/JSON that could be used to template out the `docker run` command that would actually run the container? I'm a bit fuzzy about your use case, but I might know someone who is working on that. If you could expand upon your use case, then I'll check with them.

**Comment by jvivian** [comment]
> As a user testing this out, my first instinct was to define the HelloWorld class in an interactive session

I think that's only natural, so please don't close this ticket so we can reference it in #1027 . 

> for example. integration with SLURM would be amazing to add!)

That's actually a work in progress: https://github.com/BD2KGenomics/toil/tree/issues/682-slurm-rebased-twice

**Comment by hannes-ucsc** [comment]
This ticket should be about either improving the error message and 

People are using Toil with SLURM. I would call support `beta` quality.

**Comment by vsoch** [comment]
Thanks for this helpful response! I'm working with [singularity](http://singularity.lbl.gov/#home) containers, which have something called a run script (that can be added to a container) so that when you call the container as an executable, eg:

      ./mycontainer input1 input2

it essentially runs the script specified as the run script. The step I'm on now is making it easy to capture acceptable inputs and outputs for the run script. This is a hard problem, because obviously it could be anything! However, in this case I think it's best to start simple, and assume that we have a single command (with some number of arguments) to get the container running. I was first looking at the common workflow language, but actually [wdl](https://github.com/broadinstitute/wdl) is much more intuitive to work with, as it converts a simple syntax into an abstract syntax tree, meaning this:

      wdl_code = """
      task my_task {
        File file
        command {
          ./helloworld.sh --input=${file} > results
       }
       output {
          File results = "results"
        }
      }

      workflow my_wf {
        call my_task
      }
      """

turns into this! Whala, syntax tree!

![image](https://cloud.githubusercontent.com/assets/814322/16470854/94efad9a-3e0d-11e6-989d-f65bbc79b472.png)

It looks like TOIL can easily run WDL workflows (about to test this), so I'm leaning toward using WDL. Which leads to my current question - do you know of anyone that is thinking of ways to programatically generate the WDL specifications? If not, I am going to try to come up with something simple. A programmatic solution would be ideal, but it's not too crazy an idea to have a user generate a container, and then have a small interface that pops up to select a file for the runscript, and then specify the inputs and outputs. The variables needed for a container (eg, inputs and outputs and running parameters) would then be stored with the container, and the wdl strings generated dynamically in a web tool to create workflows from some set of containers.

@jvivian this is fantastic! :D I will not close the ticket.

**Comment by hannes-ucsc** [comment]
Check out #602 and #552.

**Comment by cket** [comment]
Related #1352, built-in methods and interactively defined methods should be treated as 'belongsToToil'

**Comment by DailyDreaming** [comment]
We no longer run python2.7.

**Comment by vsoch** [comment]
lol! Well when I opened this issue in *2016* you most definitely did :) Thanks for the err, speedy response?
