### ISSUE TITLE
Docs: Explain why users can't use interactive session

### ISSUE THREAD

**Issue by jvivian** [DataBiosphere/toil#1027]
New users are likely to try Toil in an interactive session (#1026), and we need to explain why Toil needs to be executed as a user script before they try our "HelloWorld" example.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-89)
┆Issue Number: TOIL-89

**Comment by arkal** [comment]
+1

**Comment by jvivian** [comment]
Or alternatively, expand support to run in interactive sessions as @fnothaft mentions in #1026

**Comment by OliverEvans96** [comment]
Why is it that toil must be executed from a script?

**Comment by jessebrennan** [comment]
@OliverEvans96 because otherwise it throws an error! But honestly I don't think there is a good reason. I'm looking into a fix currently. I'll keep you posted with any results.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
