### ISSUE TITLE
Implement resume() and initialize() correctly in Google job store

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1049]
initialize() and resume() make up the new, deconvoluted job store creation protocol. In #1040, I've implemented it for File, AWS and Azure but deferred the Google implementation for later.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-91)
┆Issue Number: TOIL-91

**Comment by DailyDreaming** [comment]
Stale, closing.  The Google job store is also completely different now.
