### ISSUE TITLE
Clean should be more judicious

### ISSUE THREAD

**Issue by fnothaft** [DataBiosphere/toil#1059]
Opening this "on behalf of a friend". Right now, `toil clean <jobStore>` calls the `JobStore.destroy()` method, which seems to do a [`rm -rf`](https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/fileJobStore.py#L79) indiscriminately on the directory passed to it. I presume that there is some structure to a job store; I haven't looked at the job store underbelly too much. If so, it'd be great to just delete the job store structure itself, lest someone do something silly like put a job store in the root of their workflow development repository, and then run clean on that job store. That would be unfortunate.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-92)
┆Issue Number: TOIL-92

**Comment by hannes-ucsc** [comment]
Makes sense.

**Comment by hannes-ucsc** [comment]
For max robustness we could touch a `.toil` file right after `mkdir`-ing the job store directory.

**Comment by fnothaft** [comment]
Perhaps you could put it all in a `.toil` directory or something, so then you could just `rm -rf .toil`.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
