### ISSUE TITLE
Higher-order job functions fail if their arguments are defined in __main__

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1062]
http://jenkins.cgcloud.info/job/toil-scripts/418/testReport/junit/src.toil_scripts.rnaseq_cgl.test.test_rnaseq_cgl/RNASeqCGLTest/test_with_manifest/

is a build for this change

``` diff
diff --git a/src/toil_scripts/rnaseq_cgl/test/test_rnaseq_cgl.py b/src/toil_scripts/rnaseq_cgl/test/test_rnaseq_cgl.py
index a3e1271..1734377 100644
--- a/src/toil_scripts/rnaseq_cgl/test/test_rnaseq_cgl.py
+++ b/src/toil_scripts/rnaseq_cgl/test/test_rnaseq_cgl.py
@@ -7,6 +7,8 @@ from unittest import TestCase
 from urlparse import urlparse
 from uuid import uuid4

+import sys
+
 import os
 import posixpath
 from boto.s3.connection import S3Connection, Bucket
@@ -27,7 +29,9 @@ class RNASeqCGLTest(TestCase):
         self.output_dir = urlparse('s3://cgl-driver-projects/test/ci/%s' % uuid4())
         self.sample = urlparse(self.input_dir.geturl() + '/chr6_sample.tar.gz')
         self.workdir = get_work_directory()
-        self.base_command = ['toil-rnaseq', 'run',
+        self.base_command = [sys.executable,
+                             '-m', 'toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline',
+                             'run',
                              '--config', self._generate_config(),
                              os.path.join(self.workdir, 'jobstore'),
                              '--retryCount', '1',
-- 
```

which produces

```
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:  Traceback (most recent call last):
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:    File "/mnt/ephemeral/workspace/toil-scripts/venv/local/lib/python2.7/site-packages/toil/worker.py", line 316, in main
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:      job = Job._loadJob(jobWrapper.command, jobStore)
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:    File "/mnt/ephemeral/workspace/toil-scripts/venv/local/lib/python2.7/site-packages/toil/job.py", line 631, in _loadJob
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:      return cls._unpickle(userModule, fileHandle)
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:    File "/mnt/ephemeral/workspace/toil-scripts/venv/local/lib/python2.7/site-packages/toil/job.py", line 654, in _unpickle
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:      return unpickler.load()
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:    File "/mnt/ephemeral/workspace/toil-scripts/venv/local/lib/python2.7/site-packages/toil/job.py", line 648, in filter_main
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:      return getattr(userModule, class_name)
ip-172-31-24-218: 2016-07-15 05:00:32,958 WARNING: toil.leader: V/c/jobC9b5iD:  AttributeError: 'module' object has no attribute 'download_sample'
```

Debugging reveals that the job function is `map_job` from `toil_script.lib.jobs`. It's argument is the `download_sample` function from `rnaseq_cgl_pipeline.py` which is invoked as `__main__` via `-m toil_scripts.rnaseq_cgl.rnaseq_cgl_pipeline` (see above diff). The `userModule` is `toil_script.lib.jobs`. When unpickling the job, cPickle hits `__main__.download_sample` and `_unpickle` attempts to look that up in the `userModule` (`toil_script.lib.jobs`) where it isn't defined.

We can't always equate "main module" with "user module". Often it's the same, but sometimes it isn't. I got halfway to a fix by tracking userModule and mainModule independently but got stuck when `__main__` was `_toil_worker` which triggered the requirement that a module comes from a file ending in `.py` or `.pyc`. A fix for this might overlap with #858. If we know that a file contains python code, we can always resort to `imp.load_source()` rather then `importlib.import_module`. The only remaining problem is pyzipfile which would skip files with unknown extensions. @diekhans had a partial fix for this.

Then again, we are not interested in `_toil_worker` because nothing in it will ever be referenced by a pickled job. We might be able to just ignore non-.py `__main__` modules.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-93)
┆Issue Number: TOIL-93

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
