### ISSUE TITLE
Set executor requirements to non-zero

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#108]
Once https://issues.apache.org/jira/browse/MESOS-1961 is resolved.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-94)
┆Issue Number: TOIL-94

**Comment by DailyDreaming** [comment]
Closed by 9d51fdb530ee4a0a4e4cc62f27c7bd8756982608
