### ISSUE TITLE
Collect and periodically print auto-scaling stats

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1084]
… and expose a diagram in the monitoring web app. Depends on #1089.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-95)
┆Issue Number: TOIL-95

**Comment by hannes-ucsc** [comment]
… and expose a diagram in the monitoring web app. Depends on #1089.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
