### ISSUE TITLE
Improve pickling/unpickling of cache state

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1138]
Currently we pickle the cache state as dictionaries and convert to objects when needed.  This is a work-around for pickle not being able to handle nested classes. Some code uses the raw dictionaries while other code uses the objects. This is confusing and we should be able to use dill and eliminate the work around.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-98)
┆Issue Number: TOIL-98

**Comment by DailyDreaming** [comment]
Stale.  Caching was also reimplemented.  Reopen if still an issue.
