### ISSUE TITLE
Don't delete a job's files when cleanWorkDir says not to

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1140]
Depends on #1139

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-99)
┆Issue Number: TOIL-99

**Comment by hannes-ucsc** [comment]
Note to self: implement `shouldCleanWorkDir(config)`

**Comment by cket** [comment]
@arkal do you still want to work on this?

**Comment by arkal** [comment]
not really

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
