### ISSUE TITLE
Don't bump retried jobs to defaultMemory

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1158]
Makes no sense to me. If there is any bump at all it should be to maxMemory. The default for defaultMemory is 2GiB which is arbitrary and wouldn't be fulfillable on EC2 micro instances or  small Docker containers in conjunction with docker-machine on OS X (that's where I saw it).

Update from 9/22/16:

Add `--minRetryMemory` and switch the retry logic to use that instead of `--defaultMemory`. The default should be None, disabling the logic.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-103)
┆Issue Number: TOIL-103

**Comment by jvivian** [comment]
+1 for removing this.  

-1 on bumping it to maxMemory. Seems like a bad situation if a job fails for memory reasons and then we change something without notifying the user and it passes.

**Comment by hannes-ucsc** [comment]
@benedictpaten, I believe this was intentional. What do you think?

**Comment by cket** [comment]
IIRC it was to handle scenarios where jobs with artificially low memory requirements overwhelmed nodes. If their memory was not bumped up the cycle would repeat and keep killing nodes.

**Comment by hannes-ucsc** [comment]
Sounds good. The feature should be optional, however.

I'll add a spec to the description.

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is still an issue.
