### ISSUE TITLE
Autoscaling improvements.

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1206]
We've got-bare metal clusters that use SGE or a derivative covered because Toil has no native dependencies in that mode and can be installed on a shared filesystem which these types of clusters typically have. 

For bare-metal clusters that lack a shared file system (for deployment) or a cluster manager (for task distribution), we would want to use the appliance. This is a very attractive deployment scenario, in my opinion.

Create a provisioner that only assumes that 1) Docker is installed on every cluster node and 2) password-less SSH access is available. As its input it should require a flat file with username@hostname entries. When the time comes to provision a node, invoke the `docker exec` command remotely via SSH using one of those entries.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-105)
┆Issue Number: TOIL-105

**Comment by fnothaft** [comment]
+1, this is how the original spark deployment scripts worked and that provided huge traction

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
