### ISSUE TITLE
Do workflows work from a virtualenv on a shared filesystem?

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1218]
Install a workflow and Toil in a virtualenv on the shared file system of a bare-metal cluster like PODK.

We need this for the Toil docs. Preliminary link here:

http://toil.readthedocs.io/en/issues-567-537-document-deployment/developing.html#relying-on-shared-filesystems

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-106)
┆Issue Number: TOIL-106

**Comment by hannes-ucsc** [comment]
@adamnovak, did you ever try this?

**Comment by adamnovak** [comment]
Nope, I have never tried this. I just have Toil installed to my personal Python installation's module directory. And I haven't tried it on Parasol in forever, or SGE at all.

**Comment by melainalegaspi** [comment]
Closing if this is an issue, please re-open.
