### ISSUE TITLE
FileStore shutdown should not happen in __del__

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1240]
**del** is not guaranteed to be called eagerly, or at all. Exceptions that occur are ignored. **del**  generally should not block but FileStore.**del** does block joining the async write threads.

It would be better to explicitly invoke that functionality.

https://docs.python.org/2/reference/datamodel.html#object.__del__

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-107)
┆Issue Number: TOIL-107

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
