### ISSUE TITLE
Improve worker output propagation

### ISSUE THREAD

**Issue by cket** [DataBiosphere/toil#1269]
Connected to #1248. Right now we only get worker output if a job fails or if log level is set to DEBUG. We should attempt to propagate worker output whenever that output contains logging messages above the current level. 

For example, if we have logging set to INFO and we have WARNING level output in our worker we should propagate that output to the leader.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-110)
┆Issue Number: TOIL-110

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
