### ISSUE TITLE
Add a way to configure all tests to log at a given level

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1285]
Note that this is complicated by the fact that many tests run toil as a separate process. So we'd have to make sure that those process invocations honored the global setting.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-111)
┆Issue Number: TOIL-111

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
