### ISSUE TITLE
Cache test fails on m3.large

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1288]
http://jenkins.cgcloud.info/job/toil-pull-requests/2069/testReport/junit/src.toil.test.src.jobCacheTest/FileJobStoreCacheTest/testAsyncWriteWithCaching/

This was accidentally run on a m3.large instance.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-112)
┆Issue Number: TOIL-112

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.  Caching has also been reworked significantly since this was raised.
