### ISSUE TITLE
Line output by parallel tests should be prefixed with test name

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1342]
In run_tests.py, use something like `| sed -e 's/^/prefix/` to prefix every line in the output with the test's name.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-117)
┆Issue Number: TOIL-117

**Comment by DailyDreaming** [comment]
No longer applicable.
