### ISSUE TITLE
Can't defer to built-in functions

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1352]
This is introduced by my fix for #1308. A doctest revealed it:

http://jenkins.cgcloud.info/job/toil-pull-requests/lastCompletedBuild/testReport/src.toil/fileStore/toil_fileStore_DeferredFunction/

The workaround is easy: just define a wrapper and defer to that.

For now I will change the doctest to implement the workaround.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-118)
┆Issue Number: TOIL-118

**Comment by hannes-ucsc** [comment]
I should also qualify that this is ultimately caused by modules that aren't defined in a file. AFAIK, this applies to built-in functions, interactively defined ones, stuff run via `python -c` and doctests. Uses of `exec` and `eval` probably, too.

There needs to be a way to pass these through as if they "belonged to Toil".

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
