### ISSUE TITLE
Add support for hot-deploying eggs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1367]
For motivation see #1366

A .egg is a ZIP file of a distribution. When packing up a virtualenv, Toil should either A) include the .egg files and the .pth files that add them to the sys.path or B) unpack each .egg and include its contents in the hot-deployed .zip file. I think A sounds more reasonable.

Info on .pth files: https://docs.python.org/2/library/site.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-119)
┆Issue Number: TOIL-119

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
