### ISSUE TITLE
Research signed URL expiration with Google job store

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#1372]
As a follow on to #668, we should investigate how GCS expires public URLs when IAM role credentials are used to sign them. Yes, Google calls it IAM, too.

https://cloud.google.com/compute/docs/access/iam

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-120)
┆Issue Number: TOIL-120

**Comment by DailyDreaming** [comment]
Stale, closing.  The Google job store is also completely different now.
