### ISSUE TITLE
Bug in core resource check

### ISSUE THREAD

**Issue by cmarkello** [DataBiosphere/toil#1396]
When running a toil-vg pipeline over whole chr22 data on AWS, there's a point where toil hangs on an error that shouldn't occur: `toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: Requesting more cores than either physically available, or enforced by --maxCores. Requested: 8, Available: 9223372036854775807`

Issue first reported here: https://github.com/BD2KGenomics/toil-vg/issues/80

Traceback:
> INFO:toil.leader:Waiting for stats and logging collator thread to finish ...
> INFO:toil.leader:... finished collating stats and logs. Took 0.377412796021 seconds
> INFO:toil.leader:Waiting for service manager thread to finish ...
> DEBUG:toil.batchSystems.mesos.batchSystem:There are no queued tasks. Declining Mesos offers.
> DEBUG:toil.batchSystems.mesos.batchSystem:Declining offer 2de3d770-5267-4d80-9fd3-c8386b84a8eb-O6576.
> DEBUG:toil.batchSystems.mesos.batchSystem:Declining offer 2de3d770-5267-4d80-9fd3-c8386b84a8eb-O6577.
> DEBUG:toil.batchSystems.mesos.batchSystem:Declining offer 2de3d770-5267-4d80-9fd3-c8386b84a8eb-O6578.
> DEBUG:toil.batchSystems.mesos.batchSystem:Declining offer 2de3d770-5267-4d80-9fd3-c8386b84a8eb-O6579.
> DEBUG:toil.leader:Received signal to quit starting services.
> INFO:toil.leader:... finished shutting down the service manager. Took 0.241214990616 seconds
> INFO:toil.realtimeLogger:Stopping real-time logging server.
> INFO:toil.realtimeLogger:Joining real-time logging server thread.
> DEBUG:toil.common:Shutting down batch system ...
> INFO:toil.batchSystems.mesos.batchSystem:Stopping Mesos driver
> I1215 22:25:04.335552 2146 sched.cpp:1771] Asked to stop the driver
> INFO:toil.batchSystems.mesos.batchSystem:Joining Mesos driver
> I1215 22:25:04.335629 2244 sched.cpp:1040] Stopping framework '2de3d770-5267-4d80-9fd3-c8386b84a8eb-0000'
> INFO:toil.batchSystems.mesos.batchSystem:Joined Mesos driver
> DEBUG:toil.common:... finished shutting down the batch system in 0.000205039978027 seconds.
> Traceback (most recent call last):
> File "/home/mesosbox/toilvenv/bin/toil-vg", line 11, in 
> sys.exit(main())
> File "/home/mesosbox/toilvenv/local/lib/python2.7/site-packages/toil_vg/vg_evaluation_pipeline.py", line 309, in main
> toil.start(root_job)
> File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 588, in start
> return self._runMainLoop(job)
> File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 808, in _runMainLoop
> jobCache=self._jobCache)
> File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 692, in mainLoop
> innerLoop(jobStore, config, batchSystem, toilState, jobBatcher, serviceManager, statsAndLogging)
> File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 866, in innerLoop
> jobBatcher.issueJobs(successors)
> File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 159, in issueJobs
> self.issueJob(jobStoreID, memory, cores, disk, preemptable)
> File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 148, in issueJob
> jobBatchSystemID = self.batchSystem.issueBatchJob(jobCommand, memory, cores, disk, preemptable)
> File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 141, in issueBatchJob
> self.checkResourceRequest(memory, cores, disk)
> File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/abstractBatchSystem.py", line 228, in checkResourceRequest
> raise InsufficientSystemResources('cores', cores, self.maxCores)
> toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: Requesting more cores than either physically available, or enforced by --maxCores. Requested: 8, Available: 9223372036854775807

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-121)
┆Issue Number: TOIL-121

**Comment by cricketsloan** [comment]
Is this still a problem?

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
