### ISSUE TITLE
Optionally enable custom EC2 memory metrics when autoscaling

### ISSUE THREAD

**Issue by cket** [DataBiosphere/toil#1415]
Add a flag -m/--monitoring to report memory usage to cloudwatch for extra cost. Possible this could enable this monitoring for entire cluster not just the master.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-126)
┆Issue Number: TOIL-126

**Comment by DailyDreaming** [comment]
Stale. Closing, please reopen if still an issue.
