### ISSUE TITLE
Remove mesos offer log messages

### ISSUE THREAD

**Issue by cket** [DataBiosphere/toil#1422]
@arkal found that in a recent autoscaling test 90+% of the log messages were debug messages about declining mesos offers.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-127)
┆Issue Number: TOIL-127

**Comment by fnothaft** [comment]
I've found those useful for debugging during development if I've broken things in the Mesos batch system. Is the concern here around spamming the debug logs? If so, perhaps we move them to a yet lower log level?

**Comment by cket** [comment]
@fnothaft yeah, we're debugging large runs and removing this message turns 1gb logs into 70mb. I'm also ok with setting it lower and letting the user set a numerical value for `logLevel`.
