### ISSUE TITLE
Installing toil with Mesos support

### ISSUE THREAD

**Issue by matthdsm** [DataBiosphere/toil#1432]
Hi,

We'd like to use Toil to schedule jobs on our Mesos cluster. However, thu current manuals says we have to download a python egg from de Mesos website. This website currently only offers .deb binaries. Are there any updated instructions on how to install toil with mesos support and more importantly, on how to use it? 

Thanks
M

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-138)
┆Issue Number: TOIL-138

**Comment by cket** [comment]
@matthdsm I believe the python eggs are now included in mesos installation. 

However, we recommend using https://github.com/BD2KGenomics/cgcloud for managing Mesos/Toil clusters. If you don't mind building dev Toil from master, you could also use the Toil provisioner and autoscaling to setup a Mesos/Toil cluster instead. 

@natanlao can you make sure that the relevant documentation is updated?

**Comment by natanlao** [comment]
@cket My local copy already has it fixed, it'll be resolved with #1426.

**Comment by matthdsm** [comment]
Hi,
I think I'll need to clarify my needs a bit more. Let me sketch the situation:

We already have a multi node Mesos cluster (3 controllers, 4 nodes), managed in Openstack. We're looking for a way to run a CWL workflow (bcbio in our case) on this cluster. To do this we'd like to launch the workflow from another VM. This means that the VM from where the toil is called, has no Mesos installation.

I'm still quite new in this, so if you could help me understand how things work, and where which software needs to be installed, I would be a very happy man. unfortunatly, deploying a new mesos cluster using cgcloud is not an option for us.

Thanks for the help!
M

**Comment by cket** [comment]
I see - we haven't run Toil/Mesos on openstack before so there could be a couple issues. We run on AWS and use the AWS job store with Mesos, and there is no open stack job store. However if you are running on something like HDFS then you can use the file system job store, although we have never run Toil/Mesos in that configuration so it's a bit of an unknown. 

Additionally, running the Toil leader from outside the Mesos cluster is also untested, but _should_ work. 

With those caveats, the components of the system should be the same so hopefully our existing documentation will be helpful, with the obvious exception of finding the eggs - in your case they may be installed already, but if not you might have to reach out to Mesos to find where they're now hosted.

**Comment by osallou** [comment]
With the python API of mesos, scheduler framework need have have mesos locally installed to get the python code, even if no master or slave is needed/running, just the software. Then mesos master IP or zookeeper ref is given in config to access it. So if you need to conenct from a remote VM, you need to install mesos deb/rpm to get the python code (and related .so).

This could be avoided using the Mesos HTTP API, but this would need Toils modifications.

**Comment by matthdsm** [comment]
@tomiles?

**Comment by qkl871118** [comment]
@cket Hi, I am using toil to running Docker container jobs in a Mesos cluster, I find that Mesos could not detect the resource usage of Docker container jobs. Do you have any plan to fix this? Or how can I configure to make Mesos can detect the resource usage of Docker container jobs? Thank you.
