### ISSUE TITLE
Refactor/rework getRunningJobIDs() in abstractGridEngineBatchSystem

### ISSUE THREAD

**Issue by cjfields** [DataBiosphere/toil#1443]
Currently in pull request #1195, to be merged.

Some redundant code remains within the `getRunningJobIDs()` implementations for each `abstractGridEngineBatchSystem` implementation.  Also, the name of the method is a bit misleading as it returns a dict of the running job IDs along with their running times (suggestions for a better name are more than welcome).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-131)
┆Issue Number: TOIL-131

**Comment by DailyDreaming** [comment]
Stale. Closing, please reopen if still an issue.
