### ISSUE TITLE
Reconfigure abstractGridEngineBatchSystem methods to check and log all subprocess calls

### ISSUE THREAD

**Issue by cjfields** [DataBiosphere/toil#1444]
Currently in pull request #1195, to be merged.

The various implementations of `abstractGridEngineBatchSystem` (Torque, SLURM, GridEngine) have somewhat inconsistent methods for calling `subprocess` methods and logging information. 

@hannes-ucsc suggests pulling out the `subprocess.check_call` and similar into a common wrapper method and [adding logging to track all the calls](https://github.com/BD2KGenomics/toil/pull/1195#pullrequestreview-10854387).  This would also allow more consistent subprocess status checks.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-132)
┆Issue Number: TOIL-132

**Comment by DailyDreaming** [comment]
Stale. Closing, please reopen if still an issue.
