### ISSUE TITLE
add support for piped commands to docker_call

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#1468]
toil-vg needs to be able to run things like vg ids -s graph.vg | vg mod -X 100 > output.graph, where vg can be a docker container.

Am currently using cmarkello@75c2159

This logic needs to get pushed up so we don't get too far out of sync. Will make a cleaned up PR shortly.

(Moved from https://github.com/BD2KGenomics/toil-lib/issues/80)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-134)
┆Issue Number: TOIL-134

**Comment by DailyDreaming** [comment]
This is fixed afaik.
