### ISSUE TITLE
Checking `--logFile` and `--gzipLogFile` exclusivity should happen at argument-parsing time

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/toil#1495]
The logic for [choosing whether to write logs as gzip in statsandLogging.py](https://github.com/BD2KGenomics/toil/blob/master/src/toil/statsAndLogging.py#L64) should be performed at argument-parsing time.

This is an old issue from @hannes-ucsc that I never got around to entering.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-136)
┆Issue Number: TOIL-136

**Comment by DailyDreaming** [comment]
I took this on without thinking about it, but this is such a low priority refactor that I'm removing this ticket.  I might consider this evidence that statsandLogging.py and common.py overall could use larger refactors.  This would be addressed during those transitions and when they're decided to be priorities (I'm not making tickets for those until they're determined to be necessary and as a part of other work).

This functionality and check is fine as is and I'm closing this issue.
