### ISSUE TITLE
Tests leaking resources

### ISSUE THREAD

**Issue by cket** [DataBiosphere/toil#1511]
@jvivian pointed out there are s3 buckets left behind by some of the Toil tests. I'm pretty sure this issue has been addressed before so this is a regression. We should look at dealing with this in the Toil test base class.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-137)
┆Issue Number: TOIL-137

**Comment by DailyDreaming** [comment]
Stale.  I believe Adam looked into this recently.  I can see it reoccurring in the future and we could have a daemon sentinel for this living as a lambda in our space, but closing for now.
