### ISSUE TITLE
Toil can't restart a run because _cacheState in system temp directory is missing

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1524]
I'm trying to restart a Toil run on a single machine JobStore that has about 10 hours of work in it. I successfully restarted it once, but I had some jobs fail, so I Ctrl+C'd the Toil run to replace the binaries it's calling.

Now when I run Toil to restart the run I get a bunch of errors like this:

```
WARNING:toil.leader:The job seems to have left a log file, indicating failure: H/z/job0Gct4w
---TOIL WORKER OUTPUT LOG---
H/z/job0Gct4w    WARNING:toil.resource:Can't find resource for leader path '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder'
H/z/job0Gct4w    WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src', name='hgvmbuilder.build', fromVirtualEnv=False)
H/z/job0Gct4w    INFO:toil.fileStore:Starting job (C/D/job9awsA4/g/tmppE8Ay5.tmp) with ID (738f55081d09bc5b3d8a8e0f48b1717877057b4c).
H/z/job0Gct4w    CRITICAL:toil.fileStore:CACHE: Unable to acquire lock on /scratch/tmp/toil-564c5625-02e3-46ff-81f4-c6ee55f75d22/cache-564c5625-02e3-46ff-81f4-c6ee55f75d22/.cacheLock
H/z/job0Gct4w    Traceback (most recent call last):
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/worker.py", line 323, in main
H/z/job0Gct4w        caching=not config.disableCaching)
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/fileStore.py", line 108, in createFileStore
H/z/job0Gct4w        return fileStoreCls(jobStore, jobWrapper, localTempDir, inputBlockFn)
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/fileStore.py", line 103, in __init__
H/z/job0Gct4w        self._setupCache()
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/fileStore.py", line 607, in _setupCache
H/z/job0Gct4w        with self._CacheState.open(self) as cacheInfo:
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/contextlib.py", line 17, in __enter__
H/z/job0Gct4w        return self.gen.next()
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/fileStore.py", line 969, in open
H/z/job0Gct4w        cacheInfo = cls._load(outer.cacheStateFile)
H/z/job0Gct4w      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/fileStore.py", line 981, in _load
H/z/job0Gct4w        with open(fileName, 'r') as fH:
H/z/job0Gct4w    IOError: [Errno 2] No such file or directory: '/scratch/tmp/toil-564c5625-02e3-46ff-81f4-c6ee55f75d22/cache-564c5625-02e3-46ff-81f4-c6ee55f75d22/_cacheState'
H/z/job0Gct4w    Exiting the worker because of a failed jobWrapper on host juggernaut
H/z/job0Gct4w    ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host juggernaut
H/z/job0Gct4w    WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job H/z/job0Gct4w to 0
WARNING:toil.leader:Job: H/z/job0Gct4w is completely failed
INFO:toil.leader:No jobs left to run so exiting.
```

It looks like `/scratch/tmp/toil-564c5625-02e3-46ff-81f4-c6ee55f75d22/cache-564c5625-02e3-46ff-81f4-c6ee55f75d22/_cacheState` is missing, but `/scratch/tmp/toil-564c5625-02e3-46ff-81f4-c6ee55f75d22/cache-564c5625-02e3-46ff-81f4-c6ee55f75d22/` itself is still there.

In general Toil ought to tolerate any files in the temp directory not being there on restart, because system temp directories get cleaned up.

Can I fix this by putting something in that missing file? Can I fix it by deleting everything that Toil has in the system temp directory (i.e. it's just mad about an inconsistent state)?

Did this file get lost because I managed to kill my run in some kind of critical section for cache metadata validity?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-138)
┆Issue Number: TOIL-138

**Comment by cket** [comment]
@adamnovak I haven't tried turning off caching in the middle of a run so I'm not sure of the side effects, but  ``--disableCaching``  _might_ be a good work around for this issue. IMO we shouldn't assume the cacheState file will be there and we should be able to recover if it was deleted. 

@arkal do you have any opinions/advice on this issue?

**Comment by adamnovak** [comment]
The `--disableCaching` workaround works for me! But Toil should definitely handle a messed-up cache and/or not mess it up.

**Comment by cket** [comment]
@adamnovak glad to hear its working - it looks like this is caused by a relatively straightforward bug: we test for the existence of the cacheDir and then go ahead and assume the inner files must exist as well. We can fix this by testing for the cacheState file instead. It's the last file to be written during caching setup so if it exists we know the setup was completed successfully.

**Comment by cket** [comment]
Not as straightforward as I thought... The entire cache directory is set up at a tmp location and then moved to its final location, attempting to make the cache setup atomic. From the comments it seems unclear whether or not directory renaming is actually an atomic operation, which might explain this error.

**Comment by adamnovak** [comment]
It's atomic within a device, but not atomic cross-device. Maybe you can
move it to a derived name like wherever.tmp and then to wherever it really
belongs?

**Comment by arkal** [comment]
Hey, sorry github didn't show this as an unread issue so i didn't catch this earlier. There is logic to restart a failed run from an existing cache state but as CJ mentioned, there isn't anything to handle a missing `_cacheState`.  The cachedir is created atomically via a .tmp renamed to the final value. We can't add a if directory doesn't exist then delete and create new one without causing a race. Then again, Did you repeatedly hit Ctrl+C or hit it once and then wait for Toil to end gracefully? I find it weird that the cache dir exists but the cache state doesn't (This shouldn't ever happen if Toil exits gracefully). You should delete the workdir and let toil create it again.

**Comment by adamnovak** [comment]
I think I might have mashed it a couple times; Toil takes a long time doing
seemingly nothing before exiting if I just hit it once.

If you want to update a file atomically, you can rename a new one over the
old one.

**Comment by arkal** [comment]
Yes, but unfortunately that's another race. Once a thread successfully creates the cache dir, others will fail and everyone uses the dir that the first one created. Since file renaming does not raise any errors, the first thread will create the file, continue thinking that is the cache state but the subsequent ones might overwrite that one potentially causing problems.

**Comment by DailyDreaming** [comment]
Closing as I believe Adam has reworked caching and I'm assuming this is stale.
