### ISSUE TITLE
Mesos could not detect the resource usages of the Docker jobs submitted by cwltoil

### ISSUE THREAD

**Issue by qiukunlong** [DataBiosphere/toil#1557]
Mesos could not detect the resource usages of the Docker jobs submitted by cwltoil. I tried to submit a cwl job by cwltoil to Mesos, the job ran successfully , but the memory shown by Mesos was always 73M.  The memory actually used is 6G.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-141)
┆Issue Number: TOIL-141

**Comment by cket** [comment]
Hi @qkl871118, can you clarify what you mean by this? You can specify the resource requirements for jobs in the CWL which Toil should pass on to Mesos. Is that not happening for you?

**Comment by qkl871118** [comment]
Hi @cket , Toil can pass its resource requirements for jobs in the CWL to Mesos. But if CWL use DockerRequirement feature, Mesos could not detect resources of the CWL job(in a Docker container) actually used. That means if I set memory requirement of 100M in CWL(DockerRequirement), the job could use more than 100M memory(for example : 6G), but the memory usage shown by Mesos is only 73M.  
I think at ContainerInfo in batchSystems.mesos.batchSystem.py could solve this problem.

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is still an issue.
