### ISSUE TITLE
Use of qacct on GridEngine

### ISSUE THREAD

**Issue by humburg** [DataBiosphere/toil#1558]
I'm trying to run toil on a GridEngine cluster but am facing some difficulties. It appears that toil submits jobs correctly but fails to notice when they finish, i.e. even very simple pipelines hang indefinitely. I believe that this is related to #1114.

My understanding from the previous discussion is that toil monitors the output of `qacct` to determine whether jobs have completed successfully. However, I don't have access to `qacct` on the local cluster, which means that this inevitably fails. As far as I can tell this essentially working as designed but I was wondering what the rationale behind the use of `qacct` is and whether an alternative scheme that uses `qstat` instead would be feasible. That would have the benefit of being more widely available but I don't know enough about the toil internals to understand what the potential issues might be.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-142)
┆Issue Number: TOIL-142

**Comment by cket** [comment]
@humburg thanks for bringing this up. I would be in favor of adding support for `qstat` in addition to `qacct`. All the relevant code should be isolated to `gridengine.py` if you want to take a look - pull requests are very welcome!

**Comment by humburg** [comment]
@cket good to hear that you are interested in this. I'll take a look to see what I can do. Right know I know literally nothing about toil's internals, so may need some input along the way.

**Comment by humburg** [comment]
@cket I've had a brief look at this. The problem I see is that in the absence of meaningful output from `qacct` it isn't possible to determine whether a job jailed just based on the output from `qstat`. Using `qstat` is great to determine whether a job is still running but some other mechanism is needed to determine whether it was successful. It may be possible to inspect the job's output to take a reasonable guess but that seems error prone.

An alternative would be to use the [DRMAA](https://www.drmaa.org/index.php) ([Python bindings](https://github.com/pygridtools/drmaa-python)) instead. That would be a larger change, introducing a new dependency and requiring some additional setup (an environment variable needs to point to the DRMAA library). On the upside, DRMAA implementations are also available for LSF, SLURM, Torque and others, potentially allowing to target a variety of systems through the same BatchSystem implementation. If there is interest I'd be happy to take a stab at re-jigging the grid engine interface.

**Comment by humburg** [comment]
Any thoughts on this? To avoid breaking things for other people it might be best to provide a separate batch system implementation to support DRMAA. It seems that might be a bit easier with #1392 but I'm unsure what the status of that PR is. Looks like it might be in need of some attention.

**Comment by cket** [comment]
The current implementations are inflexible and error prone so the python bindings seem like a definite improvement. Since I don't want to end up maintaining multiple implementations of the same batch system I'm in favor of rewriting the current implementation rather than add another one. I also think you should base your work off the current infrastructure rather than waiting for the PR.

I'm ok with adding a Python dependency as long as the setup is automated (we set the environment variable for the user, if possible).

**Comment by evan-wehi** [comment]
@humburg #1392 would allow you to easily add your own DRMAA batch system - this is what I did and it works very well.

**Comment by DailyDreaming** [comment]
Stale. Please reopen if this is still an issue.
