### ISSUE TITLE
Support hot-deployment of non-python dependencies

### ISSUE THREAD

**Issue by arkal** [DataBiosphere/toil#1570]
If the User script has non-python dependencies in the package, they will not be hot-deployed. Add support for hot-deployment of such files.

Related to #1569

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-143)
┆Issue Number: TOIL-143

**Comment by DailyDreaming** [comment]
Stale, closing.  Also... this seems potentially complex and additional ambiguous dependencies should be probably be the responsibility of the user.  If we implement this, it is likely to be fragile because we have no idea what a user might need or want to add.
