### ISSUE TITLE
Improve error when passing a promised object to another child job function

### ISSUE THREAD

**Issue by jvivian** [DataBiosphere/toil#1607]
Never fully resolved in: https://github.com/BD2KGenomics/toil/pull/912

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-150)
┆Issue Number: TOIL-150

**Comment by DailyDreaming** [comment]
Stale, and now unclear what the issue was.  Closing, please reopen if still an issue.
