### ISSUE TITLE
Toil not hot-deploying module installed at system level

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1645]
I have a user script that depends on another module (`tsv`, which I wrote and put on PyPI). In my Azure cluster, the module is installed on my master, but not on the Mesos agents. It looks like it isn't being hot-deployed.

```
=========> Failed job 'main_job' 41d94979_88af_44bc_8554_6d7fcb598350 
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
ERROR:toil.resource:Failed to import user module ModuleDescriptor(dirPath=u'/tmp/tmpgRNEyn/d7b795521a9c20756fa7b94f204c5490', name='hgvmbuilder.importsam', fromVirtualEnv=False) from sys.path (['/usr/local/bin', '/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/mesos.interface-0.22.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/mesos-0.22.0-py2.7-linux-x86_64.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', u'/tmp/tmpgRNEyn/d7b795521a9c20756fa7b94f204c5490']).
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 325, in main
    job = Job._loadJob(jobGraph.command, jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 858, in _loadJob
    userModule = cls._loadUserModule(userModule)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 835, in _loadUserModule
    return userModule.load()
  File "/usr/local/lib/python2.7/dist-packages/toil/resource.py", line 570, in load
    return importlib.import_module(module.name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/anovak/hgvm-builder/src/hgvmbuilder/importsam.py", line 23, in <module>
ImportError: No module named tsv
ERROR:toil.worker:Exiting the worker because of a failed job on host hgvm1agent4
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'main_job' 41d94979_88af_44bc_8554_6d7fcb598350 with ID 41d94979_88af_44bc_8554_6d7fcb598350 to 0
WARNING:toil.jobGraph:We have increased the default memory of the failed job 'main_job' 41d94979_88af_44bc_8554_6d7fcb598350 to 2147483648 bytes
<=========


real    0m9.585s
user    0m0.956s
sys     0m0.128s
anovak@hgvm1master1:~$ python -i
Python 2.7.12 (default, Jul 18 2016, 15:02:52) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tsv
>>> print tsv.__file__
/usr/local/lib/python2.7/dist-packages/tsv.pyc
>>> 
anovak@hgvm1master1:~$ 
```

It's not in an egg this time.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-156)
┆Issue Number: TOIL-156

**Comment by adamnovak** [comment]
Even though `tsv.pyc` is not *in* an egg, is Toil maybe not able to deploy the module because there's an `egg-info` directory for it?

```
anovak@hgvm1master1:~/hgvm-builder$ ls /usr/local/lib/python2.7/dist-packages | grep tsv
tsv-1.1-py2.7.egg-info
tsv.py
tsv.pyc
```
I just tried to fix it with a `sudo pip install --upgrade tsv==1.1`, and that's the configuration that it produces. Since the plain `pip install` is the form recommended by the docs, the tsv module really ought to now be available for hot deployment.

**Comment by cket** [comment]
> is Toil maybe not able to deploy the module because there's an egg-info directory for it?
I don't think so, Toil doesn't skip hot deploying eggs it just fails on the attempt like you saw in the other issue. 

It looks like you didn't install `tsv` in a virtualenv. That will prevent hot deployment from working on the module.

**Comment by adamnovak** [comment]
Oh, so everything to be hot deployed also needs to be inside a virtualenv?

Does that include the user script? Meaning that I can't provide commands on a user's command line, without them entering a virtualenv, and have them be hot-deployed?

**Comment by cket** [comment]
Unfortunately it does include the user script. So to get commands outside the virtualenv you'd have to do something like symlink the executable from within the virtualenv onto the user's path.

**Comment by adamnovak** [comment]
The [documentation](http://toil.readthedocs.io/en/releases-3.6.x/deploying.html#hot-deploying-toil) shows creating a virtualenv as the "first order of business", but it definitely doesn't say that not using a virtualenv won't work. So if that's the case the documentation needs to be changed to reflect this limitation.

Since you're supposed to create the virtualenv with `--system-site-packages`, doesn't that mean that having a dependency other than Toil already installed on the system, and used from within the virtualenv, will break hot deployment? If I have `tsv` installed at the system level, then when I create a virtualenv with `--system-site-packages` and install something that depends on `tsv` in there, it'spossible it will just use the system `tsv`, right? Then Toil won't be able to hot-deploy that dependency.

Is there a good reason why it works like this? It seems extremely limiting.

**Comment by adamnovak** [comment]
The docs also say that I'm supposed to copy my workflow to each host, and the section title is "Hot-deploying Toil", which I'm pretty sure isn't possible.

**Comment by cket** [comment]
Yes, that is a typo. I can rewrite this section. 

> doesn't that mean that having a dependency other than Toil already installed on the system, and used from within the virtualenv, will break hot deployment?

Yes, if the dependency is not on the other hosts. The user script and all of its dependencies need to be within a virtualenv to use hot deployment. I'm not very familiar with the hot deployment code but IIRC the virtualenv is required as a convenient (from Toil's standpoint) way to isolate & identify the packages that need to be deployed.

**Comment by DailyDreaming** [comment]
This is stale, and possibly specific to Azure support, which has been deprecated.  If this is still an issue, please reopen.
