### ISSUE TITLE
Better integration between fileStore and Docker

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1651]
If I want to process a file from the `fileStore` in a container, I can't just do something like:

```
dockerCall(job, tool='quay.io/ucgc_cgl/samtools:latest', parameters=['view', job.fileStore.readGlobalFile(bam_id)])
```

The paths returned by the fileStore are on the node itself and not available inside the container.

It would be nice if they were available in the container, or if there was some kind of wrapper object that you could put around a path that, when encountered in the `dockerCall` arguments, would cause that file's directory to get mounted in the container and would translate the path name into the path to the mounted file.

I'm working with @cmarkello and @glennhickey 's "drunner" wrapper, which tries to abstract over running commands normally, on Docker, and on Singularity, and one of the warts that projects through that abstraction is that you can't just throw arbitrary paths in; you have to work with everything relative to a single `work_dir`. If there was some way to wrap arbitrary paths and have them translated, the interface would be a lot cleaner.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-158)
┆Issue Number: TOIL-158

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
