### ISSUE TITLE
-defaultPreemptable option could use some docs

### ISSUE THREAD

**Issue by fnothaft** [DataBiosphere/toil#1673]
Currently, it is undocumented: https://github.com/BD2KGenomics/toil/blob/master/src/toil/common.py#L460

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-162)
┆Issue Number: TOIL-162

**Comment by jessebrennan** [comment]
@fnothaft Do you still plan to add this?

**Comment by adamnovak** [comment]
We have documentation for this option now.
