### ISSUE TITLE
Toil does not detect Anaconda virtual environments

### ISSUE THREAD

**Issue by brainstorm** [DataBiosphere/toil#1675]
This breaks some assumptions (and jobs) since `inVirtualEnv` on https://github.com/BD2KGenomics/toil/blob/e9c0ef0088b560577e64a9855496126e0ea00301/src/toil/__init__.py#L38:

```
-bash-4.1$ which python
/g/data/gx8/tmp/local_miniconda_roman/bin/python
-bash-4.1$ python -c "import sys; print(hasattr(sys, 'real_prefix'))"
False
```

I wish there was a "virtualenvdetector" python package that handled this :-S

Yet, as @marcelm wisely pointed out: is there really a need to act differently depending on whether one is inside a venv or not? Can't we just pass the whole environment along from the submission node/leader down to the workers?

Also, apparently Anaconda is [not considered a venv per se](https://github.com/conda/conda/issues/448#issuecomment-54205818), thanks again @marcelm for that hint too.

I'm thinking on getting rid of the whole `resolveEntryPoint` logic, but before doing so I would like to hear some arguments on why that is in place.

/cc @ohofmann

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-163)
┆Issue Number: TOIL-163

**Comment by DailyDreaming** [comment]
This is solved.
