### ISSUE TITLE
Option to write toil output to STDOUT?

### ISSUE THREAD

**Issue by rob-stripe** [DataBiosphere/toil#1683]
We're running toil on a single machine, and would like to log its output to STDOUT in real time, ideally just using normal loggers, but it's not a dealbreaker if we had to go through some special logger object.

Would you accept a PR that added a flag that allowed the user to bypass this OS-level redirection? https://github.com/BD2KGenomics/toil/blob/43484f818126155f20dfe4f7b173f0e97c19d457/src/toil/worker.py#L158 . This feels like it could be part of some bigger-picture "LocalMode", but this is the only problem that I am experiencing right now.

Thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-165)
┆Issue Number: TOIL-165

**Comment by ejacox** [comment]
Hey @rob-stripe. We have been working on improving "LocalMode". @jessebrennan, did you add something to capture STDOUT? Otherwise, we would accept a PR if you are still interested.

**Comment by jessebrennan** [comment]
@ejacox this is unrelated to anything I've been doing. Sounds good to me.

**Comment by DailyDreaming** [comment]
This is now a thing with `disableWorkerOutputCapture` I believe.
