### ISSUE TITLE
deserialization of CWL jobs is incorrect for Process.format field

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#1692]
should be an rdflib.Graph object, but I've seen a string and a dictionary of unrelated content returned

This bug impacts users when there are multiple formats valid for a particular CWL input and the `ontology` (that is populated from a `Process`'s `format` field) is not an `rdflib.Graph` object:

https://github.com/common-workflow-language/cwltool/blob/master/cwltool/process.py#L325

When direct matching is used (single format specified, single format provided) then this code isn't traversed and the bug remains hidden

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-166)
┆Issue Number: TOIL-166

**Comment by DailyDreaming** [comment]
Not sure if this is still an issue.  3 years is pretty stale though, so I'm closing this.  Please reopen if it's still an issue.
