### ISSUE TITLE
Improve static provisioning

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/toil#1723]
A new cluster utility `manage-cluster` should be added that allows a user to add nodes of a specific type to a preexisting cluster and specify the size of their EBS volume storage. `manage-cluster` should also be able to shut down nodes.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-172)
┆Issue Number: TOIL-172

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
