### ISSUE TITLE
Strict host key checking fails locally.

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1736]
The strict host key check in utilsTest.py/testAWSProvisionerUtils works with Jenkins, but fails when integration tests are run locally. The test was commented out until it is fixed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-174)
┆Issue Number: TOIL-174

**Comment by adamnovak** [comment]
I think we removed this test instead of fixing it; I can't find it anymore.
