### ISSUE TITLE
cwltoil should not fail on unsatisfied 'hints'

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1770]
cwltoil fails if hints are not satisfied. See #1765 for an example. According to the specification (http://www.commonwl.org/draft-3/CommandLineTool.html#ResourceRequirement), hints are optional and should not cause a failure.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-179)
┆Issue Number: TOIL-179

**Comment by DailyDreaming** [comment]
I believe this is fixed.  Please reopen if this is still an issue.
