### ISSUE TITLE
python 2/3 compatibility

### ISSUE THREAD

**Issue by ryanking** [DataBiosphere/toil#1780]
It seems possible to get the codebase to a point where it is compatible with both python 2 and 3 and I am willing to tackle it.

This guide https://docs.python.org/3/howto/pyporting.html has a pretty clear path to getting a compatible codebase.

I propose using this issue to track the work, but to open up individual issues for each bit of work in the process.

Steps:

1. Futurize stage 1 – https://github.com/BD2KGenomics/toil/issues/1784
1. Futurize stage 2  – https://github.com/BD2KGenomics/toil/issues/1785
1. deal with semantic changes (text vs bytes, division, unordered dictionaries, etc) http://python-future.org/what_else.html#what-else
1. Pylint – (pylint --py3k)
1. work through dependencies – https://pypi.python.org/pypi/caniusepython3
1. continuous integration with python 2 and 3

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-200)
┆Issue Number: TOIL-200

**Comment by ryanking** [comment]
Before I dig into this too much, can I get a thumbs-up from maintainers that this sort of stuff would be accepted?

**Comment by jorvis** [comment]
If you want to dish out some tasks I can try to help.  I've been wanting to see this support for a while

**Comment by ryanking** [comment]
Thanks @jorvis. I'm still working on fleshing out some of the strategy here. If something comes up I'll let you know.

**Comment by genomematt** [comment]
Thanks for this @ryanking 
I would also note that in addition to what is listed above there is the potential effect of unordered dictionaries in python3 <3.6
This is usually not a real problem but can make testing a pain, especially if it is non determinism flowing up from dependencies.  For this reason I suggest starting with 3.6 or even making it a requirement

**Comment by benedictpaten** [comment]
I am one of those Python 2.7 luddites, but you'd get my strong +1

**Comment by ryanking** [comment]
thanks @genomematt, added a note about unordered dictionaries to the todo list

**Comment by jsmedmar** [comment]
Is there a ticket/pull request for the third action point in this ticket (deal with semantic changes)?

**Comment by jessebrennan** [comment]
@jsmedmar, not unless you count on this issue here. I believe @ejacox was planning on dealing with this next week.

**Comment by RNAer** [comment]
wondering if there is any update on this?

**Comment by psafont** [comment]
This postmortem might prove useful for migrating the code: https://medium.com/@boxed/moving-a-large-and-old-codebase-to-python3-33a5a13f8c99

**Comment by diekhans** [comment]
I got inspired to work on this a little (very limited time).
I have a fork and if any one wants to help, that would be fantastic.

Mark

**Comment by diekhans** [comment]
related work is #1936;  bd2k-python-lib is hard to port to Python 3 and many parts are not needed

**Comment by illusional** [comment]
Hey @ryanking @diekhans, just wondering what the status of this card is, because the cards #1936 and #1937 are both resolved. Just wondering how far through you guys got, and whether the changes to complete the port are trivial or there's some head-ache?

**Comment by adamnovak** [comment]
We now more-or-less-officially support Python 3. We have our CI tests running and passing under Python 3; any bugs people report when running under Python 3 are going to be seen as as important or more important than Python 2 bugs.

I won't warrant that it's been a bug-free port, but it is "done".
