### ISSUE TITLE
cwl: expose cwltool's --relax-path-checks option

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#1782]
Would allow for filenames with `:` and other non-standard characters in them

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-182)
┆Issue Number: TOIL-182

**Comment by sgosline** [comment]
Any updates on this? It seems to come up trying to use `toil` with `vep` files.

**Comment by adamnovak** [comment]
@jeffrey856 Did you come across this option while working on #2718 to fix #2613? Could you maybe tack it on to that PR if not?

**Comment by DailyDreaming** [comment]
This is fixed.
