### ISSUE TITLE
Interactive Workflows via IPython?

### ISSUE THREAD

**Issue by OliverEvans96** [DataBiosphere/toil#1788]
I see from #673 that running toil from IPython is presently not supported.

- Are there some things you *can* do from IPython? e.g., can't create a workflow, but can modify or run one?
- Is there any hope for this evolving any time soon?

Thanks,
Oliver

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-184)
┆Issue Number: TOIL-184

**Comment by jessebrennan** [comment]
related: #1026 #1352

**Comment by OliverEvans96** [comment]
@jessebrennan I found a quick partial solution - #1789

**Comment by jessebrennan** [comment]
Actually this may not be fully possible. See https://stackoverflow.com/questions/24466804/multiprocessing-breaks-in-interactive-mode.

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if this is needed in the future.
