### ISSUE TITLE
No source file for docs/toil_architecture.jpg

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#1811]
There is no source file checked into the tree for docs/toil_architecture.jpg, meaning it can't be maintained.

Also, computer generated images should be PNGs, JPEG is intended for photographs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-191)
┆Issue Number: TOIL-191

**Comment by DailyDreaming** [comment]
Stale, low priority, and I don't want to do this.  :p
