### ISSUE TITLE
Add "make uninstall" and a requirements.txt file.

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#1812]
- no requirements.txt, hidden in a makefile command line instead
- make clean attempts to uninstall toil from a virtualenv, should follow standard makefile target functionality. An uninstall target should be used to uninstall toil
  - https://www.gnu.org/prep/standards/html_node/Standard-Targets.html

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-192)
┆Issue Number: TOIL-192

**Comment by DailyDreaming** [comment]
There was a comment about our requirements perhaps being too strict: https://github.com/DataBiosphere/toil/issues/2579

I believe we should probably still keep strict requirements but also perhaps build out requirements more sensibly, something like the `make requirements.txt` build here: https://github.com/HumanCellAtlas/data-store/blob/master/requirements.txt.in

**Comment by adamnovak** [comment]
I don't think `requirements.txt` can support extras, but it might make sense to investigate whether we could dispense with our `setup.py` in favor of a `pyproject.toml`, which [as of PEP 621 supports extras](https://www.python.org/dev/peps/pep-0621/#dependencies-optional-dependencies), like [this example in PEP 630](https://www.python.org/dev/peps/pep-0631/#optional-dependencies).
