### ISSUE TITLE
AWS provisioner can leave behind security groups

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1833]
My AWS account has a bunch of left-behind security groups that look like the AWS provisioner forgot to delete them. There are no instances in the clusters that the groups belong to.

I'm not sure how this state is obtained, but you can't get out of it by running `toil destroy-cluster` again, because it will only delete the security group for the cluster if it is also deleting some instances.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-194)
┆Issue Number: TOIL-194

**Comment by DailyDreaming** [comment]
This might be better covered by #2637.  Closing.
