### ISSUE TITLE
Outdated instructions for setting mesosMaster

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/toil#1849]
This can be found here:

 - http://toil.readthedocs.io/en/latest/running/amazon.html?highlight=mesosmaster

But there are probably other places.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-196)
┆Issue Number: TOIL-196

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is still an issue.
