### ISSUE TITLE
Better jobStore debugging

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1855]
Introduce some better ways to interact and
debug with jobStore, e.g. have the ability to
expire certain runs from re-use (if messed something up) and generally
hack around in there to improve restarts.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-197)
┆Issue Number: TOIL-197

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is an issue.
