### ISSUE TITLE
Better resource management.

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1856]
Outstanding issues I have on my bucket are having some more clarity on
how to properly test whether --maxCores are respected on batch systems
(perhaps needs reintroducing globalSystemConstants?) and on the other
hand run some tests on my own on how to easily interface with resource
requirements to infer resources pre-run (pause the run and
interactively offer options to the user)... more on the latter with
Peter and Michael with their recent CWL 1.0.1 patches. (from @brainstorm)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-198)
┆Issue Number: TOIL-198

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is an issue (though I believe this was solved).
