### ISSUE TITLE
Move Toil-lib Functions to Toil

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#1860]
The functions that Toil calls from Toil-lib should be in Toil proper.  I feel like these would be better served if they were not in two separate repos.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-28)
┆Issue Number: TOIL-28

**Comment by jvivian** [comment]
-1 — Toil is not specific to genomics and toil-lib contains almost exclusively job functions for bioinformatics tasks. Even the more general functions like `download_url` are tailored to CGL and are not abstracted to a level useful for most outside users. 

I'd +1 adding useful convenience functions related to file handling and downloading if they were written to be used by a general user.

**Comment by DailyDreaming** [comment]
That's reasonable.  Just a run through makes them seem generic and worth making useful to general users (outside of the tools folder anyway):

abstractPipelineWrapper.py
 - AbstractPipelineWrapper = subclassed to define wrapper scripts to run Toil pipelines in Docker
   - w/many assorted functions to handle this

files.py
 - tarball_files = Creates a tarball from a group of files
 - __forall_files = Applies a function to a set of files and an output directory
 - copy_file_job = Job version of move_files for one file
 - move_files = Moves files from the working directory to the output directory using shutil.move
 - copy_files = Moves files from the working directory to the output directory using shutil.copy
 - consolidate_tarballs_job = Combine the contents of separate tarballs into one
 - generate_file = Checks file existance, generates file, and provides message

jobs.py
 - map_job = Spawns a tree of jobs to avoid overloading the number of jobs spawned by a single parent

spark.py
 - spawn_spark_cluster
 - _checkContainerStatus
 - SparkService = A Service job that spins up a Spark cluster that child jobs can then attach to
   - w/start + stop + more functions
 - WorkerService = Service Job that implements the worker nodes in a Spark/HDFS cluster
   - w/start + stop + more functions

urls.py
 - download_url = Downloads URL, can pass in file://, http://, s3://, or ftp://, gnos://cghub/analysisID, or gnos:///analysisID
 - download_url_job = Job version of 'download_url'
 - _download_with_genetorrent
 - s3am_upload = Uploads a file to s3 via S3AM
 - s3am_upload_job = Job version of s3am_upload
 - _s3am_with_retry = Run s3am with 3 retries

validators.py
 - bam_quickcheck = Perform a quick check on a BAM via `samtools quickcheck`
 - require_bam_quickcheck
