### ISSUE TITLE
GA4GH-DREAM Challenge cwltoil pipeline can't find output file.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#1865]
Using the GA4GH-DREAM Challenge pipeline with cwltoil running biowardrobe fails (running locally).  It is the same error for multiple pipelines on the GA4GH-DREAM Challenge.  It complains about not finding a necessary output file, specifically:

In cwltoil.py, under the class ToilFsAccess(cwltool.stdfsaccess.StdFsAccess), the p variable in ToilFsAccess._abs attempts to find the file:

/tmp/toil-23e5f8c8-3b92-49f9-9ad2-fcfbdcad9499-21789b7fd99841a0b3dcc0c94da039ef/tmpILt07N/1d00e0e1-1614-4a87-bb20-da11c97b7563/t_EzUMS2PMlTF/tmp9oaTDF.tmp

file exists?: False
Instead, tmp9oaTDF.tmp is found here: [u'/tmp/tmplvtTBZ/tmp/s/g/tmp9oaTDF.tmp']
Error given:
    [job samtools-rmdup.cwl] Job error:
    ../../../tools/samtools-rmdup.cwl:99:3: Error collecting output for parameter 'rmdup_output':
    :1:1:   Did not find output file with glob pattern: '[u'tmp9oaTDF.tmp']'

I looked for the function with the error message and found the collect_output function in the draft2tool.py.  It does not seem to handle glob as expected (if it's a file or directory, then it gives this error and never builds r?).  It looks for something called: "outputEval" in binding, but never finds it, so it never writes 'r'.  This is on line 628 here: https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py

Also, I think lines 592 to 616, in the same file, are never used, since r will always be blank when it tries to read "files in r".

I've attached an admittedly pretty mangled output file with combined print statements, stdout, and logging.  The lines of interest are 851 - 857: 
[output_biowardrobe.txt](https://github.com/BD2KGenomics/toil/files/1289153/output_biowardrobe.txt)

I just reran this hopefully with the recently merged #1863 PR, but I am getting the same error as before unfortunately.

@tetron @mr-c @chapmanb

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-6)
┆Issue Number: TOIL-6

**Comment by chapmanb** [comment]
Thanks for the report on this. Would you be able to post the error you're getting when running bcbio? The error above looks like it came from biowardrobe or some other pipeline. We don't use glob outputs with bcbio and also don't have a samtools-rmdup tool. Hopefully I'll have more of an idea seeing what error bcbio generates. Thanks again.

**Comment by DailyDreaming** [comment]
I will!  Likely in the morning knowing bcbio.

**Comment by DailyDreaming** [comment]
It works.  Though now it doesn't delete any of the temp directories, so there are 860 folders left behind.  It doesn't see where the final output file is either, so that has to be moved, but otherwise it works!

**Comment by chapmanb** [comment]
Thanks much for testing this and the successful report. Glad to hear bcbio runs with the fixes. I've sent a PR to isolate the temp directories into the work folder to avoid the extra clutter. bcbio also has a wrapper that will clean these up on job completion to try and make the final output directory a bit cleaner. Thanks again for all the testing and suggestions.

**Comment by cricketsloan** [comment]
➤ Michael R. Crusoe commented:

@sckuhn Is this issue resolved?
