### ISSUE TITLE
Will toil ssh-cluster work with only the SSH key and without AWS credentials?

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1868]
I need @jeizenga to run on one of my clusters, but I can't give him my AWS credentials and he doesn't have his own.

Can he toil ssh-cluster into a cluster that I have set up, assuming I set it up with his public key? If not, how do you accomplish whatever toil ssh-cluster does manually, assuming you have the public key and maybe the cluster IP but not the AWS credentials for the owning account?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-200)
┆Issue Number: TOIL-200

**Comment by adamnovak** [comment]
I can't see how it possibly would, because otherwise how would it be able to find the instance given only the cluster name?

To replicate its functionality I think you have to:

```
ssh core@wherever
docker exec -ti toil_leader bash
```

**Comment by joelarmstrong** [comment]
Yes, you need to have AWS credentials (at least read-only EC2 permissions) to be able to find the IP of the leader.

Unfortunately, I don't think there's a palatable way around this if you want to provide *only* the cluster name. Maybe toil ssh-cluster could work with plain IPs as well? But I think that could cause collision issues if you have a cluster with an IP-like name.

**Comment by adamnovak** [comment]
Maybe it could have a --cluster-ip option to give the IP along with the
name.

**Comment by DailyDreaming** [comment]
This seems like it's no longer an issue, otherwise please reopen.
