### ISSUE TITLE
Cannot join current thread message is spurious and should not be printed

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#1873]
Whenever you ctrl+c a Toil single machine job you get a screenful of:

```
Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method CachingFileStore.__del__ of <toil.fileStore.CachingFileStore object at 0x7fb2eef32b90>> ignored
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/cluster/home/anovak/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/cluster/home/anovak/python/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/fileStore.py", line 1468, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
```

These messages do not provide any useful info to the user, and they suggest that the thread-joining code is too uninformed to know what thread it's running on and wants to join it anyway. The messages should be suppressed and/or the underlying spurious join calls should be removed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-202)
┆Issue Number: TOIL-202

**Comment by DailyDreaming** [comment]
Stale and I believe solved.  Please reopen if I'm incorrect.
