### ISSUE TITLE
Consider adding optional stats collection.

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1894]
For example,
https://gatkforums.broadinstitute.org/gatk/discussion/1250/what-is-phone-home-and-how-does-it-affect-me

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-205)
┆Issue Number: TOIL-205

**Comment by mr-c** [comment]
+1 for an *optional and opt-in* phone home, yes

**Comment by DailyDreaming** [comment]
Stale and not something we're considering at this time.
