### ISSUE TITLE
singleMachine batchSystem may be really inefficient

### ISSUE THREAD

**Issue by joelarmstrong** [DataBiosphere/toil#1902]
Currently, the singleMachine batch system launches a huge number of threads: 10 times the maxCores number. All these threads contend on a single queue waiting for jobs to appear. When they do get a job, they hold onto it and try to contend until a "resource pool" has enough resources to continue, and they can get an exclusive lock on the pool so they can decrement it.

This seems pretty inefficient. We could get the same behavior by just having one thread spin waiting for resources and monitoring the Popen objects. It's not totally clear how much speed we'd get from doing it with fewer threads, but it definitely shouldn't hurt. Plus, this will get rid of the uber-annoying "Recieved termination signal" tens or hundreds of times when exiting a single-machine Toil workflow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-208)
┆Issue Number: TOIL-208

**Comment by diekhans** [comment]
This can be easily and efficiently addressed by using an
event-oriented programming.

In it's simplest form, a single thread could be responsible for
starting the subprocesses.  Each subprocess would have stdout
pipe coming back to the leader.  Select or another I/O polling
mechanism then waits for any pipe to become read-ready; if an
EOF is returned, then that child process has terminated.

   https://docs.python.org/2/library/select.html

The python-3 async module could be a higher-level way to
implemented it with trollius
(https://pypi.python.org/pypi/trollius) providing an
implementation for python-2.

Probably other approaches, although, while select/poll is a
little tedious to program, it is rather straight forward in what
it does.

Recommend against using SIGCHLD, as the global nature or signals
can be very difficult to implement.

**Comment by joelarmstrong** [comment]
I have a quick draft of a better single-machine batch system, though it's not ready yet and I won't have much time to fix it up in the near future. But that lets us run some tests to quantify how inefficient the current system is. When using 64 cores, sorting 10000 lines using the sort test takes 42.5 +/- 13.6 s. Under my experimental batch system without the contention, it takes 29.2 +/- 5.8 s. So for very large systems, this can reduce toil overhead by 50%. Obviously the sort test runtime is pretty much only overhead, so the gains in practice would be quite a bit smaller.

With 8 cores there's very little noticeable difference, less than 10%. (There's almost an order of magnitude less contention.) So fixing this may not do all that much for people running on their laptops.

**Comment by ejacox** [comment]
Is it ready enough for a PR?

**Comment by adamnovak** [comment]
It might be time to actually redo the single machine batch system, what with all the issues we get from people complaining it starts too many/the wrong number of threads (https://github.com/DataBiosphere/toil/issues/2308#issuecomment-588353477, 2928, etc.).

@joelarmstrong Did your reimplementation get lost, or is it around somewhere? I could step up and polish it up for inclusion if you wanted to hand it off. Otherwise I can try starting over myself.
