### ISSUE TITLE
Use the underscore correctly.

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#1916]
Many functions and parameters prefixed with an underscore are used publicly. Also, private functions and parameters should all start with an underscore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-209)
┆Issue Number: TOIL-209

**Comment by diekhans** [comment]
Python enforces `private' member names by mangling names
starting with double underscore (__).

Personally, I use `__' for private fields and methods, however
PEP8 seems to dance around this and recommends __ to limit
name collisions on inheritance, but doesn't forbid __
from mean private either.

PEP8 also recommends punch-card compatibility ;-)
