### ISSUE TITLE
CoreOS cloud-config deprecated

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/toil#1961]
The [method](https://github.com/BD2KGenomics/toil/blob/2c2c288e28df8e83984c12ade7777ea6d43f2fea/src/toil/provisioners/aws/__init__.py#L204) we're using to configure CoreOS with the AWS provisioner is now [deprecated](https://coreos.com/os/docs/latest/cloud-config.html). This isn't an urgent issue but will likely block us if we update the version of CoreOS we use in the future for whatever reason (for reference, the AWS provisioner uses v1235.4.0 and the current version is v1590.0.0).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-217)
┆Issue Number: TOIL-217

**Comment by adamnovak** [comment]
This is now tracked in #2627.
