### ISSUE TITLE
Implement batch system multiplexing

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#197]
For tasks with short-running jobs (e.g. cactus) built on long-latency batch schedulers (e.g. SGE) , the one to one mapping of toil jobs to batch system jobs becomes a bottleneck.  This also hampers portability  between batch systems, as workflows must be parametrized radically differently.

Having a given batch system job run a serially run multiple toil jobs will abstract away batch system latency.

Given this doesn't current matter for direct cancer pipeline ports, this is lower priority than getting PANCAN pipeline going.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-219)
┆Issue Number: TOIL-219

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

Job chaining has been implemented.
