### ISSUE TITLE
Toil gets in infinite loop trying to connect to server if the user's ssh ID has a passphrase on it

### ISSUE THREAD

**Issue by jeizenga** [DataBiosphere/toil#2006]
I had a passphrase on my `~/.ssh/id_rsa`, and Toil would get into a loop repeating this forever until I removed the passphrase:

```
2018-01-05 16:26:52,265 - toil.provisioners.aws.awsProvisioner - INFO - Attempting to establish SSH connection...
Warning: Permanently added 'ec2-35-167-98-105.us-west-2.compute.amazonaws.com,35.167.98.105' (ECDSA) to the list of known hosts.
Permission denied (publickey,password,keyboard-interactive).
2018-01-05 16:26:52,853 - toil.provisioners.aws.awsProvisioner - INFO - Connection rejected, waiting for public SSH key to be propagated. Trying again in 10s.
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-223)
┆Issue Number: TOIL-223

**Comment by DailyDreaming** [comment]
Toil blocks on any runtime error until it connects, so this is a known issue.  It could definitely be handled better with smarter error handling.  I'll try to fix this for the passphrase case.

**Comment by adamnovak** [comment]
@cmarkello just ran into this too; if it can't be fixed it at least needs to be documented in the hello world tutorial.

**Comment by cmarkello** [comment]
So @adamnovak gave me a workaround which works, but is probably not ideal security-wise. What worked was resetting the password to decrypting the private ssh key to null via `ssh-keygen -p`.

**Comment by ecerami** [comment]
Hi.  I followed the instructions at:  https://toil.readthedocs.io/en/latest/running/cloud/amazon.html, and I am getting the same error, e.g. 

INFO:toil.provisioners.node:Connection rejected, waiting for public SSH key to be propagated. Trying again in 10s.

I tried removing my passphrase, and uploaded the new public key to AWS, but am still getting the same error message.

Any more suggestions?
