### ISSUE TITLE
Make Toil citation more explicit.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2010]
I thought it might be a good idea to, at the beginning of the toil documentation, provide our citation in addition to the link to attempt to boost citations (and therefore track use cases).  Thoughts?

PR #2011

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-427)
┆Issue Number: TOIL-427

**Comment by mr-c** [comment]
This should be added to the main README and in a `CITATION.md` like https://github.com/idris-lang/Idris-dev/blob/master/CITATION.md

**Comment by mr-c** [comment]
Bonus would be https://citation-file-format.github.io/ as well
