### ISSUE TITLE
CWL samples in tutorial doesn't work with toil-cwl-runner

### ISSUE THREAD

**Issue by Huiziryuu** [DataBiosphere/toil#2021]
I made a sample for testing CWL in toil supplied in Toil [tutorial](https://toil.readthedocs.io/en/3.12.0/gettingStarted/quickStart.html#cwlquickstart) , test files are attached as well.
[cwlExample.zip](https://github.com/BD2KGenomics/toil/files/1638875/cwlExample.zip)

by command `toil-cwl-runner example.cwl example-job.yaml`

I got a stack of INFO trace log, no errors, however, the result output file was not produced.

I tested using cwltool by `cwltool example.cwl example-job.yaml`

the output file is produced within the same folder which contains the inputs.
Could you have a look anything wrong when I use toil?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-54)
┆Issue Number: TOIL-54

**Comment by DailyDreaming** [comment]
Weird, it's actually working on mine (Ubuntu 16.04) with your files.  Could you check on your toil version with `toil --version`?

**Comment by Huiziryuu** [comment]
yup, the version is 3.13.0, I installed through pip 2 days ago, the OS is Ubuntu Linux.
