### ISSUE TITLE
CWL: Comparison of File objects often incorrectly exclude secondaryFiles

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#2076]
This is an issue in the `src/toil/cwl/cwltoil.py`

The companion `cwltool` issue: https://github.com/common-workflow-language/cwltool/issues/667

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-229)
┆Issue Number: TOIL-229

**Comment by DailyDreaming** [comment]
Two years old and I'm unsure if this is still an issue.  If it is, please reopen this, otherwise I will assume that this has been solved since I haven't seen anyone complain about it recently.
