### ISSUE TITLE
New logo for Toil

### ISSUE THREAD

**Issue by reallinfo** [DataBiosphere/toil#2128]
Hello, I designed a logo for Toil. If you like it, I will give you this logo as a gift.

![logotype](https://user-images.githubusercontent.com/36298335/37374095-2d6456bc-2722-11e8-8f5a-dad902555505.jpg)
![logotype2](https://user-images.githubusercontent.com/36298335/37374096-2d8c5e1e-2722-11e8-9e8c-9c79161cd628.jpg)
![view2](https://user-images.githubusercontent.com/36298335/37374098-2db2024a-2722-11e8-8051-39cca338d253.jpg)
![view3](https://user-images.githubusercontent.com/36298335/37374099-2dde300e-2722-11e8-8d02-32c39c5691cc.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-235)
┆Issue Number: TOIL-235

**Comment by benedictpaten** [comment]
Very cute! Thank you for the effort, we'll talk it over as a team.

**Comment by reallinfo** [comment]
Thanks! After you make a decision, I will send you the necessary files if you post messages.
