### ISSUE TITLE
fix flaky Google cache eviction fail test

### ISSUE THREAD

**Issue by ejacox** [DataBiosphere/toil#2129]
src.toil.test.src.fileStoreTest.CachingFileStoreTestWithGoogleJobStore.testCacheEvictionFailCase

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-236)
┆Issue Number: TOIL-236

**Comment by DailyDreaming** [comment]
Stale.
