### ISSUE TITLE
AbstractGridEngineBatchSystem.getJobExitCode should throw an exception instead of using 1 as the return in case the job itself failed

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#2133]
See https://github.com/BD2KGenomics/toil/pull/2062#discussion_r167797985

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-239)
┆Issue Number: TOIL-239

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

We just reworked job exit code handling a bit. I think we decided not to actually do this.
