### ISSUE TITLE
CWL runner generates too many log files

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2146]
I've run 47 paired fastqs through a pipeline with Toil 3.14.0 and the workflow has generated 11,312 log files totaling 8.4 GB. It looks like there is a new log file created once per minute for each job

[All log files](https://gist.githubusercontent.com/ionox0/21439af324798ff287134cfe8f934c0e/raw/61c99ea2b26cda2b1c637cbf292f59b7f2b3b761/all_logs.sh)

[All logs for BWA step](https://gist.githubusercontent.com/ionox0/b136677dd69cb02bdb05f241c28991c0/raw/2e4dc98fe3c1ead9c33124490f68ab61e87ab478/all_bwa_logs.sh)

A lot of the files have "Bac" in the title, and this run is not finished. Does this mean that those are just backup files and will be deleted onSuccess?

The count of files that don't have "Bac" in the title is 92, which is close to 2x the number of fastq pairs that I'm running the pipeline on. So perhaps there's just two log files for each fastq that gets run. 

I'm not sure whether this is an issue or the intended behavior, but any suggestions or comments  would be appreciated. 

Thank you,
Ian

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-242)
┆Issue Number: TOIL-242

**Comment by DailyDreaming** [comment]
Stale.  If this is still an issue, please reopen.

**Comment by ionox0** [comment]
Thank you, yes I believe this has been fixed
