### ISSUE TITLE
Toil leaks open files that prevent job store deletion

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2162]
With #2157 in I have better visibility into a problem I have been having where the job store can't be cleaned up:

```
leader.py                  485 INFO     Job ended successfully: 'run_map_eval_align' 9/S/jobLrGOF2
leader.py                  546 INFO     Finished the main loop: no jobs left to run
serviceManager.py          156 INFO     Waiting for service manager thread to finish ...
serviceManager.py          163 INFO     ... finished shutting down the service manager. Took 0.198056936264 seconds
statsAndLogging.py         156 INFO     Waiting for stats and logging collator thread to finish ...
statsAndLogging.py         160 INFO     ... finished collating stats and logs. Took 0.173548221588 seconds
leader.py                  240 INFO     Finished toil run successfully
realtimeLogger.py          175 INFO     Stopping real-time logging server.
realtimeLogger.py          179 INFO     Joining real-time logging server thread.
fileJobStore.py            159 WARNING  Cannot delete /cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l/T; retrying in 1 seconds
fileJobStore.py            139 WARNING  Open NFS files like /cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l/T/.nfs0000000000b626210007d20b may prevent job or job store deletion
fileJobStore.py            159 WARNING  Cannot delete /cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l/T; retrying in 2 seconds
fileJobStore.py            159 WARNING  Cannot delete /cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l; retrying in 1 seconds
fileJobStore.py            159 WARNING  Cannot delete /cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l/T; retrying in 1 seconds
...
common.py                  706 INFO     Failed to delete the job store: <toil.jobStores.fileJobStore.FileJobStore object at 0x7f3ce16a8610>
```

The "..." elides a bunch of looping and retrying the delete (it seems that each level of the recursion gets its own retries, which I didn't think about when I wrote #2157 and which may cause delays).

But the underlying problem is that line about `/cluster/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/l/T/.nfs0000000000b626210007d20b` which is cluttering up the job store. As Toil is trying to delete the job store, some process (probably Toil's Python process itself, since that file is gone now that the Toil job is done) has an open file handle to something in the job store.

It's not clear if this is a file handle leak from user code opening and not closing a file in the file store (is that even where the file store lives?), or if something in Toil itself is holding this file open. Either way, the job store can't be cleaned up until it is closed.

- User code needs to be prevented from leaking open file handles to things in the job store.
- Toil code needs to make sure that everything in the job store is closed before the job store is deleted.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-244)
┆Issue Number: TOIL-244

**Comment by diekhans** [comment]
While this problem should be addressed, Adam's issue can be be
bypassed by not putting the job store under /cluster/home, which is
a NFS file system.  Data files for use on the cluster should be
on the /hive/ GPFS

Using /cluster/home for data files hit by the cluster is a
violation of the Browser terms of use agreement you signed
blood.  The potential punishment is harsh: having Jim get grumpy
at you!

**Comment by adamnovak** [comment]
The tests are all single-machine batch system runs; I'm not actually
hammering /cluster/home with the cluster machines in parallel.

I've been using /cluster/home to run the vg tests, because I keep the vg
source tree in my home directory (which is what it's for, I think) and the
tests use Toil and are designed to be run out of the source tree.

But since the vg tests can involve nontrivial computing (which is why they
want Toil), maybe they need to be engineered for out-of-source-tree storage
of the job stores.

**Comment by diekhans** [comment]
git is a bit slower on gpfs, but unless the tree is absurdly large (like
the browser tree), it is still usable.  It gets you away from NFS until
this stuff can be fixed.

**Comment by adamnovak** [comment]
This issue is now a bigger problem for me than it was before, because on the new Courtyard system we no longer have a GPFS mount. Both /public/home (home directories) and /public/groups (group data) are NFS mounts, and some of the software I'm working with really wants to be able to make Toil job stores inside the source tree, for running and debugging tests.

**Comment by adamnovak** [comment]
I've gotten some more logging information; this is happening when a file like `/public/home/anovak/build/vg/vgci-work/jobstoresim-MHC-cactus/tmp/j/W/tmpENGrYM.tmp` is open (as FD 8) in the Toil leader process (which for me is something like `'/public/home/anovak/build/vg/.env/bin/python' '/public/home/anovak/build/vg/.env/bin/pytest' '-vv' 'jenkins/vgci.py::VGCITest::test_sim_mhc_cactus' '--junitxml=test-report.xml'`), while the Toil context manager is trying to destroy the job store. The file in question is empty, but I'm not having much luck working out where it gets created (besides being from `_getTempFile` in the `fileJobStore`), or why it gets opened by the leader, or why it isn't closed. I suspect it might be a log file from a job that is getting read by the leader, but those ought to all be closed by the time the context manager wants to clean up, right?

**Comment by adamnovak** [comment]
OK, after a bunch of tinkering around, I still don't really know how the FD is escaping, but I do know that it stops doing it if I change the implementation of `writeFileStream`:

https://github.com/DataBiosphere/toil/blob/024e08525e13fb01aa5d077ef3b1b5def4479503/src/toil/jobStores/fileJobStore.py#L298-L303

If I replace this with an implementation more like `writeFile`, where it creates a file name with `_getUniqueName`, and doesn't rely on coming back after the yield to close the file, I don't seem to leak the file descriptor.

Unfortunately, I was making that change so I would be able to tell where the file was being written from, by putting the caller in the name. So I still have no good reason for the problem, but I do have a solution that I will PR.

**Comment by adamnovak** [comment]
It looks like `writeFileStream` no longer uses `_getTempFile` and works like `writeFile` does now:

https://github.com/DataBiosphere/toil/blob/422a73cc32fcbcde880eab6c41a97550ac473119/src/toil/jobStores/fileJobStore.py#L373-L381

I've run job stores on NFS a few times with Toil ~3.21 ish, and I haven't had this problem happen to me. I think this has been fixed.
