### ISSUE TITLE
high virtual memory usage of toil-cwl-runner

### ISSUE THREAD

**Issue by pkp124** [DataBiosphere/toil#2172]
Hello,

When running some tests, I noticed that the virtual memory usage of the toil-cwl-runner was high depending on the machine on which it was running.

When running on a machine with 128GB RAM and 48 cores, the virtual memory usage as reported by "top" was ~ 28GB. But when the same tests were run on a machine with 64GB RAM and 8 cores, the virtual memory as reported by top was 5 MB. Although this is not a pressing issue, it could be related to an unexposed bug.

The command that can be used to reproduce the issue:
_toil-cwl-runner --batchSystem gridEngine --logDebug --disableCaching --retryCount 0 --clean never --cleanWorkDir never  common-workflow-language/v1.0/v1.0/binding-test.cwl common-workflow-language/v1.0/v1.0/bwa-mem-job.json

where common-workflow-language/v1.0/v1.0/binding-test.cwl and common-workflow-language/v1.0/v1.0/bwa-mem-job.json are taken from the CWL conformance test suite. Any test case from the conformance test suite can be used to reproduce the issue.
.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-248)
┆Issue Number: TOIL-248

**Comment by DailyDreaming** [comment]
Thanks for reporting the issue. This isn't pressing right now as you mentioned, but I will keep it in mind in future batch system work for gridEngine.

**Comment by adamnovak** [comment]
Virtual memory address space size is mostly managed by `python`, under the level at which Toil works. The virtual memory usage statistic just measures the address space size, not the amount of RAM used for storing Toil's data (which would be the RSS or resident set size).

Some people to use ulimits on virtual memory address space size, but unless there's an actual problem resulting from Toil bumping up against such a limit, I wouldn't consider Toil sometimes having its Python have a large address space as a bug.
