### ISSUE TITLE
Exceeding node limits doesn't shut down workers

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2196]
(mentioned here #2195 but I think deserves its own issue).

If my script tries to provision a node that exceed's my account limit, my workflow stops.  And if I dig through my logs carefully I can even find the reason.  

`<Response><Errors><Error><Code>InstanceLimitExceeded</Code><Message>You have requested more instances (5) than your current instance limit o\
f 2 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit\
.</Message></Error></Errors><RequestID>18798351-a418-4a4c-8afb-e4d342681907</RequestID></Response>
`

But unlike failures for other reasons, Toil does not seem to stop my worker nodes in this case: I have to terminate them by hand.  This seems dangerous, as it can lead to people forgetting they have instances running..

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-252)
┆Issue Number: TOIL-252

**Comment by adamnovak** [comment]
This is a duplicate of #1699.
