### ISSUE TITLE
grafana doesn't show any data

### ISSUE THREAD

**Issue by oskotsky** [DataBiosphere/toil#2202]
i am trying to use grafana with toil 3.15. grafana seems to be running but empty. no any data, just black squares. is it a known problem? Thank you.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-255)
┆Issue Number: TOIL-255

**Comment by adamnovak** [comment]
This is over a year old now; I am going to assume you have given up @oskotsky. Please feel free to reopen it if you still want support for this issue, in which case it would be helpful to provide us a way to reproduce the problem. Grafana has been working fine for us all year.
