### ISSUE TITLE
.rv() path cannot be used to index into nested promises

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2214]
I have a job (job A) that calls two other jobs (job B and job C), and returns a pair of promises. Jobs B and C return their own tuples, so conceptually the whole result is a nested structure of tuples.

```
def job_A(job):
    job_b = job.addChildJobFn(job_B)
    job_c = job.addChildJobFn(job_C)
    return job_b.rv(), job_c.rv()

def job_B(job):
    return 1, 2

def job_C(job):
    return 3, 4

```

Then I have another job that does something like this:

```
def anotherJob(job):
    child = job.addChildJobFn(job_A)
    followOn = job.addFollowOnJobFn(yetAnotherJob, child.rv(0, 1))
    return followOn.rv()

def yetAnotherJob(job, arg):
    return arg
```

Basically, I am trying to take a promise for a tuple with promise-for-tuple elements, and index through both levels of promise at the same time.

It looks like the indexing is being executed when the top-level promise resolves, but before the nested promises are filled in:

```
WARNING:toil.leader:S/s/jobGrA79E    Traceback (most recent call last):
WARNING:toil.leader:S/s/jobGrA79E      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/worker.py", line 313, in workerScript
WARNING:toil.leader:S/s/jobGrA79E        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:S/s/jobGrA79E      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1329, in _runner
WARNING:toil.leader:S/s/jobGrA79E        self._serialiseExistingJob(jobGraph, jobStore, returnValues)
WARNING:toil.leader:S/s/jobGrA79E      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1251, in _serialiseExistingJob
WARNING:toil.leader:S/s/jobGrA79E        self._serialiseJobGraph(jobGraph, jobStore, returnValues, False)
WARNING:toil.leader:S/s/jobGrA79E      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 1214, in _serialiseJobGraph
WARNING:toil.leader:S/s/jobGrA79E        self._fulfillPromises(returnValues, jobStore)
WARNING:toil.leader:S/s/jobGrA79E      File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil/job.py", line 963, in _fulfillPromises
WARNING:toil.leader:S/s/jobGrA79E        promisedValue = promisedValue[index]
WARNING:toil.leader:S/s/jobGrA79E    TypeError: 'Promise' object does not support indexing
```

The relevant code is here:

https://github.com/BD2KGenomics/toil/blob/45de1029ae190b8e0bb3a4addcc7ebc7bec69173/src/toil/job.py#L954-L963

It looks like the loop at the end for indexing by each component of the path needs a check for whether it has hit a promise. Then that promise may itself need to be recursively resolved, or something.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-93)
┆Issue Number: TOIL-93

**Comment by DailyDreaming** [comment]
@adamnovak Yes, that would be a useful feature to resolve promises that way.  In terms of "best practice", and I use that term loosely, I've found it's a useful convention to return one dictionary per job, containing all of the return values.  So your code could be changed to look something like:

```
def job_A(job):
    job_b = job.addChildJobFn(job_B)
    job_c = job.addChildJobFn(job_C)
    value1 = job_b.rv('value1')
    value2 = job_b.rv('value2')
    value3 = job_c.rv('value3')
    value4 = job_c.rv('value4')
    return {'value1': value1, 'value2': value2, 'value3': value3, 'value4': value4}

def job_B(job):
    return {'value1': 1, 'value2': 2}

def job_C(job):
    return {'value3': 3, 'value4': 4}
```

This should work for your purposes.  For a bit more verbose example, see any class named "scatter*" in the attached file.  It's very ugly, but it conveys the point: [toilwdl_compiled.txt](https://github.com/BD2KGenomics/toil/files/2011337/toilwdl_compiled.txt)

@arkal In practice, jobs can return the follow-on promises they create.

**Comment by diekhans** [comment]
or if you use a namedtuple, you can have an object with fields,
rather than a map.
