### ISSUE TITLE
Version-pinned, outdated boto3 dependency causes problems when installing toil alongside awscli

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2230]
The fundamental problem here is that pip can't solve dependency constraints and select a pair of toil and awscli versions that agree on what version of botocore needs to be installed (see https://github.com/pypa/pip/issues/988).

You ought to be able to do:
```
pip install toil[aws,mesos] awscli
```

But this doesn't work, because it tries to install the current version of both packages. Toil depends on `boto3==1.4.7`:
https://github.com/BD2KGenomics/toil/blob/e14b41e7552e2aa7c161e01f93b8260299590e2d/setup.py#L24

Which in turn depends on `botocore>=1.7.0,<1.8.0`:
https://github.com/boto/boto3/blob/9d5fac2a36a31b9665a8d80c7dfe8df9fac4ceb3/setup.py#L17

But the current awscli depends on `botocore==1.10.30`:
https://github.com/aws/aws-cli/blob/9b781a5796fc950a295cc2b000f640dcdc8cd6ab/setup.py#L26

Which in turn can only be used by Boto3 1.7.0 or higher, but which will stop working when Boto3 1.8.0 comes out (since they keep the minor versions in sync):
https://github.com/boto/boto3/blob/6374e82f1d5879c4abef3873606812cd838b68e3/setup.py#L17

So there's no version of botocore that can be installed to make both Toil and awscli happy. And having one tool or the other trying to use the wrong version has caused me mysterious problems in the past; botocore is an internal module for boto/AWS things and is not very cross-compatible.

If we can't let the Toil boto3 version just float (`boto3>=1.4.7` or maybe `boto3>=1.4.7,<2.0`), Toil needs to keep up to date with Boto3 releases, so that it can be installed alongside whatever the current awscli is without problems.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-261)
┆Issue Number: TOIL-261

**Comment by adamnovak** [comment]
This is particularly troublesome because if you get this configuration:

```
awscli                       1.14.70
boto                         2.38.0   
boto3                        1.6.7    
botocore                     1.9.23   
toil                         3.16.0
```
Then you can be in a situation where toil can create clusters but it cannot destroy them:

```
toil destroy-cluster 'wgcluster' -z us-west-2a
INFO:toil.lib.bioio:Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Traceback (most recent call last):
  File "/public/home/anovak/.local/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/public/home/anovak/.local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 34, in main
    module.main()
  File "/public/home/anovak/.local/lib/python2.7/site-packages/toil/utils/toilDestroyCluster.py", line 28, in main
    cluster.destroyCluster()
  File "/public/home/anovak/.local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 203, in destroyCluster
    instances = self._getNodesInCluster(nodeType=None, both=True)
  File "/public/home/anovak/.local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 87, in wrapper
    return f(*args, **kwargs)
  File "/public/home/anovak/.local/lib/python2.7/site-packages/toil/provisioners/aws/awsProvisioner.py", line 496, in _getNodesInCluster
    allInstances = self._ctx.ec2.get_only_instances(filters={'instance.group-name': self.clusterName})
  File "/public/home/anovak/.local/lib/python2.7/site-packages/boto/ec2/connection.py", line 622, in get_only_instances
    next_token=next_token)
  File "/public/home/anovak/.local/lib/python2.7/site-packages/boto/ec2/connection.py", line 681, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/public/home/anovak/.local/lib/python2.7/site-packages/boto/connection.py", line 1170, in get_list
    response = self.make_request(action, params, path, verb)
  File "/public/home/anovak/.local/lib/python2.7/site-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/public/home/anovak/.local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by adamnovak** [comment]
For the record, a working configuration is:

```
pip install toil[aws,mesos,azure]==3.16.0 awscli==1.11.190 boto3==1.4.7 botocore==1.7.48
```

**Comment by adamnovak** [comment]
I think some of the "Name or service not known" business was caused by intermittent DNS failures on the machine I was using. Maybe just opening up the version specifier like in #2233 is enough?

**Comment by NeolithEra** [comment]
Perhaps you could try a dependency diagnosis website e.g. http://www.watchman-pypi.com/dependency_analysis. This can help diagnose dependency conflict problems and automatically visualize your full dependency tree and those of your downstream projects.

Best,
Neolith

**Comment by brainwane** [comment]
pip 20.3 has the new dependency resolver on by default; please see [the documentation on how to test and migrate](https://pip.pypa.io/en/latest/user_guide/#how-to-upgrade-and-migrate) in case it helps you address this problem.
