### ISSUE TITLE
s3 support for toil-cwl-runner?

### ISSUE THREAD

**Issue by IanMcDowell** [DataBiosphere/toil#2234]
The quickstart guide states:
>When running a CWL workflow on AWS, input files can be provided either on the local file system or in S3 buckets using s3:// URI references. Final output files will be copied to the local file system of the leader node."

However, I consistently get the error at this point in the code:
`"file." % (knownfile, self.pathmapper.mapper(knownfile)[0]))`
reporting:
`WorkflowException: Input file https://s3.amazonaws.com/<bucket>/<file> (at //s3.amazonaws.com/<bucket>/<file>) not found or is not a regular file.`

or, if I use the `s3://` URI system I get:
`WorkflowException: Input file s3://<bucket>/<file> (at //<bucket>/<file>) not found or is not a regular file.`

where `<bucket>` and `<file>` are obviously filled in with my specific bucket and file.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-103)
┆Issue Number: TOIL-103

**Comment by DailyDreaming** [comment]
Not sure what's going on there.  Will try to give it a go this weekend.

**Comment by nikhil** [comment]
Just wondering if there was an update to this? I am also getting this error in Toil version 3.18.1a1

**Comment by IanMcDowell** [comment]
I ended up having to create utilities to transfer files from S3 to the leader node.

**Comment by aesrth** [comment]
This also seems to affect secondary files with s3 links set as their "location"

**Comment by BJWiley233** [comment]
Very hard to tell whether this issue has been addressed here?

**Comment by DailyDreaming** [comment]
@BJWiley233 `s3://` files are supported but not s3:// as a `Directory` type.  The `rsync-cluster` command should not be needed for s3 inputs as long as 1. you have proper credentials to access the s3:// objects available and 2. it is not a `Directory` type.

**Comment by DailyDreaming** [comment]
@BJWiley233 If this is not the case and you are having trouble with `s3://` `File` type inputs, please reopen.

**Comment by BJWiley233** [comment]
Thanks.  I just realized that the inputs were meant for the input to the CWL.  So I am trying this with a hg38 reference file and vcf input to bcftools.  I have to manually do `toil ssh-cluster` into the leaderNode and add in my .aws/credentials.  After that however my cwl job is getting killed.  The inputs are under 4GB total but even in the t2.large it gets `killed`.  My first questions is how can we automactically enter the .aws/credentials in `toil ssh-cluster --zone us-west-2a test-cluster toil-cwl-runner` and secondly how to find why it's getting killed?

**Comment by DailyDreaming** [comment]
@BJWiley233 If launch-cluster was specified with AWS, the instance should already contain the credentials needed.

Is the leader node getting killed or the job or an rsync?

It's late here, but if you leave your run steps so that I can reproduce this, I'll try it in the morning.

**Comment by BJWiley233** [comment]
Yes here are my steps.  Thanks!

```
aws ec2 import-key-pair --key-name "my-key2" --public-key-material fileb://~/.ssh/id_rsa.pub

toil launch-cluster test-cluster --zone us-west-2a --leaderNodeType t2.large --keyPairName my-key2

toil rsync-cluster --zone us-west-2a test-cluster _bcftools_norm.cwl _norm.yml :/tmp

toil ssh-cluster --zone us-west-2a test-cluster 

mkdir ~/.aws
## to add in my Access ID and Key
vim ~/.aws/credentials

toil-cwl-runner /tmp/_bcftools_norm.cwl /tmp/_norm.yml 

toil destroy-cluster test-cluster
```

**Comment by DailyDreaming** [comment]
@BJWiley233 Hmmm... I think I see the problem.  You're supposed to run as an autoscaling job, so the command you use should look something like:

```
toil-cwl-runner --jobstore=aws:us-west-2:some-jobstore-name --provisioner aws --nodeTypes t2.large --maxNodes 2 --batchSystem mesos /tmp/_bcftools_norm.cwl /tmp/_norm.yml
```

 `~/.aws/credentials` is not there but toil has AWS credentials.  It's only intended to serve as the leader node for an autoscaling cluster though (controlling multiple instances), otherwise, if you just want to run a single job on an instance, I'd just recommend spinning up an Ubuntu instance and running `toil-cwl-runner /tmp/_bcftools_norm.cwl /tmp/_norm.yml ` with a normal aws + toil installation setup.

If you do need an autoscaling group however, I'd also recommend trying out the kubernetes batch system.

**Comment by BJWiley233** [comment]
ok thanks for the response.  I just started with toil yesterday.  I guess I missed in the documentation where you would run a "normal aws + toil installation setup".  I would prefer to start with that first over autoscaling. I tried cgcloud but could not compile on macOS.  

Following this documentation I cannot see where you would actually launch the workflow after the step of `rsync-cluster`.  
https://toil.readthedocs.io/en/latest/running/cloud/amazon.html#uploading-workflows

Do I have to ssh into the Ubuntu instance afterwards?

**Comment by BJWiley233** [comment]
Also is there a command that will terminate the instances after I run `toil destroy-cluster`?  This didn't shut down the instances and I was still billed.  Do we manually need to terminate the instances through the aws cli or AWS console?
