### ISSUE TITLE
Toil will stop if it requests more spot instances than your AWS account limits

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2238]
I'm trying to use Toil with spot instances in a shared AWS account.

If Toil makes a spot instance request that would put it over the account limits (summing over my workflow and any other workflows running on the account), Amazon returns an error, and Toil kills the whole workflow.

Instead, it should continue the workflow, with the actual number of instances running limited by the account instance limits. Since spot instances can be unavailable in the requested quantity for any number of reasons (such as the spot price being too high), it shouldn't be a fatal error for the workflow if it can't get all the instances it would like.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-264)
┆Issue Number: TOIL-264

**Comment by DailyDreaming** [comment]
Really good point.  Thanks for creating the issue.

**Comment by adamnovak** [comment]
This is actually a duplicate of #1699.
