### ISSUE TITLE
No documentation for the FileID.size attribute appears on ReadTheDocs

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2278]
I have a job that needs to use some files from the file store. I initially tried with with just 1 GB of disk, but that's not enough to download the files that it wants to work with.

I'm trying to rewrite the job to measure how big the files it wants to use are, and to re-queue itself with the appropriate amount of disk required, so it can actually download them. But the file store doesn't seem to expose a file size query. All you can do with a file in the file store is read it---and I think even if you read it streaming, your job is liable to fail if the file is bigger than the amount of disk available on the node you are running on.

The file store needs to expose file sizes, so that jobs can know how much disk they need to ask for in order to use particular files.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-296)
┆Issue Number: TOIL-296

**Comment by joelarmstrong** [comment]
Use the `size` attribute. The filestore methods should all return a FileID object, which contains both the ID string and a size.

**Comment by adamnovak** [comment]
There's no mention of this feature on http://toil.readthedocs.io/en/3.15.0/developingWorkflows/toilAPIFilestore.html and I can't find a page on ReadTheDocs for the FileID type.

So this looks like a documentation problem.

**Comment by joelarmstrong** [comment]
Yeah, it really should be documented somewhere.
