### ISSUE TITLE
Integrate WES into TOIL

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2279]
┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/TOIL-297)
┆Issue Number: TOIL-297

**Comment by cricketsloan** [comment]
This was an epic that had all of the subtickets closed.  If there are more tasks to add, we can reopen it.  Or if it is confusing to have Jira Epics in the git issues, we can prevent synchronization in the future.


Subtickets
toil/2289
toil/2288
toil/2286
toil/2290

[TLP-359](https://ucsc-cgl.atlassian.net/browse/TLP-359)  WES + Toil on AWS running TOPMed alignment workflow
[TLP-413](https://ucsc-cgl.atlassian.net/browse/TLP-413)   WES WDL unittest passing with toil.

**Comment by mr-c** [comment]
Thank you @cricketsloan for the explanation. I guess I'm used to seeing tickets closed with a link to the PR(s)
