### ISSUE TITLE
Update the coreos/docker image to handle cwltool in autoscaling.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2287]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-304)
┆Epic: Autoscaling Improvements
┆Issue Number: TOIL-304

**Comment by mr-c** [comment]
The Jira integration is very frustrating from the GitHub side. @DailyDreaming why was this rejected?

**Comment by cricketsloan** [comment]
@mr-c  Separating the fact that no rejection comment was left when this ticket was closed, can you help me to understand how the JIRA integration is bothering you.  In this ticket I see the connections posted, but I do not see excessive chatter nor information being lost from the synchronization.  As I run the sync, I am always looking for ways to make it more streamlined.


I will leave it to @DailyDreaming to add a rejection explanation comment.

**Comment by mr-c** [comment]
@cricketsloan It is the lack of rejection reason; hopefully it was "not needed". Also, there were 20+ emails on Sunday for no readily apparent reason?

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

Well, the lack of reason is not a JIRA or github issue.  Although, I think I can make JIRA force one to put something in the comment.  The chatty emails I can look into.  It was likely Lon assigning Epics, which do show in the description, but are a less than obvious change.
