### ISSUE TITLE
expose --docker-pull in toil-cwl-runner

### ISSUE THREAD

**Issue by IanMcDowell** [DataBiosphere/toil#2311]
When in the development phase of testing a cwl pipeline using toil-cwl-runner, I may revise and push updated Docker images. By default, however, cwltool does not pull an updated docker image if there is already a docker image present (see, e.g. [cwltool issue #422](https://github.com/common-workflow-language/cwltool/issues/422)). cwltool can be forced to pull images, though, with `--docker-pull`. Can  this argument be exposed to toil-cwl-runner to enable this behavior?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-321)
┆Issue Number: TOIL-321

**Comment by DailyDreaming** [comment]
#2316 should fix this.

**Comment by DailyDreaming** [comment]
Merged and should be able to run!
