### ISSUE TITLE
Toil-cwl-runner: automatic retry with increased LSF resource requirements

### ISSUE THREAD

**Issue by tonyyzy** [DataBiosphere/toil#2331]
Is there a way for jobs to automatically retry with additional resource on an LSF cluster?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-326)
┆Issue Number: TOIL-326

**Comment by DailyDreaming** [comment]
No, not currently. It would be an interesting option for batch, but I think a bit tricky so that it didn't get carried away.

It's code I think would be useful though and I'd be happy to review if a PR was submitted for it.
