### ISSUE TITLE
CWL: Bug when using cwltoil (due to overrides?)

### ISSUE THREAD

**Issue by mb1069** [DataBiosphere/toil#2333]
Hi,
I'm experiencing an issue when running my workflow with cwltoil, though it works in cwltool.
The error is:
`Traceback (most recent call last):
  File "/Users/mdb/miniconda2/bin/cwltoil", line 11, in <module>
    sys.exit(main())
  File "/Users/mdb/miniconda2/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1014, in main
    options, sys.stdin, None, [], options.job_order)
  File "/Users/mdb/miniconda2/lib/python2.7/site-packages/cwltool/main.py", line 141, in load_job_order
    overrides.extend(resolve_overrides(job_order_object, file_uri(job_order_file), tool_file_uri))
  File "/Users/mdb/miniconda2/lib/python2.7/site-packages/cwltool/load_tool.py", line 377, in resolve_overrides
    ret, _ = ovloader.resolve_all(ov, baseurl)
  File "/Users/mdb/miniconda2/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 871, in resolve_all
    val, base_url+subscope, file_base=file_base, checklinks=False)
TypeError: can only concatenate list (not "str") to list
`

[packed_workflow.txt](https://github.com/DataBiosphere/toil/files/2262267/packed_workflow.txt)
[pipeline_input.txt](https://github.com/DataBiosphere/toil/files/2262298/pipeline_input.txt)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-327)
┆Issue Number: TOIL-327

**Comment by DailyDreaming** [comment]
I believe this ought to be closed by the same PR fix as #2334.

**Comment by mb1069** [comment]
Hi,
This issue is still occurring in the latest pull from github (hash 9a38107) 
I've gone into the code and found that the base_url used in ref_resolver.resolve_all is a list when the overrides are specified, but is a string in all other cases?

Any help on this would be greatly appreciated!

**Comment by DailyDreaming** [comment]
@mr-c wrote a fix at #2333 that was just merged.  @mb1069 can you test this to see if it solves your issue?

**Comment by mb1069** [comment]
I can confirm the patch works as expected, thank you both for your support!
