### ISSUE TITLE
CWL: Bug allowing outputSources to be specified as single item lists

### ISSUE THREAD

**Issue by mb1069** [DataBiosphere/toil#2334]
https://github.com/DataBiosphere/toil/issues/2333
Comment out requirements override in job description, causes error where outputSources described as single-item list throws error in cwltoil but works in cwltool.

Related to https://github.com/common-workflow-language/common-workflow-language/issues/754

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-328)
┆Issue Number: TOIL-328

**Comment by DailyDreaming** [comment]
Should be addressed by #2068 which was recently merged.
