### ISSUE TITLE
Configurable permissions

### ISSUE THREAD

**Issue by jsmedmar** [DataBiosphere/toil#2355]
At the moment, toil sets pretty stringent permissions in the jobstore, e.g. a pipeline can't be restarted by a user different from the original user. In shared HPC environments is plausible to have multiple engineers running the operations. Would be nice if some how one could set default permissions used for files created within the jobstore. Even better if one could tell toil to honor the current `umask` configuration.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-273)
┆Issue Number: TOIL-273

**Comment by Vkale1** [comment]
We have also experienced a similar issue. We run an automated production which includes an automated reset function. To do this we need to be able to remove the toil directories from a different user on the system. All users are part of the shown group ID 'metagen'. We source two environments: our pipeline environment which specifies umask 002 followed by the toil environment. Toil doesn't appear to honour the initial umask, particularly for folders 'files' and 'jobs' within the job store. We are running with toil version 4.2.0a1-3f4e790c1fa32a2c2257bd5cd203a3b51d5d5661. Please see an example of the permissions below in the path job-store/run/files/no-job

```drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-qf5wej65
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-r00h_tz_
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-rh5keps1
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-s8ifuzti
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-soh8v4wb
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-t75mifhp
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-u78h8x62
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-v74zobuu
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-w4z7pjme
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-xdloi1ph
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-y7f1nik5
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-yct076hl
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-yd59tzgd
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-yt2vbukl
drwx--S---+ 2 emgpr_amplicon metagen 4.0K Jun 17 01:03 file-zewhk8p_

**Comment by mberacochea** [comment]
I'm trying to work on this issue. Can anyone share some thouths on how to approach to this?
