### ISSUE TITLE
Launching a cluster in AWS does not populate the name entry.

### ISSUE THREAD

**Issue by bencvdb** [DataBiosphere/toil#2371]
Running `toil launch-cluster [CLUSTER_NAME] --provisioner aws...` does not populate the `Name` field of the instance. This will cause some confusion to those who wish to programatically check instances name with libraries such as libcloud.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-277)
┆Issue Number: TOIL-277

**Comment by DailyDreaming** [comment]
@bencvdb What's the status on this?

**Comment by melainalegaspi** [comment]
We think this works now.
