### ISSUE TITLE
Please consider to add retry limit for SLURM

### ISSUE THREAD

**Issue by xzhub** [DataBiosphere/toil#2381]
When using SLURM **sbatch** in busy cluster, sometime you will see error like this: 
```
sbatch:error:Batch job submission failed: Socket timed out on send/recv operation
```
This will happen for command **sacct**, **squeue** and **scontrol** as well.

When we read the code, we noticed that "src/toil/batchSystems/slurm.py" has caught the exception, but there is no code to retry submiting, it just print out some error messages. This will cause the workflow fail:
```
def submitJob(self, subLine):
    try:
        output = subprocess.check_output(subLine, stderr=subprocess.STDOUT)
        # sbatch prints a line like 'Submitted batch job 2954103'
        result = int(output.strip().split()[-1])
        logger.debug("sbatch submitted job %d", result)
        return result
    except subprocess.CalledProcessError as e:
        logger.error("sbatch command failed with code %d: %s", e.returncode, e.output)
        raise e
    except OSError as e:
        logger.error("sbatch command failed")
        raise e
```

Would you please consider to implement the retry function, and let user choose how many times to retry submitting a job? 
Note, there might be a same issue for SGE and Torque.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-349)
┆Issue Number: TOIL-349

**Comment by mr-c** [comment]
Hello @xzhub , this is a good suggestion. I made a basic first pass of this at https://github.com/DataBiosphere/toil/pull/2382 but I haven't tested it personally yet
