### ISSUE TITLE
The subnet ID does not exist

### ISSUE THREAD

**Issue by Secretloong** [DataBiosphere/toil#2385]
My AWS IAM user need to use VPC to launch an instance, when I use  `--vpcSubnet my_subnet_ID` the toil will alert that the subnet ID does not exist. my vpc of this subnet is not the default vpc. So do I need to specify the vpc ID? But how? I found --vpc doesn't work. could you help me? Thank you.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-351)
┆Issue Number: TOIL-351

**Comment by DailyDreaming** [comment]
Is auto assign IPs turned on for the subnet?

**Comment by Secretloong** [comment]
> Is auto assign IPs turned on for the subnet?

Yes you are right! I have also turn on the DNS resolution and hostname for VPC. Then it works.
