### ISSUE TITLE
How to choose EC2 instance type and number of nodes?

### ISSUE THREAD

**Issue by edraizen** [DataBiosphere/toil#2391]
Hello, I was wondering if someone could give some advice on which ec2 instances would be best for my toil workflow. This isn't an issue so not sure if this is the right place. I am switching over from the slurm provisioner, where I was able to run 10,000 jobs at once and would like something similar on AWS.

For one stage of my workflow, I have ~280,000 child jobs that need only one core and 12 GB of memory and can run on preemptable nodes. They can also be split into ~6000 different categories, that can be jobs that submit subsets of the 280,000 jobs.

1. Would it be better to split into categories and then:
a. Run a new job for each, or
b. Get an instance with ~96 cores and handle the parallelization with dask/joblib
2. Not split and run all 280,000 child jobs using the map_jobs function from toil rnaseq

For either of these scenarios, which ec2 would be best for this and how many should I request? Best as in low-cost, quick to start, however, since I am new to AWS, I don't know what to look for. 

I was approved to run 50 m5.12xlarge and 50 m5.24xlarge, which seem ideal if I want 48 or 96 cores and do the parallelization myself.

However, I would only need instances with one core if I submit each job separately.  Amazon denied my request for 100 t2.nanos, so I am confused on which smaller instances to request and how many of them I should get.

I am also unsure how to account for toils job chaining.

Thanks for your help!

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-354)
┆Issue Number: TOIL-354

**Comment by DailyDreaming** [comment]
How aggressively Toil parallelizes can be controlled with `--targetTime`.  Two good examples of how this works are in the unittests:

https://github.com/DataBiosphere/toil/blob/master/src/toil/test/provisioners/clusterScalerTest.py#L135
https://github.com/DataBiosphere/toil/blob/master/src/toil/test/provisioners/clusterScalerTest.py#L156

I'm not sure about your efficiency, though I can say we generally try to optimize cost here (generally the other side is optimizing time, in which case you want to parallelize as much as possible with as many instances as you have).  `us-west-2 (Oregon)` is generally cheaper than `us-west-1 (N. California)`.  There's a good site here as well: https://www.ec2instances.info/?region=us-west-2

I (hope) the unittest links explain a little about Toil's job chaining, but if you had anything specific, what would you like to know?

**Comment by edraizen** [comment]
Thanks, that was helpful. I decided to use 1000 t2.micros/t2.smalls.

**Comment by joelarmstrong** [comment]
Just butting in to mention, you may get worse performance than expected if you use more than 100 T2 instances. [See the AWS docs for details](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-standard-mode.html#launch-credits), but the gist of it is that past a certain limit, T2 instances start with 0 CPU credits, meaning that they will only be running at "baseline performance", which is typically 5-30% of the max performance of the instance.

**Comment by edraizen** [comment]
Hi Joel, thanks for letting me know about that. However, I am still confused. 

Amazon gave me permission to run 1000 t2.small spot instances. Toil seems to be creating individual instances for them. Is there I way to have toil start a spot fleet? and start it multiple regions? 

The number of jobs/followOn jobs/followOn encapsulated jobs/etc is over a million -- and some jobs will run for a max of 10 minutes, most will be v. short. What is best way to have 1000+ concurrent jobs?
