### ISSUE TITLE
Conda recipe issues

### ISSUE THREAD

**Issue by matthdsm** [DataBiosphere/toil#2394]
Hi,

I noticed the bioconda recipe for toil includes a lot of pinned versions of dependencies.
Is there a reason for this? Because of the pins a lot of other tools get downgraded to be able to comply with the strict version control.

Thanks
M

ping @chapmanb, this relates to https://github.com/bcbio/bcbio-nextgen/issues/2510

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-356)
┆Issue Number: TOIL-356

**Comment by matthdsm** [comment]
the offending packages for a clean installation in a bcbio env are
```
The following packages will be DOWNGRADED:

    arvados-cwl-runner: 1.0.20160715171107-py27_0  bioconda    --> 1.0.20160502202716-py27_0 bioconda
    boto:               2.48.0-py27h9556ac2_1                  --> 2.38.0-py27_0
    paramiko:           2.4.0-py27hc00b698_0                   --> 2.1.2-py27_0              conda-forge
    pynacl:             1.1.2-py27_0               conda-forge --> 0.3.0-py27_0              bioconda

```

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
The underlying cwltool API has changed so the toil conda recipe pins to a working cwltool that cwltoil is compatible with. It would be great to avoid the pinning and move forward to the latest cwltool but this will take development work to update cwltoil to be compatible. In general I'd recommend installing toil in a more isolated conda environment to avoid the downgrades affecting our tools.

**Comment by DailyDreaming** [comment]
@matthdsm We could loosen up the version dependencies, though it would take some experimenting.  Toil only has 2 dependencies on that list as far as I know (`boto` and `pynacl`), so I'm assuming the rest are dependent on dependencies that toil has.  `pynacl` may only be used for our Azure implementation, though it may have been taken out too, looking at the code.  I'll check and see.

**Comment by matthdsm** [comment]
Hi @DailyDreaming 

Thanks! It would be great to be able to keep everything up to date!
Cheers
M
