### ISSUE TITLE
changes to tutorials

### ISSUE THREAD

**Issue by emlys** [DataBiosphere/toil#2396]
- In Quick Start Examples - Error Handling, two examples are missing a job store argument
- Spelling and punctuation errors in Command Line Options section
- In Toil Debugging section, toil-debug command not found
- In Status Command section, error in example code
    - Change example file names in discoverfiles.py

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-358)
┆Issue Number: TOIL-358

**Comment by DailyDreaming** [comment]
Closed by #2393 and #2399.
