### ISSUE TITLE
Monitoring of a CWL workflow step

### ISSUE THREAD

**Issue by thomasyu888** [DataBiosphere/toil#2406]
Example workflow: test.cwl

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: python

inputs:
  - id: input
    type: string

arguments: 
  - valueFrom: test.py

requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: test.py
        entry: |
          #!/usr/bin/env python
          import logging
          logging.basicConfig()
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          logger.info("test")
          logger.warning("warn")
          logger.error("error")
          logger.critical("crit")
     
outputs: []
```

test.yaml

```
input:foo
```

When I run `toil-cwl-runner --defaultMemory 100M --retryCount 0 --defaultDisk 1000000 --logInfo test.cwl test.yaml`, none of the print statements in the python script is printed, but when I run `toil-cwl-runner --defaultMemory 100M --retryCount 0 --defaultDisk 1000000 --logDebug test.cwl test.yaml`, they are all printed out, with a lot of other logs.

```
...
DEBUG:toil.statsAndLogging:'file:///home/ubuntu/temp/test.cwl' python o/Z/jobUBnXcb    INFO:root:test
DEBUG:toil.statsAndLogging:'file:///home/ubuntu/temp/test.cwl' python o/Z/jobUBnXcb    WARNING:root:warn
DEBUG:toil.statsAndLogging:'file:///home/ubuntu/temp/test.cwl' python o/Z/jobUBnXcb    ERROR:root:error
DEBUG:toil.statsAndLogging:'file:///home/ubuntu/temp/test.cwl' python o/Z/jobUBnXcb    CRITICAL:root:crit
...
```

Is there a way for me to format the `logging` in my python script to have them be displayed without using the `--logDebug` flag?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-283)
┆Issue Number: TOIL-283

**Comment by DailyDreaming** [comment]
@thomasyu888 I think setting the commandline option is the only way with CWL/toil, short of directly editing this line yourself: https://github.com/DataBiosphere/toil/blob/master/src/toil/cwl/cwltoil.py#L1139

There's a straight forward way with pure python toil files.

Though maybe there's a nifty inherited cwltool trick @mr-c ?

**Comment by thomasyu888** [comment]
@DailyDreaming  Thanks for the prompt response.  For further context, we are running CWL workflows with toil and one of the steps is running a docker container.  However, I like the option of showing all the INFO logs from the Toil, but I don't want all the DEBUG logs. 

When you say pure python toil files, do you mean not using cwl?

**Comment by mr-c** [comment]
Hello all,

As part of the CWLProv work we will be separating out STDOUT/STDERR for each tool execution. Once this is done, `toil-cwl-runner` could gain an option to print / write to a file these separately from toil's own logs.

See also https://github.com/common-workflow-language/cwltool/issues/903

Though this is currently unscheduled work for me, so if someone wants to jump in sooner I would be happy to provide guidance.

**Comment by DailyDreaming** [comment]
@thomasyu888 Yes, that's what I meant.  Though I think waiting on the feature @mr-c mentioned is probably the best option.

@mr-c I may have time next sprint, though we have a demo on the 16th and I was hoping I could finish the python3 PR so it's not certain.

**Comment by thomasyu888** [comment]
Thank you both!
