### ISSUE TITLE
Add recognition of Conda virtual environments

### ISSUE THREAD

**Issue by ibebio** [DataBiosphere/toil#2421]
Hi,
we used Conda virtual environments instead of virtualenv and ran into the issue that toil does not recognize that it is running inside a Conda virtual environment. _toil_worker could thus not be found, without explicitely setting the PATH variable to point to its location in .bash_profile.

Extending the check for virtual environments inVirtualEnv() in src/toil/__init__.py to
    return hasattr(sys, 'real_prefix') or 'CONDA_DEFAULT_ENV' in os.environ
solved the problem for us. Would this change make sense, and should I submit a pull request?

Thanks, Ilja

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-377)
┆Issue Number: TOIL-377

**Comment by DailyDreaming** [comment]
@ibebio Yes, that sounds like a sensible change.  Please do submit a PR!  Thanks for posting this.  :)
