### ISSUE TITLE
Add test files to path on toil's tests.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2427]
This is mimicing the DSS tests:

[https://github.com/DataBiosphere/cgp-data-store/blob/master/tests/test_bundle.py#L18](https://github.com/DataBiosphere/cgp-data-store/blob/master/tests/test_bundle.py#L18)

In addition, the copyright header comment at the top of each file (all of toil) wouldn't be bad to clean up.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-295)
┆Issue Number: TOIL-295

**Comment by DailyDreaming** [comment]
Closing this.  This is stale, and if it happens it'll likely happen slowly as a part of general test refactoring, as needed, not all in one fell swoop.
