### ISSUE TITLE
Question: why toil doesn't Q my jobs to SLURM?

### ISSUE THREAD

**Issue by xzhub** [DataBiosphere/toil#2431]
I have a pipeline that has many jobs. To my surprise, Toil always control the job by itself and never queue all the jobs to SLURM. This is fine most of the time, however, I noticed an issue that it only release jobs up to the number of nodes.

I have 8 nodes, each has 8core and 32G memory, so this looks fine to me:
<img width="466" alt="screen shot 2018-10-31 at 6 54 52 pm" src="https://user-images.githubusercontent.com/3990687/47829099-133b4980-dd43-11e8-9e50-dc8a25e680d7.png">

However, here is an example that things are wrong, you can see there are only 8 jobs running, but most of my compute nodes are idle. There are 1000 more on the way but Toil won't release them to SLURM.
<img width="474" alt="screen shot 2018-10-31 at 7 24 59 pm" src="https://user-images.githubusercontent.com/3990687/47829106-1a625780-dd43-11e8-886b-e4e33d71935f.png">
<img width="364" alt="screen shot 2018-10-31 at 7 27 38 pm" src="https://user-images.githubusercontent.com/3990687/47829109-1e8e7500-dd43-11e8-9569-6e8438aa5ce4.png">

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-381)
┆Issue Number: TOIL-381

**Comment by xzhub** [comment]
Hi guys, after I downgraded my Toil to 3.17, issue resolved! This should be a bug in 3.18.
<img width="448" alt="screen shot 2018-10-31 at 7 52 12 pm" src="https://user-images.githubusercontent.com/3990687/47829806-80041300-dd46-11e8-8fbc-c7cb90c05d44.png">
<img width="355" alt="screen shot 2018-10-31 at 7 52 20 pm" src="https://user-images.githubusercontent.com/3990687/47829808-82666d00-dd46-11e8-9194-501b289badb6.png">

**Comment by xzhub** [comment]
Looks like in Toil 3.18, the max job number is set up to the total CPU in the current node.(not the total number of nodes in the cluster)

**Comment by DailyDreaming** [comment]
@xzhub Thanks for the catch!  If you'd like to submit a PR, I'd be happy to review it.

**Comment by xzhub** [comment]
> @xzhub Thanks for the catch! If you'd like to submit a PR, I'd be happy to review it.

That might be too difficult for me as a user, but I'll start looking at the code slowly, if I find anything suspicious, I'll let you know.

**Comment by DailyDreaming** [comment]
@xzhub Alright, will take a look and likely make a PR Monday.

**Comment by DailyDreaming** [comment]
@xzhub After looking into this a bit more, you can override this behavior by specifying the option: `--maxLocalJobs`.  Please comment if that doesn't work!

Code is here: https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/options.py#L142

I believe it was set this way because Grid Engine needed to limit the number of jobs to submit and this got chosen as the default conservative limit for all systems.

**Comment by xzhub** [comment]
Sure enough it works perfectly now. Thanks for the help!

**Comment by DailyDreaming** [comment]
@xzhub Awesome, I'm glad!  Let us know if any other issues arise.
