### ISSUE TITLE
Toil AWS clusters in 3.18 don't set terminal size on login when 3.17 did

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2433]
Toil 3.18 now has the wrong terminal window size detected when you connect to an AWS cluster head node. It was correct in 3.17.

Having the wrong terminal size makes things scroll wrong when commands produce a lot of output. I end up using only the upper-left corner of my terminal window.

Bash, the Bash profile/bashrc files, and the libraries Bash uses appear to all be identical between the two conditions. The bash `checkwinsize` option is on in both conditions but doesn't seem to actually be taking effect.

Resizing your terminal window or running the `resize` command from the `xterm` package (which you have to install) seems to make it pick up the correct terminal size.

To reproduce, from Toil 3.18:

```
toil launch-cluster amntest --leaderNodeType=t2.medium -z us-west-2a --keyPairName=anovak@kolossus
```

From Toil 3.17:

```
toil launch-cluster amntest2 --leaderNodeType=t2.medium -z us-west-2a --keyPairName=anovak@kolossus
```

And then ssh in to each from Toil 3.18:

```
toil ssh-cluster -z us-west-2a amntest
tput lines # Should print "24"
exit

toil ssh-cluster -z us-west-2a amntest2
tput lines # Should print actual number of lines in your terminal window; I get "55"
exit
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-298)
┆Issue Number: TOIL-298

**Comment by DailyDreaming** [comment]
@adamnovak That's odd.  Thanks for reporting the issue.

**Comment by DailyDreaming** [comment]
I feel like this has been fixed.  Please reopen if still an issue.
