### ISSUE TITLE
`screen` on Toil AWS leader nodes starts /bin/sh instead of Bash

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2434]
When you run `screen` on a Toil-created cluster's head node, to run your workflow under it, it starts /bin/sh instead of your user's shell, `bash`, as set in /etc/passwd. This means things like the arrow keys to move the cursor do not work inside of `screen`. This in turn annoys our rotation students who are trying to run long-running Toil workflows on AWS from laptops.

If you `export SHELL` before running `screen`, it picks up that you are supposed to be using `bash`.

Toil's images ought to set themselves up so that `bash` is run in `screen`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-384)
┆Issue Number: TOIL-384

**Comment by DailyDreaming** [comment]
Just tested this and it works for me.  Let me know if it works alright for you: https://github.com/DataBiosphere/toil/pull/2435

**Comment by DailyDreaming** [comment]
Closed by #2435 .
