### ISSUE TITLE
temp files not deleted until array job is completed

### ISSUE THREAD

**Issue by claudiodonati** [DataBiosphere/toil#2442]
Hi all,

I am using toil to run a CWL array job that processes a long list of files. Each input is processed independently and produces an output, together with a lot of temp files that I do not need. 

toil gives me the all the outputs only at the end of the array job, when all the temp files are deleted. Until then the temp files stay on disk (and can fill my filesystem if the job is long enough), and I have no access to outputs.

Is there a way to tell toil that I want to see the output for each input as soon as it is produced, and that it should not wait the end of the array job to delete temp files?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-300)
┆friendlyId: TOIL-300

**Comment by DailyDreaming** [comment]
@claudiodonati Currently there isn't an option to do what you're asking directly that I'm aware of, though @mr-c might know of a way?

I suppose as a way of getting around this, you might be able to run something like this: https://toil.readthedocs.io/en/latest/running/cwl.html#running-cwl-within-toil-scripts

Where each job should complete and delete the temp files before the next runs.

This is a good option request though, and should be implemented at some point.
