### ISSUE TITLE
Plan a 2.7 timeline.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2453]
`2.7 will receive bugfix support until January 1, 2020.` - https://www.python.org/dev/peps/pep-0373/

Should we also drop python 2.7 on January 1, 2020?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-83)
┆Issue Number: TOIL-83

**Comment by adamnovak** [comment]
We should bump the major version when we drop 2.7 support. `networkx` dropped 2.7 going from 2.2 to 2.3 and it seems to have broken a bunch of package dependency specifiers that assumed that wouldn't happen.

**Comment by diekhans** [comment]
it would be good to move the minimum version up to 3.6 or above, due to the 3.6 subprocess encoding changes.
