### ISSUE TITLE
Update Dockerfile to Ubuntu 18.04 (maybe 16.04?)

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2461]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-75)
┆Issue Number: TOIL-75

**Comment by DailyDreaming** [comment]
The new plan is to maintain the Dockerfile on Ubuntu 16 for as long as possible before moving over to Kubernetes.
