### ISSUE TITLE
add option '--preserve-entire-environment' to cwltoil

### ISSUE THREAD

**Issue by elarsonneur** [DataBiosphere/toil#2477]
Hi, 

It coul be nice if you add the option '--preserve-entire-environment' to cwltoil arguments.
This option already exists in cwltool.

Thanks,
Elise

**Comment by DailyDreaming** [comment]
Sure, I've been meaning to port over more `cwltool` arguments.  I'll probably have a PR up next week.

**Comment by DailyDreaming** [comment]
@elarsonneur There's a PR at #2481 that should resolve this.

**Comment by DailyDreaming** [comment]
@elarsonneur There's a PR at #2481 adding `--preserve-entire-environment`.
