### ISSUE TITLE
add option '--tmpdir' to cwltoil

### ISSUE THREAD

**Issue by elarsonneur** [DataBiosphere/toil#2478]
Hi,

It could be nice you add an option to specify a temp directory.

Indeed, even if I specify the currentoptions : 
`--basedir`
`--outdir`
`--workDir`
`--tmpdir-prefix`
`--tmp-outdir-prefix`
there are still files which are written into `/tmp` directory.

A new option `--tmp-dir` (or an existing one) could be used to prevent files to be written on `/tmp`.

Thanks,
Elise

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-64)
┆Issue Number: TOIL-64

**Comment by DailyDreaming** [comment]
Will bring this up at our next meeting on Monday.

**Comment by ionox0** [comment]
This may have to do with the `TMPDIR` environment variable, what do you have it set to? @elarsonneur

**Comment by elarsonneur** [comment]
@ionox0 I didn't try to modify `TMPDIR` variable. 
But it's a good idea:
`$ TMPDIR=<path>`
`$ cwltoil --preserve-environment TMPDIR [...]`

**Comment by DailyDreaming** [comment]
Stale, closing this.  Please reopen if still an issue.
