### ISSUE TITLE
TOIL Analytics

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2488]
Benedict has asked that we figure out a way to see who is using toil besides us.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/TOIL-419)
┆Issue Number: TOIL-419

**Comment by natanlao** [comment]
We have Google Analytics set up on the Toil ReadTheDocs and landing page that might help with this.

**Comment by DailyDreaming** [comment]
Not sure that we're going to do this.  We can always reopen it if we reevaluate.
