### ISSUE TITLE
Allow treating case sensitive file systems as insensitive in the job store

### ISSUE THREAD

**Issue by theboocock** [DataBiosphere/toil#2501]
Thanks for creating this pipelining framework.

So I have been using toil in a dropbox folder, which unfortunately does not support case sensitive file or folder names (it actually will scrub the directory and rename those folders). I understand this could maybe also be an issue on OSX. Is it possible to add an option to toil to only create case insensitive job store ids folders etc?

Thanks,

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-61)
┆friendlyId: TOIL-61

**Comment by DailyDreaming** [comment]
Quite possible!  If you'd like to submit some code, I'd be happy to review it.
