### ISSUE TITLE
Need psutil>=5.4.3 on systems with GLIBC<2.13

### ISSUE THREAD

**Issue by ckandoth** [DataBiosphere/toil#2503]
As of Toil 3.18, `psutil==3.0.1` is enforced in `setup.py`. On our LSF cluster running CentOS 6.9, this installs fine, but when toil tries to `import psutil`, it complains about our outdated `libc` system libraries:
```
$ python -c 'import psutil'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/psutil/__init__.py", line 63, in <module>
    from . import _pslinux as _psplatform
  File "/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/psutil/_pslinux.py", line 24, in <module>
    from . import _psutil_linux as cext
ImportError: /lib64/libc.so.6: version `GLIBC_2.13' not found (required by /opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/psutil/_psutil_linux.so)
```
We only have `GLIBC_2.12` across our cluster:
```
$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
Thankfully, psutil 5.4.3 and newer versions add backward compatibility for `GLIBC_2.12`, and this tested fine on our cluster. Could you [edit this code](https://github.com/DataBiosphere/toil/blob/releases/3.18.x/setup.py#L27) to install `psutil==5.4.3` or `psutil>=5.4.3` in your next release? Thanks so much.

**Comment by mr-c** [comment]
Hello @ckandoth and thank you for sharing your issue.

I'm not seeing any reference to GLIBC backwards compatibility in the the `psutil` changelog. Perhaps your cluster has an incorrectly compiled local binary for `psutil`?

Here's a `Dockerfile` I made to test my hypothesis:

```
FROM centos:6.9
RUN yum -y install centos-release-scl
RUN yum -y install python27 gcc
RUN scl enable python27 -- pip install toil
RUN scl enable python27 -- toil --help
```

**Comment by ckandoth** [comment]
@mr-c thanks, you're right. We have an awkward but temporary build/test/deploy setup, where build (venv, toil, psutil, etc.) happens on a CentOS 7.3 box (with glibc 2.17), while test/deploy happens on the older CentOS 6.9 cluster (with glibc 2.12). Deploy (for production) should move to a CentOS7 cluster soon, but we need to support the CentOS6 cluster at least thru 2019. `psutil==3.0.1` was the only package that would not work on CentOS6, if it was installed by a box running CentOS7. I'm not sure what's happening under the hood, but `psutil>=5.4.3` installed in a venv by a CentOS7 box, appears to work fine on a CentOS6 box. And that led me to create this issue. Feel free to close the issue without upgrading `psutil`. We will change our setup to build/test/deploy separately for the separate clusters.

@ionox0 the issue we had was with `psutils` not `pybedtools`.

**Comment by mr-c** [comment]
@ckandoth Thanks for the update; my best wishes for your future unified build environment!
