### ISSUE TITLE
GridEngine can't use more running jobs than would fit on the leader node

### ISSUE THREAD

**Issue by joelarmstrong** [DataBiosphere/toil#2509]
Potentially also affects LSF, torque, etc.

https://github.com/DataBiosphere/toil/blob/33112d99b1edce8af5dd06e234db25a84fe2bc19/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L130-L131

I think this is mixing up `maxLocalJobs` and `maxCores`. `maxLocalJobs` is set to the number of cores on the leader, so mixing these up really affects throughput! If you had say 2 cores on the leader, only 2 jobs would be run at a time!

Haven't replicated this myself, but I've gotten some complaints recently and I think this is likely the root cause.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-58)
┆Issue Number: TOIL-58

**Comment by jsmedmar** [comment]
@joelarmstrong I think there are a lot of confusion around these concepts. See this previous issue https://github.com/DataBiosphere/toil/issues/2323.

**Comment by joelarmstrong** [comment]
Interesting, thanks. I think there is definitely some confusion between `maxCores`, `maxLocalJobs` and the detected `maxCPU` for gridengine. The default behavior where everything is controlled by `--maxLocalJobs` on gridengine is pretty unintuitive, because `--maxLocalJobs` claims it is "the maximum number of housekeeping jobs to run on the local system".

I think we should certainly use `maxCPU` as the default cap--I've seen users spend days trying to figure out why their workflows aren't running at full speed. The question is what to do with `--maxLocalJobs` vs. `--maxCores`: people have been using `--maxLocalJobs` for this purpose for months now, so maybe it makes sense to embrace that, but change its documentation to reflect what it actually does.

**Comment by jsmedmar** [comment]
It was previously set to use `maxCores`:

https://github.com/DataBiosphere/toil/blob/5650a0eef8d317c1e7f2b046b949c110bb04292b/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L111-L112

But the total number of cores in the batch system is stored in `maxCPU`:

https://github.com/DataBiosphere/toil/blob/33112d99b1edce8af5dd06e234db25a84fe2bc19/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L307

**Comment by jsmedmar** [comment]
I think `--maxCores` is the right flag.  `--maxLocalJobs` is only used by `HTCondorBatchSystem` and `abstractGridEngineBatchSystem` and in both cases for the same goal:

https://github.com/DataBiosphere/toil/blob/33112d99b1edce8af5dd06e234db25a84fe2bc19/src/toil/batchSystems/htcondor.py#L46

https://github.com/DataBiosphere/toil/blob/33112d99b1edce8af5dd06e234db25a84fe2bc19/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L130-L131

I think we should make sure that both flags are mutually exclusive (meaning they can't be used together) and that the documentation says they do exactly the same thing. And perhaps put a deprecation warning on `--maxLocalJobs`.

**Comment by jsmedmar** [comment]
Another reason toil struggles to run at full speed is the fact that by default, toil checks on all running jobs every second (`statePollingWait=1`), and if it does not finish checking on jobs it wont submit more jobs. In the case of LSF, it runs bjobs so many times that it spends all the time checking on jobs instead of submitting jobs. There are two ways of addressing this issue, (1) use a large `--statePollingWait`, something like 300 seconds (2) cache all currently running jobs as we did in toil container: 

https://github.com/papaemmelab/toil_container/blob/976d606b7a568bee9228713285685d4153b90690/toil_container/lsf.py#L103-L113

**Comment by adamnovak** [comment]
I think this arose in https://github.com/DataBiosphere/toil/pull/2347; someone thought this was what `--maxLocalJobs` was meant to do.

**Comment by adamnovak** [comment]
Is `--maxJobs` free?
