### ISSUE TITLE
Memory requirement can't be given a PromisedRequirement

### ISSUE THREAD

**Issue by mflevine** [DataBiosphere/toil#2525]
I am trying to set memory for a job based on the returned values from a previous job but it seems that `memory` requirement is not allowed to be passed a PromisedRequirement.

`TypeError: The 'memory' requirement does not accept values that are of <class 'toil.job.PromisedRequirement'>`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-52)
┆Issue Number: TOIL-52

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if this is still an issue.  If you include a small sample script that can reproduce the error, I can probably debug what's going on and fix it.
