### ISSUE TITLE
python3.6.7 support and _toil_mesos_executor: not found error

### ISSUE THREAD

**Issue by edraizen** [DataBiosphere/toil#2529]
Hello,

What is the status of fully converting to python3? Some of the toil required packages can only work in 3.6.7 not 3.7, so that is what I am testing in.

The error I keep getting is: "Executor: b'sh: 1: _toil_mesos_executor: not found'". Full output relevant to starting tasks can be found here: https://gist.github.com/edraizen/64580011eed6c23d8a2448357876fa53

So far, I've updated the toil_appliance to use python3.6.7 as default and changed it to use miniconda instead of virtualenv: https://hub.docker.com/r/edraizen/toil-gpu

My first thought was that it might not be including the user_data correctly to start the docker image, so I tried converting all spot requests to use boto3. However, that didn't change anything either.

Do you have any suggestions?

Thanks,
Eli

**Comment by adamnovak** [comment]
We have tested the Mesos batch system on Python 3, as part of the original port.

It looks like you're replacing the Toil appliance Docker image with your own, which is built on a different base image that provides GPU computing support. From the log you provided, it looks like your Mesos is working correctly and the Toil task is actually trying to execute. It gets a container started up for it in Mesos (which isn't a Docker container itself; Mesos says `containerizer.cpp:196] Using isolation: posix/cpu,posix/mem,filesystem/posix,network/cni'`), but then the command that is supposed to run (`_toil_mesos_executor`) isn't found.

When I `docker run --rm -t -i edraizen/toil-gpu:latest`, I do have `_toil_mesos_executor` on the path, although as soon as I get in I get an aeeror from the `.bashrc`: `bash: activate: No such file or directory`. It looks like `_toil_mesos_executor` is `/root/miniconda3/envs/py36/bin/_toil_mesos_executor`. Compare to `docker run --rm -t -i quay.io/ucsc_cgl/toil:3.18.0` which puts it as `/usr/local/bin/_toil_mesos_executor`.

I think it's just not on the $PATH for the user Mesos is running as in your appliance. Try moving where you install Toil.

**Comment by DailyDreaming** [comment]
Old issue seems solved, closing.
