### ISSUE TITLE
test posting an issue

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2543]
this issue is not synced yet

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-424)
┆Issue Number: TOIL-424

**Comment by jessebrennan** [comment]
Whoever is doing this, please know that you're spamming everyone's inbox with lots of assignment notifications.

**Comment by yech1990** [comment]
PLEASE report abuse from this user. 

https://github.com/contact/report-abuse?report=cricketsloan+%28user%29

**Comment by adamnovak** [comment]
Please don't report Cricket, who is one of our managers at UCSC. That account is being used to try and sync the Github issues with one of our internal systems, but the folks working on it are having some trouble, and the bot is sometimes over-enthusiastic. We're not thrilled with it either, but as it is UCSC's bot and more or less UCSC's repo, we'd rather not have the Github Police involved.

**Comment by cricketsloan** [comment]
➤ Stefan Kuhn commented:

Unclear how I came to be a 'reporter' in this ticket. Also, can we determine who 'this user' is as commented by YC? Best I can tell there are two TOIL-related syncs registered in Unito and one of them was de-activated several days ago, likely due to the fore-mentioned spamming issue.
