### ISSUE TITLE
Intermediate files in a CWL workflow that should be copied to the workdir fail completely when the input data is on a separate filesystem from the jobstore.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2553]
See #2534.

**Comment by liinus** [comment]
I mounted `/vol1` or `/vol2` as separate bind mounts in a docker container with cwltoil. This would mimic having two separate hard drives or nfs mounts on a host system when it comes to creating hard links. Some observations:
- If I have an input file in a bind mount (`/vol1/input.file`), then workdir must **always** be in the container itself (tested with `/tmp`). The location of jobstore doesn't matter.
- If I have an input file on the host (`/tmp/input.file`), then workdir and jobstore can't be on **separate** bind mounts (having them on the same works).
- The input file, workdir and jobstore can never be on the **same** bind mount. Having everything in `/tmp` works fine.

**Comment by liinus** [comment]
I found the error and this was likely introduced with the feature of creating symlinks for jobstore files  (#1687). The fileJobStore checks if the jobstore file is on the same device as the workdir before creating a hard link. If the file is a symlink it will be resolved during the device check but not when creating the hard link. If the symlink is on a different device from the workdir the hard link will fail.
