### ISSUE TITLE
toil-cwl-runner sort of works without 'cwl' extra installed

### ISSUE THREAD

**Issue by chrisbarber** [DataBiosphere/toil#2555]
I neglected to install the 'cwl' extra and was trying to run toil-cwl-runner. I had previously installed cwltool. I got an error from toil code trying to import from cwltool:
```
Traceback (most recent call last):
  File "/cluster/home/barberc/software/anaconda/envs/py3/bin/toil-cwl-runner", line 6, in <module>
    from toil.cwl.cwltoil import main
  File "/cluster/home/barberc/software/anaconda/envs/py3/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 60, in <module>
    from cwltool.process import (shortname, fill_in_defaults, compute_checksums,
ImportError: cannot import name 'collectFilesAndDirs'
```
This symbol at one time existed in cwltool. In fact, I went so far as identifying and installing cwltool==1.0.20180819175200 which was close enough to the required version for toil 3.18.0 (cwltool==1.0.20180820141117) that everything seemed to work.

Apologies if there is not a practical way to do this with setup.py extras, but I am opening this in hopes that there is a simple way I haven't thought of by which to address this. Ideally the cwl-related commands would not be present, or not be on the PATH, or a warning would be issued when running. Another line of argumentation might be: users may be trying toil after experimenting with cwltool, so there is a good chance they have it already installed (likely the wrong version), and the cwl extras are currently not so heavy of dependencies that they couldn't just be moved out of extras and into a base `pip install toil`. I'm not sure if those points are true, but it could be a way around this.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-45)
┆Issue Number: TOIL-45

**Comment by adamnovak** [comment]
Does `cwltool` expose a `__VERSION__` or `version` or similar field in its module? We could have the Toil code that uses it check that against the version Toil requires and complain if the user has managed to install the wrong version. But then the user would have a hard time overriding Toil's demanded cwltool version with another one that they know is compatible.

**Comment by chrisbarber** [comment]
Searching cwltool repo for the current version (1.0.20190228155703) finds nothing in the code, so I don't think they do, though I'm sure if they were asked nicely they could.

It's interesting that setuptools has a syntax for defining relevant extras for console_scripts (see [setuptools docs for extras]()), which is used for the cwl-related scripts in toil (https://github.com/DataBiosphere/toil/blob/0ba88bbdf375df74883c85ce12737b48deea797d/setup.py#L162-L163), but that apparently this is only for limiting dynamic dependencies. I don't know how they implement it, but maybe it could be hooked into to somehow.
