### ISSUE TITLE
Time for a toil release..?

### ISSUE THREAD

**Issue by stain** [DataBiosphere/toil#2572]
Toil [3.18.0](https://github.com/DataBiosphere/toil/releases/tag/releases%2F3.18.0) was released in October 2018. 

Lots of work has happened since then, including Python 3 support which is strongly requested. 

Is there a plan for releasing toil 3.19.0?

**Comment by benedictpaten** [comment]
Yes! @DailyDreaming

**Comment by DailyDreaming** [comment]
@stain @benedictpaten Was planning to release this evening actually.  Stay tuned!

**Comment by DailyDreaming** [comment]
@stain @benedictpaten Toil 3.19.0 has been released!

**Comment by benedictpaten** [comment]
Thanks Lon!
