### ISSUE TITLE
Add an option to set custom AWS IAM policies

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2575]
The AWS IAM policies are currently [hardcoded](https://github.com/DataBiosphere/toil/blob/c483abf5c91894de876f43ab14761238f1021963/src/toil/provisioners/aws/awsProvisioner.py#L563), so it's not possible to use additional services (e.g. KMS, ECR, etc) with default settings

I can think of two options:
* **(preferred)** Allow setting custom IAM role via a flag. This would enable arbitrary role definitions and customizations. We'd need to ensure to not delete the role when `destroy-cluster` is called though. Also, workers would need to get the role via the master rather than assuming it's based on the cluster name.
* Add an option for setting additional policies when creating the custom role. This would work, but has limits (e.g. it can't be used in other places prior to launching the cluster; complex policies would be difficult to specify).

@DailyDreaming @adamnovak : do you have other options/thoughts in mind?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-41)
┆Issue Number: TOIL-41

**Comment by DailyDreaming** [comment]
@arostamianfar I'm definitely a fan of making this configurable.  I agree with your preferred method though the role should still be deleted from Amazon provided it is set in a config somewhere.  Making a new deployment should make new roles each time.  There's no reason to keep the old ones around if the cluster was deleted.
