### ISSUE TITLE
toil writes to /tmp although --tmpdir-prefix is set

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2576]
Hi. I'm running toil (3.19.0) like:
```
$ /toil-cwl-runner --cleanWorkDir always \               
        --logFile $(CURDIR)/log --outdir $(CURDIR)/results \                
        --jobStore file:///$(CURDIR)/$(RUN)/job_store \               
        --workDir $(CURDIR)/work --tmpdir-prefix=$(CURDIR)/tmp --clean always                  
```
My pipeline creates quite some huge intermediate files, which toil writes to `/tmp`. I can't have that in `/tmp` since no space, but `--tmpdir-prefix` doesn't seem to have much effect.

**Comment by gijzelaerr** [comment]
it also happens when I set `--tmp-outdir-prefix`

**Comment by gijzelaerr** [comment]
This is probably related:

https://gist.github.com/gijzelaerr/eccd3cb159b312e2e60810e28fea20cf

I'm running toil on a cluster where `/tmp` is not shared. i've set both `tmpdir` and `tmpout-dir` prefixes, but still toil looks in `/tmp`

**Comment by gijzelaerr** [comment]
setting a temp dir using a `TMPDIR` environmental variable seems to do the trick.

**Comment by adamnovak** [comment]
I suspect the offending code is here:

https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L585-L588

Your temp files are all under directories with "out_tmpdir" in the name, and this is where that is in the code.

The underlying problem I think is confusion between `workdir` and `options.workDir` here:

https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L1119-L1130

We try and override the working directory when a `--tmpdir-prefix` is set, but we only seem to modify it in the options, and the actual local `workdir`, which stays under /tmp, is what is getting passed along to the jobs to work in. Setting `TMPDIR` in the environment is affecting that initial `mkdtemp()` and getting it put in the right place.
