### ISSUE TITLE
can't ctrl-c toil

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2577]
What is the proper way to kill toil?

If I ctrl-c a cwl toil (3.19.0) run it keeps on going. For now i'm using:

`$ ps ax | grep toil | awk '{ print $1 }' | xargs kill`

in a different console, but there must be a better way?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-40)
┆friendlyId: TOIL-40

**Comment by diekhans** [comment]
This is a known issue that needs to be address in the code:

  http://www.regexprn.com/2010/05/killing-multithreaded-python-programs.html

I always used create threads with daemon = True approach.

In the mean time you can also ctrl-z toil it and kill %1

**Comment by mr-c** [comment]
In what PR was this fixed?

**Comment by adamnovak** [comment]
It looks like we set up a SIGTERM handler in #3779 which is at https://github.com/DataBiosphere/toil/blame/b5abd3c6565cee88edde94eb5546fa85909adbc3/src/toil/common.py#L928.

I think this ought to be working now, for cases where the Toil main thread is actually available to receive the signal and none of the other threads are hung.
