### ISSUE TITLE
tmp files in output dir

### ISSUE THREAD

**Issue by gijzelaerr** [DataBiosphere/toil#2578]
hi! Whenever I run toil all the intermediate output products are also written to the `outdir`. Is there a way to remove these, preferably directly after step completion? I have a pipeline producing a huge amount of intermediate data and my filesystem can't deal with it.

**Comment by gijzelaerr** [comment]
it looks like this issue has been solved in toil `3.19.0`! Or am I confused?

**Comment by DailyDreaming** [comment]
@gijzelaerr I believe you're correct and that this has been solved in `3.19.0`.  If you encounter this again in the future however, please feel free to reopen this ticket.
