### ISSUE TITLE
Env value of TOIL_DOCKER_REGISTRY is not honored in the docker image

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2585]
When a docker image is build with a custom `TOIL_DOCKER_REGISTRY`, the built docker image still looks at `quay.io/ucsc_cgl` for pulling related images (e.g. `mtail`, `grafana`, etc). The fix is to put the actual registry in `version_template.py`.

**Comment by DailyDreaming** [comment]
Can you list the commands used to do this?  Setting `TOIL_DOCKER_REGISTRY` should work.

**Comment by arostamianfar** [comment]
@DailyDreaming : the issue is that the `TOIL_DOCKER_REGISTRY` env is not set inside the docker image, so by default, it gets the value from the version file ([code](https://github.com/DataBiosphere/toil/blob/cf1e668279775d3c679cb5ba51505eda4994692b/src/toil/common.py#L1100)). Writing the actual registry to the version file seems like the correct solution (PR #2583 ), otherwise you'd have to set the env variable again when running toil commands from within the docker instance.
