### ISSUE TITLE
toil-wdl-runner inconsistencies

### ISSUE THREAD

**Issue by azzaea** [DataBiosphere/toil#2592]
Hello,

I'm trying to use Toil as a back end engine to run [this wdl pipeline](https://github.com/ncsa/MayomicsVC/blob/dev-gatk/src/wdl/gatk/GermlineMasterWorkflow_toil.wdl), in light of the supported features mentioned in [Toil documentation here](https://toil.readthedocs.io/en/latest/running/wdl.html#wdl-specifications). 

This script has been tested with `cromwell-37`, and runs as expected. However, I couldn't get it to work with `toil-wdl-runner`. From debugging, I could form a few conclusions but would like to hear from you nonetheless.

1. _Documentation fix_: With WDL [v1.0](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) being out, and supported by cromwell; it is helpful for readers to know that toil does not actually support WDL v1.0 (so, for example, the `version` statement should not be there, inputs need to be directly listed before the command within a task and not eclosed by explicit `input {` and `}`, ... etc )
1. _A note to self_: For some of my inputs, it was appropriate to pass some parameters as ` -o "'${BWAExtraOptionsString}'" ` within the command block of the wdl `task` definition. The toil runner was not happy and generated the rather non-informative error message below. It took a minute to relate to this part, but thought to mention it nonetheless.

```
  File "/home/azza/github_repos/varCall/toilwdl_compiled.py", line 574
    command49 = r''' -o "''''
                            ^
SyntaxError: EOL while scanning string literal
```

1. _Conditionals_: Control flow via `if` statements is supported by toil
1. _Scatter_: Scatter logic is supported by toil as rightfully mentioned in the toil documentation link
1. _Conditionals nested within scatter _: An `if` statement nested within a wdl `scatter` block is not evaluated. For example, the parsing/compilation of my wdl script above (in `toilwdl_compiled.py`) breaks due to such occurance. Below are code snippets of the error, context within the parsed code, and a strip down of the corresponding wdl code:

```
# The error message:
  File "/home/azza/github_repos/varCall/toilwdl_compiled.py", line 2303
    rvDict = {}
         ^
IndentationError: expected an indented block
```

```
# Relevant lines in toilwdl_compiled.py:
2301        for lane in NormalInputReads:
2302
2303        rvDict = {} 
2304        return rvDict
```

```
# The nested scatter-if block in the wdl script:
        scatter (lane in NormalInputReads) {
           if(PairedEnd) {
              call trimsequencesTask as TRIMSEQ_paired
	   }
	   if(!PairedEnd) {
	      call trimsequencesTask as TRIMSEQ_single
	   }
	}
	
```

1. _**_Help needed_**_: From the previous observation, I removed conditions from scatter blocks; yet I'm not able to go past the first scatter block. I also stripped down the script to the minimum (
[GermlineMasterWorkflow_toilsimplified.wdl.txt](https://github.com/DataBiosphere/toil/files/3065375/GermlineMasterWorkflow_toilsimplified.wdl.txt); and the corresponding json [germlinemasterworkflow_toil.json.txt](https://github.com/DataBiosphere/toil/files/3065374/germlinemasterworkflow_toil.json.txt) ). Yet, I get this error message which I can not follow through. Would you be able to help with this? I'm not sure if there is a way to show more informative error log.

```
$ toil-wdl-runner GermlineMasterWorkflow_toilsimplified.wdl germlinemasterworkflow_toil.json

INFO:toil.wdl.wdl_functions:Importing /home/azza/github_repos/varCall/Inputs/HG00120.lowcoverage.chr20.smallregion_1.fastq.gz into the jobstore.
INFO:toil.wdl.wdl_functions:Importing /home/azza/github_repos/varCall/Inputs/HG00120.lowcoverage.chr20.smallregion_2.fastq.gz into the jobstore.
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (4).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (6141247488).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (5690355712).
INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
INFO:toil.leader:Issued job 'EncapsulatedJob' R/l/jobPAfDuE with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/varCall/toil-tsts/toilWorkflowRun'.
INFO:toil.leader:Job ended successfully: 'EncapsulatedJob' R/l/jobPAfDuE
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'alignmentTaskCls' R/l/jobPAfDuE
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpFtgESg-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpt1yL4w-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpbmanrZ-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: initialize_jobs
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpk2QR4n-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpCS_0ka-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: scatter0
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmp4xc6aB-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: trimsequencesTask
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpAdpGKZ-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpQOpmvQ-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: scatter1
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:Can't globalize module ModuleDescriptor(dirPath='/home/azza/github_repos/varCall/toil-tsts', name='toilwdl_compiled', fromVirtualEnv=False).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpb8LznN-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: alignmentTask
WARNING:toil.leader:R/l/jobPAfDuE    Traceback (most recent call last):
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/worker.py", line 324, in workerScript
WARNING:toil.leader:R/l/jobPAfDuE        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:R/l/jobPAfDuE        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:R/l/jobPAfDuE        return self.run(fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/github_repos/varCall/toil-tsts/toilwdl_compiled.py", line 668, in run
WARNING:toil.leader:R/l/jobPAfDuE        OutputBams = process_outfile(output_filename, fileStore, tempDir, '/home/azza/github_repos/varCall/toil-tsts')
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/wdl/wdl_functions.py", line 277, in process_outfile
WARNING:toil.leader:R/l/jobPAfDuE        return process_single_outfile(f, fileStore, workDir, outDir)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/wdl/wdl_functions.py", line 259, in process_single_outfile
WARNING:toil.leader:R/l/jobPAfDuE        '{}\n'.format(f, tmp, exe))
WARNING:toil.leader:R/l/jobPAfDuE    RuntimeError: OUTPUT FILE: HG00120.bam was not found!
WARNING:toil.leader:R/l/jobPAfDuE    total 4.3M
WARNING:toil.leader:R/l/jobPAfDuE    drwx------ 3 azza azza 4.0K Apr 10 20:38 .
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxrwx 3 azza azza 4.0K Apr 10 20:38 ..
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxr-x 2 azza azza 4.0K Apr 10 20:38 execution
WARNING:toil.leader:R/l/jobPAfDuE    -rw-rw-r-- 1 azza azza 2.2M Apr 10 20:38 HG00120.lowcoverage.chr20.smallregion_1.fastq.gz
WARNING:toil.leader:R/l/jobPAfDuE    -rw-rw-r-- 1 azza azza 2.2M Apr 10 20:38 HG00120.lowcoverage.chr20.smallregion_2.fastq.gz
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    total 8.0K
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxr-x 2 azza azza 4.0K Apr 10 20:38 .
WARNING:toil.leader:R/l/jobPAfDuE    drwx------ 3 azza azza 4.0K Apr 10 20:38 ..
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    ERROR:toil.worker:Exiting the worker because of a failed job on host azza-Satellite-P845
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'alignmentTaskCls' R/l/jobPAfDuE with ID R/l/jobPAfDuE to 1
INFO:toil.leader:Issued job 'alignmentTaskCls' R/l/jobPAfDuE with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 2.0 G
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/home/azza/github_repos/varCall/toil-tsts/toilWorkflowRun'.
INFO:toil.leader:Job ended successfully: 'alignmentTaskCls' R/l/jobPAfDuE
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'alignmentTaskCls' R/l/jobPAfDuE
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.resource:'JTRES_148fe75160b89a3a979fcad3e835d3c1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.fileStore:Starting job R/l/jobPAfDuE/g/tmpb8LznN-_serialiseJob-stream with less than 10% of disk space remaining.
WARNING:toil.leader:R/l/jobPAfDuE    INFO:toil.fileStore:LOG-TO-MASTER: alignmentTask
WARNING:toil.leader:R/l/jobPAfDuE    Traceback (most recent call last):
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/worker.py", line 324, in workerScript
WARNING:toil.leader:R/l/jobPAfDuE        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:R/l/jobPAfDuE        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:R/l/jobPAfDuE        return self.run(fileStore)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/github_repos/varCall/toil-tsts/toilwdl_compiled.py", line 668, in run
WARNING:toil.leader:R/l/jobPAfDuE        OutputBams = process_outfile(output_filename, fileStore, tempDir, '/home/azza/github_repos/varCall/toil-tsts')
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/wdl/wdl_functions.py", line 277, in process_outfile
WARNING:toil.leader:R/l/jobPAfDuE        return process_single_outfile(f, fileStore, workDir, outDir)
WARNING:toil.leader:R/l/jobPAfDuE      File "/home/azza/toilenv/lib/python2.7/site-packages/toil/wdl/wdl_functions.py", line 259, in process_single_outfile
WARNING:toil.leader:R/l/jobPAfDuE        '{}\n'.format(f, tmp, exe))
WARNING:toil.leader:R/l/jobPAfDuE    RuntimeError: OUTPUT FILE: HG00120.bam was not found!
WARNING:toil.leader:R/l/jobPAfDuE    total 4.3M
WARNING:toil.leader:R/l/jobPAfDuE    drwx------ 3 azza azza 4.0K Apr 10 20:38 .
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxrwx 3 azza azza 4.0K Apr 10 20:38 ..
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxr-x 2 azza azza 4.0K Apr 10 20:38 execution
WARNING:toil.leader:R/l/jobPAfDuE    -rw-rw-r-- 1 azza azza 2.2M Apr 10 20:38 HG00120.lowcoverage.chr20.smallregion_1.fastq.gz
WARNING:toil.leader:R/l/jobPAfDuE    -rw-rw-r-- 1 azza azza 2.2M Apr 10 20:38 HG00120.lowcoverage.chr20.smallregion_2.fastq.gz
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    total 8.0K
WARNING:toil.leader:R/l/jobPAfDuE    drwxrwxr-x 2 azza azza 4.0K Apr 10 20:38 .
WARNING:toil.leader:R/l/jobPAfDuE    drwx------ 3 azza azza 4.0K Apr 10 20:38 ..
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    
WARNING:toil.leader:R/l/jobPAfDuE    ERROR:toil.worker:Exiting the worker because of a failed job on host azza-Satellite-P845
WARNING:toil.leader:R/l/jobPAfDuE    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'alignmentTaskCls' R/l/jobPAfDuE with ID R/l/jobPAfDuE to 0
WARNING:toil.leader:Job 'alignmentTaskCls' R/l/jobPAfDuE with ID R/l/jobPAfDuE is completely failed
INFO:toil.leader:Finished toil run with 1 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'alignmentTaskCls' R/l/jobPAfDuE
INFO:toil.common:Successfully deleted the job store: FileJobStore(/home/azza/github_repos/varCall/toil-tsts/toilWorkflowRun)
Traceback (most recent call last):
  File "/home/azza/github_repos/varCall/toil-tsts/toilwdl_compiled.py", line 2368, in <module>
    fileStore.start(job0)
  File "/home/azza/toilenv/lib/python2.7/site-packages/toil/common.py", line 771, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/azza/toilenv/lib/python2.7/site-packages/toil/common.py", line 1044, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/azza/toilenv/lib/python2.7/site-packages/toil/leader.py", line 245, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
Traceback (most recent call last):
  File "/home/azza/toilenv/bin/toil-wdl-runner", line 10, in <module>
    sys.exit(main())
  File "/home/azza/toilenv/lib/python2.7/site-packages/toil/wdl/toilwdl.py", line 146, in main
    subprocess.check_call(cmd)
  File "/home/azza/toilenv/lib/python2.7/site-packages/subprocess32.py", line 307, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess32.CalledProcessError: Command '['python', '/home/azza/github_repos/varCall/toil-tsts/toilwdl_compiled.py']' returned non-zero exit status 1.
```

Would you be able to comment on these issues, and maybe help with debugging the last error message? 

Thank you
Azza

====

* My environment:

```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

* Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6  (from the execution log)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-37)
┆Epic: Improved WDL support and more complex conformance tests Q5
┆Issue Number: TOIL-37

**Comment by adamnovak** [comment]
1. As for documentation of our supported WDL version, it looks like @DailyDreaming wrote all the WDL code. Lon, what version of WDL did you implement? It could be https://github.com/openwdl/wdl/blob/master/versions/draft-2/SPEC.md or https://github.com/openwdl/wdl/blob/master/versions/draft-3/SPEC.md. Also, do we have the resources to bring WDL support up to 1.0?

2. It looks like our WDL-to-Python compiler is vulnerable to code injection and does not properly escape what you are trying to pass here. I think the Right Way to fix this is to generate all our code as syntax trees with the Python [`ast`](https://docs.python.org/3.7/library/ast.html#ast.AST) module, and then turn it into source with [`astor`](https://astor.readthedocs.io/en/latest/#astor.to_source), but that would be a major refactor. As it is, it seems to be identifying a non-variable part of the command, `-o "'`, and then trying to translate it into Python by [just wrapping it in `r'''` and `'''`](https://github.com/DataBiosphere/toil/blob/ad54ae525b22ab782a7adba1a266c558b69e0cca/src/toil/wdl/wdl_analysis.py#L261), which doesn't work if the last character is a single quote. We need to escape `code_snippet.source_string` on that line. We also probably need to add a bunch of other escapes throughout the code generation, because I didn't see a concept of escaping literals anywhere.

3. We do indeed support conditionals.

4. We also support scatter.

5. We seem to not support conditionals in scatters, because the code to generate the conditional inside the scatter, which would go [in this if statement](https://github.com/DataBiosphere/toil/blob/8057b47f3841f177e040def8ef1b2f1968f0cd94/src/toil/wdl/wdl_synthesis.py#L517-L524), is absent. We also don't have an `else` to throw an error about an unsupported shape of WDL syntax tree, so we continue on without ever writing a body for that loop, leading to the error you observed.

5. (again) The error message you gave looks to me like the AlignmentScript (`/home/azza/github_repos/varCall/MayomicsVC/src/shell/gatk/alignment.sh`) ran or was supposed to have run, but it didn't produce the output file that the WDL thinks it should have produced (`"${SampleName}.bam"`). I guess the WDL implementation checks each task to make sure the expected outputs exist, and aborts if it can't find them.

Are you sure `alignment.sh` works? Do you have any evidence that it actually ran? Does it (or can you make it) log somewhere so you can see if it is running and if it is encountering any problems?

**Comment by azzaea** [comment]
Thank you @adamnovak! 
- On points 1-5 from your list: for context, I'm benchmarking different workflow management systems, hence it matters to me to examine and explicitly specify features/ capabilities as was done above. Thank you for your explanations for how it was done.
- On point 6: Yes, the [alignment.sh.txt](https://github.com/DataBiosphere/toil/files/3072063/alignment.sh.txt)  bash script works individually (this is a log without extensive debugging: [bash_run_nodebug.log.txt](https://github.com/DataBiosphere/toil/files/3072144/bash_run_nodebug.log.txt), and here is a log with debugging enabled (by passing a '-d' parameter like in the Json file) [bash_run_debug_mode.log.txt](https://github.com/DataBiosphere/toil/files/3072141/bash_run_debug_mode.log.txt). I can also confirm that the wdl script works when invoked via cromwell ( [cromwell_run.log.txt](https://github.com/DataBiosphere/toil/files/3072164/cromwell_run.log.txt) )

* For some reason, `toil-wdl-runner` simply deletes the temporary folder it uses for processing intermediate results, and leaves none but a log (attached again: [toil_run.log.txt](https://github.com/DataBiosphere/toil/files/3072206/toil_run.log.txt) ). It seems that `toil-wdl-runner` is checking the task output as specified in the wdl code, but I can't tell whether it attempte to rund the command part of the task nor how it went.

Thanks again.

**Comment by DailyDreaming** [comment]
@azzaea Our WDL support is based on pre-WDL 1.0 (draft 3 I believe), and as the documentation states, still in alpha, and thus doesn't fully support all of the features of WDL.  There hasn't been bandwidth for a while to get this up to where it needs to be for a beta release unfortunately.

One step to comprehensive WDL support would be a suite of conformance tests similar to those we run for CWL.  It's been quite a while since I worked on this code, but the last I checked, that did not exist.  Since Cromwell does not seem to have them (a brief search indicates this is likely still the case?) we would have to create them.

@adamnovak I think it'd be simplest to write out a translated bash script file for each job, as this is Cromwell's behavior and let bash handle the escaping.  This would be a refactor (though not as dramatic as adopting astor) and has some disadvantages, but I think it would simplify things.

We do generate an AST via the same method that Cromwell does (Hermes), and it is mostly directly translatable to python, even trivially so in many cases.  The main hurtle which was never fully addressed however, is toil's use of pickling and promises.  There is some logic in the code to get around this, but it is in need of rethinking.

**Comment by azzaea** [comment]
Thanks @DailyDreaming . I understand. 
Helpful pointers would be, for example: some good context for what constitutes a "basic" wdl script that toil can handle? Or, how to stop automatic deletion of the execution folder so that one can actually see some useful logs?
The execution logs from running toil on my script indicate that toil is looking for inputs and outputs, but does not at all tell that it actually attempts to execute the command part of a wdl task.

**Comment by DailyDreaming** [comment]
@azzaea You're right, we haven't nailed down exactly what works.  We have a few wdl scripts that run as a part of our testing, including all of the tutorial wdl scripts from their site and an ENCODE workflow I believe, which I admit is not very helpful.

If I get bandwidth in the coming weeks, there might be an attempt to shore this up and address your points, to see about saving the logs as well as providing better information in those logs.  If so, the documentation will be updated.

Thanks for your feedback on this, it's much appreciated!

**Comment by azzaea** [comment]
Hello @DailyDreaming !

Just thought to report on a relevant pattern that doesn't seem supported. While simple Scattering of tasks works, chaining tasks within a Scatter does not.
Below is an example snippet that works fine (with toil-wdl-runner) outside a Scatter, or if a single task is called, but not via a chain:
```
$ cat chained_scatter.wdl
task hostTask {
	Int i

	command {
		hostname	
	}
	output {
		Int taskID = i 
		String result = read_string(stdout())
	}
	runtime {
		cpu:  1
	}
}

task catHostsTask {
	Array[String] result1
	Array[String] result2
    String logfile

	command {
		#echo "${sep=';' result1}"| tr ";" "\n" | sort -u > ${logfile}
        echo "${sep=';' result1};${sep=';' result2}" | tr ";" "\n" | sort -u > ${logfile}
	}
	output {
		File result = "${logfile}"
	}
}

workflow hostwf {
    String logfile
	Int ntasks

	scatter (n in range(ntasks)) {
		call hostTask as host1 {input: i=n}
		call hostTask as host2 {input: i=host1.taskID}
	}

	call catHostsTask {input: result1 = host1.result, result2 = host2.result, logfile = logfile }

	output {
		File log = catHostsTask.result
	}
}

$
$ cat inputs.json
{
  "hostwf.ntasks": 3 ,
  "hostwf.logfile": "log.txt2"

}
```
