### ISSUE TITLE
Temporary CWL workdir files are not cleaned up

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2601]
The CWL runner creates temporary dirs in `workdir` to use as temporary output dirs ([code](https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L586)). These are added to `openTempDirs` variable and are supposed to be cleaned up after the workflow is done through the [`cleanTempDirs`](https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L1031) function. However, this function is only added as a [followOn to the first CWLJob](https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L1273) and not for the nested workflows [*]. This results in intermediate files being left on the workers, which can take up a lot of space.

[*] It doesn't even seem to work for the first one as [`wf1 is CWLJob`](https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L1272) is always false. Should it be `isinstance(wf1, CWLJob)` instead?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-35)
┆Issue Number: TOIL-35

**Comment by arostamianfar** [comment]
Actually, it looks like we can safely delete the temporary files in the `run` method itself just [after the output files are copied to the global filesystem](https://github.com/DataBiosphere/toil/blob/6a18b8a6a4ad885729ef9fa53542e0a6fd4b6c0a/src/toil/cwl/cwltoil.py#L615). I tested it on a sample workflow and it seems to work fine as those temporary files are not referenced anymore.

**Comment by adamnovak** [comment]
OK, I am able to replicate this issue using the workflow at https://www.commonwl.org/user_guide/05-stdout/index.html
