### ISSUE TITLE
Advertise Python 3 support

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2603]
https://github.com/DataBiosphere/toil/blob/5c68dc4a1781f63a5190ee8efaf22da1a2bfa086/setup.py#L126

We now run on Python 3; setup.py should say so.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-34)
┆Issue Number: TOIL-34

**Comment by illusional** [comment]
The docs website might also need to be updated:

> Toil currently supports only Python 2.7 and requires a virtualenv to be active to install.

**Comment by adamnovak** [comment]
OK, #2710 should fix this, after Read the Docs gets updated.

@DailyDreaming RtD seems to still be showing the 3.19 docs as "latest". Did you manage to update the current version to 3.20 in the admin interface yet?

**Comment by DailyDreaming** [comment]
Looks like this is done.
