### ISSUE TITLE
Delete Redundant Tests.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2623]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-21)
┆Issue Number: TOIL-21
┆Epic: Better Testing

**Comment by adamnovak** [comment]
#2716 is merged now. I'm not sure if we should keep looking for more redundant tests.

**Comment by cricketsloan** [comment]
➤ Jeffrey Wu commented:

Yeah everything looks pretty reasonable.
