### ISSUE TITLE
Update Versions: Cloud-Config -> Ignition

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2627]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-17)
┆Issue Number: TOIL-17

**Comment by DailyDreaming** [comment]
Not sure if this will ever be done.  I think the current plan is to leave the mesos structure in place and eventually move to kubernetes.

Leaving this open just in case though.  It would/should probably be done in conjunction with https://github.com/DataBiosphere/toil/issues/2954 if it comes to it.

**Comment by adamnovak** [comment]
We use Ignition templates now for configuring Flatcar.
