### ISSUE TITLE
Decide When/Whether to Drop python2.7 and Go Only python3 (Should be Coordinated with CWL folks if/when they/we do this).

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2629]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-15)
┆Issue Number: TOIL-15

**Comment by DailyDreaming** [comment]
Probably after Python2.7 goes out of support Jan 1st, 2020.

**Comment by mr-c** [comment]
You can drop py2.7 any time you want to, from my perspective. `cwltool` already has robust py3 support.
