### ISSUE TITLE
Allow jobs to wrap class functions, nested functions and lambda functions

### ISSUE THREAD

**Issue by benedictpaten** [DataBiosphere/toil#264]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-307)
┆Issue Number: TOIL-307

**Comment by benedictpaten** [comment]
I am making this part of the release because it is an important user interface feature, I also think it's easy to add.

**Comment by hannes-ucsc** [comment]
I'm afraid this won't make it into the release.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
