### ISSUE TITLE
Fix Toil for Python 3.7

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#2645]
```
_____________ ERROR collecting src/toil/test/src/fileStoreTest.py ______________
src/toil/test/src/fileStoreTest.py:1347: in <module>
    _exportStaticMethodAsGlobalFunctions(hidden.AbstractFileStoreTest)
src/toil/test/src/fileStoreTest.py:1341: in _exportStaticMethodAsGlobalFunctions
    method = value.__func__
E   AttributeError: 'builtin_function_or_method' object has no attribute '__func__'
_____________ ERROR collecting src/toil/test/src/fileStoreTest.py ______________
src/toil/test/src/fileStoreTest.py:1347: in <module>
    _exportStaticMethodAsGlobalFunctions(hidden.AbstractFileStoreTest)
src/toil/test/src/fileStoreTest.py:1341: in _exportStaticMethodAsGlobalFunctions
    method = value.__func__
E   AttributeError: 'builtin_function_or_method' object has no attribute '__func__'
```

From https://travis-ci.org/DataBiosphere/toil/jobs/523850578#L458

Also, fix all the warnings: https://travis-ci.org/DataBiosphere/toil/jobs/523850578#L471

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-4)
┆Issue Number: TOIL-4

**Comment by DailyDreaming** [comment]
Adding this here.  Installing on python3.7 via normal methods seems to error on gcc compiling `http-parser`.  Manually running `pip install git+https://github.com/benoitc/http-parser` to install the latest seems to fix this.

Looking into fixing the tests now.
