### ISSUE TITLE
Jobs "ended successfully" when they fail

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2648]
We report jobs in the log as having "ended successfully" even when the jobs have actually failed. We should not lie to our users; they complain to me that they get confused. We should change that message to "has stopped running" or something.

```
2018-07-03 12:46:55,043 - toil.leader - INFO - Job ended successfully: ...
2018-07-03 12:46:55,050 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: ...
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-3)
┆Issue Number: TOIL-3

**Comment by jeffrey856** [comment]
Made a PR on #2729

**Comment by adamnovak** [comment]
We should probably leave this open until #2729 actually is merged.

If you write "Closes #XXXX" in your PR description, the issue will automatically be closed when the PR is merged.

**Comment by DailyDreaming** [comment]
#2729 was merged.  Closing this.
