### ISSUE TITLE
WDL standard 'read_json" function not implemented, leading to NameError: name 'read_json' is not defined

### ISSUE THREAD

**Issue by pb-cdunn** [DataBiosphere/toil#2672]
```py
Traceback (most recent call last):
  File ".../toilwdl_compiled.py", line 51, in <module>
    cfg = (read_json(config_fn))
NameError: name 'read_json' is not defined
```
```py
 44 if __name__=="__main__":
 45     options = Job.Runner.getDefaultOptions("./toilWorkflowRun")
 46     options.clean = 'always'
 47     with Toil(options) as fileStore:
 48
 49         # WF Declarations
 50         config_fn = process_infile('config.json', fileStore)
 51         cfg = (read_json(config_fn))
 52         env_script_fn = (cfg[env_script])
 53         reads_fn = process_infile((cfg[input]), fileStore)
...
```
```java
workflow AssembleCLR {
    File config_fn = "config.json"
    Map[String, String] cfg = read_json(config_fn)
    String env_script_fn = cfg["env_script"]
...
```
* https://software.broadinstitute.org/wdl/documentation/spec#map-deserialization-using-read_json

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-359)
┆Issue Number: TOIL-359
┆Epic: WDL Standard Library Implementation

**Comment by adamnovak** [comment]
I believe the `read_json` function from the WDL standard library has not yet been implemented in Toil. Somebody will have to implement it before it can be used.

**Comment by pb-cdunn** [comment]
It's an invaluable function. It allows an array of outputs to be converted into a file of filenames. It's especially useful for `Array[Array[File]]`, which can be the result of a parallel task.

**Comment by DailyDreaming** [comment]
Superceded by https://github.com/DataBiosphere/toil/issues/2417 .  Should be included in: https://github.com/DataBiosphere/toil/pull/2886 .
