### ISSUE TITLE
WDL "version" specifier leads to SyntaxError: Finished parsing without consuming all tokens.

### ISSUE THREAD

**Issue by pb-cdunn** [DataBiosphere/toil#2673]
* https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html

```java
version 1.0  # my only change, as this is required for Cromwell

workflow write_simple_file {
    call write_file
}
task write_file {
    String message
    command { echo ${message} > wdl-helloworld-output.txt }
    output { File test = "wdl-helloworld-output.txt" }
}
```
```py
toil-wdl-runner wdl-helloworld.wdl wdl-helloworld.json
Traceback (most recent call last):
  File "/pbi/flash/cdunn/repo/ipacd/.git/LOCAL/bin/toil-wdl-runner", line 11, in <module>
    load_entry_point('toil==3.19.0', 'console_scripts', 'toil-wdl-runner')()
  File "/pbi/flash/cdunn/repo/ipacd/.git/LOCAL/lib/python3.7/site-packages/toil/wdl/toilwdl.py", line 116, in main
    ast = wdl_parser.parse(wdl_string).ast()
  File "/pbi/flash/cdunn/repo/ipacd/.git/LOCAL/lib/python3.7/site-packages/toil/wdl/wdl_parser.py", line 1074, in parse
    raise ctx.errors.excess_tokens()
toil.wdl.wdl_parser.SyntaxError: Finished parsing without consuming all tokens.
```
Maybe Toil should use the standard WDL parser? `pip3 install wdl_parser`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-360)
┆Issue Number: TOIL-360

**Comment by DailyDreaming** [comment]
`wdl_parser` uses the same parser we do: https://github.com/TMiguelT/WdlParserPackaging/blob/master/regenerate_parsers.sh#L14

Which is generated by Hermes.  We just pinned the version rather than always using the latest in order to prevent breakage.  It looks like `wdl_parser` only has one release back in 2018, so I'd hesitate to call it a standard.

That said, we should probably update our parser.

**Comment by pb-cdunn** [comment]
Has Toil updated its parser yet? I might try Toil on our Cromwell WDLs.

**Comment by Prakash2403** [comment]
@DailyDreaming @pb-cdunn 
Actually I did regenerate the parser for v1.0 and replaced existing `wdl_parser.py` with the one I generated, but that only made things worse. Some of the WDL workflows, which were parsed by the existing parser start throwing errors.

**Comment by adamnovak** [comment]
We think that after #3468 and a bit more sprucing up of that, we can cut over to a MiniWDL-based system here that will be able to parse this.

**Comment by DailyDreaming** [comment]
This shouldn't apply to our current parser and I'm closing this as resolved.  Please reopen if this is not the case.
