### ISSUE TITLE
CWL conformance longer timeout

### ISSUE THREAD

**Issue by jeffrey856** [DataBiosphere/toil#2676]
CWL conformance tests need a longer timeout.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-362)
┆Issue Number: TOIL-362

**Comment by adamnovak** [comment]
@jeffrey856 Did you close this because you fixed it? If so, it should probably stay open until the PR that fixes it is merged.
