### ISSUE TITLE
[Question] Schedule and poll use pattern

### ISSUE THREAD

**Issue by innovate-invent** [DataBiosphere/toil#2679]
Hi, I am interested in building off of your project but my use pattern doesn't seem to fit the documented method of launching a job graph.
Does Toil support launching a workflow and have the client terminate with a invocation token of some sort? I would like to then poll the state of the invocation periodically.

All I can find is this use pattern:
```python
with Toil(options) as toil:
    toil.start(Job())
```
which requires a running shell on the client until the workflow returns.

Any advice is greatly appreciated.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-363)
┆Issue Number: TOIL-363

**Comment by adamnovak** [comment]
Hello, @innovate-invent! Glad to hear you're considering using Toil!

Toil isn't a multi-tenant or even a multi-workflow scheduler. The Toil architecture has each workflow take care of its own scheduling (either by running its jobs on the current machine, or by farming them out to other machines using some backing multi-tenant scheduling system like Mesos or Slurm).

If you want to kick off workflows and get the results later, you'd need some extra machinery besides just Toil: some kind of server sitting in front of it that takes workflow scripts/environments and their arguments, runs them to completion, and lets you poll them through some kind of API.

Another option, if you're using a cluster scheduler like Slurm, might be to submit the toil workflow command to the cluster scheduler as a job itself, which then kicks off more jobs to actually run the workflow. Essentially you'd use the scheduler Toil is going to run against to also be the extra machinery sitting in front of Toil.

**Comment by DailyDreaming** [comment]
@innovate-invent Hi, you may be interested in https://github.com/common-workflow-language/workflow-service

The code there was originally written for WES with an API that allows running jobs remotely.  It allows for a toil backend and you ought to be able to get it up and running from the readme on the front page.

Hope that helps.  :)

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if this is still an issue.
