### ISSUE TITLE
Docker mount problem on MAC

### ISSUE THREAD

**Issue by FarahZKhan** [DataBiosphere/toil#2680]
This issue is similar to the one closed earlier: [#1778](https://github.com/DataBiosphere/toil/issues/1778). 
I have used [somatic workflow](https://github.com/FarahZKhan/bcbio_test_cwlprov/blob/master/somatic/somatic-workflow/main-somatic.cwl), [job file](https://github.com/FarahZKhan/bcbio_test_cwlprov/blob/master/somatic/somatic-workflow/main-somatic-samples.json) and the [test data](https://github.com/FarahZKhan/bcbio_test_cwlprov/tree/master/testdata). The following command was executed: 

 `time TMP=$PWD toil-cwl-runner --workDir=./ main-somatic.cwl main-somatic-samples.json`

**Error:**

`WARNING:toil.leader:Q/h/job4qHzIW        run_number=0
WARNING:toil.leader:Q/h/job4qHzIW    docker: Error response from daemon: Mounts denied: EOF.
WARNING:toil.leader:Q/h/job4qHzIW    time="2019-05-21T16:56:08+10:00" level=error msg="error waiting for container: context canceled"`. 

**Mac OS specs**

High Sierra Version 10.13.3

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-364)
┆Issue Number: TOIL-364

**Comment by adamnovak** [comment]
@FarahZKhan Does your Docker installation work for you when you try and manually run a container with a mount in the directory you are working in?

Can you provide more of the log? What step of the workflow is it trying to run when it fails?

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if this is still an issue.

**Comment by adamnovak** [comment]
FWIW, there's a configuration GUI in Docker for Mac where there's a list of the directories you are allowed to mount over to Docker. By default, you can't mount directories from just anywhere on your system. So make sure that a parent of the directory Toil is working in (which might be the current directory, or your system temp directory) is on that list of allowed directories.
