### ISSUE TITLE
Cloud strategy!  Make tutorials for deploying useful toil workflows in AWS in a research context for new grads.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2692]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-370)
┆Issue Number: TOIL-370

**Comment by diekhans** [comment]
I volunteer to be a test case and work with the writer.  I am still spoiled
by having access to hgwdev.

**Comment by adamnovak** [comment]
Lon thinks we have these now.
