### ISSUE TITLE
Use boto3 API for s3 uploads/downloads

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2704]
Currently, uploading/downloading large files to/from the S3 jobstore is slow as it's single threaded. The new `boto3` API actually has a [nice interface](https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/s3/transfer.html) with multithreaded uploads/downloads that can dramatically speed up the process especially for large files. It also simplifies the logic as we no longer need to add custom logic to specify the chunkSize ourselves.

Related tutorial: https://medium.com/@niyazi_erd/aws-s3-multipart-upload-with-python-and-boto3-9d2a0ef9b085

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-378)
┆Issue Number: TOIL-378

**Comment by arostamianfar** [comment]
@adamnovak FYI, I renamed this issue to extend the scope in light of your comment in #2707 ... I unassigned myself for now as I may not have time to look into it soon. So please feel free to pick it up!

**Comment by arostamianfar** [comment]
Reopening this issue as the PR that closed this was reverted in https://github.com/DataBiosphere/toil/pull/3177

**Comment by DailyDreaming** [comment]
That PR has been updated and merged back into master: https://github.com/DataBiosphere/toil/pull/3400
