### ISSUE TITLE
x86_64 "type" is hardcoded in lsf.py but not set on all LSF clusters

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2725]
Our LSF batch system requires nodes to have `type==X86_64`, bit not all LSF clusters actually put that type on their nodes (and in theory someone might want to run jobs on ARM or something).

We shouldn't hardcode this restriction. Eventually, we may need to expose required architecture through to the Toil layer, or add this restriction back in as an option for people running clusters with heterogeneous architectures.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-389)
┆Issue Number: TOIL-389

**Comment by drkennetz** [comment]
I think you can close this @adamnovak as explicit architecture has been removed from the code.
