### ISSUE TITLE
toil-cwl-runner isn't assigning defaults for subworkflow

### ISSUE THREAD

**Issue by illusional** [DataBiosphere/toil#2727]
Hi, I've got a little problem with the way Toil is providing defaults for subworkflows:

In CWL, I've got a sub-workflow (`sbwf`) that has an input with a default that goes to a tool that takes a required input (`tool.inp`). I wrap this sub-workflow in a new workflow (`wf`) and **don't** map an input from `wf`,

This workflow (provided at the bottom) does not have any validation issues with CWLTool (or Toil, but this uses CWLTool), and runs successfully on CWLTool. However, on Toil this workflow fails with when executing the tool: 

```
WARNING:toil.leader:I/a/jobv8meez5o    cwltool.errors.WorkflowException: tools/Echo.cwl:6:3: 
    Missing required input parameter 'inp'
```

I'm happy to submit a patch for this, but need a bit of assistance working out where the best place to start would be. I'm presuming it's probably somewhere on `cwltoil` where there should be an additional `fill_in_defaults` call.

---

WORKFLOWS:

Place these all in the same folder and run:
- `toil-cwl-runner wf.cwl`
- `cwltool wf.cwl`

`wf.cwl`
```cwl
class: Workflow
cwlVersion: v1.0
id: wf
inputs: {}
outputs:
  outputid:
    id: outputid
    outputSource: wf/output_identifier
    type: File
requirements:
  SubworkflowFeatureRequirement: {}
steps:
  wf:
    in: {}
    out:
    - output_identifier
    run: sbwf.cwl
```
`sbwf.cwl`
```cwl
class: Workflow
cwlVersion: v1.0
id: sbwf
inputs:
  input_identifier:
    default: test
    id: input_identifier
    type: string
outputs:
  output_identifier:
    id: output_identifier
    outputSource: step_identifier/outp
    type: File
steps:
  step_identifier:
    in:
      inp:
        id: inp
        source: input_identifier
    out:
    - outp
    run: Echo.cwl
```

Tool: `Echo.cwl`
```cwl
baseCommand: echo
class: CommandLineTool
cwlVersion: v1.0
id: Echo
inputs:
- id: inp
  inputBinding:
    position: 0
  label: inp
  type: string
outputs:
- id: outp
  label: outp
  type: stdout
requirements:
  DockerRequirement:
    dockerPull: ubuntu:latest
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-390)
┆Issue Number: TOIL-390

**Comment by mr-c** [comment]
Thank you @illusional for the report. I can reproduce this error and once we confirm this I'll even use this for a CWL conformance test.

**Comment by ionox0** [comment]
just making a note that this may be related to https://github.com/DataBiosphere/toil/issues/2512

**Comment by DailyDreaming** [comment]
Stale, closing.  Hoping that this is a cwl conformance test now.  Please reopen if this is still an issue.
