### ISSUE TITLE
Document --debugWorker flag

### ISSUE THREAD

**Issue by TMiguelT** [DataBiosphere/toil#2735]
As a toil user, I was looking for a way to let my IDE set breakpoints in my toil workflow, and I came across #1910. Once I worked out I could `--debugWorker`, this totally solved my problem.

However, this flag isn't documented:
* On the debugging help page: https://toil.readthedocs.io/en/3.15.0/running/debugging.html
* On the CLI help page: https://toil.readthedocs.io/en/3.15.0/running/cliOptions.html

I realise you may have done this because the flag is considered experimental (is it still experimental?), but even if it is I think it would be invaluable for users to document it in one or both of these places, even with some kind of disclaimer, because it improved productivity considerably for me.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-394)
┆Issue Number: TOIL-394

**Comment by TMiguelT** [comment]
I'm happy to put in a PR for this, but I figure it should have an issue and someone telling me it's a reasonable change first.

**Comment by adamnovak** [comment]
I think it makes sense to have a PR to document this, if it proves useful to you. I'm not sure we have it under test, or a really good way to test it, and I don't think anyone on the UCSC team is currently using Toil with the Python debugger, but the feature seems worth having and not too hard to maintain.

**Comment by mr-c** [comment]
@tmiguelt I wrote this feature and I'm very happy to have it better documented and publicized!

**Comment by TMiguelT** [comment]
Excellent. I'm surprised no-one else at UCSC has needed this before, I would struggle to debug a task without being able to step through the code.

**Comment by TMiguelT** [comment]
While I'm doing this, have you guys considered making the CLI docs autogenerated using [sphinx-argparse](https://sphinx-argparse.readthedocs.io/en/stable/)?

**Comment by adamnovak** [comment]
I haven't. It could certainly help people wade through our huge pile of options...
