### ISSUE TITLE
Upgrade Toil appliance to Python 3

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2742]
We want the Toil appliance Docker image to be on Python 3 *before* Python 2 goes out of support.

This involves modifying its build process, and also fixing bugs in Toil's AWS support on Python 3, which most users haven't encountered before because nobody uses the AWS job store and batch system and provisioner without the (Python 2) appliance images.

This will probably involve starting from https://github.com/DataBiosphere/toil/pull/2737 and will fix https://github.com/DataBiosphere/toil/issues/2736.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-399)
┆Issue Number: TOIL-399

**Comment by arostamianfar** [comment]
Curious if there are any updates/ETA on this?

**Comment by DailyDreaming** [comment]
@arostamianfar Not yet.  Some on setting up the testing infrastructure, but this should be next on the priority queue after that.

**Comment by adamnovak** [comment]
I'm a little concerned that we might have to keep the Python 2 version around at least until we properly end Python 2 support, because we need to support Cactus/Kubernetes, and AFAIK Cactus is still all Python 2 with no immediate plan in place to port it. We want at least one Toil release that Cactus can run on on Kubernetes before January.
