### ISSUE TITLE
Job running forever "INFO:toil.leader:Reissued any over long jobs"

### ISSUE THREAD

**Issue by multimeric** [DataBiosphere/toil#2753]
I created and SSH'd into my AWS head node according to the instructions on the documentation, and then I try to run my workflow:
```bash
python -m thousand_genomes_multiqc.workflow aws:us-west-2:toil-py2-dict --provisioner aws --nodeTypes c5.xlarge --maxNodes 4 --batchSystem mesos --retryCount 0
```

However, this just runs forever without stopping, and I have to manually terminate it. This ran for at least a day, but the actual process should only take minutes:
```
 --clean never 
DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG:botocore.credentials:Looking for credentials via: env
DEBUG:botocore.credentials:Looking for credentials via: assume-role
DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: custom-process
DEBUG:botocore.credentials:Looking for credentials via: config-file
DEBUG:botocore.credentials:Looking for credentials via: ec2-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: boto-config
DEBUG:botocore.credentials:Looking for credentials via: container-role
DEBUG:botocore.credentials:Looking for credentials via: iam-role
DEBUG:urllib3.util.retry:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
DEBUG:urllib3.connectionpool:http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 9
DEBUG:urllib3.util.retry:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
DEBUG:urllib3.connectionpool:Resetting dropped connection: 169.254.169.254
DEBUG:urllib3.connectionpool:http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/toil_toil HTTP/1.1" 200 1306
DEBUG:botocore.credentials:Found credentials from IAM Role: toil_toil
DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
DEBUG:botocore.hooks:Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fc406ac1848>
DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/s3/2006-03-01/service-2.json
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fc40a545f50>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function _handler at 0x7fc4059f10c8>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fc40a545d70>
DEBUG:botocore.args:The s3 config key is not a dictionary type, ignoring its value of: None
DEBUG:botocore.endpoint:Setting s3 timeout as (60, 60)
DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/_retry.json
DEBUG:botocore.client:Registering retry handlers for service: s3
DEBUG:botocore.client:Defaulting to S3 virtual host style addressing with path style addressing fallback.
DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python2.7/dist-packages/boto3/data/s3/2006-03-01/resources-1.json
DEBUG:botocore.hooks:Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fc406ac1848>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fc40a545f50>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function _handler at 0x7fc4059f10c8>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fc40a545d70>
DEBUG:botocore.args:The s3 config key is not a dictionary type, ignoring its value of: None
DEBUG:botocore.endpoint:Setting s3 timeout as (60, 60)
DEBUG:botocore.client:Registering retry handlers for service: s3
DEBUG:botocore.client:Defaulting to S3 virtual host style addressing with path style addressing fallback.
DEBUG:boto3.resources.factory:Loading s3:s3
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (4137213952).
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (36196081664).
Agent pid 3152
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
INFO:toil.leader:Issued job 'ThousandGenomesMultiQc' 4f0429f2-41eb-4258-9194-57f6f0570304 with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.provisioners.clusterScaler:Adding 1 non-preemptable nodes to get to desired cluster size of 1.
INFO:toil:Using default user-defined custom docker init command of  as TOIL_CUSTOM_DOCKER_INIT_COMMAND is not set.
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Overriding docker appliance of quay.io/ucsc_cgl/toil:3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6 with quay.io/ucsc_cgl/toil:3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6 from TOIL_APPLIANC
E_SELF.
INFO:toil.lib.ec2:Creating c5.xlarge instance(s) ... 
INFO:toil.leader:Job ended successfully: 'ThousandGenomesMultiQc' 4f0429f2-41eb-4258-9194-57f6f0570304
INFO:toil.leader:Issued job 'DownloadS3File' 8a02d301-9185-494c-b5bb-f38572990e21 with job batch system ID: 1 and cores: 1, disk: 1.0 G, and memory: 500.0 M
INFO:toil.leader:Issued job 'DownloadS3File' 084e3060-dc62-4b53-98d2-df3f33249796 with job batch system ID: 2 and cores: 1, disk: 1.0 G, and memory: 500.0 M
INFO:toil.leader:Job ended successfully: 'DownloadS3File' 084e3060-dc62-4b53-98d2-df3f33249796
INFO:toil.leader:Issued job 'BamToFastq' 6b0c98d4-3d28-4a86-8032-fbe936c81634 with job batch system ID: 3 and cores: 4, disk: 50.0 G, and memory: 1.0 G
INFO:toil.leader:Job ended successfully: 'DownloadS3File' 8a02d301-9185-494c-b5bb-f38572990e21
INFO:toil.leader:Issued job 'BamToFastq' 46d94bd4-b7cd-4158-9e67-32031a44d811 with job batch system ID: 4 and cores: 4, disk: 50.0 G, and memory: 1.0 G
INFO:toil.leader:Reissued any over long jobs
        INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
^[^[INFO:toil.leader:Reissued any over long jobs
stINFO:toil.leader:Reissued any over long jobs
^[[AINFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Reissued any over long jobs
```

I also checked the logs and there are none, apparently? So I have no idea what's going wrong:

```
$ toil status aws:us-west-2:toil-py2-dict --logInfo --printLogs
INFO:toil.utils.toilStatus:Traversing the job graph gathering jobs. This may take a couple of minutes.
LOG_FILE_OF_JOB:'ProcessSample' 4f0429f2-41eb-4258-9194-57f6f0570304 LOG: Job has no log file
LOG_FILE_OF_JOB:'DownloadS3File' 8a02d301-9185-494c-b5bb-f38572990e21 LOG: Job has no log file
LOG_FILE_OF_JOB:'BamToFastq' 46d94bd4-b7cd-4158-9e67-32031a44d811 LOG: Job has no log file
LOG_FILE_OF_JOB:'FastQC' 3f8ece42-43a7-4845-a98f-54b54b025a61 LOG: Job has no log file
LOG_FILE_OF_JOB:'MultiQc' 5a978aff-38d8-43bc-b713-7fd55da3c3f1 LOG: Job has no log file
LOG_FILE_OF_JOB:'FastQC' d518fc1d-8299-4a9c-b5db-813557f949e3 LOG: Job has no log file
LOG_FILE_OF_JOB:'MultiQc' 8ea7726d-114e-49a0-b2a1-1e1b64e2e57d LOG: Job has no log file
LOG_FILE_OF_JOB:'DownloadS3File' 084e3060-dc62-4b53-98d2-df3f33249796 LOG: Job has no log file
LOG_FILE_OF_JOB:'BamToFastq' 6b0c98d4-3d28-4a86-8032-fbe936c81634 LOG: Job has no log file
LOG_FILE_OF_JOB:'FastQC' ec723c81-51e8-42b9-bf3e-d89a6261f15a LOG: Job has no log file
LOG_FILE_OF_JOB:'MultiQc' aa2aa588-a8fb-42ed-be5c-8464232b9e7c LOG: Job has no log file
LOG_FILE_OF_JOB:'FastQC' 735fce93-b347-4f01-bcfb-654ff5fccbfd LOG: Job has no log file
LOG_FILE_OF_JOB:'MultiQc' 48342097-1404-418e-b84c-a0ecafd5cc89 LOG: Job has no log file
Of the 13 jobs considered, there are 9 jobs with children, 4 jobs ready to run, 0 zombie jobs, 0 jobs with services, 0 services, and 0 jobs with log files currently in <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7f1fc31cd710>
```

Is there any way to tell what's going on here? What does it mean for the workflow to be "Reissued any over long jobs"

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-401)
┆friendlyId: TOIL-401

**Comment by adamnovak** [comment]
`Reissued any over long jobs` is printed periodically by some code whose job it is to, I think, detect if jobs have been scheduled but never actually ran and try and run them again. It is printed whether or not there actually are any jobs for it to work on. So seeing it a lot in your log just means that a lot of time is passing without any other log messages.

I believe that by default log files for successfully completed jobs are cleaned up, so an absence of any log files just means that all the jobs that did run ran successfully.

You can get into this state when you have jobs that are too big to schedule on any of the node types you made available to the provisioner. Toil hands the jobs off to Mesos, but Mesos never runs them. If you look at https://aws.amazon.com/ec2/instance-types/c5/ you can see that a c5.xlarge machine, despite being "extra large", only has 8 GB of memory, which isn't a whole lot. They also have no instance storage besides what the provisioner gives them via EBS when it sets them up, which is controlled with the `--nodeStorage` option, and which I think defaults to 50 GB. So if you have any jobs in this workflow that need more than 8 GB of memory or 50 GB of disk, they won't be scheduled. I believe that if you pass --logDebug, you will see messages in the log indicating the size of the Mesos resource offers, and maybe complaining that they are too small to run the jobs that are pending.

We have code that is supposed to detect this problem, and throw warning messages if it thinks that the jobs you have to run are too big for the nodes you have available:

https://github.com/DataBiosphere/toil/blob/17b355a73f1ec8023c54e236c33471fc74f7e9de/src/toil/provisioners/clusterScaler.py#L83-L93

However, it does not appear to be getting triggered here.

Your problem might be disk space related; the default disk space provisioned for the nodes is 50 GB, and I noticed that the `BamToFastq` jobs that your log shows being issued but never finishing have a disk requirement of exactly 50 GB. It could be that the provisioner thinks it has 50 GB sized nodes to run your jobs, but Mesos sees that some of the disk space has already been used by Toil's internal temp files or something and doesn't offer the full 50 GB to run jobs. To fix this we might need to introduce some more slack in the provisioner.

This could also maybe happen if your previous jobs cluttered up the system temp directory and didn't clean up after themselves. We don't use containerization to sandbox the Mesos jobs, so they have write access to places like `/tmp`, and Mesos can't clean up after them by itself. Well-behaved Toil jobs need to ensure that they keep all their temp files in `job.filestore.getLocalTemDir()`, which is managed by Toil, using whatever command line options or environment variables are respected by child processes they run.

Try doing something like `--nodeStorage 100G` to provision more storage, and `--logDebug` (or looking at the Mesos web UI, which should be forwarded to `http://localhost:5050` on the machine you are running `toil ssh-cluster` from) to get an idea of what resources Mesos sees as available and why the jobs aren't actually being scheduled.

**Comment by TMiguelT** [comment]
Thanks @adamnovak, these are all very helpful points. I reran with `--logDebug and --nodeStorage 100`, and your prediction seems to be correct, I get this message printed out ad infinitum:

```
DEBUG:toil.batchSystems.mesos.batchSystem:Offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30782 not suitable to run the tasks with requirements {'disk': 2147483648, 'cores': 1, 'preemptable': False, 'memory': 2147483648, 'wallTime': 0}. Mesos offered 5850005504.0 memory, 0 cores and 42495639552.0 of disk on a non-preemptable agent.
DEBUG:toil.batchSystems.mesos.batchSystem:Although there are queued jobs, none of them could be run with offer {u'value': u'3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30782'} extended to the framework.
DEBUG:toil.batchSystems.mesos.batchSystem:Got offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30783 for a non-preemptable agent with 5579.00 MiB memory, 0.00 core(s) and 40527.00 MiB of disk.
DEBUG:toil.batchSystems.mesos.batchSystem:Offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30783 not suitable to run the tasks with requirements {'disk': 2147483648, 'cores': 1, 'preemptable': False, 'memory': 2147483648, 'wallTime': 0}. Mesos offered 5850005504.0 memory, 0 cores and 42495639552.0 of disk on a non-preemptable agent.
DEBUG:toil.batchSystems.mesos.batchSystem:Although there are queued jobs, none of them could be run with offer {u'value': u'3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30783'} extended to the framework.
DEBUG:toil.batchSystems.mesos.batchSystem:Got offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30784 for a non-preemptable agent with 5579.00 MiB memory, 0.00 core(s) and 40527.00 MiB of disk.
DEBUG:toil.batchSystems.mesos.batchSystem:Offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30784 not suitable to run the tasks with requirements {'disk': 2147483648, 'cores': 1, 'preemptable': False, 'memory': 2147483648, 'wallTime': 0}. Mesos offered 5850005504.0 memory, 0 cores and 42495639552.0 of disk on a non-preemptable agent.
DEBUG:toil.batchSystems.mesos.batchSystem:Although there are queued jobs, none of them could be run with offer {u'value': u'3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30784'} extended to the framework.
DEBUG:toil.batchSystems.mesos.batchSystem:Got offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30785 for a non-preemptable agent with 5579.00 MiB memory, 0.00 core(s) and 40527.00 MiB of disk.
DEBUG:toil.batchSystems.mesos.batchSystem:Offer 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30785 not suitable to run the tasks with requirements {'disk': 2147483648, 'cores': 1, 'preemptable': False, 'memory': 2147483648, 'wallTime': 0}. Mesos offered 5850005504.0 memory, 0 cores and 42495639552.0 of disk on a non-preemptable agent.
DEBUG:toil.batchSystems.mesos.batchSystem:Although there are queued jobs, none of them could be run with offer {u'value': u'3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-O30785'} extended to the framework.
DEBUG:toil.batchSystems.mesos.batchSystem:Although there are queued jobs, none of them were able to run in any of the offers extended to the framework. There are currently 1 jobs running. Enable debug level logging to see more details about job types and offers received.
DEBUG:toil.batchSystems.mesos.batchSystem:Got framework message from executor toil-3457 running on agent 3849f37a-b9b2-4f75-8135-ec3c9fd3f5ea-S18: {'nodeInfo': {'coresTotal': 4, 'workers': 1, 'memoryUsed': 0.081, 'memoryTotal': 7997911040L, 'coresUsed': 0.042}, 'address': '172.31.7.96'}
```

What is strange is that the resource requirement issue is not due to the lack of disk or memory size, but because the node reports itself as having 0 cores? It's a very strange problem to have.

Also, in terms of improving the user experience with this issue, if we have a fixed node shape, and Toil encounters a job that can't fit into that shape (like I have here), can't we log that into critical or error and then fail? Because I don't see how you can recover from this.

**Comment by adamnovak** [comment]
We can probably make the bin packing logic for the autoscaler raise an
error if it can't find a node that will fit your job. The issue you
were having though occurs because the bin packing algorithm thinks the
job will just fit, while Mesos disagrees and won't fit the job. We
could make the bin packing algorithm insist on a certain amount of
margin (especially for disk), and bail out if the node shapes look
merely big enough, or we could make the scaler destroy and recreate
idle nodes periodically in case their disks fill up with left-behind
files.

However, I think the log you posted doesn't actually show a deadlocked
state. See where it says "There are currently 1 jobs running."? Mesos
is offering 0 cores because the other cores are currently in use by a
job; Mesos offers only the free resources to Toil. It's also offering
~42 GB of disk, which with a 100 GB node size and a 50 GB job running,
would make sense as the amount of disk free, especially if cruft is
getting left on the disk in a way that was preventing progress with
the 50 GB nodes. 8 GB of cruft is rather a lot, unfortunately; that
suggests to me that something is really being left behind by a
previous job. We could look into a way to improve Mesos sandboxing to
prevent this from happening, but that might interfere with our caching
system's ability to share files between jobs.

If your workflow is getting stuck here, it could be that your job
itself is running forever. You can enable Toil's real-time logging
with --realTimeLogging, do from toil.realtimeLogger import
RealtimeLogger in your workflow, and log stuff with
RealtimeLogger.info() if you want to add some debugging to your job
itself so it can report its internal progress.

If you go in the Mesos web UI, you can get a nice view of what jobs
are running and what resources they are consuming. There's also the
Toil Grafana dashboard at `http://localhost:3000` which lets you keep
an eye on the number of running jobs in a nicer way than trawling the
logs.

**Comment by TMiguelT** [comment]
Sorry, yes you're right about the 0 core offers: they're definitely because jobs are currently running. I'm starting to think you're right about disk space, 42GB is pretty consistently what is offered, suggesting to me that temporary files are taking up space. Having said that, I don't see how either of my preceding jobs are leaking temporary files, since they should be using the correct temp directory:

```python
class DownloadS3File(Job):
    def __init__(self, key):
        super().__init__(memory='500M', cores=1, disk='50G')
        self.key = key

    def run(self, file_store):
        return file_store.importFile('s3://{}/{}'.format('1000genomes', self.key))

class BamToFastq(Job):
    def __init__(self, file_id):
        super().__init__(memory='1G', cores=4, disk='50G')
        self.file_id = file_id

    def run(self, file_store):
        cwd = Path(file_store.getLocalTempDir())
        bam = InputDockerFile('alignment.bam', cwd, file_store, self.file_id)
        r0 = OutputDockerFile('r0.fastq', cwd, file_store)
        r1 = OutputDockerFile('r1.fastq', cwd, file_store)
        r2 = OutputDockerFile('r2.fastq', cwd, file_store)

        apiDockerCall(
            self,
            entrypoint='samtools',
            image='quay.io/biocontainers/samtools:1.8--4',
            working_dir=str(cwd),
            parameters=[
                'fastq',
                '-0', r0.docker,
                '-1', r1.docker,
                '-2', r2.docker,
                '-@', str(self.cores),
                bam.docker,
            ]
        )

        return dict(r0=r0.upload(), r1=r1.upload(), r2=r2.upload())

```
The `r0.docker` properties are all within `/data` in the Docker container, which is mounted from the output of `getLocalTempDir()`, so I don't see how that could be leaking anything. Does `importFile()` somehow leave behind temp files?

**Comment by adamnovak** [comment]
I don't think that it should, although I've only ever used it on the
leader and never actually thought to use it in a job.

That Docker image must be getting downloaded somewhere, and I don't
think Toil will delete it automatically, so that will take up some
space (though 8 GB is a lot for a Docker container). Also, if you were
to enable Toil's caching, that could leave files behind, but it is off
by default.

You could run a "find /" in your job to see what's on the machine,
maybe. Or I think if you add a -D8080 to your ssh-cluster command and
use localhost:8080 as a SOCKS proxy, you can get to the Mesos agent
web UIs through the Mesos web UI, and maybe from there see what files
are on the machine.

**Comment by arostamianfar** [comment]
Just to add my 2cents: Mesos disagreeing about disk/memory with autoscaler is a known issue. I spent some time trying to fix it, but it gets tricky as autoscaler doesn't know how much disk/memory will actually remain after provisioning before launching the instance. In fact, we currently [underestimate memory](https://github.com/DataBiosphere/toil/blob/bf5eeef8832e40a57a5dff1eeeeaff4151016ec7/src/toil/provisioners/aws/awsProvisioner.py#L196) to work around this issue, but I've found that the actual memory is even less (by as much as 20% in some cases). We could probably do the same for disk, but disk is relatively cheap and easily configurable, so one can always overprovision.

I think at least one short term workaround to prevent pipelines from getting stuck is to change [this logic](https://github.com/DataBiosphere/toil/blob/bf5eeef8832e40a57a5dff1eeeeaff4151016ec7/src/toil/batchSystems/mesos/batchSystem.py#L498) to fail the pipeline if no job is running and nothing has been scheduled in some time (e.g. 30mins-1hr should be more than enough to allow for instances to get provisioned).

**Comment by TMiguelT** [comment]
Okay I finally got to look into this.

I had a look at the disk usage before and after a job completed.

Before:
```bash
$ sudo du -sh /mnt/ephemeral/var/lib/*
8.0K	cwl
6.7G	docker
496K	mesos
70G	toil

$ docker ps
CONTAINER ID        IMAGE                                                                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
bddc20256f5d        biocontainers/fastqc:0.11.5                                             "fastqc /data/read.b…"   18 minutes ago      Up 18 minutes                                FastQC--ZVHqI3Jfe3p
869459114f25        quay.io/ucsc_cgl/toil:3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6   "mesos-slave --log_d…"   3 hours ago         Up 3 hours                                   toil_worker
5f546ab4480c        prom/node-exporter:v0.15.2                                              "/bin/node_exporter …"   3 hours ago         Up 3 hours          0.0.0.0:9100->9100/tcp   node-exporter
```

Then, once it finishes:
```
$ sudo du -sh /mnt/ephemeral/var/lib/*
8.0K	cwl
9.0G	docker
580K	mesos
2.1M	toil

$ docker ps
CONTAINER ID        IMAGE                                                                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
869459114f25        quay.io/ucsc_cgl/toil:3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6   "mesos-slave --log_d…"   4 hours ago         Up 4 hours                                   toil_worker
5f546ab4480c        prom/node-exporter:v0.15.2                                              "/bin/node_exporter …"   4 hours ago         Up 4 hours          0.0.0.0:9100->9100/tcp   node-exporter
```

So it looks like toil is basically cleaning up all its files, which is great. What it's not doing, as suggested above, is cleaning up docker *images*. Even when nothing is running on my node, I get:
```bash
$ docker images
REPOSITORY              TAG                                               IMAGE ID            CREATED             SIZE
ewels/multiqc           dev                                               03c3eff98648        11 days ago         237MB
ewels/multiqc           1.7                                               e59e7a63498b        4 months ago        169MB
ewels/multiqc           latest                                            e59e7a63498b        4 months ago        169MB
quay.io/ucsc_cgl/toil   3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6   34ab730a0ee7        5 months ago        1.83GB
ewels/multiqc           v1.7                                              499fdd67db1d        8 months ago        505MB
ewels/multiqc           v1.6                                              d9b834ed653b        13 months ago       498MB
biocontainers/fastqc    0.11.5                                            35a358eb52f5        17 months ago       1.1GB
ewels/multiqc           v1.5                                              f77b368855e3        17 months ago       493MB
ewels/multiqc           v1.4                                              68ddd73a5676        19 months ago       517MB
prom/node-exporter      v0.15.2                                           ff5ecdcfc4a2        21 months ago       22.8MB
ewels/multiqc           v1.3                                              b4f3ec37bcbc        22 months ago       514MB
```
So that's at least 2.7 GB being wasted. My feeling is that toil's `apiDockerCall` should have an option to clean up the *image* (not just the container) on exit, because that's generally what you want it to do. This could even be the default, because tasks that run multiple docker containers are probably going to be rare.

**Comment by arostamianfar** [comment]
I personally don't think deleting docker images is a good idea:
* Docker image reuse is pretty common (e.g. GATK has a single docker image with many tasks that run sequentially/concurrently in a worker).
* Deleting a docker image can get complex (e.g. one needs to ensure no other concurrent task on a worker is using that image).
* Disk is cheap, so I don't think it's worth adding complexity in favor of optimizing a few GBs (it costs [~$0.14/TB/hour](https://aws.amazon.com/ebs/pricing/) on AWS).

However, I think the original issue (preventing pipelines from getting stuck) is definitely worth resolving, even if it's at a cost of over-provisioning resources (disk and memory).

**Comment by adamnovak** [comment]
I'm going to close this in favor of #4135.

**Comment by adamnovak** [comment]
I don't

**Comment by adamnovak** [comment]
I don't think the right way to deal with this is really to delete the images, because we don't want to redownload the Docker images for every job, but I'm not quite sure what the right way to handle this actually is.

In practice, you probably want to size your node disks large enough to hold all the Docker images you will use in your workflow, and then set your job disk requirements so that they don't include disk used for Docker images, which Toil doesn't really account as having been used by the job.

In theory, we'd want some way to see what Docker images a job is going to use, and what Docker images are already available on a node that could run a job, and use that information at scheduling time. Jobs should preferentially go to the nodes that already have their images, and should require more disk when running on nodes that don't already have the images than when running on nodes that do. But we can't actually get the set of images that might be used, in advance, nor can Mesos tell us what images are already there.
