### ISSUE TITLE
List completed and running jobs

### ISSUE THREAD

**Issue by multimeric** [DataBiosphere/toil#2754]
Currently none of the toil CLI commands simply tells you what jobs are currently running, and which have already completed. This seems like basic functionality, but I swear I can't find it anywhere.

`toil status` returns:
```
Of the 9 jobs considered, there are 7 jobs with children, 2 jobs ready to run, 0 zombie jobs, 0 jobs with services, 0 services, and 0 jobs with log files currently in <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7fa3f1dca6d0>
```

This doesn't really tell me anything helpful. There are 9 jobs, but which ones have completed? Are there any currently running? If they're currently running are they considered "ready to run"?

I still can't get this information using `--printPerJobStatus`:
```
INFO:toil.utils.toilStatus:Traversing the job graph gathering jobs. This may take a couple of minutes.
JOB:'ProcessSample' a6c6d4da-29fd-4379-9b87-82cfd8f00362        LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:FalseS_SERVICE:False
JOB:'DownloadS3File' 0e4041c9-9ef4-4443-8581-ce8819d21058       LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False  IS_SERVICE:False
JOB:'BamToFastq' f4857b47-ffac-4723-a0a8-afdd505a2d7b   LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
JOB:'FastQC' 539d235f-e17b-4dbd-9295-ad289c711b5e       LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
JOB:'MultiQc' 15b5800f-6219-42bb-8f57-7c9590ba6797      LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
JOB:'FastQC' 4d302c7f-37a4-4281-a0a4-ff106b1318e7       LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
JOB:'MultiQc' 24655f63-0ed1-44b2-ad63-447b3d147924      LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
JOB:'DownloadS3File' d5261943-9b3d-42ea-a176-3d38428bf115       LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False  IS_SERVICE:False
JOB:'BamToFastq' 980f2860-6cda-4d8a-8cbc-d3b7ffb42525   LOG_FILE:None   TRYS_REMAINING:1        CHILD_NUMBER:2  READY_TO_RUN:True       IS_ZOMBIE:False HAS_SERVICES:False      IS_SERVICE:False
Of the 9 jobs considered, there are 7 jobs with children, 2 jobs ready to run, 0 zombie jobs, 0 jobs with services, 0 services, and 0 jobs with log files currently in <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7ff09746e6d0>.
```
Again, this doesn't tell me which of these jobs have started or finished or are currently running.

I feel like I'm going insane. Surely it's possible to find this information somewhere?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-402)
┆Issue Number: TOIL-402

**Comment by TMiguelT** [comment]
The mesos dashboard (https://toil.readthedocs.io/en/latest/running/cloud/amazon.html#dashboard) certainly is useful, and it mostly solves this issue for AWS execution, but this isn't a general solution for any backend. Also there would ideally be a solution that doesn't require a GUI.

**Comment by adamnovak** [comment]
The job store doesn't currently track whether jobs are running, AFAIK.
That state stays in memory in the leader, and when we restart a
workflow we don't have any support for re-using old job invocations.
(In fact, I think it is important to clear them out before restarting
a workflow or they can modify the job store unexpectedly and finish
when they weren't supposed to have been running.)

Finished jobs are supposed to record their finished-ness by cleaning
themselves up, so by default only the jobs that are ready to run and
the jobs that are waiting for something should be in the job store.

It would be nice to have something that can talk to the Toil leader
and get a status report like what you describe, though. Maybe it could
somehow pull from the same data that goes into the Grafana dashboard.

**Comment by TMiguelT** [comment]
Hmm, well even if you made a decision not to store this status in the job store, I think being able to ask the leader node for job status would be okay.

**Comment by adamnovak** [comment]
I think `toil status --status` will do this now, if you are using a file job store or are on the same machine as the leader. It looks at the message bus log and prints out the current state of all the jobs.

I'm going to close this out, but we could still probably improve the UI and docs here.
