### ISSUE TITLE
WDL basename with suffix string is not supported

### ISSUE THREAD

**Issue by adthrasher** [DataBiosphere/toil#2757]
In my WDL workflows, I have several places where I use WDL's basename function with a suffix string to get a prefix for output file names. Similar to the following. 

`String basename = basename(bam, ".bam")`

When using Toil as the runner, this gets converted to using Python's built-in basename function from os.path. 

`self.id_basename = (basename(bam, '.bam'))`

However, Python's implementation of basename does not support suffix strings. This leads to the rather opaque error

```    
self.id_basename = (basename(bam, '.bam'))
TypeError: 'str' object is not callable
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-404)
┆Issue Number: TOIL-404

**Comment by DailyDreaming** [comment]
@adthrasher Sorry about that, not all of the WDL functions are complete.

Should be fixed by: https://github.com/DataBiosphere/toil/pull/2758

**Comment by adthrasher** [comment]
Thanks for the quick fix. I look forward to trying it out.

**Comment by adthrasher** [comment]
Unfortunately, it looks like there are still some issues with this. In my testing, I've run into two cases where `strip()` is invalid, because the input object is of type `tuple` or type `Promise`. 

I've attached WDL workflows which demonstrate both cases. 

`toil-wdl-runner test2.wdl test_input.json` produces the `tuple` case.

`toil-wdl-runner test.wdl test_input.json` produces the `Promise` case.

[test_wdl.zip](https://github.com/DataBiosphere/toil/files/3487415/test_wdl.zip)
