### ISSUE TITLE
WDL basename function

### ISSUE THREAD

**Issue by adthrasher** [DataBiosphere/toil#2759]
Thanks for the quick response to #2757. Unfortunately, it looks like there are some issues with the solution. In my testing, I've run into two cases where strip() is invalid, because the input object ("path") is of type tuple or type Promise, rather than string.

I've attached WDL workflows which demonstrate both cases.

toil-wdl-runner test2.wdl test_input.json produces the tuple case.

toil-wdl-runner test.wdl test_input.json produces the Promise case.

[test_wdl.zip](https://github.com/DataBiosphere/toil/files/3493256/test_wdl.zip)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-405)
┆epic: WDL Standard Library Implementation
┆friendlyId: TOIL-405

**Comment by DailyDreaming** [comment]
@adthrasher Thanks for posting this!  Will fix and use your examples as unit tests.
