### ISSUE TITLE
assertion error: #Check alignment is of right length with respect to the query

### ISSUE THREAD

**Issue by lac2208** [DataBiosphere/toil#2761]
Hello,

I'm running cactus locally on a PBS cluster on 40 cores. I'm not running in parallel because after many attempts with other datasets, I found that the following command worked best: cactus cactus-job seqfile genomeAlign.hal --binariesMode local --maxCores 40 --workDir pso-zchrom --restart.

I've run it successfully twice on other datasets. Now, after cactus runs for about 12hs it crashes with the error below. I think it might be due to sequence quality, but I'm not sure what the specific problem could be.

> Job 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z with ID W/z/jobWVrC4z is completely failed
> 2019-08-13 13:08:43,432 - toil.leader - WARNING - Job 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z with ID W/z/jobWVrC4z is completely failed
> No jobs left to run so exiting.
> 2019-08-13 13:08:57,474 - toil.leader - INFO - No jobs left to run so exiting.
> Finished the main loop
> 2019-08-13 13:08:57,475 - toil.leader - INFO - Finished the main loop
> Waiting for service manager thread to finish ...
> 2019-08-13 13:08:57,475 - toil.serviceManager - INFO - Waiting for service manager thread to finish ...
> ... finished shutting down the service manager. Took 0.727831125259 seconds
> 2019-08-13 13:08:58,203 - toil.serviceManager - INFO - ... finished shutting down the service manager. Took 0.727831125259 seconds
> Waiting for stats and logging collator thread to finish ...
> 2019-08-13 13:08:58,205 - toil.statsAndLogging - INFO - Waiting for stats and logging collator thread to finish ...
> ... finished collating stats and logs. Took 0.86012005806 seconds
> 2019-08-13 13:08:59,065 - toil.statsAndLogging - INFO - ... finished collating stats and logs. Took 0.86012005806 seconds
> Finished toil run with 7 failed jobs
> 2019-08-13 13:08:59,070 - toil.leader - INFO - Finished toil run with 7 failed jobs
> Failed jobs at end of the run: 'RunCactusPreprocessorThenProgressiveDown2' S/U/jobj0VtJN 'BlastFirstOutgroup' I/l/jobCkyc7E 'CactusTrimmingBlastPhase' 5/w/jobOYxLe3 'BlastIngroupsAnd
> Outgroups' L/e/jobVpEqZt 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z 'EncapsulatedJob' R/D/jobXaINpe 'RunCactusPreprocessorThenProgressiveDown' v/T/jobdBxO3S
> 2019-08-13 13:08:59,071 - toil.leader - INFO - Failed jobs at end of the run: 'RunCactusPreprocessorThenProgressiveDown2' S/U/jobj0VtJN 'BlastFirstOutgroup' I/l/jobCkyc7E 'CactusTrim
> mingBlastPhase' 5/w/jobOYxLe3 'BlastIngroupsAndOutgroups' L/e/jobVpEqZt 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z 'EncapsulatedJob' R/D/jobXaINpe 'RunCactusPreprocessorThenProgressiv
> eDown' v/T/jobdBxO3S
> Traceback (most recent call last):
> File "/home/lcoelho/array1/miniconda2/bin/cactus", line 11, in 
> load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 477, in main
> halID = toil.restart()
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/common.py", line 773, in restart
> return self._runMainLoop(rootJobGraph)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/common.py", line 1018, in _runMainLoop
> jobCache=self._jobCache).run()
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/leader.py", line 226, in run
> raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
> toil.leader.FailedJobsException: The job store 'file:/nas1/lcoelho/pso-zchrom/cactus-job' contains 7 failed jobs: 'RunCactusPreprocessorThenProgressiveDown2' S/U/jobj0VtJN, 'BlastFirstOutgroup' I/l/jobCkyc7E, 'CactusTrimmingBlastPhase' 5/w/jobOYxLe3, 'BlastIngroupsAndOutgroups' L/e/jobVpEqZt, 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z, 'EncapsulatedJob' R/D/jobXaINpe, 'RunCactusPreprocessorThenProgressiveDown' v/T/jobdBxO3S
> =========> Failed job 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z
> INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
> INFO:toil:Running Toil version 3.14.0-b91dbf9bf6116879952f0a70f9a2fbbcae7e51b6.
> WARNING:toil.resource:'JTRES_3f16598175194404dc255f8ff30578ce' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
> INFO:toil.lib.bioio:Calculating coverage of cigar file /home/lcoelho/nas1/pso-zchrom/toil-a882c66a-80e3-4fbc-b198-f49cb5eca110-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmp63qQwx/babbcba8-4c81-4eae-9c3d-1f45db5aaa57/tmpQJd0Et.tmp on /home/lcoelho/nas1/pso-zchrom/toil-a882c66a-80e3-4fbc-b198-f49cb5eca110-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmp63qQwx/babbcba8-4c81-4eae-9c3d-1f45db5aaa57/tmphssV75.tmp, writing to /home/lcoelho/nas1/pso-zchrom/toil-a882c66a-80e3-4fbc-b198-f49cb5eca110-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmp63qQwx/babbcba8-4c81-4eae-9c3d-1f45db5aaa57/tmpLQ6TbZ.tmp
> INFO:cactus.shared.common:Running the command ['cactus_coverage', u'/home/lcoelho/nas1/pso-zchrom/toil-a882c66a-80e3-4fbc-b198-f49cb5eca110-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmp63qQwx/babbcba8-4c81-4eae-9c3d-1f45db5aaa57/tmphssV75.tmp', u'/home/lcoelho/nas1/pso-zchrom/toil-a882c66a-80e3-4fbc-b198-f49cb5eca110-901745c3-81f2-471d-91a5-515b0cd7d7fd/tmp63qQwx/babbcba8-4c81-4eae-9c3d-1f45db5aaa57/tmpQJd0Et.tmp']
> Traceback (most recent call last):
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/worker.py", line 309, in workerScript
> job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/shared/common.py", line 1096, in _runner
> super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/job.py", line 1328, in _runner
> returnValues = self._run(jobGraph, fileStore)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/toil/job.py", line 1273, in _run
> return self.run(fileStore)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/blast/blast.py", line 291, in run
> outputFile=f)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/cactus/blast/upconvertCoordinates.py", line 76, in upconvertCoords
> for alignment in cigarRead(sortedCigarFile):
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/sonLib/bioio.py", line 1195, in cigarRead
> pA = cigarReadFromString(line)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/sonLib/bioio.py", line 1182, in cigarReadFromString
> return PairwiseAlignment(m[4], start2, end2, strand2, m[0], start1, end1, strand1, float(m[8]), ops)
> File "/home/lcoelho/array1/miniconda2/lib/python2.7/site-packages/sonLib/bioio.py", line 1119, in init
> assert i == abs(end1 - start1) #Check alignment is of right length with respect to the query
> AssertionError
> ERROR:toil.worker:Exiting the worker because of a failed job on host amnh-gen-001.internal.amnh.org
> WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'TrimAndRecurseOnOutgroups' W/z/jobWVrC4z with ID W/z/jobWVrC4z to 1

Do you have any idea of what the problem could be?
Thank you!

Laís

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-407)
┆Issue Number: TOIL-407

**Comment by adamnovak** [comment]
I don't think this is likely to be Toil's fault, if you are running this on a single machine after being deployed by PBS. I suspect this is a Cactus bug.

I'm going to close this in favor of https://github.com/ComparativeGenomicsToolkit/cactus/issues/88 which I think is the right place for this to be looked into.

**Comment by lac2208** [comment]
Noted. Thank you, Adam.
