### ISSUE TITLE
awscli on worker nodes can’t find credentials

### ISSUE THREAD

**Issue by edraizen** [DataBiosphere/toil#2775]
I’ve been using the IOStore module for a while. It’s great, except it relies on boto3 for downloading files, so I cannot download files in batch. The fastest way I've found is to use the awscli driver instead of boto.  However, it always fails on the worker nodes since it can’t find the credentials file. 

Using IOStore:
```python
store = IOStore.get("aws:us-east-1:bucket")
for key in store.list_input_directory(prefix):
    store.read_input_file(key, os.path.basename(key))
```

Using awscli:
```python
import awscli.clidriver
driver = awscli.clidriver.create_clidriver()
rc = driver.main(args=["s3", "sync", "s3://bucket/prefix", "."])
```
which errors with:
```
UnknownCredentialError: Credential named assume-role-with-web-identity not found.
DEBUG:awscli.clidriver:Exiting with rc 255
```

Is there a way to make sure the ~/.aws/credentials files is copied to all new workers?

Thanks,
Eli

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-412)
┆Issue Number: TOIL-412

**Comment by adamnovak** [comment]
I don't think that Toil has native support for copying files to workers. What it can do is distribute environment variables, so if awscli can take its credentials from  the environment, you can configure the environment on the leader and have it propagate out to the workers automatically.

The best way to do this, if your workflow is itself running on a Toil-managed AWS-based cluster, is to create an IAM role that has access to S3, and to make Toil use it with the `--awsEc2ProfileArn` flag that was added in https://github.com/DataBiosphere/toil/pull/2656. Your role will also need access to the other AWS services that Toil uses, so it also needs the permissions described at https://github.com/DataBiosphere/toil/blob/master/docs/appendices/aws_min_permissions.rst#minimum-aws-iam-permissions. If you do this, awscli will notice that the machine it is running on has access via a role, and won't bother with `~/.aws/credentials`.

The other thing you could do, if you aren't using a Toil-managed AWS cluster, is have some Python code in your workflow, at the top of every function that wants to use awscli, which sets up the credentials if they aren't available. If you use the class-based method for defining Toil jobs, you could create a base class that does this setup (maybe by copying the credentials from the environment to the file) and have your jobs inherit from it. If you use the function-based API, I think you could do this in an annotation.

We could also try and devise a batch version of the IOStore API.

**Comment by edraizen** [comment]
Thanks for your replay! I was able to get it by running: `TOIL_CUSTOM_DOCKER_INIT_COMMAND='pip install awscli && eval $(aws ecr get-login --no-include-email --region us-east-1)'` from #2561
