### ISSUE TITLE
Add an option to log output from all jobs without --logDebug

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2779]
It's often useful to see the logs from all jobs for debugging. Currently, the only way to turn this on is through `--logDebug`, which enables all kinds of other debug logging and is too noisy.

We can add a new option, `--writeLogsFromAllJobs`, to enable logging from all jobs without enabling debug mode.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-413)
┆Issue Number: TOIL-413

**Comment by mr-c** [comment]
Yes, please and thank you!
