### ISSUE TITLE
Update psutil version

### ISSUE THREAD

**Issue by jvivian-atreca** [DataBiosphere/toil#2780]
`psutil` is pinned to version 3.0.1, which causes dependency conflicts with other packages like `dask`, which requires version >=5.0. All `psutil` calls are in **src/toil/batchSystems/mesos/executor.py** and I confirmed that on the latest version (5.6.3), every `psutil` call works the same:

```
In [1]: import psutil

In [2]: psutil.cpu_percent()
Out[2]: 8.9

In [3]: psutil.cpu_count()
Out[3]: 8

In [4]: psutil.virtual_memory()
Out[4]: svmem(total=17179869184, available=5836066816, percent=66.0, used=9086025728, free=72404992, active=5766565888, inactive=5725958144, wired=3319459840)

In [5]: psutil.__version__
Out[5]: '5.6.3'
```

Happy to file a PR if that's helpful.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-414)
┆Issue Number: TOIL-414

**Comment by mr-c** [comment]
Maybe change it to `psutil >= 3.0.1, <6` ?

**Comment by DailyDreaming** [comment]
@jvivian-atreca Definitely okay to submit a PR!  For requirement bumps, I would even maybe forgo the issue and just go straight to making the PR.  We'll know pretty quickly if there are any conflicts once the tests come back.

In the meantime, I've made a PR here.  Once tests pass, I'll merge.

**Comment by adamnovak** [comment]
But if we ignore the issue, what should we name the PR's testing
branch? I guess just after itself, since we'd be importing an external
PR from outside the repo?
