### ISSUE TITLE
Tar file created in the job store, but disappearing after execution completes

### ISSUE THREAD

**Issue by TMiguelT** [DataBiosphere/toil#2794]
I have a very strange issue, whereby I have two files created in the same task, both are created and assigned a file ID, but one of them never appears in the final S3 bucket:

`ba9ff2e...` is the file that disappears:
```
DEBUG:toil.statsAndLogging:'FastQC' 30800183-2b82-4c9f-89b9-20ad594b269a    DEBUG:toil.jobStores.aws.jobStore:Wrote FileInfo(fileID='ba9ff2e...1bcc21fa', ownerID=None, encrypted=Fal
se, version='', previousVersion='', content='././@LongLink\x0...0\x00\x00\x00\x00', _numContentChunks=10) bound to <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7fe8231f89d0>
 of from '/var/lib/toil/toil-9fcb9e0a-8b3e-41c3-8c72-8f2439d6e11f-69d14ae953f0400cbe6f0dc87a7486c9/tmpG53hHO/a337ba6d-2b5b-4726-b836-29be4f364dae/tMcXOAD/tmpzuLteu.tar'
```
`fce14c6`, however, is still there at the end of the execution:
```
DEBUG:toil.jobStores.aws.jobStore:Wrote FileInfo(fileID='fce14c6...d8379806', ownerID=None, encrypted=Fal
se, version='mE5kl0O1oVv6x4qzaEz28Fhs4xizOZas', previousVersion='mE5kl0O1oVv6x4qzaEz28Fhs4xizOZas', content=None, _numContentChunks=0) bound to <toil.jobStores.aws.jobStore.AWSJobSt
ore object at 0x7fe8231f89d0> of from '/var/lib/toil/toil-9fcb9e0a-8b3e-41c3-8c72-8f2439d6e11f-69d14ae953f0400cbe6f0dc87a7486c9/tmpG53hHO/a337ba6d-2b5b-4726-b836-29be4f364dae/tMcXOA
D/multiqc_report.html'
DEBUG:toil.statsAndLogging:'FastQC' 30800183-2b82-4c9f-89b9
```

My internal logging shows that `ba9ff2e` exists, and has valid contents, and this file ID travels throughout the pipeline, until I get my final output:
```
        "mapped": {
            "phase1/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20101123.bam": {
                "report": "fce14c67-1f4d-4f34-80cb-cdf0d8379806", 
                "data": "ba9ff2e4-6148-476d-b62e-8ef01bcc21fa"
            }
        }
 ```

However, it simply isn't in the final S3 bucket, unlike `fce14c6`!

```
$ aws s3 ls s3://aws-toil-17--files/fce14c67-1f4d-4f34-80cb-cdf0d8379806 
2019-09-08 18:24:53    1131835 fce14c67-1f4d-4f34-80cb-cdf0d8379806
 /tmp/tmp.p1UZCbqHey
$ aws s3 ls s3://aws-toil-17--files/ba9ff2e4-6148-476d-b62e-8ef01bcc21fa
```

Both of these files are uploaded using:
```
self.file_store.writeGlobalFile(name)
```

Any idea how or why this might be happening?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-419)
┆Issue Number: TOIL-419

**Comment by TMiguelT** [comment]
I note that `version` and `previousVersion` are both empty for the file that gets deleted. Could this be

**Comment by TMiguelT** [comment]
Possibly this is caused by the files being inlined? I'm not exactly sure what that means in the context of Toil, but it seems that they don't actually get uploaded to S3 when they are small enough to be inlined? This seems like an issue though.

**Comment by adamnovak** [comment]
The Right Way to get the output files from your workflow out of the FileStore is to use `exportFile`, either [on the Toil context manager in your main script](https://toil.readthedocs.io/en/releases-3.19.0/developingWorkflows/toilAPI.html?highlight=export#toil.common.Toil.exportFile), or directly on the FileStore in a job. See for example this [example code in the documentation](https://toil.readthedocs.io/en/releases-3.19.0/gettingStarted/quickStart.html?highlight=exportfile#describing-the-source-code):

```
    with Toil(options) as workflow:
        sortedFileURL = 'file://' + os.path.abspath(sortedFileName)
        if not workflow.options.restart:
            sortFileURL = 'file://' + os.path.abspath(fileName)
            sortFileID = workflow.importFile(sortFileURL)
            sortedFileID = workflow.start(Job.wrapJobFn(setup, sortFileID, int(options.N), options.downCheckpoints, options=options,
                                                    memory=sortMemory))
        else:
            sortedFileID = workflow.restart()
        workflow.exportFile(sortedFileID, sortedFileURL)
```

The only guarantee that having a FileID gives you is that you can read the file through the FileStore using that FileID. It doesn't guarantee that the file will be visible in the S3 bucket (which backs the JobStore, which in turn backs the FileStore) under a predictable file name or at all. Moreover, when the Toil workflow finishes successfully, the default behavior is to delete the job store and all the files that live in it, so even if the files you wanted were always accessible in S3, they wouldn't remain so. That S3 bucket is scratch space, not the "final" output of your workflow.

I think you might be right about the files that you don't see in S3 having been inlined. If files are sufficiently small, we store their content directly in the SimpleDB database that we use to guarantee a consistent view of the files and jobs that exist. Only big files actually get an entry in S3 for their contents. However, I think trying to get the AWS JobStore to stop inlining things is barking up the wrong tree; if you want to get at these files without having a Toil FileStore and retrieving them by file ID, you need to export them from the workflow.

**Comment by TMiguelT** [comment]
Ah, thank you! I didn't know about the export function. I think this answers all my questions!
