### ISSUE TITLE
WDL: Non-file outputs

### ISSUE THREAD

**Issue by davidlougheed** [DataBiosphere/toil#2799]
As far as I can tell, there's no way to convince `toil-wdl-runner` to output non-File outputs from tasks as JSON or some other format. [Cromwell](https://cromwell.readthedocs.io/en/stable/tutorials/FiveMinuteIntro/) outputs JSON in a similar format as WDL input.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-422)
┆epic: Moving WDL Support to Beta
┆friendlyId: TOIL-422

**Comment by DailyDreaming** [comment]
@davidlougheed That's correct and a feature we should probably add eventually.  Right now our priorities are refactoring tests, and implementing kubernetes support, but we should eventually come around to making improvements to the WDL implementation.

**Comment by adamnovak** [comment]
I think this will just go away when we change to leveraging MiniWDL code to make Toil's WDL front-end go.
