### ISSUE TITLE
Toil tries to move directories by copy instead of through the FileStore in CWL conformance tests

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2801]
As discovered in #2770, this CWL conformance test will pass with job chaining enabled on Toil master:

```
wget https://github.com/common-workflow-language/common-workflow-language/archive/a062055fddcc7d7d9dbc53d28288e3ccb9a800d8.zip
unzip a062055fddcc7d7d9dbc53d28288e3ccb9a800d8.zip
mv common-workflow-language-a062055fddcc7d7d9dbc53d28288e3ccb9a800d8/ test/
toil-cwl-runner --disableCaching=True --jobStore ./chain --logDebug --realTimeLogging --outdir=/tmp/tmpb5MyuT2 test/v1.0/v1.0/iwdr_with_nested_dirs.cwl test/v1.0/v1.0/empty.json
```

But it will fail when chaining is disabled:

```
toil-cwl-runner --disableCaching=True --disableChaining --jobStore ./nochain --logDebug --realTimeLogging --outdir=/tmp/tmpb5MyuT2 test/v1.0/v1.0/iwdr_with_nested_dirs.cwl test/v1.0/v1.0/empty.json
```

It is failing because, when setting up the second job cwltool ends up trying to recursively copy a directory form the first job's local temp directory. With chaining on this directory happens to still exist, but with chaining off it will have already been cleaned up. In general, two jobs might run on completely different machines, so cwltool needs to be shipping the directory tree around via Toil's FileStore.

The exceptions look like this:

```
Traceback (most recent call last):
  File "/Users/anovak/Documents/Workspace/toil/venv35/lib/python3.5/site-packages/cwltool/executors.py", line 182, in run_jobs
    job.run(runtime_context)
  File "/Users/anovak/Documents/Workspace/toil/venv35/lib/python3.5/site-packages/cwltool/job.py", line 445, in run
    symlink=True, secret_store=runtimeContext.secret_store)
  File "/Users/anovak/Documents/Workspace/toil/venv35/lib/python3.5/site-packages/cwltool/process.py", line 253, in stage_files
    shutil.copytree(entry.resolved, entry.target)
  File "/Users/anovak/Documents/Workspace/toil/venv35/lib/python3.5/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/toil-dfba1124-76bd-45d9-ada7-12e2e8d2020f-106618767760070/tmp5tgq0qpe/3f3d9b8e-b1cd-4ff7-ac5a-2dd0a8c05afc/tcc4hil93/tmp-outnngwbct7/deeply'
```

@mr-c Is there something you can do about this in cwltool? Or is there something wrong in cwltoil that is causing cwltool to try and do these local copies when it needs to be shipping around tarballs or rebuilding the directory structure instead?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-424)
┆Issue Number: TOIL-424

**Comment by mr-c** [comment]
@adamnovak Good find!

> Is it Toil or cwltool who is supposed to be responsible for packing up Directory-type outputs and their files for transport?

Toil (or `cwltoil.py` in this case) is responsible for transportation of data, `Directory` or otherwise.  `cwltool` doesn't move data around except by soft link or the occasional copy when a writable input is needed.

**Comment by adamnovak** [comment]
I'm going to see if I can make progress on this today.

**Comment by adamnovak** [comment]
I think the problem is maybe that there aren't actually any files, and we don't seem to upload directories.

Here's the upload code:

https://github.com/DataBiosphere/toil/blob/1ae5547fe93c73f68e3eb7f5d3dd05aeceb413ab/src/toil/cwl/cwltoil.py#L939-L946

The relevant functions we're calling are here: https://github.com/common-workflow-language/cwltool/blob/445f6b3a214f0c48317b25f7af278ae919ce5403/cwltool/pathmapper.py#L56-L66

We visit and upload all the files, but we visit the directories and run the [undocumented `get_listing()`](https://github.com/common-workflow-language/cwltool/blob/445f6b3a214f0c48317b25f7af278ae919ce5403/cwltool/pathmapper.py#L154), which looks to just scan the directories for their contents. We never actually do anything for directories themselves, independent of their contained files.
