### ISSUE TITLE
Question about toil - aws - cwl interfacing

### ISSUE THREAD

**Issue by drkennetz** [DataBiosphere/toil#2805]
I am currently in the process of learning how to directly interact with aws EC2 instances with toil. I have started with the documentation [here](https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#awscwl), but am still working my way through figuring some of it out.
Currently, I am provisioning my instances with software using a 3rd party infrastructure as code resource (terraform). I was wondering if toil can interact with instances that it has not instantiated as long as I have the cluster name? Through scripting, is it possible for me to ssh into a cluster that I have already provisioned and use toil as a workflow runner on that cluster?

Thanks,
Dennis

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-428)
┆Issue Number: TOIL-428

**Comment by DailyDreaming** [comment]
Terraform is great and if you have it set up a kubernetes cluster we will have support soon: https://github.com/DataBiosphere/toil/pull/2786

With a straight EC2 instance, I'd have to know how your cluster was set up, but I suspect you'd need to write a custom provisioner.  Our native AWS provisioner sets up a coreOS EC2 instance with a docker image of the toil runtime environment so ssh-ing it assumes the EC2 instance user name is `core` and that the docker image is running prior to sshing directly into the docker image.

Any of the local clusters (GridEngine, Slurm, HTCondor, etc.) that toil knows how to talk to can be run via a virtual docker image setup as far as I know, which might also be a proxy, but I wouldn't recommend that route unless that's what you're already doing.

**Comment by adamnovak** [comment]
Toil can run work on instances that you set up yourself, but only if
you also set up an actual scheduler on top of those instances (e.g.
Mesos or Slurm) and install Toil on them. Have a look at the
--batchSystem mesos and the --mesosMaster options to Toil, for
example. Toil doesn't have a built in way to launch jobs by just
ssh-ing into a pool of deployed machines.

You might be able to work out how to install the right version of the
Mesos agent and point it at Toil's deployed Mesos master (from toil
launch-cluster) yourself, but at that point you might be better off
just managing the Mesos master yourself too, or deploying a more
popular cluster schedule that Toil also supports.

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if this is still an issue.
