### ISSUE TITLE
CWL scatter outputs overwrite each other in Toil's outdir

### ISSUE THREAD

**Issue by dicknetherlands** [DataBiosphere/toil#2819]
When using Toil to execute any CWL workflow that includes a scattered subworkflow, Toil's outdir contains only the output files of the final iteration of the subworkflow. Output files from previous iterations should also be included (perhaps by creating subfolders, one per scattered iteration, to contain the outputs specific to that iteration?).

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-436)
┆Issue Number: TOIL-436

**Comment by dicknetherlands** [comment]
To clarify a little: the outputs are overwritten only if they have identical names. So if the subworkflow produces an output file called 'myfile.txt' then only the final version of 'myfile.txt' is seen in outdir. But if the subworkflow produces an output file with a name uniquely derived from its input, e.g. 'outfile-number-3.txt' for 'input-number-3.txt', then all are retained. The behaviour really should be to retain all outputs from all subworkflow iterations even if they have name clashes.

**Comment by dicknetherlands** [comment]
Version : toil[cwl]==3.19.0

**Comment by adamnovak** [comment]
How does cwltool handle this @mr-c ?

@dicknetherlands Do you have a CWL runner that doesn't exhibit this clobbering behavior, which you want Toil to work like?

It looks like [the spec](https://www.commonwl.org/v1.0/Workflow.html#Execution_concepts) gives pretty broad leeway for "transforming file paths", but I don't know if we want to do something that other tools don't and that workflow authors won't expect.

To me the least surprising thing to happen if you write two files with the same name is for the second to clobber the first.

**Comment by dicknetherlands** [comment]
I have not used other CWL tools so couldn’t really say if this is unique to Toil or if it is a more general situation.

While I agree that in general if a workflow writes two files of the same name then one would logically be expected to clobber the other, the scattering use-case is interesting because you may well want to record the outputs of each scattered execution.

Although one further thought is that input filenames are always unique to each scattered execution so perhaps there is simply a way to use them to generate unique output names too. In which case problem solved.

Not sure which is theoretically neater though.

**Comment by dicknetherlands** [comment]
Renaming all files using the technique described in https://www.biostars.org/p/343413/ has the desired effect. I think this is more of a CWL feature for sure, regarding better ways of renaming or gathering outputs, so you can probably close this Toil ticket.

**Comment by adamnovak** [comment]
OK, I'll go ahead and close this. If there's a movement for a new way to do things all across CWL-land, or if we work out that Toil is in disagreement with other tools, then we can re-open it.

**Comment by mr-c** [comment]
@adamnovak 
> How does cwltool handle this @mr-c ?

Historically we did worse than `toil-cwl-runner` which does adjust file names in other circumstances. A recent release of `cwltool` did improve some filenaming, perhaps it helps in this case?

https://github.com/common-workflow-language/cwltool/releases/tag/1.0.20191022103248
https://github.com/common-workflow-language/cwltool/pull/1138

I can open a PR to update the `cwltool` version used by `toil-cwl-runner` if you'd like.
