### ISSUE TITLE
Allow cleaning the S3 jobstore even if there are versioning inconsistencies 

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2825]
We currently check that the versioning of the s3 bucket is consistent when binding the bucket [here](https://github.com/DataBiosphere/toil/blob/3e950e4326ed55bd969eda15217aeab88a9d3d26/src/toil/jobStores/aws/jobStore.py#L744). However, this check can fail if the s3 bucket is in a 'strange' state (I've seen this occasionally happening where the s3 bucket has not been fully deleted; perhaps an internal API call failed?). When this happens, then it's not possible to clean the jobstore and one needs to manually delete the bucket outside of Toil.

I don't think this check is needed when cleaning the s3 jobstore as we're about to delete the bucket anyway.

Proposal is to add a flag to ignore this check only when cleaning the jobstore.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-439)
┆Issue Number: TOIL-439

**Comment by adamnovak** [comment]
Sounds like a good idea to me. I guess the alternative would be
skipping binding for cleaning and using some other codepath. Depending
on how far/from where you have to pull the flag to get it there, that
might be better, but setting out to implement a flag is probably the
way to start.

**Comment by arostamianfar** [comment]
That's also a good idea! Although, we've been testing the change with the flag in production for a while now (on our branch) and it has been very robust, so there was no need for other changes. 

Already sent the change for review :)
