### ISSUE TITLE
toil-cwl-runner on slurm fails to run jobs on multiple nodes

### ISSUE THREAD

**Issue by johnbradley** [DataBiosphere/toil#2855]
I have been trying to run a CWL workflow with toil and Slurm.
I do so by running an sbatch script containing `toil-cwl-runner`.
When the job runs entirely on one Slurm node it succeeds.
If slurm chooses to run `_toil_worker` on a different node than the node running `toil.leader` the `_toil_worker` job fails and the following is included in `toil-cwl-runner` output:
```
MainThread WARNING toil.leader: No log file is present, despite job failing...
```
If you look at the failed job with `sacct` the `State` is `FAILED` and `ExitCode` is `1:0`.
I have not been able to find any output logs on the nodes attempting to run `_toil_worker`.
I have been using toil from the master branch.

NOTE: If you specify `--workDir` with a path shared across all nodes this problem does not occur.

---

I added some logging and found that the `sbatch` command issued by `toil.leader` is attempting to write stderr and stdout to files within a directory in /tmp that does not exist on the node trying to run `_toil_worker`:

```
sbatch 
...
-o /tmp/toil-882d58aa-9bc5-4faa-abf5-4906fc65e8af-8c697123-fa43-4d9b-9948-405a15a8957d/toil_job_0_batch_slurm_%j_std_output.log
 -e /tmp/toil-882d58aa-9bc5-4faa-abf5-4906fc65e8af-8c697123-fa43-4d9b-9948-405a15a8957d/toil_job_0_batch_slurm_%j_std_error.log
--wrap=_toil_worker...
```
This `/tmp/toil-<uuid>/` directory does get created on the `toil.leader` node.

I think the following code specifies the file paths for the `-o` and `-e` arguments:
https://github.com/DataBiosphere/toil/blob/81a543d0e1a8e6c299f22bb8e862d34097e1f0bc/src/toil/batchSystems/slurm.py#L190-L191

[sbatch documentation](https://slurm.schedmd.com/sbatch.html)

## Reproducing
This requires a slurm cluster and toil installed from the master branch (to get another bug fix).
Identify two nodes you wish run `toil.leader` and `_toil_worker` on which I will refer to as `c1-leader` and `c1-worker` from now on.

Create a sbatch script `toil.sbatch` with the following contents:
```
#!/usr/bin/env bash

source env/bin/activate
export TOIL_SLURM_ARGS="-w c1-worker"

time toil-cwl-runner \
  --jobStore ${HOME}/jobstore \
  --batchSystem slurm \
  --outdir results \
  tar.cwl tar-job.yml 
```

Follow the steps from https://www.commonwl.org/user_guide/04-output/index.html
but instead of running 
```
cwl-runner tar.cwl tar-job.yml
```
run 
```
sbatch -w c1-leader toil.sbatch
```
This should run `toil-cwl-runner` on the `c1-leader` node and `_toil_worker` on the `c1-worker node`. You should see the job fails with `No log file is present, despite job failing.` in toil-cwl-runner's output.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-452)
┆Issue Number: TOIL-452

**Comment by mr-c** [comment]
Hello @johnbradley; thank you for your detailed issue.

Can you try setting `$TMPDIR` to a directory that is shared across your cluster?

**Comment by johnbradley** [comment]
> Can you try setting $TMPDIR to a directory that is shared across your cluster?

@mr-c I just tested and if I set `$TMPDIR` to a shared directory the problem does not occur. I think this is the equivalent of setting `--workDir` to a shared directory.

Previously I tried running a larger workflow on a slurm cluster with `workDir` set to a shared NFS directory and encountered issues where randomly `_toil_worker` got stuck in cleanup. `_toil_worker` kept trying to delete a `deferred/.../.nfs...` file (that it still had open). I switched to using the default `workDir`(/tmp on each node) to get around this problem.  This NFS problem may be related to https://github.com/DataBiosphere/toil/issues/2162

**Comment by dleehr** [comment]
@johnbradley I was digging into this today as we discussed. I found that it's working as designed/intended, including for slurm: The behavior is documented in [hpcEnvironments.rst](https://github.com/DataBiosphere/toil/blob/master/docs/running/hpcEnvironments.rst#standard-outputerror-from-batch-system-jobs).

> If capturing standard output and error is desired, `--workDir` will generally need to be on a shared file system; otherwise if these are written to local temporary directories on each node (e.g. `/tmp`) Toil will not be able to retrieve them. Alternatively, the `--noStdOutErr` option forces Toil to discard all standard output and error from batch system jobs.

So `workDir` cannot be on NFS (#2162), and without `workDir` on a shared filesystem, we cannot capture stdout/stderr from batch systems. So, when using slurm+NFS, we can set `workDir` to `/tmp` and use the `--noStdOutErr` option.

I confirmed that setting `--workDir /tmp` and `--noStdOutErr`. results in the toil workflow dir created in /tmp and that stdout/stderr are redirected to /dev/null:

```
xxx.yyy.zzz 2020-01-15 10:24:44,827 Thread-217 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Running ['sbatch', '-J', 'toil_job_1', '--mem=2048', '--cpus-per-task=1', '-o', '/dev/null', '-e', '/dev/null', '--wrap=_toil_worker CWLWorkflow file:/path/to/jobstore kind-CWLWorkflow/instanceqojs7s_f']
```

**Comment by johnbradley** [comment]
@dleehr I see how adding the `--noStdOutErr` flag will prevent this failure. 
The original problem I encountered was that `toil-cwl-runner` using slurm and a non-shared workdir fails with an generic error message. 
I don't see how a typical user would make the leap to the assumption that not capturing logging would fix such an error. 
If the `No log file is present, despite job failing` error is intended functionality when users run with a non-shared workdir and default stdout/stderr settings perhaps the documentation could be improved to mention this requirement explicitly.

**Comment by diekhans** [comment]
@johnbradley 
we have a PR that attempts to make the grid-engine like batch systems more robust and easier to debug. However, we are unable to test them. Would you be able to test it?

https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging

**Comment by johnbradley** [comment]
@diekhans Sure. I can test your branch on my work slurm cluster.

**Comment by johnbradley** [comment]
@diekhans The logging is improved for my error case here when using debug logging:
```
... DEBUG toil.batchSystems.slurm: Getting exit code for slurm job 15671064
... DEBUG toil.batchSystems.slurm: sacct output b'FAILED|1:0\n'
... DEBUG toil.batchSystems.slurm: sacct job state is FAILED
... DEBUG toil.batchSystems.slurm: sacct exit code is 1:0, returning status 1
```

Unfortunately successful runs using slurm seem to get stuck getting exit status from completed jobs with this branch. I will comment further on the PR.

**Comment by DailyDreaming** [comment]
@adamnovak Did #2956 solve this?

**Comment by adamnovak** [comment]
I suspect so, but I don't have the setup to test.

@johnbradley, does this work correctly with Toil 4.0?

**Comment by johnbradley** [comment]
@adamnovak @DailyDreaming I retested the problem and it worked on toil 4.0.
As far as I am concerned this problem is resolved.

**Comment by adamnovak** [comment]
Hooray! Glad to hear it.
