### ISSUE TITLE
Jobs should be somehow tagged with a user-id

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2885]
Right now, if two people are running Toil kubernetes jobs with the same Toil image, I can't see any way to tell their jobs apart with kubernete's paltry interface.  Can we have an option to let toil add a name to jobs or otherwise tag them somehow?  As it stands, I don't think it's possible for me to get a list of my own Toil jobs.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-469)
┆Issue Number: TOIL-469

**Comment by adamnovak** [comment]
We have this already in master; you need to set the `TOIL_KUBERNETES_OWNER` environment variable before launching your jobs:

https://github.com/DataBiosphere/toil/blob/2c97cfd999a657b639ed683b83eab7c5962d3318/src/toil/batchSystems/kubernetes.py#L107-L111
