### ISSUE TITLE
Add an option to not count preemptible failures towards task failures

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2890]
Currently preemptible/spot failures also count towards task failures. As a result, `retryCount`  needs to be set to a reasonably high value when using spot/preemptible instances, which can result in many unnecessary retries when tasks are actually failing due to other reasons (this can become a problem if there are a large number of similar tasks that fail for the same reason).

Ideally, spot failures should be separated out from other types of failures. Some other workflow engines have a "max preemptible try" feature that allocates tasks on regular instances after X retries, but implementing that on Toil is more involved.

In the short term, I propose adding a flag (e.g. `--enableUnlimitedPreemptibleRetries`) that does not count preemptible failures (i.e. anything with `TASK_LOST` status) towards failures. This is a relatively simple change and allows setting `retryCount` to a low value.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-471)
┆Issue Number: TOIL-471

**Comment by adamnovak** [comment]
We probably want this to work with more than just Mesos; we have an eye on using Kubernetes instead of Mesos in our Toil clusters to get around our inability to upgrade our appliance to 18.04 due to not being able to install Mesos.

So the batch system API may need a way to communicate `TASK_LOST` status on jobs, and we'd want to report it from the Kubernetes batch system whenever a pod gets unscheduled due to a node going away (whatever that looks like).

**Comment by arostamianfar** [comment]
Good point. I was thinking we'd return a special `exitStatus` only for `TASK_LOST` [here](https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/mesos/batchSystem.py#L650). Then add logic inside the [leader](https://github.com/DataBiosphere/toil/blob/master/src/toil/leader.py#L830) to treat that differently and not decrement the retryCount.

This should work on any batch system as long as the special exitStatus is used for 'lost' tasks.

**Comment by adamnovak** [comment]
That makes sense I think. Maybe a string exit status ("lost") instead
of a number?

**Comment by arostamianfar** [comment]
hmm...i feel a bit uneasy about using a different type of param since we expect an int and there could be places where it would unintentionally break things (e.g. currently, there are some `%i` refs). I was thinking about using a 'unique' constant (e.g. `2550`). I can send the PR and we can discuss the details there?
