### ISSUE TITLE
clarify whether JobStore.updateFile is atomic or not

### ISSUE THREAD

**Issue by michaelkarlcoleman** [DataBiosphere/toil#2897]
Code in Cactus currently assumes that JobStore.updateFile is atomic, but this appears not to always be the case in practice, since the fileJobStore implementation just uses Python's `shutil.copyfile` (with no further interlocks).

It would be useful to clarify the intended behavior.

Here's the related Cactus code: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/pipeline/cactus_workflow.py#L301-L309

See also https://github.com/ComparativeGenomicsToolkit/cactus/issues/114

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-474)
┆Issue Number: TOIL-474

**Comment by adamnovak** [comment]
After talking with @diekhans and @joelarmstrong it sounds like we do want to provide an atomic update to support Cactus, but that we historically have not had one, at least for the file job store.

So we need to patch the file job store to get the new file on the same device and then do an atomic move.

**Comment by diekhans** [comment]
I am working on a patch

**Comment by diekhans** [comment]
@michaelkarlcoleman The S3 store is atomic.  I will be making the local file store atomic.  In the meantime, throwing in a sleep before accessing might keep you going.
