### ISSUE TITLE
on restart, avoid long sleeps while checking job store

### ISSUE THREAD

**Issue by michaelkarlcoleman** [DataBiosphere/toil#2917]
Not sure whether this is a cactus or toil issue, but on a --restart, it appears that the jobStore is being checked.  For each missing job file, a 30s sleep loop occurs.  The point seems to be to wait for a job file that might appear, but on a full restart, this seems pointless.  For large jobs, running through these can take hours.  Perhaps this could be avoided for the startup case?

(Also, that '#' character seems spurious.)

WARNING:toil.jobStores.fileJobStore:Job file `/gpfs/projects/hpcrcf/mkc/cactus-20191116_84way/jobStore/tmp/n/4/jobb23bLC/job` for job `n/4/jobb23bLC` does not exist (yet). We will try #29 more times with 1s intervals.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-483)
┆Issue Number: TOIL-483

**Comment by adamnovak** [comment]
This should be fixed by #2990 which I just merged.
