### ISSUE TITLE
file store read/write open function should  probably allow binary/encode for PY3

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#2918]
I suspect we need to add binary/text, encode, and error options similar to open() to the job store read and write functions for python 3.

For instance,` fileHandle.write("failed once\n")`
in toil/test/src/resumabilityTest.py will fail
with `TypeError: a bytes-like object is required, not 'str'`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-484)
┆Issue Number: TOIL-484

**Comment by adamnovak** [comment]
What I've been working towards is all the file streams to/from the FileStore being binary-mode, and all the tests (and user code) doing their own encoding/decoding.

**Comment by adamnovak** [comment]
@jonathanxu18 I thought about this a bit more, and I think you want the args to look like `mode='b', encoding=None, errors=None`. Then you can make people use `mode='t'` for text streams, everyone who wants binary can explicitly pass `mode='b'`, and eventually we can make a relatively safe breaking change to make the default mode `'t'` if we ever want to.
