### ISSUE TITLE
Priority of toil job

### ISSUE THREAD

**Issue by ashlingcha** [DataBiosphere/toil#2920]
Hi there,
Unsure if this has already been answered - but I'm running cactus on a cluster system (slurm) where toil jobs are being scheduled but due to the nature of this I've put my main jobscript as high priority, but it isn't making these toil jobs of high priority - this leads to the parent job waiting for too long and timing out - wondering if there was a flag to handle this.

Thanks,
Ashling

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-486)
┆Issue Number: TOIL-486

**Comment by adamnovak** [comment]
If you can express the priority you want as options to sbatch, you can
set the TOIL_SLURM_ARGS environment variable for the Toil leader, and
it will split the string on spaces and pass all the parts as extra
options when it uses sbatch to submit a Slurm job.

The underlying code is here:

https://github.com/DataBiosphere/toil/blob/7471248edc8569e37ec3d4c6161c65e9330b54e9/src/toil/batchSystems/slurm.py#L194-L201

And the documentation is here:

https://toil.readthedocs.io/en/latest/developingWorkflows/toilAPIBatchsystem.html#batch-system-enivronmental-variables

**Comment by adamnovak** [comment]
I think this question has been answered. Please feel free to reopen if you still need more help.
