### ISSUE TITLE
Input files not reachable in tmp dir

### ISSUE THREAD

**Issue by Fifan31** [DataBiosphere/toil#2921]
Hi,
I'm currently using toil and cwl to run workflows on a mesos cluster with a shared file system.
So far so good but even if I use options

- --workdir <path_to_shared_dir>
- --tmpdir-prefix <path_to_shared_dir>
- --preserve-environment TMPDIR   [which points to path_to_shared_dir]
Inpout files are still copied into /tmp/tmpXYZ and workflow fails as they are not reachable for execution nodes.
The same workflow works well (with the same options) if I add the suitable 'InitialWorkDirRequirement' requirement in the cwl file. This way, input files are copied in the outputdir and file are reachable.

Expected behaviour:
Input files should be copied into the (file) JobStore (which is in a dir on the shared file system) and input file paths should be within the JobStore and not any local tmp dir.

Software versions are:

- cwltoil==3.21.0
- cwltool==1.0.20190906054215 

any help is welcome,
Stéphan

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-487)
┆Issue Number: TOIL-487

**Comment by adamnovak** [comment]
Hm. That definitely isn't supposed to happen...

Any clue as to whether it is Toil itself or cwltool code that is doing the copying?

**Comment by adamnovak** [comment]
I don't think this should happen anymore since we changed CWL to use the file store and added `--bypassFileStore` as an option, so I'm going to close this. Please let us know it it still happens.
