### ISSUE TITLE
queue flag

### ISSUE THREAD

**Issue by ashlingcha** [DataBiosphere/toil#2927]
Is there a toil flag for specifying what queue the jobs should be run on?
I'm trying to run cactus on one queue, and have the toil jobs it is spawning running on a different queue

Thanks,
Ashling

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-492)
┆Issue Number: TOIL-492

**Comment by mr-c** [comment]
Hello @ashlingcha. For the Batch backends you can configure which queue to use using backend specific environment variables: see the bottom of https://toil.readthedocs.io/en/latest/appendices/environment_vars.html for detailed information.

**Comment by ashlingcha** [comment]
Thanks!
