### ISSUE TITLE
toil leader thread model uses an insane number of threads

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#2928]
Toil's use of threads causes fork failures on very beefy machines.

This needs to scale better :-(

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-493)
┆Issue Number: TOIL-493

**Comment by diekhans** [comment]
I justed DoS-ed myself on hgwdev with toil creating 20K threads

**Comment by adamnovak** [comment]
20k threads is a lot of threads. We are supposed to be making ~10 per
core for the weirdly thread-intensive single machine batch system, and
hgwdev doesn't have 2k cores.

Did you try and run several workflows at once in single machine mode
without limiting the max cores of each? Or is there some source of
extremely numerous threads other than the single machine batch
system's weird way of allocating cores to jobs that is tripping you
up?

**Comment by diekhans** [comment]
I am trying to paralyzed the cactus tests, so I was potentially
running 10 test batches at once.  So that is like wanting to
allocate 6400 threads, which is awful but not 20K horrible.
