### ISSUE TITLE
DEBUG log level should not be needed to see job failures

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#2949]
DEBUG log level is required to see the details of failures in jobs.

This is more of an ERROR level event.

**Comment by adamnovak** [comment]
In my experience, when jobs fail, you do get their logs logged above DEBUG level. Although I run with logging at INFO usually, so it could be that they are coming out at INFO or WARNING. You want failed job logs to be ERROR? Even when the workflow retries the job?

**Comment by diekhans** [comment]
After looking at the Toil code, I thing this might actually be a
problem in how the Cactus tests are calling Toil.

Assigning this bug to and will close if it is cactus's fault

**Comment by adamnovak** [comment]
@diekhans Did this turn out to be Cactus's fault?

**Comment by diekhans** [comment]
unsure.  I need to look into this more.  I will own the ticket and can figure it out at some point

**Comment by adamnovak** [comment]
I think the log levels are currently correct.
