### ISSUE TITLE
IndexError: list index out of range (Error while running Cactus)

### ISSUE THREAD

**Issue by luisacusick** [DataBiosphere/toil#2951]
Hi,

I am trying to run cactus on a slurm job scheduler am getting toil-related errors when I run the program on the test data.

Here are my arguments:
export TOIL_SLURM_ARGS="-q dept_64"
cactus_args="--binariesMode local --batchSystem slurm --maxCores 360 tmpdir cactus/examples/evolverMammals.txt out"

Here's the error message:

INFO:toil.leader:Issued job 'BatchPreprocessor' D/i/jobcEnKUr with job batch system ID: 7 and cores: 1, disk: 2.0 G, and memory: 2.0 G
2020-01-30 11:51:10,362 - toil.leader - INFO - Issued job 'BatchPreprocessor' D/i/jobcEnKUr with job batch system ID: 7 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.leader:Issued job 'logAssemblyStats' o/7/jobwZmBK7 with job batch system ID: 8 and cores: 1, disk: 2.0 G, and memory: 2.0 G
2020-01-30 11:51:10,363 - toil.leader - INFO - Issued job 'logAssemblyStats' o/7/jobwZmBK7 with job batch system ID: 8 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 219, in run
    activity |= self.createJobs(newJob)
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 121, in createJobs
    batchJobID = self.submitJob(subLine)
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/slurm.py", line 71, in submitJob
    result = int(output.strip().split()[-1])
IndexError: list index out of range

Do you know what could be causing this error? Thank you!

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-500)
┆Issue Number: TOIL-500

**Comment by adamnovak** [comment]
Well the immediate problem here is that Slurm `sbatch` is not producing output that looks like `Submitted batch job 2954103` when a job is submitted, and in fact is not producing any real non-space output at all (so splitting on spaces gives an empty list).

Can you provide an example `sbatch` command that submits a job to your cluster successfully, and the standard output and the output that `sbatch` prints when you run it? Maybe your cluster works differently than the ones we developed against.

**Comment by luisacusick** [comment]
The only thing by default printed to std out is a message like this: "Submitted batch job 3322158 on cluster smp"
If the user doesn't specify an output file to print to, the default is to create one called "slurm-<job number>".out 

After attempting to run the program that uses toil (cactus), I did find empty slurm output files in the directory I ran it from. Thank you!

**Comment by adamnovak** [comment]
I don't think the empty output files from the submitted jobs are the
problem; the issue here is that we aren't getting good output from the
sbatch command itself.

I think we're trying to read that message that gets printed to
standard output. I'm not sure we would handle the "on cluster smp"
part correctly; we're trying to parse the last word as a number. But
that doesn't look to be the error we're getting; it doesn't look like
the message is making it to Toil at all.

If you do sbatch ... >out.txt 2>&1, do you see anything in out.txt?
Maybe it is trying to be smart about whether it is talking to a pipe.

**Comment by luisacusick** [comment]
I ran that command and checked the contents of out.txt 
There is only one line in the file:
Submitted batch job 114509

**Comment by adamnovak** [comment]
Hm, that's exactly what we would expect to be there if everything were
working properly, which is no help for debugging.

I think we might have to hack Toil to be a bit more robust where it is
failing for you, and catch this exception and report what exactly it
thinks Slurm is telling it. Then you could run that improved version
and maybe it would shed some light on what is going wrong.

When you encounter this error, is it for every job that Toil tries to
submit to Slurm, or just some of them? And are any jobs actually
making it to Slurm's queue?

**Comment by diekhans** [comment]
@luisacusick 

we have a PR that attempts to make the grid-engine like batch systems more robust and easier to debug. However, we are unable to test them. Would you be able to test it?

https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging

**Comment by luisacusick** [comment]
Thank you and sorry for the delayed response! This error occurs for every job that toil tries to submit, so none of them are making it to Slurm's queue. Yes, I will try testing this.

**Comment by adamnovak** [comment]
I'm going to close this; we can't fix it with the information we have here, and we have new logging machinery that should produce more useful information if this problem happens to anyone else.
