### ISSUE TITLE
 _toil_worker: command not found

### ISSUE THREAD

**Issue by ashlingcha** [DataBiosphere/toil#2953]
trying to run on slurm batch system and this error keeps cropping up - is there something I've missed in the installation?
Thanks,
Ashling

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-502)
┆Issue Number: TOIL-502

**Comment by mr-c** [comment]
@ashlingcha is toil install to a path that is visible (and the same) on all the slurm nodes?

**Comment by ashlingcha** [comment]
Thanks got it to work this morning.

**Comment by mr-c** [comment]
@ashlingcha Glad to hear it, you are welcome.
