### ISSUE TITLE
CoreOS replaced with Flat Car OS.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2954]
CoreOS is being deprecated: https://coreos.com/os/eol/

We should use the new inheritor: https://www.flatcar-linux.org/

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-503)
┆Issue Number: TOIL-503

**Comment by diekhans** [comment]
that is container coreos, fedora coreos seems to live ...

**Comment by adamnovak** [comment]
It looks like Flatcar would be a drop-in replacement, if it survives,
while the Fedore CoreOS migration guide includes a bunch of stuff like
moving away from cloud-config that I think means we would have to
materially change the provisioner.

**Comment by DailyDreaming** [comment]
Flatcar makes sense as a drop-in to me, though ideally we'll eventually move to a kube only system at some point and be able to drop flat car too.
