### ISSUE TITLE
Uncaught socket timouts prevent launching AWS clusters

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#2963]
Apparently we can get socket timeouts in our AWS cluster launch code, which we need to catch.

See https://github.com/DataBiosphere/toil/issues/2881#issuecomment-583571197

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-506)
┆Issue Number: TOIL-506

**Comment by brantfaircloth** [comment]
This may be due to the fact that I was behind a proxy.  I don’t see this error on other machines in front of the proxy.

**Comment by adamnovak** [comment]
This has now been fixed:
https://github.com/DataBiosphere/toil/blob/d0b85c1f8a0af9cc9cf4ca3f16049664a3e27a49/src/toil/lib/aws/__init__.py#L163-L167
