### ISSUE TITLE
boto attempts to connect to AWS when running locally

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#2965]
Some clusters don't route to the internet.

https://github.com/ComparativeGenomicsToolkit/cactus/issues/139#issuecomment-584278852

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-508)
┆Issue Number: TOIL-508

**Comment by adamnovak** [comment]
As I mentioned in https://github.com/ComparativeGenomicsToolkit/cactus/issues/139#issuecomment-584320688 I think this is just Boto going through its startup procedure. I don;t think it really makes sense to try and guess if we are on the Internet and convince Boto not to do this, although it might be worth reporting a bug to Boto about why its logging is so noisy if all you do is import it and you are not online.

**Comment by diekhans** [comment]
Could we not import the jobstores that are not being used???

**Comment by adamnovak** [comment]
For the batch systems we have a fancy factory pattern to import only what we actually use:

https://github.com/DataBiosphere/toil/blob/8491a03a620f09f3e477405b5d4a5fabfe92c8bd/src/toil/batchSystems/registry.py#L15-L17

For the job stores, we just if/else, but we do constrain the imports to when they are needed:

https://github.com/DataBiosphere/toil/blob/efeaa75465e9c6dd3df8e4535a810a47b17f0561/src/toil/common.py#L848-L868

But we also support reading from AWS when importing input files by URL, and I think the logic that supports that just imports the AWS jiob store on the off chance it may be used later:

https://github.com/DataBiosphere/toil/blob/aebde92234ba4eb06c1eee3dc6570a9f70db8100/src/toil/jobStores/abstractJobStore.py#L231-L254

We would probably want use a smarter import tracing tool to see if that is the first/only place Boto is coming from, though, if we really wanted to avoid importing it unless actually necessary.

**Comment by diekhans** [comment]
I think this is pretty straight-forward to code.  How well to the CI test these paths?

**Comment by adamnovak** [comment]
We definitely run workflows through on the CI, and I am pretty sure we
test importing from files and the AWS job store. I'm not sure we test
importing from any of the fancier URL types, and we don't test all the
batch systems.

**Comment by adamnovak** [comment]
We don't think that changing the import management, to import Boto only when an AWS job store or AWS provisioner or S3 URL is actually used, is worth doing. We think the existing logic of trying to import boto and gracefully handling an import failure is good enough, and probably the more Pythonic approach.

If anyone has an issue where Toil actually can't *start* because of boto's on-import network requests, we can revisit this.
