### ISSUE TITLE
Build docker with the current python version.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2967]
This shouldn't be hard-coded and should be changed to the version we're running from: https://github.com/DataBiosphere/toil/blob/master/docker/Dockerfile.py#L128

Discussed here: https://github.com/DataBiosphere/toil/issues/2964

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-509)
┆Issue Number: TOIL-509

**Comment by adamnovak** [comment]
I think this has been finished. We now support lots of Python versions.
