### ISSUE TITLE
Toil slurm state polling frequency default too high

### ISSUE THREAD

**Issue by cmarkello** [DataBiosphere/toil#3018]
I've been running Toil workflows on the NIH Biowulf cluster which runs under the SLURM batch system. The default job status query rate for Toils support of the SLURM batch system is too frequent. Biowulf CIT found that it pings the batch scheduler every 1-2 seconds while the scheduler daemons only update the status of their jobs every 30-60 seconds.

In order to fix this CIT recommended changing the `--rescueJobsFrequency` and `--statePollingWait` parameters to 180 seconds to be safe and reduce load on the system. It's likely that having defaults set to less frequent state polling will be useful to other users of SLURM systems. 

Looking at the code, it looks like `statePollingWait ` defaults to the value of `getWaitDuration()` https://github.com/DataBiosphere/toil/blob/e6dea9602ca05dcf28b190be97673fd57f69022f/src/toil/batchSystems/options.py#L161

For Toils support of SLURM the value of `getWaitDuration()` looks to be set to 1
https://github.com/DataBiosphere/toil/blob/e193fdce9c7a5b36498f1d40475aff04abc35495/src/toil/batchSystems/slurm.py#L227

And `rescueJobsFrequency` seems to be set to 1 universally https://github.com/DataBiosphere/toil/blob/6e99a91fcf189593e85f6c6c613a7a2e75728b90/src/toil/common.py#L269

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-531)
┆Issue Number: TOIL-531

**Comment by cmarkello** [comment]
@adamnovak

**Comment by adamnovak** [comment]
@cmarkello When you change these parameters, does that mean that the absolute shortest time that it can take a job to run is 180 seconds?

I'm worried that if we make long wait times the default, Cactus will take forever because of how it wants to run very short jobs.

**Comment by cmarkello** [comment]
@adamnovak I guess this can escalate into a discussion about design. But wouldn't a workflow with many tiny jobs impact the IO performance by being bottlenecked by the scheduler?

180 seconds is probably overkill, but if it chokes a scheduler for other users then that's an overall bigger cost on productivity.

Would it make sense to tag jobs by an expected walltime? Then we could set these parameters as a function of that walltime and make this more adaptable by job length.

**Comment by diekhans** [comment]
It seems like this should be configurable.  180 seconds would ruin
cactus.

@cmarkello; are you willing to work on a patch to pass this through?

**Comment by cmarkello** [comment]
@diekhans Cactus runs can adjust `--statePollingWait` and `--rescueJobsFrequency` prior to a run. My concern is for average users of TOIL who aren't aware of these parameters so I don't know if having the default of 1sec frequency of job polling is appropriate for the average user.

It doesn't have to be 180 seconds, it could be 30 to 60 seconds. If a batch system is configured to update a jobs state every 30 seconds, I don't know what purpose a 1 sec `statePollingWait` would do other than overwhelm the batch system.

**Comment by diekhans** [comment]
Is it possible to query the configuration of how frequently it
checks?  That would be the best way to come up with a default.

**Comment by cmarkello** [comment]
I'll have to look into that. It looks like for SLURM there is a config file, though I don't know if an average user would have read access to that file.

http://baobabmaster.unige.ch/slurmdoc/slurm.conf.html

**Comment by diekhans** [comment]
Normally such files are readable.  How, the configuration would
need to be findable even if installed in a non standard place.

The batch systems are desperate from some TLC, hence me wanting
contributions ..

**Comment by diekhans** [comment]
the best would be if SLURM could give you it's configuration via
a command.

**Comment by cmarkello** [comment]
@diekhans Good point. I'll look for options and modify `getWaitDuration` in `slurm.py` with what works.

**Comment by diekhans** [comment]
@cmarkello thank you!

**Comment by adamnovak** [comment]
This was fixed in https://github.com/DataBiosphere/toil/pull/3026
