### ISSUE TITLE
Update conda recipe to support python3

### ISSUE THREAD

**Issue by ifiddes** [DataBiosphere/toil#3020]
The current conda recipe for toil is version 0.24.1, but requires python be 2.*.

https://bioconda.github.io/recipes/toil/README.html

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-533)
┆Issue Number: TOIL-533

**Comment by adamnovak** [comment]
It looks like @matthdsm and @chapmanb might be the Bioconda recipe maintainers.

It also looks like Bioconda does some magic reading from PyPI or something to track our releases. Maybe it will be able to pick up that we [ask for Py3.6 via classifier](https://github.com/DataBiosphere/toil/blob/eda5d4cc05518b761c6a4e0c1905286ffd139552/setup.py#L127) when we do the 4.0 release?

**Comment by adamnovak** [comment]
I'm trying explaining to setuptools that we want Python 3.6. Maybe bioconda can figure that out?

**Comment by matthdsm** [comment]
The latest version of toil in bioconda (3.24.0) is supposed to be noarch, which means it's compatible with py2 and py3.
If there's a hard requirement for py2, then it's derived from one of the listed dependencies or pinned versions of those dependencies

You can check the listed dependencies [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/toil/meta.yaml). If there's anything that doesn't need to be pinned or any dependencies that are deprecated, please remove them from the yaml file. It'll help the build process and improve compatibility.

Cheers
M

**Comment by matthdsm** [comment]
actually, since v4.0 drop py2 support, it might be an ideal time to clean up the dependencies! Huraah for progess! 🥇 

M
