### ISSUE TITLE
gridengine incorrect parsing of qhost output

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#3027]
result in:
```
 File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/batchSystems/gridengine.py", line 166, in obtainSystemConstants
    if items[cpu_index] != '-' and items[cpu_index] > maxCPU:
TypeError: list indices must be integers or slices, not NoneType
```

I happen to have a login to help someone on a grid engine systems, so I will come up with a patch.  I don't get how this ever worked.

**Comment by adamnovak** [comment]
Maybe we should set those when we call into the scheduler. I think a
lot of our parsing is looking for words in English.

**Comment by diekhans** [comment]
> Maybe we should set those when we call into the scheduler. I think a lot of our parsing is looking for words in English.

exactly what I am doing. ;-)  fixing this as part of finishing #2959

**Comment by diekhans** [comment]
fixed
