### ISSUE TITLE
cwl: out of disk space error should give guidance on how to fix that

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3030]
> Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested 

This should mention setting / increasing `outdirMin`  under `ResourceRequirements`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-536)
┆Epic: Improved CWL experience 
┆Issue Number: TOIL-536

**Comment by adamnovak** [comment]
To make this work, we would need to inform the Toil-level code about the existence of the Toil CWL runner, and that it should give different advice depending on whether the workflow is a normal Toil workflow or a CWL workflow (or maybe even a WDL workflow). That or we can write a single broadly-applicable statement ("Consider setting or increasing the disk space requirement", or "Consider increasing the disk requirement for your Toil job, or the outdirMin requirement for your CWL job").

**Comment by mr-c** [comment]
In which PR was this implemented?

**Comment by DailyDreaming** [comment]
@mr-c Ah, I think that it was confused with the fix: https://github.com/DataBiosphere/toil/pull/3362

New PR is up addressing this: https://github.com/DataBiosphere/toil/pull/3495
