### ISSUE TITLE
When killing single machine batch system, child processes outlive parent process

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3045]
Since the daddy-thread refactor of the `SingleMachineBatchSystem`, when we ctrl+c Toil, Toil stops without waiting for its child processes to go away. Then they print errors because the leader cleaned up all its working directories out from under them, clobbering your prompt.

We should `kill -9` all the `_toil_worker` processes instead of just vanishing on them.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-543)
┆Issue Number: TOIL-543

**Comment by adamnovak** [comment]
This seems to maybe only happen with Cactus; I think Cactus is getting its workers to create other child workers (instead of chaining?).

**Comment by adamnovak** [comment]
Yeah, when running Cactus at least, we definitely have workers forking off more workers.

Unless we put all the worker processes into their own process groups, there's no way to kill the whole group. We *might* be able to stop the process groups of our children from being re-used until we wait on them to avoid a race?

But we don't necessarily want the Toil workers to not be in Toil's own process group, because that causes trouble for people above us trying to kill Toil and all descendants.

I think Cactus should just stop doing that.

**Comment by diekhans** [comment]
> I think Cactus should just stop doing that.

Sounds very tacky; how would Cactus do this??
It might not be intentionally..

**Comment by adamnovak** [comment]
I'm not sure; I don't see anywhere in Cactus where it tries to start its own worker from a worker, but I also don't see anywhere where the Toil worker itself will try to start another worker process. But I'm definitely observing worker processes that claim their parents are other worker processes.
