### ISSUE TITLE
Enable caching by default.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3047]
We can probably already do this for native toil workflows.

To enable caching by default on CWL workflows, I think we need to fix issue: #2801

Currently we don't run cwl conformance tests with caching (https://github.com/DataBiosphere/toil/blob/master/src/toil/test/cwl/cwlTest.py#L417) because of #2801 so once this is fixed we should enable them by taking off the `@pytest.mark.xfail` decorators.

Tagging @adamnovak as this would prevent some grid engine issues from being posted but also his inborn love of caching.

**Comment by diekhans** [comment]
It seems like caching should be disabled automatically if the
batchsystem doesn't support it.

**Comment by adamnovak** [comment]
This issue never synced to Jira; I made https://ucsc-cgl.atlassian.net/browse/TOIL-548 for it.

I think we should try to do this in our next sprint.
