### ISSUE TITLE
AWS marketplace product not available

### ISSUE THREAD

**Issue by JaroAmsterdam** [DataBiosphere/toil#3059]
Hi everyone,
I have some trouble launching a cluster on AWS. I followed the setup instructions in the docs and wanted to launch a cluster using:

`toil launch-cluster testcluster --leaderNodeType t2.medium --zone eu-central-1a --keyPairName id_rsa`

this is the output:

```
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Using default docker appliance of quay.io/ucsc_cgl/toil:4.1.0-5ad5e77d98e1456b4f70f5b00e688a43cdce2ebe-py3.6 as TOIL_APPLIANCE_SELF is not set.
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:toil:Using default user-defined custom docker init command of  as TOIL_CUSTOM_DOCKER_INIT_COMMAND is not set.
INFO:toil:Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
INFO:toil:Using default docker name of toil as TOIL_DOCKER_NAME is not set.
INFO:toil:Using default docker appliance of quay.io/ucsc_cgl/toil:4.1.0-5ad5e77d98e1456b4f70f5b00e688a43cdce2ebe-py3.6 as TOIL_APPLIANCE_SELF is not set.
INFO:toil.lib.ec2:Creating t2.medium instance(s) ... 
Traceback (most recent call last):
  File "/home/jaro/myvenv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/home/jaro/myvenv/lib/python3.6/site-packages/toil/utils/toilMain.py", line 25, in main
    module.main()
  File "/home/jaro/myvenv/lib/python3.6/site-packages/toil/utils/toilLaunchCluster.py", line 154, in main
    awsEc2ExtraSecurityGroupIds=config.awsEc2ExtraSecurityGroupIds)
  File "/home/jaro/myvenv/lib/python3.6/site-packages/toil/provisioners/aws/awsProvisioner.py", line 172, in launchCluster
    spec=specKwargs, num_instances=1)
  File "/home/jaro/myvenv/lib/python3.6/site-packages/toil/lib/ec2.py", line 255, in create_ondemand_instances
    **spec).instances
  File "/home/jaro/myvenv/lib/python3.6/site-packages/boto/ec2/connection.py", line 977, in run_instances
    verb='POST')
  File "/home/jaro/myvenv/lib/python3.6/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>OptInRequired</Code><Message>In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=ryg425ue2hwnsok9ccfastg4</Message></Error></Errors><RequestID>905b50f3-9e44-4dc3-befb-8ca28ed506a0</RequestID></Response>
```

It says that I have to subscribe to an AWS marketplace product, but when following the link it says that Container Linux by CoreOS (Stable) is no longer available to new customers.
Is there any way around this?
Thanks in advance,
Jaro

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-551)
┆Issue Number: TOIL-551

**Comment by adamnovak** [comment]
Sounds like this is https://github.com/DataBiosphere/toil/issues/2954 coming to fruition. CoreOS has pulled its images (or the "marketplace" thing that lets you find the right image for your region) from AWS, since it isn't being updated anymore. Presumably they think we would prefer all published versions of Toil breaking to something being compromised.

We need to change this here to something that matches a compatible AMI that actually exists still:

https://github.com/DataBiosphere/toil/blob/ba1f150dbb2f28081227e9f0d52748928d0be76c/src/toil/provisioners/aws/awsProvisioner.py#L389

The workaround is to set `TOIL_AWS_AMI` to an AMI that still exists; either your own upload of CoreOS, or something compatible like Flatcar. [Look up the right AMI for your region here](https://docs.flatcar-linux.org/os/booting-on-ec2/#choosing-a-channel) and try using that:

```
TOIL_AWS_AMI=ami-0a9a5d2b65cce04eb toil launch-cluster testcluster --leaderNodeType t2.medium --zone eu-central-1a --keyPairName id_rsa
```

**Comment by adamnovak** [comment]
I did some testing today; people on Amazon accounts that have already used Toil to start a cluster (and thus have the CoreOS marketplace entry hooked up) can still do so, but AWS accounts that haven't already used this marketplace product can't do it now. We either need to make our own marketplace product or tell Toil how to find the right AMI for every AWS region (at which point we maybe might as well upgrade to Flatcar).

**Comment by DailyDreaming** [comment]
Looks like flatcar use is now urgent.  Guess we should add it to the sprint.
