### ISSUE TITLE
Kubernetes documentation.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3068]
Our documentation is a bit light, for reference: https://toil.readthedocs.io/en/latest/search.html?q=kubernetes&check_keywords=yes&area=default

@adamnovak We should probably add this next sprint if possible I think.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-557)
┆Issue Number: TOIL-557

**Comment by adamnovak** [comment]
Yeah, we definitely need some examples. There are a bunch of secret environment variables you need to set for it to really work (like TOIL_AWS_SECRET_NAME).
