### ISSUE TITLE
toil debug-job can't configure the workdir

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3074]
The `toil debug-job` command lets you run a job locally, but it doesn't have the `--workDir` option, so you can't set a workdir that exists on your local machine if you're running a job from a workflow with a TOIL_WORKDIR set in its environment.

Also, digging through the option parsing code, we have a bunch of stuff that thinks we still support optparse, but some checks that mean we don't actually still support optparse.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-561)
┆Issue Number: TOIL-561

**Comment by melainalegaspi** [comment]
this was fixed by the TOIL_WORKDIR_OVERRIDE
