### ISSUE TITLE
Add a `--nodeStorageOverride` option to customize disk per node type

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#3084]
Currently, all nodes have a uniform disk size specified via the `--nodeStorage` flag. However, some jobs can be heterogeneous requiring vastly different disk requirements. For example, we have a pipeline where some tasks require 2TB+ of disk per task, but the rest require much smaller (e.g. 100GB) amount of disk per task, so setting 2TB of disk for all workers is wasteful especially when there are hundreds of such workers running.

Since the auto scaler is disk-aware, then adding the override to the `nodeShape` definition will automatically let the autoscaler choose the node type that has the override for the particular task (typically, these tasks also require large number of CPUs/RAM, so in practice, they turn out to be "extra large nodes in all aspects").

Example use case: `--nodeTypes c5.9xlarge:1.53,m4.10xlarge:2.0 --nodeStorage 200 --nodeStorageOverride m4.10xlarge:2000`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-568)
┆Issue Number: TOIL-568

**Comment by adamnovak** [comment]
I ran into this problem recently too. The toil-vg construct pipeline
has a few jobs that need a lot of disk, but mostly doesn't.

We could just make `--nodeStorage` accept a single number or a
comma-separated list, to match the min and max node count options.

**Comment by arostamianfar** [comment]
@adamnovak  If you dont feel strongly about it, I actually prefer having a separate flag, since in practice the override is only for one of the node types. Also, I personally like flags that have a more strict definition rather than ones that can change depending on context.
