### ISSUE TITLE
Investigate CWL Caching.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3087]
It looks like we have two failures in the CWL conformance tests when we turn on caching: https://ucsc-ci.com/databiosphere/toil/-/jobs/54084

They xfail, so the runner just automatically says that they pass.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-570)
┆Issue Number: TOIL-570

**Comment by melainalegaspi** [comment]
This has been done already.
