### ISSUE TITLE
cwltool fails for secondary files stored on S3 jobstore

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#3107]
CWL workflows that contain a secondary file that is stored on the S3 jobstore fail with the new `cwltool` version with the exception below:

```
traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cwltool/executors.py", line 233, in run_jobs
    for job in jobiter:
  File "/usr/local/lib/python3.6/dist-packages/cwltool/command_line_tool.py", line 591, in job
    builder = self._init_job(job_order, runtimeContext)
  File "/usr/local/lib/python3.6/dist-packages/cwltool/process.py", line 893, in _init_job
    discover_secondaryFiles=getdefault(runtime_context.toplevel, False),
  File "/usr/local/lib/python3.6/dist-packages/cwltool/builder.py", line 343, in bind_input
    discover_secondaryFiles=discover_secondaryFiles,
  File "/usr/local/lib/python3.6/dist-packages/cwltool/builder.py", line 410, in bind_input
    0 : cast(str, datum["location"]).rindex("/") + 1
ValueError: substring not found
```

The reason is that the `location` for S3 Toil objects is actually like `"location": "toilfs:17008:0b6b9de2-ef48-4bce-834f-fa94a1cd068e",`, which doesn't contain a `/`.
 
@mr-c this looks like a CWL bug rather than a Toil bug, but I figured to file it here first since apparently it only happens on Toil. Please file another issue on the CWL side if desired. Thanks!

P.S. This didn't happen in previous CWL versions as that code only ran [if `basename` didn't exist](https://github.com/common-workflow-language/cwltool/blob/1e5ad10c6b0d1c5f531737d12ef64062a00baef2/cwltool/builder.py#L394), which in Toil, it always exists.

**Comment by mr-c** [comment]
Thanks for catching this @arostamianfar . Maybe you can help develop a toil or cwltool test so this doesn't happen again?

Here's a simple attempt at fixing this issue: https://github.com/common-workflow-language/cwltool/pull/1319/files

**Comment by arostamianfar** [comment]
Thank you for the quick fix, @mr-c ! I've verified that your fix indeed works.

And great point about adding tests to cover these. I filed https://github.com/DataBiosphere/toil/issues/3109

**Comment by arostamianfar** [comment]
Will keep this issue open on the Toil side until a new version of cwltool with the fix has been released and Toil is updated to use that version. @mr-c any ideas when the next release will be?

**Comment by mr-c** [comment]
@arostamianfar I'm making a new cwltool new and I'll update the existing PR to update the toil pin on cwltool

**Comment by mr-c** [comment]
https://pypi.org/project/cwltool/3.0.20200709181526/ has been released

**Comment by mr-c** [comment]
https://github.com/DataBiosphere/toil/pull/3105 has been updated to use that release

**Comment by arostamianfar** [comment]
Amazing! Thank you so much for the quick fixes!

**Comment by mr-c** [comment]
Everything has been merged in, so I'm closing this issue
