### ISSUE TITLE
Toil throws KeyError after workflow execution ends

### ISSUE THREAD

**Issue by Prakash2403** [DataBiosphere/toil#3112]
I tried running toil on an RNA-Seq workflow, accessible at https://github.com/FarahZKhan/cwl_workflows/blob/master/topmed-workflows/TOPMed_RNAseq_pipeline/rnaseq_pipeline_fastq.cwl

The workflow runs smoothly and produces all relevant files(I cross checked by running same pipeline with `cwltool`). But it crashes as soon as workflow execution ends.

Here's the log

```
  File "/home/prakash/.conda/envs/toil/bin/toil-cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 1702, in main
    destBucket=options.destBucket)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 738, in toilStageFiles
    visit_class(cwljob, ("File", "Directory"), _check_adjust)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/cwltool/utils.py", line 231, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/cwltool/utils.py", line 231, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/cwltool/utils.py", line 234, in visit_class
    visit_class(d, cls, op)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/cwltool/utils.py", line 229, in visit_class
    op(rec)
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 733, in _check_adjust
    pm.mapper(f["location"])[1])
  File "/home/prakash/.conda/envs/toil/lib/python3.6/site-packages/cwltool/pathmapper.py", line 385, in mapper
    return self._pathmap[src]
KeyError: 'toilfs:89664:files/for-job/kind-file_mnt_disk8tb_prakash_cwl_workflows_topmed-workflows_TOPMed_RNAseq_pipeline_markduplicates.cwl_run-MarkDuplicates/instance-p59fm9hc/file-21j7zgac/LC_C13_cRNA.Aligned.sortedByCoord.out.md.bam.bai'
```

Any clue on what could've gone wrong?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-585)
┆Issue Number: TOIL-585

**Comment by Prakash2403** [comment]
Steps to reproduce

```
git clone https://github.com/FarahZKhan/cwl_workflows.git
cd cwl_workflows/
git lfs pull
./topmed-workflows/TOPMed_RNAseq_pipeline/input-examples/download_examples.sh
toil-cwl-runner topmed-workflows/TOPMed_RNAseq_pipeline/rnaseq_pipeline_fastq.cwl topmed-workflows/TOPMed_RNAseq_pipeline/input-examples/Dockstore.json
```

Node version: `12.18.2`
Python version: `3.6.10`

**Comment by mr-c** [comment]
Hello. What is your toil version?

--
Michael R. Crusoe

**Comment by Prakash2403** [comment]
@mr-c 
`4.1.0`

Installed it via `pip install toil[all]`

**Comment by DailyDreaming** [comment]
@Prakash2403 I'm attempting to reproduce the problem now based on the readme instructions.

**Comment by DailyDreaming** [comment]
@Prakash2403 Do you have a rough estimate of how long the workflow takes to complete?

**Comment by Prakash2403** [comment]
@DailyDreaming 15-20 mins on MacBook Air having core i5 5th gen processor and 8 GB RAM. Although toil asks for 50 GB disk space, even though resultant output files are of ~5GB.

**Comment by DailyDreaming** [comment]
@Prakash2403 Cool.  Just wanted to make sure I wasn't waiting an hour+.

50GB appears to be defined in the workflow: https://github.com/FarahZKhan/cwl_workflows/blob/master/topmed-workflows/TOPMed_RNAseq_pipeline/rnaseq_pipeline_fastq.cwl#L26

tmpdirMin is specified in Mebibytes: https://www.commonwl.org/draft-3/CommandLineTool.html#ResourceRequirement

2^20 * 51200 = 53687091200 bytes = 53.7 Gigabytes

**Comment by Prakash2403** [comment]
@DailyDreaming Thanks for the info. I mentioned disk space issue because toil crashed initially saying that more disk space is required. I ran the same workflow using `cwltool` and it worked just fine. I'll post the exact stack trace by tomorrow. 

Regarding running RNA-Seq pipeline, just make sure that you're not creating required input files manually. You can follow the steps I wrote [in this comment](https://github.com/DataBiosphere/toil/issues/3112#issuecomment-660040628)

**Comment by DailyDreaming** [comment]
@Prakash2403 I agree it's problematic that we have inconsistent behavior with cwltool (sorry for the trouble).  We should probably follow the cwltool model and make the attempt rather than fail when minimum requirements aren't met just to preserve consistent behavior.

Thanks, following it now.

**Comment by DailyDreaming** [comment]
@Prakash2403 I've successfully reproduced the error with the latest toil from source.  I'll investigate, thanks for providing a reproducible use-case.

**Comment by DailyDreaming** [comment]
@Prakash2403 I think I have a fix here: https://github.com/DataBiosphere/toil/pull/3114

Will wait for tests to pass, but it seems to run your particular workflow successfully and address the issue.  I think the main problem was that it was ignoring secondary files.

**Comment by Prakash2403** [comment]
@DailyDreaming Thanks for the fix :)
