### ISSUE TITLE
[Question] Are there any plans for UI for Toil?

### ISSUE THREAD

**Issue by Prakash2403** [DataBiosphere/toil#3119]
A basic web UI where user can 

* See the workflow progress
* Start/Stop a workflow.
* Override default configurations for a workflow before starting it.
* Visualize the workflow.

Could be inspired by [Apache Airflow](https://github.com/apache/airflow) or [Luigi](https://github.com/spotify/luigi)

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-589)
┆Issue Number: TOIL-589

**Comment by adamnovak** [comment]
I don't think this is on our roadmap for the UCSC team to implement at the moment.

We do have a CLI progress bar I hacked together when you run a workflow under a terminal on the command line, but it doesn't quite have the view of the workflow it needs to be really accurate. We also have the Grafana dashboard, which works with Toil-managed Mesos clusters, when you `toil ssh-cluster` and go to `http://localhost:3000`. It shows statistics about the nodes in the cluster, and the currently running tasks, along with a count of failed jobs. Also, I know that @arostamianfar has a private dashboard that sits over Toil that can do some of these things.

What we do have on the roadmap is tools for dumping workflow visualizations (especially for CWL workflows), and some kind of server that can live over Toil and run workflows on command (although for that I think we're wanting to make it more of an API and less of a web app).

That being said, we'd love it if someone were to put together something like this. I'm not sure we really would be able to maintain it to the same standard as the rest of the project (web stuff sort of assumes that you're reading your web app's browser console diligently for deprecation warnings at least every few months), but we could definitely at least have an option to spin it up in a thread in the leader. And giving the leader a bit of HTTP server capability would support some vague plans I've had for a while for a leader-served JobStore implementation.

**Comment by arostamianfar** [comment]
ah, yes, I still owe you a design doc on our private dashboard! It's pretty basic and doesn't do much of things that Prakash mentioned (ours in mainly built for keeping track of multiple concurrent clusters). It's also heavily built on top of AWS components, so not sure how extensible it will be for other use cases.

And yes, it would be amazing to have a UI that does some of the things that @Prakash2403 mentioned! The current Grafana and Mesos dashboards are decent for most of our use cases and provide some visibility into the cluster.

High level idea for our private dashboard:
* We have an EC2 instance that's always up that hosts the dashboard. It also spins up and keeps track of multiple Toil clusters (we spin up one cluster per job). All data is stored in Redis.
* When a job is run in each Toil cluster, we run a private docker image in parallel to the Toil leader (similar to how Grafana is run) that basically monitors the `worker_logs` directory as set by `--writeLogs` and `--writeLogsFromAllJobs`. It watches for `failed_` files in that directory and uploads those to Redis. This is useful to quickly look at the logs from failed jobs. Running the docker in parallel also means that we dont need to make any changes to the main Toil docker image.
* Our EC2 instance pulls from Redis and displays the following: all running/completed jobs, any failed logs from tasks, and links to Mesos and Grafana dashboards (these links use AWS Route 53 and forward the requests to the corresponding ports on each Toil leader).
Hope this helps!
