### ISSUE TITLE
Update minor dependencies

### ISSUE THREAD

**Issue by davidlougheed** [DataBiosphere/toil#3138]
A few of the minor Toil dependencies are outdated, leading to clutter in commands such as `pip list --outdated`:

* `addict<=2.2.0`
  * Latest version is 2.2.1, with the only change being licenses and tests being added to the release versions
* `dill==0.3.1.1`
  * Latest version is 0.3.2, which drops support for Python 3.4 (not supported by toil anyway) and fixes some minor issues
* `docker==2.5.1`
  * This is a few major versions behind, so updating might be a bit more complex. However, there are some newer releases on the 2.x branch.
* `pathlib2==2.3.2`
  * The latest is 2.3.5, which (vs 2.3.2) drops Py3.3 support and fixes some minor issues

If any of these make sense, I'm happy to make a PR updating `setup.py`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-597)
┆Issue Number: TOIL-597

**Comment by adamnovak** [comment]
We'd definitely welcome a PR updating any of these.
