### ISSUE TITLE
ceil() implemented for WDL.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3150]
Description of WDL function to be added:

 ```
## ceil()

Converts a Float value into an Int by:

    ceil: Round up to the next higher integer

```
https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#int-floorfloat-int-ceilfloat-and-int-roundfloat

 - [x] Add the following WDL function to https://github.com/DataBiosphere/toil/blob/master/src/toil/wdl/wdl_functions.py
 - [ ] Add a test that runs a wdl/json with toil and then checks against cromwell to verify that toil and cromwell have the same behavior
       See: https://github.com/DailyDreaming/wdl-conformance-tests/tree/master/tests/standard_library

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-604)
┆Issue Number: TOIL-604

**Comment by w-gao** [comment]
I did some work in [issues/3150-3151-wdl-ceil-floor](https://github.com/DataBiosphere/toil/compare/issues/3150-3151-wdl-ceil-floor). Please let me know if that's what you had in mind for the first item in the checklist. I wasn't sure if I should add unittests if we'll test them with wdl-conformance-tests.

**Comment by DailyDreaming** [comment]
@w-gao Those changes look good to me for part 1.  Please go ahead with the pull request!  We can add the wdl file tests separately.
