### ISSUE TITLE
read_string() implemented for WDL.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3159]
Description of WDL function to be added:

```
## String read_string(String|File)

The `read_string()` function takes a file path which is expected to contain 1 line with 1 string on it.  This function returns that string.

No trailing newline characters should be included

If the entire contents of the file can not be read for any reason, the calling task or workflow will be considered to have failed. Examples of failure include but are not limited to not having access to the file, resource limitations (e.g. memory) when reading the file, and implementation imposed file size limits.
```
https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#string-read_stringstringfile

 - [ ] Add the following WDL function to https://github.com/DataBiosphere/toil/blob/master/src/toil/wdl/wdl_functions.py
    - Partially implemented here: https://github.com/DataBiosphere/toil/blob/master/src/toil/wdl/wdl_functions.py#L463
 - [ ] Add a test that runs a wdl/json with toil and then checks against cromwell to verify that toil and cromwell have the same behavior
       See: https://github.com/DailyDreaming/wdl-conformance-tests/tree/master/tests/standard_library

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-612)
┆Issue Number: TOIL-612
┆Epic: WDL Standard Library Implementation

**Comment by w-gao** [comment]
I'm not sure if I understand the current implementation of `read_string()` (as well as `read_int()`, `read_float()`, etc) in `wdl_functions`: https://github.com/DataBiosphere/toil/blob/releases/4.2.x/src/toil/wdl/wdl_functions.py#L463-L478

```python
def read_string(inputstring):
    if isinstance(inputstring, tuple):
        inputstring = inputstring[0]
    return str(inputstring)
```

If I understand correctly, this function parses the input _path_, instead of reading the content from the path which is what the function is supposed to do. Are these functions used for another purpose?

**Comment by DailyDreaming** [comment]
@w-gao You're right, these are incorrectly implemented.  Please remove the current functions and add the correct functions which read from a file.
