### ISSUE TITLE
Update prom/node-exporter to use quay.io

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#3172]
Docker just introduced [new limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) around pulling docker images for anonymous users (100 per 6hr period), which can be too low when running large pipelines.

It looks like the only image from dockerhub is `prom/node-exporter` and there is a [mirror on quay](https://github.com/prometheus/node_exporter/blob/master/README.md#using-docker) that we can use instead.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-622)
┆Issue Number: TOIL-622

**Comment by jonathanxu18** [comment]
@arostamianfar I could finish up this issue today if you haven't done so already.

**Comment by arostamianfar** [comment]
@jonathanxu18 awesome! i havent started, so please feel free to do this. thanks!

**Comment by DailyDreaming** [comment]
Fixed by #3186.
