### ISSUE TITLE
Change apiDockerCall to handle stream=True.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3184]
Currently, apiDockerCall returns one output of stdout and stderr joined together:

```
>>> cmd = '/bin/sh -c "echo hello stdout ; echo hello stderr >&2"'
>>> res = client.containers.run(cmd, stream=False)
>>> res.output
b'hello stderr\nhello stdout\n'
```

The API inside can be changed with stream=True, which returns an iterator:

```
>>> cmd = '/bin/sh -c "echo hello stdout ; echo hello stderr >&2"'
>>> res = client.containers.run(cmd, stream=True)
>>> next(res.output)
b'hello stdout\n'
>>> next(res.output)
b'hello stderr\n'
>>> next(res.output)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

Our apiDockerCall would need to change to handle the case where stream=True, so that we can return separate stdout and stderr streams.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-628)
┆Issue Number: TOIL-628

**Comment by adamnovak** [comment]
I'm not clear on what this means. You illustrate the underlying Docker API combining output and error streams. Do you want us to add a `stream=True` to apiDockerCall that streams output and also un-combines them somehow?

**Comment by w-gao** [comment]
@DailyDreaming I'm not sure if using `stream=True` would fully separate stdout and stderr. For example, the `hello-world` image outputs multiple lines to stdout: 

```python
output = client.containers.run(image='hello-world', stream=True)
print(next(output))
print(next(output))
```
This output: 
```
b'\n'
b'Hello from Docker!\n'
```

**Comment by w-gao** [comment]
@DailyDreaming I'm not sure if using `stream=True` would fully separate stdout and stderr. For example, the `hello-world` image outputs multiple lines to stdout: 

```python
output = client.containers.run(image='hello-world', stream=True)
print(next(output))
print(next(output))
print(next(output))
```
This outputs: 
```
b'\n'
b'Hello from Docker!\n'
b'This message shows that your installation appears to be working correctly.\n'
```
with more to read.

**Comment by DailyDreaming** [comment]
@w-gao I see two ways of doing this.

The first is that the docker iterator appears to have a hidden "content" attribute with the `stderr` and `stdout` prefixed with `\x02\x00\x00\x00\x00\x00\x00\r` and `\x01\x00\x00\x00\x00\x00\x00\r` respectively:

```
import docker


client = docker.from_env(version='auto', timeout=3600)

cmd = '/bin/bash -c "' \
      'echo hello stdout ; ' \
      'echo hello stderr >&2 ; ' \
      'echo hello stdout ; ' \
      'echo hello stderr >&2 ; ' \
      'echo hello stdout ; ' \
      'echo hello stdout"'

stdout = client.containers.run(image='ubuntu', command=cmd, stream=True, stderr=True)

print(stdout._response.content)
```

```
b'\x01\x00\x00\x00\x00\x00\x00\rhello stdout\n\x02\x00\x00\x00\x00\x00\x00\rhello stderr\n\x02\x00\x00\x00\x00\x00\x00\rhello stderr\n\x01\x00\x00\x00\x00\x00\x00\rhello stdout\n\x01\x00\x00\x00\x00\x00\x00\rhello stdout\n\x01\x00\x00\x00\x00\x00\x00\rhello stdout\n'
```

OR... we add another function that wraps 'container.exec_run()` which will separate the streams internally when `demux=True` (which I honestly was probably looking at by mistake when I created the issue):

```
>>> res = container.exec_run(cmd, stream=True, demux=True)
>>> next(res.output)
(b'hello stdout\n', None)
>>> next(res.output)
(None, b'hello stderr\n')
>>> next(res.output)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

**Comment by w-gao** [comment]
@DailyDreaming I was looking at `container.exec_run()` though that requires to run in detach mode to get the container object. I'll tinker with it more or look into the first way. Thanks for the suggestions!
