### ISSUE TITLE
cwltool uses --net=none

### ISSUE THREAD

**Issue by alexiswl** [DataBiosphere/toil#3189]
When running `toil-cwl-runner` with a DockerRequirement the docker command uses `--net=none` instead of `--net=host` or not specifying it at all.

I've found this can causes some java tool crash.

This may be related to [this CWL issue](https://github.com/common-workflow-language/cwltool/issues/1139) that has been resolved in the latest issue of CWL.

I've used the following command as a workaround for each time I install toil.

```
sed -i 's/net=none/net=host/g' "${CONDA_PREFIX}/lib/python3.8/site-packages/cwltool/docker.py
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-631)
┆Issue Number: TOIL-631

**Comment by alexiswl** [comment]
```
$ toil-cwl-runner --version
4.2.0
```

```
$ cwltool --version
cwltool 3.0.20200709181526
```

**Comment by DailyDreaming** [comment]
@alexiswl This might be better as a cwltool issue and to speak with those folks: https://github.com/common-workflow-language/cwltool/issues

That change is to a `cwltool` file, which we don't control, I believe.  Both the latest and the version you specified seem to have `--net=none`:
https://github.com/common-workflow-language/cwltool/blob/master/cwltool/docker.py#L392
https://github.com/common-workflow-language/cwltool/blob/3.0.20200709181526/cwltool/docker.py#L392

If they make the change, we can easily update our version and the change should take effect in toil.

**Comment by alexiswl** [comment]
Thanks @DailyDreaming, I think I need to use `NetworkAccess` in order to flip the logic. 

Closing the issue.
