### ISSUE TITLE
slurm.py error, undefeind stdout - stdout should be stderr in code

### ISSUE THREAD

**Issue by DavidBerryNOC** [DataBiosphere/toil#3192]
There's a potential bug in slurm.py that leads to toil-cwl-runner failing. Line 127 declares stderr but line 129 references stdout leading to an error message (NameError: name 'stdout' is not defined)

Line 129 from [slurm.py](https://github.com/DataBiosphere/toil/blob/0aec2884aa829d4e1c9a888a4959b762bca39168/src/toil/batchSystems/slurm.py#L129) should be 

```python
            for line in stderr:
```

not

```python
            for line in stdout:
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-634)
┆Issue Number: TOIL-634

**Comment by DailyDreaming** [comment]
Well, that's embarrassing.  Should have a fix in shortly: https://github.com/DataBiosphere/toil/pull/3194
