### ISSUE TITLE
Add more debug logging to single machine batch system

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3310]
I've been informed that the single machine batch system and file job store, used together, have been observed taking a minute or two between issuing a job and seeing the message from the resulting worker about redirecting its logging. This is happening at the scale of tens of jobs. It's apparently intermittent, which to me suggests a slow filesystem, but it would be nice to know for sure. It could be that there's too much synchronization and contention around the single machine daddy thread, which does all its thinking by using the issued job queue as a delay line.

It might be filesystem-slowness-related or it might not, but we don't currently have debug logging at e.g. the point where the child process is launched, or the point where the worker first starts running, to see where the time is going.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-718)
┆Issue Number: TOIL-718

**Comment by thiagogenez** [comment]
Just to confirm, the problem of slowness to handover the logging was certainly the cluster filesystem. However, a debug logging on this level at Toil would facilitate the investigation where the time is going.

For instance the 2-minutes of no info below:

```
[2020-10-30T16:24:17+0000] [MainThread] [I] [toil.leader] Issued job 'Job' kind-Job/instance-mksb3x09 with job batch system ID: 64 and cores: 0, disk: 100.0 M, and memory: 512.0 M

[2020-10-30T16:26:47+0000] [MainThread] [D] [toil.common] Obtained node ID d7499de5-16c9-4f1d-81b6-6c7a0b8ff866 from file /proc/sys/kernel/random/boot_id
```
