### ISSUE TITLE
WDL GATK Tutorial Test 04 Breaks.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3339]
There are 4 WDL GATK tutorials here: https://support.terra.bio/hc/en-us/sections/360007347652-WDL-Tutorials

We used to have them run with Toil as tests, but it's been a long time since they've run.  I've re-enabled them, but tutorial 4 is now breaking (which I've marked as something to skip now).  See: #3340

The error looks like this:

```
[2020-11-23T22:58:51-0800] [MainThread] [I] [toil.wdl.wdl_functions] ('files/no-job/file-fad0debb1bf046909342e9e6d5ef4860/inputsTSV.txt', 'inputsTSV.txt')
[2020-11-23T22:58:51-0800] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/home/quokka/git/toil/toilWorkflowRun)
Traceback (most recent call last):
  File "/tmp/toil-wdl-test-4a125997-5508-4811-a721-a34c3f842f03/toilwdl_compiled.py", line 373, in <module>
    inputSamples = parse_value_from_type((read_tsv(inputSamplesFile)), var_type='File', file_store=fileStore)
  File "/home/quokka/git/toil/src/toil/wdl/wdl_functions.py", line 713, in read_tsv
    with open(path, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not tuple
Traceback (most recent call last):
  File "/home/quokka/git/toil/src/toil/wdl/toilwdl.py", line 149, in <module>
    main()
  File "/home/quokka/git/toil/src/toil/wdl/toilwdl.py", line 144, in main
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/quokka/git/toil/v3nv/bin/python3.6', '/tmp/toil-wdl-test-4a125997-5508-4811-a721-a34c3f842f03/toilwdl_compiled.py']' returned non-zero exit status 1.
```

Looking at the file, this is the relevant compiled portion:

```
...
...

if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./toilWorkflowRun")
    options.clean = 'always'
    with Toil(options) as fileStore:

        # WF Declarations
        inputSamplesFile = parse_value_from_type("src/toil/test/wdl/GATK_data/inputsTSV.txt", var_type='File', file_store=fileStore)
        inputSamples = parse_value_from_type((read_tsv(inputSamplesFile)), var_type='File', file_store=fileStore)

...
...

```

`read_tsv(filename)` tries to `open(filename, 'r')` but gets a `Tuple` like this: `('files/no-job/file-fad0debb1bf046909342e9e6d5ef4860/inputsTSV.txt', 'inputsTSV.txt')` from the previously imported file instead.

This ticket would be fixing the error and re-enabling the test.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-732)
┆Issue Number: TOIL-732

**Comment by w-gao** [comment]
@DailyDreaming Looks like we need to read the files after we import them for workflow definitions as well. Should we make the workflow itself a Toil job, so we can have access to a fileStore and properly read the input files?

**Comment by DailyDreaming** [comment]
@w-gao That would be in line with what CWL does, and I would support it if you want to tackle that refactor.  That would be a major change though I think.  I think we should probably start trying to turn the WDL logic into an interpreter rather than a compiled file.

We should keep the compiled functionality for now, and build the interpreter in isolation.  We should talk about it tomorrow at stand up.  If this would be interesting for you, we can work on this together.  There are a lot of good ideas in https://github.com/chanzuckerberg/miniwdl , particularly of interest to you recently might be their typing: https://github.com/chanzuckerberg/miniwdl/blob/main/WDL/Type.py#L340

**Comment by w-gao** [comment]
@DailyDreaming Ahh, I see. I won't do that refactor then. I'm definitely interested in building the interpreter with you. I'll take a closer look at miniwdl but so far it seems like what I am doing in #3335 is similar to their typing.
