### ISSUE TITLE
Toil's S3 I/O is way slower than awscli

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3367]
It is almost 3X slower to transfer S3 files with Toil than with `aws s3 cp`.  This translates to significant overhead when trying to work on huge datasets

```
time aws s3 cp s3://vg-k8s/vgamb/wg/fasta/dna-brnn-masked/HG002.mat.fa.gz .
download: s3://vg-k8s/vgamb/wg/fasta/dna-brnn-masked/HG002.mat.fa.gz to ./HG002.mat.fa.gz

real	1m43.611s
user	0m12.310s
sys	0m10.049s
```
Using Toil to import this same file (see #3366 for script)
```
time python import_file.py
real	4m49.146s
user	0m16.440s
sys	0m9.841s
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-744)
┆Issue Number: TOIL-744

**Comment by DailyDreaming** [comment]
This and #3366 should both be fixed by the move from boto to boto3 in the AWS jobstore.  Will be addressed next sprint.

**Comment by DailyDreaming** [comment]
This worked for me before, but is now actually forbidden using both `aws s3 cp` and `toil`.  I tested the branch #3400 before it was merged and it seemed to fix this, so I'm considering this closed, as that has been merged.  Please reopen if this is still a problem.
