### ISSUE TITLE
Toil can't delete AWS IAM roles if the instances are gone

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3377]
https://github.com/DataBiosphere/toil/blob/98dbf33147ed029800dd43a73ee5c64e83feda7b/src/toil/provisioners/aws/awsProvisioner.py#L576

The only place where Toil deletes IAM roles is where it deletes all the roles it created attached to a list of instances. If the instances have all gone away, Toil cannot find the roles it created and will leave them behind when you `toil destroy-cluster`.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-756)
┆Issue Number: TOIL-756

**Comment by DailyDreaming** [comment]
Oh, I missed these entirely.  I'll bet that there are a ton of leftover roles in there.
