### ISSUE TITLE
toil launch-cluster error in AWS

### ISSUE THREAD

**Issue by hehuiying1125** [DataBiosphere/toil#3392]
Hi,
I would like run cactus in AWS and following the introduction in "Running in AWS", I installed toil 4.2.0 with python3.6.6. When I started to launch-cluster as "toil launch-cluster -z cn-northwest-1b test --keyPairName id_rsa --leaderNodeType t2.medium" , I always got the error "**Unknown option "launch-cluster".  Pass --help to display usage information**." However, when I used " toil launch-cluster --help" ,I could get the help information successfully. 
If I only give one of culsterName and --leaderNodeType to launch-cluster, I could get the information to remind me that the leaderNodeType or clusterName is missing. "toil: error: the following arguments are required: --leaderNodeType" or "toil: error: the following arguments are required: clusterName". It seemed "toil launch-cluster" worked normally.
 At begging, I though this error was due to the version of Python3 and toil. I have tried python3.6.1 , python3.8.6 and toil 5.2.0, but I always get the same error. When I tried python3.6.6 and toil3.12.0, this error was disappered but I got errors about "TypeError: a bytes-like object is required, not 'str'".
If anyone could give suggestion about this error, it will be appreciated.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-764)
┆Issue Number: TOIL-764

**Comment by hehuiying1125** [comment]
If I only give one of culsterName and --leaderNodeType to launch-cluster, I could get the information to remind me that the leaderNodeType or clusterName is missing. But if typed as “toil launch-cluster test --leaderNodeType t2.medium”， I will got the error "Unknown option "launch-cluster". Pass --help to display usage information."

**Comment by hehuiying1125** [comment]
Hi,
Thanks for for reply. I am running on a centOS linux system on AWS. Previously, I used **cn-northwest-1b** in AWS, the error always came out and it was maybe due to "cn-northwest-1 " not in the regionDirct. When I used **us-east-2c**, the error disappear.
But I met a new error. I could launch-cluster, rsync-cluster and ssh-cluster successfully. When I start run cactus as "cactus --nodeTypes c4.8xlarge:0.6,r3.8xlarge --minNodes 0,0 --maxNodes 2,2 --provisioner aws --batchSystem mesos --metrics **aws:us-east-2:agis-2020-4-jobstore** seqFile.txt output.hal", I got an error as "ValueError: Could not connect to SimpleDB.Make sure 'us-east-2' is a valid SimpleDB region" in "/toil/jobStores/aws/jobStore.py line 686".  Then I run cactus again as "cactus --nodeTypes c4.8xlarge:0.6,r3.8xlarge --minNodes 0,0 --maxNodes 2,2 --provisioner aws --batchSystem mesos --metrics **aws:us-west-2:agis-2020-4-jobstore** seqFile.txt output.hal" while the cluster was still launched in us-east-2c. I got an error as "boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request". Does this due to I launch-cluster in us-east-2 but build jobstore in us-west-2?  As the spot instance in us-east-2 is much cheaper than the other regions, if I still want to use us-east-2, what should I do? If you could give some suggestions, it will be appreciated. 
Best wishes for the coming new year.

**Comment by hehuiying1125** [comment]
The full log of running Cacuts in us-west-2 region was as following:
[2021-01-03T07:43:59+0000] [MainThread] [I] [toil.lib.bioio] xmlRoot = <multi_cactus inputSequenceNames="CW01 NH188 NIP punctata" inputSequences="s3://agis2020aws/CW01.soft_masked.fa s3://agis2020aws/NH188.soft_masked.fa s3://agis2020aws/Os-7.soft_masked.fa s3://agis2020aws/punctata.soft_masked.fa">
	<tree>(NH188:0.00015,NIP:0.52327,CW01:1.14096,punctata:1.6193199999999999)ac;</tree>
	<cactus experiment_path="/tmp/tmpbnarqa1j/progressiveAlignment/ac/ac_experiment.xml" name="ac" />
</multi_cactus>
Traceback (most recent call last):
  File "//venv/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 389, in main
    runCactusProgressive(options)
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 424, in runCactusProgressive
    project.inputSequenceIDMap[genome] = toil.importFile(seq)
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 1026, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 305, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 413, in _importFile
    srcKey = self._getKeyForUrl(url, existing=True)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 500, in _getKeyForUrl
    location = s3.get_bucket(bucketName).get_location()
  File "/root/.local/lib/python3.6/site-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/root/.local/lib/python3.6/site-packages/boto/s3/connection.py", line 556, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

**Comment by DailyDreaming** [comment]
@hehuiying1125 Ah, we have a method for updating our instances but not regions.  We should probably pull in `cn-northwest-1` and any other new regions.  Thanks for bringing that to our attention.

Hmmm... we're going to try to replace simple DB this year, but it's not on a sprint yet.  us-east-2 appears to be an invalid region:

```
SimpleDB is currently available in the US East (Northern Virginia), US West (Oregon), US West (Northern California), EU (Ireland), Asia Pacific (Singapore), Asia Pacific (Tokyo), Asia Pacific (Sydney), and South America (Sao Paulo) Regions.
```
https://aws.amazon.com/simpledb/details/

There currently isn't a way to run it in that region until the code is written that replaces simpleDB with s3 now that s3 is strongly consistent.  If you were sufficiently motivated, we'd very much welcome outside contributions to that effect.  Otherwise, it may be some months away.

As for the error in us-west-2 region, it looks like s3 can't `head bucket` so it's likely a permissions issue with accessing these files: `"s3://agis2020aws/CW01.soft_masked.fa s3://agis2020aws/NH188.soft_masked.fa s3://agis2020aws/Os-7.soft_masked.fa s3://agis2020aws/punctata.soft_masked.fa"`.  We had a similar error recently and I'll try to have the fix in on Monday.

**Comment by hehuiying1125** [comment]
@DailyDreaming Thank you very much for your reply. Looking forward to your good news about the error fixing.

**Comment by DailyDreaming** [comment]
@hehuiying1125 I asked @w-gao to reopen #3400 , which I believe will fix the issue.  We'll have to wait for tests.

**Comment by hehuiying1125** [comment]
@DailyDreaming @w-gao Thanks for fixing the issue. If you need any help in testing, I am willing to help.

**Comment by DailyDreaming** [comment]
@hehuiying1125 That would be much appreciated.  The previous set of tests appear to be passing, but it'll be another few hours before the the latest complete.  I'll wait for @w-gao to say when it's done.

**Comment by DailyDreaming** [comment]
@hehuiying1125 #3400 has been merged.  If you could test access to importing your s3 inputs again, it would be appreciated!  :slightly_smiling_face:

**Comment by hehuiying1125** [comment]
I was using toil 4.2.0 to run cactus. I have tried to use  jobStore.py and utils.py from github to replace those in toil 4.2.0. I got errors as following:
Traceback (most recent call last):
  File "//venv/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 389, in main
    runCactusProgressive(options)
  File "//venv/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 395, in runCactusProgressive
    with Toil(options) as toil:
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 771, in __enter__
    jobStore = self.getJobStore(config.jobStore)
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 909, in getJobStore
    from toil.jobStores.aws.jobStore import AWSJobStore
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/jobStore.py", line 45, in <module>
    from toil.jobStores.aws.utils import (SDBHelper,
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/aws/utils.py", line 32, in <module>
    from toil.lib.retry import (
ImportError: cannot import name 'old_retry'

Does his error due to different version of toil?

**Comment by DailyDreaming** [comment]
@hehuiying1125 Yes, that looks like the old retry that was refactored.  I think if you fork cactus, update the toil version in it to be version-less, install cactus from source and then install toil from source, it should work.

I'll make a new toil release to 5.3.0 too.

**Comment by DailyDreaming** [comment]
Release has been made and I've posted an issue on cactus to update.  Please let me know if you run into any more issues.
