### ISSUE TITLE
Add maxLocalJobs to documentation.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3402]
Especially here: https://toil.readthedocs.io/en/latest/running/cliOptions.html .  This should(?) be the correct way to push Toil to submit more jobs in a system like LSF (which is otherwise limited by cpu), but get context from the original PR first.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-768)
┆Issue Number: TOIL-768

**Comment by adamnovak** [comment]
See also: https://github.com/DataBiosphere/toil/issues/2509#issuecomment-454066174
