### ISSUE TITLE
Update kubernetes reqs if possible.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3425]
If one runs `pip list --outdated` :

```
(v3nv) quokka@qcore 09:43 PM ~/git/toil$ pip list --outdated
Package                Version Latest  Type
---------------------- ------- ------- -----
idna                   2.10    3.1     wheel
kubernetes             10.1.0  12.0.1  wheel
```

Our kubernetes reqs could probably use updating, though this is low priority.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-781)
┆Issue Number: TOIL-781

**Comment by adamnovak** [comment]
This was fixed in #3357; we currently accept any release of Kubernetes v12.
