### ISSUE TITLE
Creating cluster fails

### ISSUE THREAD

**Issue by imilos** [DataBiosphere/toil#3429]
I'm trying to create a cluster on AWS according to [this recipe](https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#running-a-cwl-workflow-on-aws). However:
```
toil launch-cluster probniklaster --leaderNodeType t2.medium --nodeTypes t2.medium -w 1 --zone eu-central-1a --keyPairName Milos --provisioner aws
```
fails with:
```
Traceback (most recent call last):
  File "/home/milos/.local/bin/toil", line 8, in <module>
    sys.exit(main())
  File "/home/milos/.local/lib/python3.8/site-packages/toil/utils/toilMain.py", line 26, in main
    module.main()
  File "/home/milos/.local/lib/python3.8/site-packages/toil/utils/toilLaunchCluster.py", line 142, in main
    cluster.addNodes(nodeType=worker_node_type,
  File "/home/milos/.local/lib/python3.8/site-packages/toil/provisioners/aws/awsProvisioner.py", line 326, in addNodes
    sgs = [sg for sg in self._ctx.ec2.get_all_security_groups() if sg.name in self._leaderSecurityGroupNames]
  File "/home/milos/.local/lib/python3.8/site-packages/toil/provisioners/aws/awsProvisioner.py", line 326, in <listcomp>
    sgs = [sg for sg in self._ctx.ec2.get_all_security_groups() if sg.name in self._leaderSecurityGroupNames]
AttributeError: 'AWSProvisioner' object has no attribute '_leaderSecurityGroupNames'
```
TOIL_APPLIANCE_SELF is the default one, quay.io/ucsc_cgl/toil:5.2.0-047d0c4f2949c576c80e452a0807c5be6355c63d-py3.6. What am I doing wrong?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-783)
┆Issue Number: TOIL-783

**Comment by imilos** [comment]
Launching a single node cluster on AWS actually works as expected (only leader), but still no luck in getting the functional multinode Mesos cluster. The second thing I tried is to launch only a leader using `toil launch-cluster`, SSH to it, and try to auto-scale from the leader instance:
```
toil-cwl-runner --provisioner aws --jobStore aws:us-west-1:toil-kubernetes-example-milos-33 --batchSystem mesos --nodeType t2.medium --minNodes 1 --maxNodes 2 /tmp/workflow.cwl /tmp/inputs.yml
```
However,
```
Traceback (most recent call last):
  File "/usr/local/bin/toil-cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/toil/cwl/cwltoil.py", line 2281, in main
    outobj = toil.start(wf1)
  File "/usr/local/lib/python3.8/dist-packages/toil/common.py", line 817, in start
    return self._runMainLoop(rootJobDescription)
  File "/usr/local/lib/python3.8/dist-packages/toil/common.py", line 1105, in _runMainLoop
    return Leader(config=self.config,
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 228, in run
    self.innerLoop()
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 608, in innerLoop
    self._processReadyJobs()
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 514, in _processReadyJobs
    self._processReadyJob(updatedJob, resultStatus)
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 462, in _processReadyJob
    self.issueJob(readyJob)
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 736, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode)
  File "/usr/local/lib/python3.8/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 182, in issueBatchJob
    resources=MesosShape(wallTime=0, **jobNode._requirements),
AttributeError: 'JobDescription' object has no attribute '_requirements'
```
Any idea what is going on? Where should these `_requirements` be specified?

**Comment by DailyDreaming** [comment]
@imilos We're looking into these.  They're likely errors that were overlooked with some of the recent refactors.  Thanks for posting the issue.

**Comment by adamnovak** [comment]
I think I ran into this when I was doing #3357. We hadn't been running the provisioner tests, and we managed to break manual creation of nodes with the cluster (the first error) somehow, and also the Mesos batch system (the second error) in my JobDescription refactor.

These issues are both fixed in the current `master` branch, and the tests have been turned back on so these features should not break again.

As a workaround, if you set `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:5.3.0a1-8f9c457ce9aebed6c2b143296dba9bc9a544760a-py3.6` and launch the leader-only cluster with 5.2, then inside the cluster you will have the fixed version. Then you should be able to let the workflow scale the cluster up.

**Comment by imilos** [comment]
Dear @adamnovak many thanks! It is now working perfectly! My CWL workflows are all running fine. 

Moreover, I noticed a mention of `mesos.cli` in [the documentation](https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#running-a-cwl-workflow-on-aws). When logged in the leader node, there is already a number of `mesos-*` commands installed. I was wondering how to use them to monitor the status of the Mesos cluster, etc. For example, I'm getting something like:
```
(venv) root@ip-172-31-21-234:/# mesos-state 
NameError: name 'cfg_name' is not defined
```
How one is supposed to interact with a batching system?

**Comment by adamnovak** [comment]
If you want to examine Mesos, there's a Mesos web dashboard that you can use. Unfortunately we don't really have documentation for getting to it, but it should be forwarded out to local port 5050 when you `toil ssh-cluster`, and you can open it in a browser. But in newer Mesos versions it doesn't work well unless you get a `-D<port>` option into your ssh command line string to the cluster, and use the resulting proxy in your browser.

If you use the new Kubernetes cluster type, `kubectl` should be available in the leader and configured to work properly for interacting with Kubernetes.
