### ISSUE TITLE
MyPy checks.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3430]
This means means adding type hinting to each file and then a line to run mypy on those files in the `gitlab-ci.yml` file.  This is going to be long and tedious, but should help development in the long run and provide a sanity check for basic type mismatch errors.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-784)
┆Issue Number: TOIL-784

**Comment by mr-c** [comment]
FYI: https://mypy-lang.blogspot.com/2021/02/mypy-0812-released.html

**Comment by DailyDreaming** [comment]
@mr-c Oh, `version 0.8+` no longer requires `__init__.py` files.  That's awesome.  I definitely support replacing the current script with a `mypy.ini` config eventually then.

**Comment by mr-c** [comment]
Hmm.. the mypy branch was merged without being run on the latest commits; this is blocking other PRs

https://ucsc-ci.com/databiosphere/toil/-/jobs/76445#L1362
