### ISSUE TITLE
PermissionError for readGlobalFile()

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#3433]
We are having this issue as of toil 5.2.0:

```
Traceback (most recent call last):
  File "/home/shahr2/tools/system/miniconda/versions/4.6.14/envs/nucleo_test/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 615, in visit
    deref = self.get_file(path) if self.get_file else ab
  File "/home/shahr2/tools/system/miniconda/versions/4.6.14/envs/nucleo_test/lib/python3.6/site-packages/toil/cwl/cwltoil.py", line 756, in toil_get_file
    src_path = file_store.readGlobalFile(FileID.unpack(file_store_id[7:]))
  File "/home/shahr2/tools/system/miniconda/versions/4.6.14/envs/nucleo_test/lib/python3.6/site-packages/toil/fileStores/nonCachingFileStore.py", line 99, in readGlobalFile
    os.chmod(localFilePath, os.stat(localFilePath).st_mode | stat.S_IXUSR)
PermissionError: [Errno 1] Operation not permitted: '/home/shahr2/bergerlab/test/nucleo_test/test_29Jan2020/toil_1/node-5bbdc7f7-e26f-4958-aff8-2986c4b0b199-2919ee05-ad3b-4b1c-a90e-1d35c9ebd4ab/tmpt5zanbkb/4f6b5fd2-537c-4aed-ac07-87cbb60d665a/tmpwwfjv6k7.tmp'
```

I believe it's related to this change:

https://github.com/DataBiosphere/toil/pull/3322/files#diff-7141faf78b8bb77178d22d78d6af5f62ae090690f86a87f53ee2ca02f2b2fca3R98

Would it be possible to get some info regarding whether this is an intended error, and perhaps we're trying to import a file (using toil-cwl-runner) incorrectly? Or whether there is an issue with how execute permissions are set on imported files?

Let us know if I can provide any additional information, thank you kindly!

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-786)
┆Issue Number: TOIL-786

**Comment by mr-c** [comment]
@ionox0 This is not an intended error. The goal was to replicate the executable bit (if set) after copying a file from the filestore to the local system.

I'm curious as to which filesystem was involved, and why the user (that `toil` was running as was) was unable to set the executable bit on a file it made itself.

I would be happy to review A PR to catch the exception and log a warning instead of failing :-)

**Comment by diekhans** [comment]
this would happen if a file is linked rather than copied

**Comment by mr-c** [comment]
> this would happen if a file is linked rather than copied

ah-ha! This makes more sense. We should either detect when a symlink is being used, or add a `try`/`catch` to avoid failing unnecessarily

**Comment by DailyDreaming** [comment]
@ionox0 Could you test #3437?  I believe the logic in there should address this... but I had trouble reproducing this.  Also... if you had a test case, that would be greatly appreciated!

**Comment by ionox0** [comment]
Thanks so much for the quick response, I'm away at the moment but can take a look when I get back.

**Comment by DailyDreaming** [comment]
@ionox0 This should be merged now.  Please reopen if this didn't fix the problem!
