### ISSUE TITLE
Expose a way to set the ServiceAccount used by freshly created Kubernetes pods

### ISSUE THREAD

**Issue by abatilo** [DataBiosphere/toil#3436]
When the [new pod is created](https://github.com/DataBiosphere/toil/blob/8f9c457ce9aebed6c2b143296dba9bc9a544760a/src/toil/batchSystems/kubernetes.py#L453-L455), there's no way to specify a ServiceAccount.

This means that I **must** put the IAM permissions for interacting with SimpleDB directly on the EC2 node which is widely known to be a huge security hole.

I'd like to be able to specify a ServiceAccount so that I can do things like specify per pod permissions with features like [AWS EKS's IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-788)
┆Issue Number: TOIL-788

**Comment by DailyDreaming** [comment]
We also see this as important.  Thank you for raising the issue.
