### ISSUE TITLE
In-place updates of files in CWL don't seem to work when run manually without caching

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3464]
On Courtyard, with commit 5b70540708973d0116d73605ee7daa3b171481cf (current `master` branch), when I run this one particular test from the CWL 1.1 conformance tests, I get the wrong answer when caching is off: 

```
git clone https://github.com/common-workflow-language/cwl-v1.1.git ~/build/toil/src/toil/test/cwl/spec_v11 && cd ~/build/toil/src/toil/test/cwl/spec_v11 && git checkout 664835e83eb5e57eee18a04ce7b05fb9d70d77b7

toil-cwl-runner --disableCaching=True --clean=always --outdir=/tmp/tmp7fb6na8h --workDir=/tmp/adamnovak-toil/test --quiet tests/inp_update_wf.cwl tests/empty.json
```

(I need to put the `--workDir` on local storage to work around https://github.com/common-workflow-language/cwltool/issues/1405.)

It thinks and logs for a minute or so and finally outputs:

```
{
    "a": 3,
    "b": 4
}
```

If I change to `--disableCaching False`, I get the answer that the conformance tests actually check for:

```
{
    "a": 4,
    "b": 4
}
```

The `a` answer is generated by a job that looks at the output file of a prior job, and is *supposed* to be waiting on another successor of that prior job to have made an in-place update. With caching off, either that update is not happening or it is not visible (in time?) to the job that wants to see it.

I'm not sure why this doesn't come up in the CI tests before; it has started failing on CI in the branch for #3323. My current theory is that when I changed the number of tests to run in parallel (which we had been misoverestimating due to seeing all the Kubernetes host cores but only having access to some of them), it changed the usual outcome of a race condition.

@DailyDreaming Any idea what's going on here? Can you replicate this issue when you run this test?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-807)
┆Issue Number: TOIL-807

**Comment by DailyDreaming** [comment]
I just ran this with:

```
git clone https://github.com/common-workflow-language/cwl-v1.1.git ~/build/toil/src/toil/test/cwl/spec_v11 && cd ~/build/toil/src/toil/test/cwl/spec_v11 && git checkout 664835e83eb5e57eee18a04ce7b05fb9d70d77b7

/home/quokka/venv/bin/toil-cwl-runner --disableCaching=False --clean=always --outdir=/tmp/tmp7fb6na8h --workDir=/tmp tests/inp_update_wf.cwl tests/empty.json
```


And I got:

```
{
    "a": 4,
    "b": 4
}
```

With both caching and disableCaching.  I used a fresh clone of toil's `master` branch and installed from source with `make prepare && make develop extras=[all]`.

**Comment by DailyDreaming** [comment]
I tried creating and setting `--workDir=/tmp/adamnovak-toil/test` exactly as you did as well, and still get `{"a": 4, "b": 4}` for both caching and disableCaching.

**Comment by DailyDreaming** [comment]
@adamnovak This is supposed to be acting upon a file with a symlink to the original.  If there is no symlink, it might be acting on a new file, which would cause an error like the one you're seeing, so that's my current guess.  I'd have to dig into this more in order to determine exactly why it's failing.

**Comment by adamnovak** [comment]
Hmmm. Is your CWL test checkout on the same device as your /tmp? On Courtyard it isn't.

**Comment by DailyDreaming** [comment]
Yes, they're on the same device.  I'm not sure I can easily replicate that.  I'm not even sure I have access to courtyard.

**Comment by adamnovak** [comment]
It looks like it succeeds when `TMPDIR` and the work directory (and thus jobstore) are on the same device, and fails otherwise.

This works for me on Courtyard:
```
TMPDIR=/tmp toil-cwl-runner --disableCaching=True --clean=always --outdir=/tmp/tmp7fb6na8h --workDir=/tmp/adamnovak-toil/test --quiet tests/inp_update_wf.cwl tests/empty.json
```

**Comment by adamnovak** [comment]
Normally I have my TMPDIR set to a different, larger device.

**Comment by adamnovak** [comment]
I feel like we're missing some code to detect and reupload files that CWL jobs tried to modify in place, and to get the new IDs for those files to other jobs that expect to see those modifications just by virtue of their execution order constraints.

If we don't have that, how do we expect modified files to make it from one Mesos or Kubernetes node to another? We can't commit the modification back to the original file ID.

**Comment by adamnovak** [comment]
We've completely rewritten CWL filesystem support since this happened, and we now have `--bypass-file-store` to enable the in-place update requirement that CWL offers.
