### ISSUE TITLE
FYI: I turned on "Require branches to be up to date before merging"

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3472]
Since we always squash, the extra commit doesn't matter. Had this been turned on we wouldn't have had the mypy issue :-)

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-812)
┆Issue Number: TOIL-812

**Comment by adamnovak** [comment]
It seems to be working well so far! I will go ahead and close this notification issue.
