### ISSUE TITLE
Exited Docker containers are not cleaned up

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3505]
I ran this command a bunch in `toil-vg` commit b3c290f7143376978e35e98ed524ca613941de01 or so:

```
make test tests=src/toil_vg/test/test_vg.py::VGCGLTest::test_10_construct_multiple_contigs
```

Now I have a lot of "Exited" Docker containers on my machine:

```
$ docker ps -a | wc -l
1950
```

It looks like when Toil runs a Docker container, it does not delete the finished container. It could be because `toil-vg` always uses `detach=True` with `apiDockerCall`.

Toil should delete the job's containers after the job is finished, or, better yet, always do the equivalent of `docker run --rm` when running Docker containers.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-830)
┆Issue Number: TOIL-830

**Comment by w-gao** [comment]
@adamnovak It looks like we would just need to set `auto_remove=True` in `apiDockerCall()` when `detach=True` (and `remove=True, auto_remove=False` when `detach=False`) to properly remove the containers after they exit. Are you suggesting that this should be the default behavior? We might want to be consistent with docker (i.e.: only remove the container if specified by the --rm flag). Though, it would also make sense to clean up everything after a Toil job is finished.

**Comment by adamnovak** [comment]
That sounds about right. I would suggest that removing be the default behavior, even though it's not the default with the Docker command on the command line. It's really the only behavior that makes sense for running containerized commands as part of a workflow, unless you want to break into a dead container to debug something somehow.
