### ISSUE TITLE
Implement batch creation of jobs and files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#351]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-311)
┆Issue Number: TOIL-311

**Comment by hannes-ucsc** [comment]
Depends on #355

**Comment by hannes-ucsc** [comment]
Post-poned until immutability is implemented for job stores.

**Comment by hannes-ucsc** [comment]
Currently worked around in toil-scripts/lib

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
