### ISSUE TITLE
pip install toil-cwl-runner should work

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3566]
┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-879)
┆Issue Number: TOIL-879

**Comment by mr-c** [comment]
I made https://pypi.org/project/toil-cwl-runner/ to prevent typo-squatting. Happy to add @DailyDreaming @adamnovak as owners and then you can remove me or demote me to a maintainer.

**Comment by DailyDreaming** [comment]
@mr-c Oh, awesome idea!  We should probably do the same for toil-wdl-runner.  Yes, please add @adamnovak and I as owners!  I don't mind you remaining an owner, unless you want to relinquish responsibility for it.  Thanks for doing this!

**Comment by mr-c** [comment]
> Yes, please add @adamnovak and I as owners! 

I found https://pypi.org/user/adamnovak/ What is your pypi.org username, @DailyDreaming ?
