### ISSUE TITLE
Add back `addBatchSystemFactory` feature for workflow-supplied batch systems

### ISSUE THREAD

**Issue by multimeric** [DataBiosphere/toil#3618]
I'm trying to update `toil-container` for recent versions of Toil. It seems that in maybe version `5.0.0` the `addBatchSystemFactory` function was removed. It's easy enough to recreate, but does this suggest there is a better way to add to the batch systems registry?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-902)
┆Issue Number: TOIL-902

**Comment by multimeric** [comment]
Specifically it was this commit: https://github.com/DataBiosphere/toil/commit/e8dac0218829cefd3a95ba4e83110446b3eb7798#diff-9bb3555241fd8ef74577b7acfc10c32c02f124c5dc6858ed93217b7fec37a1cb

**Comment by mr-c** [comment]
Did you see https://github.com/DataBiosphere/toil/pull/3314/files#diff-9bb3555241fd8ef74577b7acfc10c32c02f124c5dc6858ed93217b7fec37a1cbR61 ?

**Comment by multimeric** [comment]
Yes so the commit above is from that PR, but I can't find any explanation behind why this API was deleted or if there is a new alternative.

**Comment by adamnovak** [comment]
It looks like we never really documented `addBatchSystemFactory` or the batch system plugin system; there was no docstring on the function explaining what it was supposed to do, let alone that user code was supposed to use it. Nobody who was active on the project in 2016 when #1392 was added was still around in 2020 when @DailyDreaming simplified that function away.

If you're actually using it @multimeric we can add it back, with a docstring and a test to make it clear that this is actually a public-facing feature and not a stub bit of code that we forgot to call from anywhere.

I think the workaround would be to go get `toil.batchSystems.registry.BATCH_SYSTEM_FACTORY_REGISTRY` and `toil.batchSystems.registry.BATCH_SYSTEMS` and add your batch system into those by mutating them yourself. But those are even less of a public API than the old way was.

**Comment by multimeric** [comment]
It's not me that's using it, but rather https://github.com/papaemmelab/toil_container. But yes I think it might be helpful to have a public API function for adding batch systems rather than just mutating the data structures, just so that we can target it with unit tests to ensure that it's stable.
