### ISSUE TITLE
`linkImports` seems to be on by default, also no option to hard link?

### ISSUE THREAD

**Issue by multimeric** [DataBiosphere/toil#3620]
I've noticed that, for a Python workflow (not CWL), using `file_store.importFile()` will by default link the input file from the original location instead of copying it. This should probably be documented, as this breaks under Docker which can't use symlinks. This is defined as a default here: 
https://github.com/DataBiosphere/toil/blob/3ff4acd0da8911c1751b451916b5fea3758e7ac2/src/toil/batchSystems/options.py#L67

In addition, I note that this flag (`--linkImports`/`--noLinkImports`) only lets you choose between symlink imports and copy imports: https://github.com/DataBiosphere/toil/blob/3ff4acd0da8911c1751b451916b5fea3758e7ac2/src/toil/jobStores/fileJobStore.py#L279-L285
 Of course I don't want to symlink if I'm using Docker, but are hard links a possibility here?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-904)
┆Issue Number: TOIL-904

**Comment by adamnovak** [comment]
In #3795 we fixed an issue where hardlinks-to-symlinks would be given to file store clients that couldn't accept symlinks, which caused trouble passing paths to docker containers.

With that fix, `readGlobalFile` should be able to always produce a non-symlink that you can pass to a Dcoker command, whether or not the file is in the job store as an imported symlink. I believe, if possible, it will hardlink through to the original imported file, if it is on the right device.

@multimeric Are you somehow in a situation where some Toil components can see the symlink destination and other Toil components are containerized differently and can't? Or would the fix in #3795 have solved your problem?

If having symlinks in the job store is still a problem for you, even if file store readers that can't tolerate symlinks are protected from seeing them, can you describe your setup a bit more and maybe give an example workflow that illustrates how the symlinks are a problem?

**Comment by multimeric** [comment]
I assume I was just importing the file from outside the workflow which was a symlink, and then running a dockerized task using that file as a mount. So yes, toil itself would be able to see the destination of the symlink, but when it mounts the symlink into the container it would break.
