### ISSUE TITLE
Parallelize CWL workflow over multiple instances on AWS.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3638]
Forwarding an old biostars issue: https://www.biostars.org/p/448085/ so that we can address it here.

The current suggested hack to make this work with CWL seems to be to set `coresMin` equal to the instance size.  I think we can do a bit better in terms of making this straight forward for the user.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-916)
┆Issue Number: TOIL-916

**Comment by adamnovak** [comment]
I think the main ask here might be for a way to get a request from CWL through to the backing scheduler that a task have an instance all to itself, regardless of job size? But also it doesn't look like the person asking for that actually wants that; I think they probably don't have a good reason not to just specify job size and let jobs be scheduled one or a few to a node depending on node size, like we usually do.

So in the absence of a clearer ask from someone who really wants a one-job-per-node feature for an articulated reason, I am going to close this; users should set CWL requirements to what their jobs need and everything should Just Work.
