### ISSUE TITLE
Pass additional options to docker in toil-cwl-runner

### ISSUE THREAD

**Issue by pmiddend** [DataBiosphere/toil#3639]
This is first a question and then a request: is there an option or environment variable in toil to pass additional parameters to docker? Our Docker environment is configured so that bind-mounting directories doesn't work by default, only if you pass some additional parameters.

Note that I'm _not_ asking for `TOIL_CUSTOM_DOCKER_INIT_COMMAND`, I actually want to run `docker $mycustomargs --toil-args`.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-917)
┆Issue Number: TOIL-917

**Comment by mr-c** [comment]
Hello @pmiddend 

No, that doesn't exist. Can you share the needed options? I would like to understand them better.

**Comment by pmiddend** [comment]
Absolutely, although I am myself in the process of understanding this. :)

So when I run toil without any modifications, I get this error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/pmidden/workflow-research/slurm/workdir/node-c9b69d57-0096-4045-8e01-9aeae7d1586d-dcf7ea29-1e17-4226-a89b-c753b0dbb4e2/tmpv2nsr3c2/eea4fd0a-e20c-47e2-8542-11f86dcef682/tb8z7uaa_/tmp-outan5417gw" to rootfs at "/ebajSx" caused: stat /home/pmidden/workflow-research/slurm/workdir/node-c9b69d57-0096-4045-8e01-9aeae7d1586d-dcf7ea29-1e17-4226-a89b-c753b0dbb4e2/tmpv2nsr3c2/eea4fd0a-e20c-47e2-8542-11f86dcef682/tb8z7uaa_/tmp-outan5417gw: permission denied: unknown.
```

And I see that toil passes a few `mount=type=bind` options (for each input file), as well as `--workdir=/ebajSx` and `--user=37383:3512` to `docker` (37383 being my user ID, not sure where 3512 is coming from).

To make this work on our cluster, I have to pass in:

```
docker run ... -u $(id -u):$(id -g) --userns=host --security-opt no-new-privileges ...
```

It's clearly some sort of permissions issue between the user in the Docker container and the host. But it's a bit messy.

**Comment by mr-c** [comment]
> not sure where 3512 is coming from

`3512` should be your group id https://github.com/common-workflow-language/cwltool/blob/d91e812e8aafe58692991f04cbeeeb9b823cf7bc/cwltool/docker.py#L391

> To make this work on our cluster, I have to pass in:
> 
> ```
> docker run ... -u $(id -u):$(id -g) --userns=host --security-opt no-new-privileges ...
> ```
> 
> It's clearly some sort of permissions issue between the user in the Docker container and the host. But it's a bit messy.

Is your container public? I'd like to take a look at it

In general, yes, we could make this happen. But if there is a way to detect or avoid this situation then I would prefer that.

**Comment by pmiddend** [comment]
You're right about the group id, of course...

The container is, sadly, not public. As you might have guessed, this has licensing issues. The container is pretty simple though: it's based on `debian:unstable-slim` and just extracts a pre-downloaded software-package. The important part is that this software package contains thousands of tools and they need a ton of environment variables to work. So there's a little bash script that you're supposed to `source` before you call a program from the suite.

I'm completely understand your point of not adding unnecessary customization points to the software. But I'm not sure how to fix the issue otherwise.

Singularity doesn't seem to be an alternative. toil calls `singularity exec`, circumventing my `ENTRYPOINT` that sources the initialization script.

**Comment by mr-c** [comment]
oh no, not `ENTRYPOINT` again :-)

Can you obviate the need for your script by setting those environment variable as part of the image itself?

We discourage the use of ENTRYPOINT for a variety of reasons: https://www.commonwl.org/v1.1/CommandLineTool.html#DockerRequirement → https://f1000research.com/articles/7-742/v2#d4828e881

**Comment by pmiddend** [comment]
Ah, do I see a mountain of threads and discussions about this issue in the subtext of your reply? :)

Since I am out of alternatives, I will try to do just that. It feels like unnecessary "decompilation" of this nice, self-contained Docker image and the software suite, but there you go.

**Comment by mr-c** [comment]
> Edit: PS: And using Docker would be my preferred way to do things - the image is already 2GiB, converting this to Singularity adds another few seconds to the runtime. ;)

FYI: There is a cache for converted Singularity images! You probably want to set `CWL_SINGULARITY_CACHE` to a shared path, though

**Comment by mr-c** [comment]
@pmiddend were you able to implement the workaround?

**Comment by pmiddend** [comment]
Well, what I did was get rid of entrypoint and use singularity and then it "worked". But Docker is still a no-go for me. I guess I can reopen the issue if it comes up again and keep the issue list cleaner. :)
