### ISSUE TITLE
"CWL in Toil", usage of jobStore

### ISSUE THREAD

**Issue by pmiddend** [DataBiosphere/toil#3640]
I took a look at:

https://toil.readthedocs.io/en/latest/running/cwl.html

Which uses `--jobStore my_jobStore` and describes it as: "Path to a folder that already exists, which will contain the Toil jobstore and all related job-tracking information."

However, when I pass an existing path, I get this error:

```
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store '/.../jobstore' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
```

Just to be clear, do you mean the _parent_ path has to exist, then?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-918)
┆Issue Number: TOIL-918

**Comment by mr-c** [comment]
> Just to be clear, do you mean the _parent_ path has to exist, then?

Yes, this is a confusing message. Thanks for pointing this out.
