### ISSUE TITLE
Support CWL Directory inputs from S3 URLs

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3643]
Good Morning All,

Hoping to get some guidance regarding using S3 buckets with Toil. 

In particular, we are trying to store input files (some set of input data) in S3, and pass in the S3 URI as part of the toil-cwl-runner command. As part of trying this, we have also run into some questions surrounding permissions needed for the S3 bucket. Here is the example command that we are running:

`toil-cwl-runner --jobStore <jobStore> <s3 pipeline.cwl file> --ometiff_directory <s3 link to the input directory>`

Here are the steps we used to debug, and the issues we've run into:

- s3 pipeline.cwl file
-   Unable to use the s3 URI. Rather, had to use the full HTTPS URL to have this function.
-   Had to set this object as being globally public, despite having launched the toil-cluster with the same account that created the s3 bucket.

- s3 link to the input directory
-   Haven't been able to get this functional. When the CWL pipeline attempts to collect the input files, we receive the following error:
- `docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist:`

Thank you in advance for any help with trying to get this nailed down!

Best regards,

Juan

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-920)
┆Issue Number: TOIL-920

**Comment by mr-c** [comment]
Dear Juan,

Thanks for your issue. The Toil Devs are working on adding proper support for S3 (also in the CWL input object), probably via the `ToilFsAccess` object: https://github.com/DataBiosphere/toil/blob/7ab54194adfe3866c758ba11b63648c23f95b8ff/src/toil/cwl/cwltoil.py#L684

**Comment by jpuerto-psc** [comment]
@mr-c - Thanks for the information here! Is this something that might be added in the near future, or is this more of a long term thing? Might be worth updating the documentation, this blurb is a bit confusing:

![image](https://user-images.githubusercontent.com/68066250/122073525-7aa84980-cdc6-11eb-8674-7fefa2e67996.png)

**Comment by mr-c** [comment]
@jpuerto-psc we're on the CWL video chat now, could you join us? https://meet.jit.si/cwl

**Comment by mr-c** [comment]
Summary from the call: toil-cwl-runner might not support s3 URIs for `Directory` types yet; @DailyDreaming doesn't think it would be too hard to add

**Comment by adamnovak** [comment]
#3652 brought in proper support for CWL on the AWS JobStore, and stopped just assuming all CWL Files and Directories were local paths. Is your workflow working any better after that @jpuerto-psc?

@mr-c Is `cwltool` responsible for doing the enumeration of files in the S3 directory and handing them off to Toil for import? Toil doesn't itself have a concept of importing a directory, just a file.

If the S3 URL is making it into just a CWL Directory object without anyone ever enumerating and importing the files, we might be being asked to pull from the input S3 location in the individual workers. That could be implemented, but we'd need to add S3 URL support in a few places in `toil-cwl-runner.py` where currently we only support I think `file`, `http(s)`, and `toilfile/toildir`

**Comment by jpuerto-psc** [comment]
@adamnovak I have been `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:5.4.0a1-0339197e80ba1083e1d772cd18629efc4f670c03-py3.7` as you had suggested to get this working. I haven't tested with the latest release yet.

**Comment by adamnovak** [comment]
That's not in any real releases yet, but it is merged in as part of #3652, so it should be in the next release. I'm going to close this, since it should be fixed.

**Comment by DailyDreaming** [comment]
@jpuerto-psc @adamnovak I'll do a release either tonight or tomorrow.

**Comment by mr-c** [comment]
Can someone help me make a test for this?
