### ISSUE TITLE
Allow specifying arbitrary tags for AWS resources created by workflows

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3653]
Good Morning Toil Team,

Wanted to reach out to see if there were any additional AWS Tagging options beyond the "Owner" tag? Having the option to apply misc tags to resources spawned by toil-cwl-runner would allow us to track our costing much more accurately.

Best regards,

Juan

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-926)
┆epic: AGC
┆friendlyId: TOIL-926

**Comment by DailyDreaming** [comment]
@jpuerto-psc Yes, I think that that would be an easy one to add.  Will also follow up via email about assisting in general with HubMap work.

I believe also that currently tags are only applied to certain resources (buckets and EC2 instances I believe), but could be broadened.

**Comment by adamnovak** [comment]
I think we need this to fix https://github.com/aws/amazon-genomics-cli/issues/468

**Comment by adamnovak** [comment]
This was fixed in #4220.
