### ISSUE TITLE
toil-wdl-runner: 'WDLFile' object has no attribute 'strip'

### ISSUE THREAD

**Issue by varikmp** [DataBiosphere/toil#3660]
Hello,

I used the Toil (5.2.0) to execute this script https://github.com/gatk-workflows/gatk4-rnaseq-germline-snps-indels/blob/master/gatk4-rna-best-practices.wdl, but it threw out an error as below

```
Traceback (most recent call last):
  File "toilwdl_compiled.py", line 2677, in <module>
    (basename(inputBam, '.bam')))
  File "/usr/local/lib/python3.6/dist-packages/toil/wdl/wdl_functions.py", line 563, in basename
    path = path.strip()
AttributeError: 'WDLFile' object has no attribute 'strip'
```

Is there anyway that can help me fix this issue?

Thank you.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-930)
┆Issue Number: TOIL-930

**Comment by DailyDreaming** [comment]
We have a new (entirely rewritten) WDL runner, so this is no longer an error that should pop up.
