### ISSUE TITLE
Travis CI is on strike for better pay

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3674]
We migrated from .org to .com, and now we've spent the free 1000 minutes of CI runtime they give us, and they want us to pay them.

Apparently we were also paying them $250/month for DataBiosphere through April, but we stopped. I'm not sure if that was actually in use by something else in the org or if we somehow signed up and forgot about it.

We could see what it would look like to dump all the CI we can on Gitlab, though if we want to test anything on Mac we'd need to pull in Github Actions for that. Or we could pay the Travis Tax, but digging up the money from the lab admins might take a while.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-937)
┆Issue Number: TOIL-937

**Comment by DailyDreaming** [comment]
I think we should just drop travis.  The tests are supposed to be 20-30 minutes and it doesn't make sense to separate that out from gitlab unless it's free (and even then only a marginal gain).
