### ISSUE TITLE
no posted changeling for last two releases (5.4.0 & 5.3.0)

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3677]
https://github.com/DataBiosphere/toil/releases

![Screenshot_20210628-083000](https://user-images.githubusercontent.com/1330696/123590668-3a47c300-d7eb-11eb-87aa-177712f0b07a.png)

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-939)
┆Issue Number: TOIL-939

**Comment by mr-c** [comment]
@DailyDreaming Do you want help with this?

**Comment by DailyDreaming** [comment]
@mr-c Just updated this, though thanks for the offer!  Should be all up-to-date!
