### ISSUE TITLE
Batch systems stdout and stderr logs not reported back by leader

### ISSUE THREAD

**Issue by mberacochea** [DataBiosphere/toil#3678]
We used Toil + CWL and run jobs using a shared work directory when debugging to capture the batch system stdour and stderror files. Those provide really useful data to debug issues.

The latest version of Toil (5.4) is not capturing those files because there is a mismatch between the leader.py processFinishedJobs > batchsysteFilePrefix format and the format used when submitting the jobs. The regression was introduced on this commit: https://github.com/DataBiosphere/toil/pull/3438/files#diff-5261c41037d396bf86d8d39bd97eaa78a26d0f3ab08a1def595761e1bcacbfd3R366

Steps to reproduce:
- Run job on Slurm/LSF (I haven't test this on other batch systems)
- Use a shared filesystem as workdirectory
- Use --logDebug in toils parameters
- Inspect Toil log and there is not information about Slurm or LSF outputs.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-940)
┆Issue Number: TOIL-940

**Comment by adamnovak** [comment]
This seems to be fixed.
