### ISSUE TITLE
Support for WDL's gpuType: and gpuCount: runtime keys

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3738]
We now have some UCSC-side motivation to be able to use Toil to run workflows that need GPUs, in order to run @cmarkello's DeepVariant/Giraffe pipeline.

It looks like the right way to run it now might be on Terra, which supports scheduling workflows with GPU tasks if you write them in WDL and use the `gpuType` and `gpuCount` fields in each task's `runtime` section. These keys are also supported by Cromwell when running on GCP, and DNANexus can run GPU tasks written in WDL using a slightly different syntax. I don't know of any CWL runners that let you schedule a task to have access to a GPU. So we're going to start doing up the pipeline in WDL using the de facto standard syntax.

But since we're going to have this pipeline, we would really like to be able to run it on Toil in AWS, in addition to on Terra/Cromwell on GCP. So we need to:

* [x] Give Toil's WDL frontend support for `gpuType` and `gpuCount`, so it can translate them into
* [x] An internal format for `JobDescription` requirements that lets us say we need so many of such and such a kind of such and such a brand and model of GPU (which might also be a general free form requirement setup that could help with #3462), and which can be read by
* [x] Code in the `KubernetesbatchSystem` that can generate `nvidia.com/gpu: N` and `amd.com/gpu: N` requirements on Toil jobs, and label selectors to match them to nodes that have the right size/model of accelerator as requested by the job, using labels set up by
* [ ] Code in the provisioner that will be able to tell when we have a GPU instance type in a Kubernetes cluster and make sure that it comes up with the right labels, and that autoscaling groups are tagged so the Kubernetes autoscaler knows what lebels and requirements it will come up with
* [ ] More code in the provisioner, to deploy a Kubernetes Device Plugin and the relevant drivers on nodes that have GPUs. For nVidia GPUs we probably want [Google's Device Plugin](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#nvidia-gpu-device-plugin-used-by-gce), which I *think* works outside GCE and doesn't require swapping out the entire container runtime for nVidia's Docker fork.
* [x] Something in the single machine batch system to either ignore GPU requirements or work out how many of what kind of GPUs the machine has and schedule tasks appropriately.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-985)
┆Epic: GPU support
┆Issue Number: TOIL-985

**Comment by adamnovak** [comment]
@mr-c We'd also want to bind this to the CWL frontend. Do you know how CWL is looking to support specifying requirements like this? It would inform the design of how we want to represent them internally in Toil.

**Comment by mr-c** [comment]
> @mr-c We'd also want to bind this to the CWL frontend. Do you know how CWL is looking to support specifying requirements like this? It would inform the design of how we want to represent them internally in Toil.

https://github.com/common-workflow-language/common-workflow-language/issues/587#issuecomment-857731421 which links to https://dev.arvados.org/issues/17240#CWL-support is the current proposal

**Comment by adamnovak** [comment]
I broke off the Toil cluster support for GPUs into #4457 and the rest of this is done so I am going to close this.
