### ISSUE TITLE
Feature request: more informative naming for function wrapping jobs

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3744]
I make most toil jobs with `addChildJobFn()` and `addFollowOnJobFn()` rather than creating `Job` subclasses, as I find this interface much cleaner usually.  

The downside is that in the Toil logs, and in the `_toil_worker` command arguments (that I may check with `top`), every single Job created this way  is is called `JobFunctionWrappingJob`.  I'm probably wrong, but I don't think this was always the case.  But anyway, would it be possible to have a name that incorporates the name of the function that's actually being wrapped?  
Thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-988)
┆Issue Number: TOIL-988

**Comment by adamnovak** [comment]
I'm sure this is possible. We might even have had it like that in the past. I think we just need to look at the function we're wrapping and steal its name.
