### ISSUE TITLE
Make --disableCaching the default when using --batchSystem slurm

### ISSUE THREAD

**Issue by gmloose** [DataBiosphere/toil#3769]
Apparently, Toil doesn't support caching when using Slurm as batch system.
``` 
  File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/common.py", line 960, in createBatchSystem
    raise RuntimeError(f'{config.batchSystem} currently does not support shared caching, because it '
RuntimeError: slurm currently does not support shared caching, because it does not support cleaning up a worker after the last job finishes. Set the --disableCaching flag if you want to use this batch system.
```
It would make sense to disable caching be default when using Slurm, instead of burdening the user with this.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1006)
┆Issue Number: TOIL-1006

**Comment by adamnovak** [comment]
I'm going to close this; we now key on the job store type to try and guess whether caching is appropriate. Jobs that use Slurm with a file job store should have caching default to off.

**Comment by adamnovak** [comment]
I think we also enabled cleanup job election for Slurm, so you can turn caching on for it now.
