### ISSUE TITLE
Worker logs get lost with a local --workDir

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3771]
When --workDir is a directory not accessible from the leader, worker logs go there, but aren't available on the leader if something goes wrong.

> Another issue with using a "local" workdir is that logs are not copied over so it's very hard to debug if something goes wrong.

_Originally posted by @mberacochea in https://github.com/DataBiosphere/toil/issues/3758#issuecomment-909291465_

We *should* already have machinery for the worker to upload its log to the job store, but that's no help if e.g. the worker runs out of memory and gets killed by an angry cluster scheduler.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1008)
┆Issue Number: TOIL-1008

**Comment by mberacochea** [comment]
Thank you creating the issue. I've been running Toil + CWL using a shared dir for "--writeLogs" (and a small change -> https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/abstractBatchSystem.py#L369).
This allows me to check the logs (out and error ouputs)  for each job, it a great help for debugging.

Not sure how that would work for other use cases (AWS or k8s).

**Comment by adamnovak** [comment]
This issue got lost in Jira and I forgot to do it.

So far we have machinery to let the leader use a *different* workDir than the workers (#2373), but nothing for sending the logs to some other mutually-shared place.
