### ISSUE TITLE
CWL compatibility issues

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3796]
Good Morning Team,

Having some trouble with trying to run toil-cwl-runner with latest cwltool version (3.1.20210816212154):

```
root@ip-xxx:~# toil-cwl-runner --provisioner aws --jobStore aws:us-west-2:xxx cwl_workflows/salmon-rnaseq/pipeline.cwl --assay 10x_v2 --fastq_dir /tmp/hca-immune-scrnaseq
Traceback (most recent call last):
  File "/usr/local/bin/toil-cwl-runner", line 5, in <module>
    from toil.cwl.cwltoil import main
  File "/usr/local/lib/python3.8/dist-packages/toil/cwl/cwltoil.py", line 78, in <module>
    from cwltool.utils import (
ImportError: cannot import name 'convert_pathsep_to_unix' from 'cwltool.utils' (/usr/local/lib/python3.8/dist-packages/cwltool/utils.py)
```

Seems to work fine when using the cwltool version (3.0.20201203173111) that comes with the toil[cwl] install. This is an issue for us currently as our cwltool fork is currently up to date with main cwltool (3.1.2xxx).

Best regards,

Juan P.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1029)
┆Issue Number: TOIL-1029

**Comment by jpuerto-psc** [comment]
Thanks for clarifying @mr-c! In this case, is backwards compatibility maintained? I only ask because, like I said, we are using a fork of CWLtool which adds GPU support. So we would have to make sure that we have our fork synced with the version that Toil supports, if there is no backwards compatibility.

**Comment by mr-c** [comment]
> Thanks for clarifying @mr-c! 

Of course!

> In this case, is backwards compatibility maintained?

> I only ask because, like I said, we are using a fork of CWLtool which adds GPU support. So we would have to make sure that we have our fork synced with the version that Toil supports, if there is no backwards compatibility.

I'm not quite sure what "backwards compatibility" means in this context. I suggest you try to keep your fork of `cwltool` up to date with version that `toil-cwl-runner` is pinned to, just to be safe.

For example, the recent [5.5.0 release of Toil](https://github.com/DataBiosphere/toil/releases/tag/releases%2F5.5.0) is pinned to [`cwltool` version 3.1.20210922203925](https://github.com/common-workflow-language/cwltool/releases/tag/3.1.20210922203925)

Is this your fork? https://github.com/common-workflow-language/cwltool/compare/main...hubmapconsortium:docker-gpu

If so, this extension could be added to `toil-cwl-runner` which would reduce your maintenance burden. If you are feeling very motivated, you all can start implementing the proposed `CUDARequirement` in `toil-cwl-runner` which has gotten preliminary support from the CWL community for inclusion in a future version of the CWL standards. (Proposal: https://github.com/common-workflow-language/common-workflow-language/issues/587 ; current specific syntax under discussion: https://dev.arvados.org/issues/17240#CWL-support )

**Comment by adamnovak** [comment]
I'm going to close this; we have Toil warn if it doesn't see the "right" cwltool version now, and while we sometimes can run OK with other versions, we hook into the guts of cwltool enough that we don't really use any interface that the cwltool versions guarantee to be stable.

Toil now also has some support for CUDARequirement in CWL, for some batch systems.
