### ISSUE TITLE
5.6.0 with the recent LSF, Slurm, CWL fixes?

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3840]
In a couple of weeks?

I volunteer to make the release.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1053)
┆Issue Number: TOIL-1053

**Comment by DailyDreaming** [comment]
@mr-c That works for me, though we use semantic versioning with the format: `MAJOR.MINOR.PATCH`, so the next release should be 5.6.0: https://semver.org/

MAJOR: Breaking changes.
MINOR:  Backwards compatible changes.
PATCH:  Generally a hot-fix to a version that was released and needs patching quickly enough that the release only includes that fix.  In practice, bumping this number is rare for us.

I'll bring this up with Adam, but releases have been ad-hoc, so we should probably include some kind of schedule in the release instructions: https://github.com/DataBiosphere/toil/wiki/Toil-Release-Instructions

I'm going to propose at least once every month, but see no reason why releases can't be made more frequently, if you, say, wanted to mint a new release tomorrow.

**Comment by adamnovak** [comment]
@mr-c I think we decided that a 5.6.0 would be fine.
