### ISSUE TITLE
Toil's `global_mutex` needs to tolerate `OSError: [Errno 116] Stale file handle` in its locking code 

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3867]
The Toil `global_mutex` is designed to work on a lock file that is deleted when the lock is released, so as not to require a separate cleanup step.

To tolerate this, when we open and lock the file, we check to make sure that the file is still in the directory at the name we opened it with. If not, we managed to catch a pre-existing lock file exactly as it was being deleted, and we didn't try to lock it until the previous holder had unlocked it, and we're holding a worthless lock on an invisible file.

https://github.com/DataBiosphere/toil/blob/9126a4e953b5e6225cae3d524f057bad971db554/src/toil/lib/threading.py#L339-L344

But that's only how it works on normal filesystems. On NFS, instead of letting us hold a deleted file open, the file handle goes stale, and when we try to check if the file is in place still we get an error.

We need to catch that error and treat it the same as the file having been removed (since that's what it indicates), and go back to the beginning of the locking loop.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1061)
┆Issue Number: TOIL-1061

**Comment by gmloose** [comment]
I think I can safely claim that `global_mutex` is broken when used on an NFS file system. Besides regular `OSError: [Errno 16] Device or resource busy` and `OSError: [Errno 116] Stale file handle` errors, I caught the following trace-back yesterday:
```
        Traceback (most recent call last):
          File "/project/rapthor/Software/rapthor/bin/_toil_worker", line 8, in <module>
            sys.exit(main())
          File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/worker.py", line 710, in main
            with in_contexts(options.context):
          File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
            return next(self.gen)
          File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/worker.py", line 684, in in_contexts
            with manager:
          File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/batchSystems/cleanup_support.py", line 87, in __enter__
            self.arena.enter()
          File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/lib/threading.py", line 455, in enter
            fcntl.lockf(self.lockfileFD, fcntl.LOCK_EX) # type: ignore
          File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
            next(self.gen)
          File "/project/rapthor/Software/rapthor/lib/python3.6/site-packages/toil/lib/threading.py", line 373, in global_mutex
            os.unlink(lock_filename)
        FileNotFoundError: [Errno 2] No such file or directory: '/project/rapthor/Share/prefactor/L667520/working/toil-mutex-820dc778-1c66-4891-9f18-219ee085fdf5-cleanup-arena-lock'
 ```
This traceback is very worrysome. The code assumes that it has sole ownership over the file, because it's supposed to own an exclusive lock on it, but the file is gone when the call to `os.unlink()` is done.

Furthermore, when googling for `lockf nfs` you can find many links that tell you that `lockf` and `flock` don't work on NFS. See for example https://stackoverflow.com/a/38239456/16350552. The package [flufl.lock](https://pypi.org/project/flufl.lock/) may provide a possible solution to reimplement `global_mutex`.

**Comment by adamnovak** [comment]
We've been getting around brokenness in `global_mutex` on NFS by never putting it there (with the coordination directory refactor), but now we're wanting to use it to synchronize access to an NFS-shared Singularity image cache directory, to avoid multiple simultaneous Singularity pulls of the same image, which Singularity can't handle.

We've managed to reproduce the amazing vanishing lock file in our environment, and I thought it was maybe some odd but still safe quirk of how NFS handles deleting a file that is currently locked. But maybe it's actually just common for NFS to pretend that `fcntl` locking works? Or to not let you delete a locked file in a way that prevents other people from locking it while you do it?

I don't think we can reimplement `global_mutex` on top of `flufl.lock`, because those locks are timeout-based and can only be held for so long in real time, whereas I don't think we require a similar guarantee from `global_mutex` users. We *might* be able to introduce one? Or maybe have some way for a thread in the process to ping the lock to keep it alive?
