### ISSUE TITLE
`toil kill` doesn't cancel batch system jobs

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3917]
As noted in https://gitter.im/bd2k-genomics-toil/Lobby?at=618eb0f3fb3dcd4e88818830, `toil kill` doesn't seem to be using the normal shared file machinery to find `pid.log`, and when we reorganized where shared files live, it lost the ability to find it.

We should change `toil kill` to use the normal shared file read code, so it will always be able to find the files it is looking for, no matter where we store them.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1087)
┆friendlyId: TOIL-1087

**Comment by adamnovak** [comment]
We might also think about adding a test for `toil kill`.

**Comment by kannon92** [comment]
What work would be needed to expand toil kill so that it kills spawned processes also?  

https://github.com/DataBiosphere/toil/blob/master/src/toil/utils/toilKill.py#L44

The above code uses the pid.log to kill the parent process but it doesn't go out and kill the spawned jobs.  It works for single machine but for batch systems, I think we have to tell the batch system jobs to die.

**Comment by adamnovak** [comment]
The easy way to kill the spawned jobs would be to send SIGTERM instead of SIGKILL. The leader already knows how to clean up its jobs, and it will do so if it can intercept the signal and shut down cleanly, as long as it hasn't gone rogue.

I'm not sure that the hard way (kill -9 the leader and then somehow find and stop its jobs) is possible. For one thing, I don't think we record what batch system is in use in the job store. For another, we wouldn't be able to find all the jobs reliably. Some of the batch systems (like Kubernetes) identify their jobs by giving them a randomly-generated, per-run prefix, which isn't saved. Others just keep track of the IDs from the backing scheduler in memory, which they also don't save to the job store.

For single machine, we could have all the child processes in a process group with the leader, but instead we've chosen to organize each job as its own process group, to let the *leader* reliably terminate a job and all its children.

**Comment by adamnovak** [comment]
It does look like `toil kill` *wants* to be able to resume a job store and then resume a batch system and have some notion of the running jobs, where we have that comment that says it doesn't work anymore. We could *try* letting all the batch systems journal to the job stores, if we really need to be able to clean up mostly cleanly after a broken leader.

**Comment by kannon92** [comment]
So for my project, a feature request is the ability to stop workflows in our cloud platform and in our hpc platform.  I believe I fixed toil kill to find the right pid.log and I added a unit test for toil kill.  I can open a PR for this but I think there may be more issues.  In my project, I then use the slurm cli to clean up any existing jobs that the leader spawned.  I found that if I don't kill the parent process, the leader will keep spawning jobs.  

I tried to change the os.kill for the parent process to be SIGTERM but I don't think that is killing the children processes correctly.  Do you think we should have this as a separate issue?

I could open a PR that fixes the toil kill and adds a test into the CI for toil kill.  And we can think a bit more about the other problem.

**Comment by kannon92** [comment]
I have https://github.com/DataBiosphere/toil/pull/3932 that should fix toil kill.  But I still think my above point is not addressed.

**Comment by mr-c** [comment]
#3932 was merged via #3941
