### ISSUE TITLE
`ResourceRequirement` on a CWL `CommandLineTool` is not being respected by Toil if the tool is part of a workflow.

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3926]
As mentioned in https://gitter.im/bd2k-genomics-toil/Lobby?at=6194522f10df16294528c288, apparently `ResourceRequirement` on a CWL `CommandLineTool` is not being respected by Toil if the tool is part of a workflow.

_Originally posted by @adamnovak in https://github.com/DataBiosphere/toil/issues/3919#issuecomment-971820069_

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1095)
┆friendlyId: TOIL-1095

**Comment by mr-c** [comment]
Already reported at https://github.com/DataBiosphere/toil/issues/3920 ; thanks!
