### ISSUE TITLE
Renamed parameter, scaling breaks with --metrics

### ISSUE THREAD

**Issue by mhpopescu** [DataBiosphere/toil#3943]
Variable `nodeType` was renamed to `instance_type`, so this function is called with the wrong parameter name and it breaks:
https://github.com/DataBiosphere/toil/blob/52745e400a825abd6eb05b8719e674db77926258/src/toil/common.py#L1448
Called from:
https://github.com/DataBiosphere/toil/blob/52745e400a825abd6eb05b8719e674db77926258/src/toil/provisioners/clusterScaler.py#L512-L515

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1101)
┆friendlyId: TOIL-1101

**Comment by mr-c** [comment]
@mhpopescu Thanks for the report. Are you going to send a fix in? Looks like we need a test to trigger this code path..

**Comment by mhpopescu** [comment]
Created a PR. I'm not sure how to test this

**Comment by adamnovak** [comment]
This should be fixed now!
