### ISSUE TITLE
This line throws a bunch of logging complaints whe running `cwltoil`

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3950]
https://github.com/DataBiosphere/toil/blob/5494761fca1891a5e2affafbe66839b7979e2cf2/src/toil/cwl/cwltoil.py#L3431

We're missing a `%s`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1104)
┆friendlyId: TOIL-1104

**Comment by mr-c** [comment]
Already fixed in https://github.com/DataBiosphere/toil/pull/3945
