### ISSUE TITLE
`TOIL_S3_HOST` only applies to imported files

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#3959]
Here's the only place we use it:
https://github.com/DataBiosphere/toil/blob/7db3435bfb76d329f02b5eeb5677df972684d66a/src/toil/jobStores/aws/jobStore.py#L494

We don't use it for exports, and we don't use it for the actual job-storing part of the job store, and we don't use it for the buckets for the provisioner (although arguably there it would just break things).

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1108)
┆friendlyId: TOIL-1108

**Comment by Hexotical** [comment]
Already completed
