### ISSUE TITLE
when will v5.6.0 be released

### ISSUE THREAD

**Issue by jixinchi** [DataBiosphere/toil#3995]
The `toil server` feature is not in v5.5.0.

When will v5.6.0 be released, and will the `toil server` feature be release in v5.6.0?

Thanks!

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1123)
┆friendlyId: TOIL-1123

**Comment by DailyDreaming** [comment]
@jixinchi I'll do a release today.

**Comment by DailyDreaming** [comment]
@jixinchi All systems should be go (although the appliance images are still building, and should be finished in an hour or two).
