### ISSUE TITLE
Feature Request: Allow a user to access logs of container while workflow is running

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#4005]
Hello,

My team is interesting in running long running workflows using toil.  I currently capture logs of workflows as outputs.  This is needed to be able to view logs once the workflow is running.

I use the cwltoil and I primiarly use the slurm batch system.

But, this does not allow a user to view or toil logs as the workflow runs.  

Ideally, I would like a user to be given path so they could view the logs as they are rewritten out.  

Is this possible?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1128)
┆friendlyId: TOIL-1128

**Comment by adamnovak** [comment]
This was fixed in #4031, as long as one only wants to run on a shared filesystem.
