### ISSUE TITLE
Any reason why "futures" is a requirement?

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#4028]
It's listed in [requirements-aws.txt](https://github.com/DataBiosphere/toil/blob/95982020dd263ed2b3ad5c41cd99fee19a6bdb30/requirements-aws.txt#L4)
```
futures>=3.1.1, <4
```
And seems to be behind this [Cactus CI error](https://ucsc-ci.com/comparativegenomicstoolkit/cactus/-/jobs/8808) that I'm getting all of the sudden (via Cactus's [Dockerfile](https://github.com/ComparativeGenomicsToolkit/cactus/blob/4259ad72fce9c1e81c5c7f13b2dd3bb8619eb4dc/Dockerfile#L46-L48)):
```
ERROR: Could not find a version that satisfies the requirement futures<4,>=3.1.1; extra == "all" (from toil[all]) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
```
Where it seems that pip just stopped wanting to make wheels of it altogether.  I'm guessing this may have something to do with [futures](https://pypi.org/project/futures/) being python 2-specific?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1139)
┆friendlyId: TOIL-1139

**Comment by mr-c** [comment]
There's a fix pending over at https://github.com/DataBiosphere/toil/pull/4025/commits/9041c54d9802add8973e31eddd8ba33529218f94

**Comment by glennhickey** [comment]
Great, thanks @mr-c. I guess this problem was triggered by pip version 22 which was [just released yesterday](https://pypi.org/project/pip/#history), so the simple workaround in the meantime is to use an older version of that (where futures installs fine).
