### ISSUE TITLE
Enable debugs logs of cwltool from toil

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#4040]
Hello,

In my recent PR, I found enabling debug logs into cwltool to be very useful even when running tool.

I was thinking I can set debug before using cwltool.  I did this on a local branch and it worked.

would this be of interest to developers?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1144)
┆friendlyId: TOIL-1144

**Comment by mr-c** [comment]
Hello @kannon92 . Do you mean `--logDebug` or something else?

**Comment by kannon92** [comment]
I more mean that when you run `cwltool --debug` you can get logs in cwltool.  

But when you do `toil-cwl-runner --logLevel Debug` that doesn't enable logging in cwltool.  I'm not sure about logDebug.

I didn't see anything in code that sets the debug arg in runtime context for cwltool

**Comment by mr-c** [comment]
I think it used to

Probably need to move
https://github.com/DataBiosphere/toil/blob/e3d0df04ab8e362cccfb490d6cbaf36f5c54db9d/src/toil/cwl/cwltoil.py#L3327

to be before https://github.com/DataBiosphere/toil/blob/e3d0df04ab8e362cccfb490d6cbaf36f5c54db9d/src/toil/cwl/cwltoil.py#L3253

**Comment by kannon92** [comment]
After doing some testing, I think I was mistaken.  I do see debug logs from cwltool if I use debug logging from toil.  I will close this issue.
