### ISSUE TITLE
some slurm batch systems need a separate queue for single vs multi-core jobs

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#4097]
https://github.com/DataBiosphere/toil/pull/4096#issue-1233675992

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1167)
┆friendlyId: TOIL-1167

**Comment by adamnovak** [comment]
Looks like the bug was that Toil couldn't support sending to multiple queues according to job core count, and that feature was added in #4096.
