### ISSUE TITLE
SLURM jobs failing, does _toil_worker need to be in path?

### ISSUE THREAD

**Issue by pmiddend** [DataBiosphere/toil#4100]
I'm trying to run a job on SLURM and am getting this error:

```
[2022-05-17T11:59:05+0200] [MainThread] [W] [toil.leader] Log from job "kind-setup/instance-qhcr8c72" follows:
=========>
        /var/spool/slurmd/job11051241/slurm_script: line 4: _toil_worker: command not found
<=========
```

I'm running:

```
TOIL_SLURM_ARGS="-t 1:00:00 --partition cfel-cdi" python sort.py file:jobStore --batchSystem slurm --disableCaching --logDebug --workDir $(pwd)/worker-tmp
```

Where I'm in a virtual environment with toil installed. The error message indicates that we need `_toil_worker` in the `PATH` in order to run it. Is it possible to circumvent this? I wouldn't want to globally install Python dependencies in order to use toil.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1169)
┆friendlyId: TOIL-1169

**Comment by adamnovak** [comment]
Have you tried installing Toil in a `virtualenv`? When it sees that it is running from a `virtualenv` it makes sure to invoke the worker with the right Python for the `virtualenv`. There's [a flag to turn that virtualenv-detection off](https://toil.readthedocs.io/en/latest/appendices/environment_vars.html?highlight=TOIL_CHECK_ENV#environment-variables) and the feature is explained there.

**Comment by mr-c** [comment]
Can you try adding `--export=ALL` to your `TOIL_SLURM_ARGS`? That fixed this problem for me in the past.

**Comment by pmiddend** [comment]
> Can you try adding `--export=ALL` to your `TOIL_SLURM_ARGS`? That fixed this problem for me in the past.

Thanks @mr-c, that did the trick, and I kind of understand what the problem was (also by looking at @adamnovak's reply). So it's either using `virtualenv` to "detector the environment or lets the user export it in a batch-system specific manner. Cool! Two questions though (if it's okay to ask this here):

1. Why `virtualenv` and not `venv`? Historical reasons?
2. Shall one put this `--export=ALL` solution somewhere in the documentation, maybe? Or is it there and I was too impatient to find it?

**Comment by mr-c** [comment]
> > Can you try adding `--export=ALL` to your `TOIL_SLURM_ARGS`? That fixed this problem for me in the past.
> 
> Thanks @mr-c, that did the trick, 

great!

> 2. Shall one put this `--export=ALL` solution somewhere in the documentation, maybe? 

Yes, that would be a welcome contribution! Some SLURM installations default to this, some don't need it. The default may have changed in a recent version of SLURM as well, that could be investigated.

**Comment by adamnovak** [comment]
>     1. Why `virtualenv` and not `venv`? Historical reasons?

We aren't using the `virtualenv` command line tool to detect virtual environments; maybe I shouldn't be backticking it if I just mean the concept.

The virtual environment detection code also supports Conda environments. I'm not sure if `venv` builds them any differently than `virtualenv` does, but we probably want to detect virtual environments built by any method:
https://github.com/DataBiosphere/toil/blob/95982020dd263ed2b3ad5c41cd99fee19a6bdb30/src/toil/__init__.py#L117-L124
