### ISSUE TITLE
Toil jobs get stuck if `TOIL_KUBERNETES_HOST_PATH` doesn't exist on a node

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4145]
When Toil tries to mount the `TOIL_KUBERNETES_HOST_PATH` into its containers, it mounts it with a type of `Directory` and not `DirectoryOrCreate`.

https://github.com/DataBiosphere/toil/blob/88d73fbfd42ec22fd692940fc1efdacaf53b1b76/src/toil/batchSystems/kubernetes.py#L477-L478

This causes the pods to sit in `ContainerCreating` indefinitely, waiting for the directory to come into existence, if they get scheduled on a node that doesn't have the directory already.

The Kubernetes batch system itself doesn't notice this or time out the `ContainerCreating` pods, and so in our CI tests the whole Toil execution will be timed out, and killed without getting a chance to clean up its pods.

This is causing Toil CI failures, and also causing one of out Kubernetes nodes to become clogged up with these stuck, abandoned Toil pods.

We should change the Kubernetes batch system to time out pods that stay in ContainerCreating for some notion of "too long". We should also probably use `DirectoryOrCreate` as our hostpath volume type, because we probably want to be able to use this directory on our GI Kubernetes cluster even if nobody has gone around to all the nodes creating it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1188)
┆friendlyId: TOIL-1188

**Comment by mr-c** [comment]
Likely fixed in #4146
