### ISSUE TITLE
CWL: run all ExpressionTools on the leader

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#4157]
[`ExpressionTool`](https://www.commonwl.org/v1.2/Workflow.html#ExpressionTool)s just manipulate data structures; no actual data movement nor computation happens

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1193)
┆friendlyId: TOIL-1193

**Comment by adamnovak** [comment]
Expression tools are still allowed to use a full Node environment for their JS, which means they can call out to the filesystem and expect to see the files they asked for staged, right? Or is that just a cwltool implementation detail and not part of the spec?

Are they also specced to do only trivial computation? Or is a workflow with an expression tool that needs a gigabyte of memory to compute something allowed?

If the expression tools aren't allowed to see the disk and are only supposed to be working with stuff injected into their namespace, then this ought to be possible. We'd just have to figure out how to set up the File and Directory object inputs and their listings, and outputs, without anything actually needing to be on disk.

**Comment by mr-c** [comment]
> which means they can call out to the filesystem and expect to see the files they asked for staged, right?

The CWL expressions run in a very limited context; the `File` objects won't have `path`s (just Toil location URis); though the first 64KiB of contents will be loaded for any inputs that have `loadContents: true` set.

> Are they also specced to do only trivial computation? Or is a workflow with an expression tool that needs a gigabyte of memory to compute something allowed?

Yes, from the [standard](https://www.commonwl.org/v1.2/Workflow.html#ExpressionTool): "It is meant to be used sparingly as a way to isolate complex Javascript expressions that need to operate on input data and produce some result; perhaps just a rearrangement of the inputs. No Docker software container is required or allowed."

> We'd just have to figure out how to set up the File and Directory object inputs and their listings, and outputs, without anything actually needing to be on disk.

That might already be done; maybe more of a matter of teaching https://github.com/DataBiosphere/toil/blob/9e73170ba180e76f93b967da2271e74c64d72f53/src/toil/batchSystems/local_support.py#L38 to recognize `ExpressionTool` jobs

**Comment by adamnovak** [comment]
> the first 64KiB of contents will be loaded for any inputs that have loadContents: true set.
We probably could do this with streaming? We might have to no longer allow job stores to implement streaming by actually downloading, and make sure that none of our CachingFileStore stuff ever does that either.

We might have to change some cwltool code, because the virtual filesystem stuff we present to cwltool right now doesn't have streaming as part of its API. I can't think how cwltool is managing to do this right now without asking Toil to just download the whole file and then reading from it.

**Comment by mr-c** [comment]
Oh, I was not precise with my words. If a file is greater than 64KiB and `loadContents` is used, then that is an error; so plain downloading is probably easier than streaming
