### ISSUE TITLE
Could toil also store requested cores data for stats purposes? 

### ISSUE THREAD

**Issue by jsmedmar** [DataBiosphere/toil#4173]
I'm not aware if recent versions do this already, but it would be nice to store stats about the number of cpus requested by jobs. Doing `clock / cores` could help calculate cpu efficiency.

Thoughts?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1201)
┆friendlyId: TOIL-1201

**Comment by adamnovak** [comment]
I think the `JobDescription` tracks the `cores` requirement for each job, unless it ended up using the default for the workflow run because no explicit requirement was set.

Where would you want this information to be visible to the user, @jsmedmar? Maybe in the table from `toil stats`?

**Comment by jsmedmar** [comment]
Yes, toil stats human and json. This would be very nice!
