### ISSUE TITLE
CWL-dependency-is-standalone test fails due to CacheControl 0.12.12 release

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4212]
Yesterday [we used `CacheControl 0.12.11` and everything worked](https://ucsc-ci.com/databiosphere/toil/-/jobs/22243#L2211). Today, [we pick up the (new?) `CacheControl 0.12.12`, which fails our test for installing with the CWL extra](https://ucsc-ci.com/databiosphere/toil/-/jobs/22349#L339).

In release 0.12.12, CacheControl switched from `lockfile` to `filelock` as the optional dependency needed to make its `FileCache` work.

The pinned `schema-salad` seems to depend on `lockfile` directly, and not [the `CacheControl[filecache]` extra it ought to be using to be protected from this](https://github.com/ionrock/cachecontrol/commit/f0cd6b49e5c4215137e5c24ac0b46752f0c61e69#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R25). So now our build fails.

**Comment by mr-c** [comment]
Thanks for catching this!

release 0.12.12 of cachecontrol has been yanked

https://github.com/common-workflow-language/schema_salad/releases/tag/8.3.20220913105718 has been released to avoid this problem in the future

So toil can increase its schema-salad pin to 8.3.20220913105718 and drop the `lockfile` dep
