### ISSUE TITLE
Support the `arv:UsePreemptible` hint in CWL to allow CWL tasks on spot instances

### ISSUE THREAD

**Issue by boyangzhao** [DataBiosphere/toil#4258]
Is it possible to specify in a multi-stage workflow, consisted of multiple tasks (e.g. alignment, sort vcf, index vcf, etc), specific task to be using on-demand (non-preemptable) nodes, while others can use preemptable. This is because for very long running workflow, there are some steps that will for sure take 15+ hours to finish and because it is not using spot instances, no matter how many retries, it'll very likely be killed if using spot. But I don't want the entire workflow to be using on-demand instances, as there are many other smaller tasks fully suitable for using spot.

From the arguments (`defaultPreemptable`, `nodeTypes`, `preemptableCompensation`), they only control at the entire job level, and not to the individual task. It was mentioned in [documentation](https://toil.readthedocs.io/en/releases-3.6.x/running/cloud.html) "While individual jobs can each explicitly specify whether or not they should be run on preemptable nodes via the boolean preemptable resource requirement, ...", was this referring to specify `preemptable` in `ResourceRequirement` in the CWL? This would result in the error `invalid field preemptable, expected one of: 'class', 'coresMin', 'coresMax', 'ramMin', 'ramMax', 'tmpdirMin', 'tmpdirMax', 'outdirMin', 'outdirMax'`, as `preemptable` isn't one of the options.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1235)
┆friendlyId: TOIL-1235

**Comment by adamnovak** [comment]
Toil has support for this internally, but it's possible it isn't bound to the CWL front-end.

@mr-c, where in a CWL workflow should something like a hint that a task should run on a spot-market, preemptable node be placed?

**Comment by mr-c** [comment]
> @mr-c, where in a CWL workflow should something like a hint that a task should run on a spot-market, preemptable node be placed?

`hints`/`reqs` can be added in many places: the CWL input object, workflow level, step level, sub-workflow (and its steps, etc.), in a `CommandLineTool` ; or via an external `overrides` file with `--overrides`.

As for the syntax of such a hint, I would suggest reusing `http://arvados.org/cwl#UsePreemptible` (a.k.a. `arv:UsePreemptible`) if you only need a boolean Yes/No.

https://github.com/arvados/arvados/blob/f293f0f41c5de9623239fe2b1eb6c4ef83ae00a0/sdk/cwl/arvados_cwl/arv-cwl-schema-v1.0.yml#L389

If users need more control than that, then we can develop a custom requirement for toil.

**Comment by mr-c** [comment]
> I think cwltool does most of the parsing and namespace stuff for us, and we already have logic to look at extensions like this for GPUs, so this shouldn't be too hard to add.

Correct!
