### ISSUE TITLE
Provide suffix/prefix when creating temporary files using getLocalTempFile

### ISSUE THREAD

**Issue by ghB111** [DataBiosphere/toil#4273]
Hey hi!

Currently `AbstractFileStore.getLocalTempFile()` method creates a temporary file with default suffix `tmp` and prefix `.tmp`. It is fine as default parameters, but it may be reasonable to provide those as parameters of `getLocalTempFile()`. The problem I have encountered with it is, in my pipeline, I wrote to such temp file, and on that file I used software which relied on file extension to deduce whether the file is gzipped or not. It would be really handy to have control over suffixes for such purposes.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1241)
┆Issue Number: TOIL-1241
┆Link To Issue: https://ucsc-cgl.atlassian.net/browse/TOIL-1241

**Comment by adamnovak** [comment]
This was fixed in #4274
