### ISSUE TITLE
Support for GPU scheduling with Slurm

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4308]
As noted in https://github.com/ComparativeGenomicsToolkit/cactus/issues/887, people want to use Cactus with GPU support on Slurm, but Toil donen't yet know how to ask for GPUs on Slurm, and we don't have a GPU Slurm cluster to test with yet.

We can probably just try throwing `--gres=gpu:<count>` into the submission commands, and hope that all Slurm clusters with GPUs use that name. Which I think they might, because despite the "generic resource" name of GRES, the [documentation](https://slurm.schedmd.com/gres.html) talsk about some pretty tight integration that Slurm has with e.g. nVidia's CUDA.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1257)
┆Issue Number: TOIL-1257

**Comment by oneillkza** [comment]
It might be worth looking at the discussions the Nextflow folks had around this four years ago: https://github.com/nextflow-io/nextflow/issues/997

**Comment by oneillkza** [comment]
And yep, I think it may just be as simple as throwing `--gres=gpu:<count>` into the submission commands.

**Comment by oneillkza** [comment]
I'd be happy to give this a try on our cluster -- I have a test run of Cactus all ready to go.

I guess in the meantime I'll have to try submitting to a chunk of a node and having Cactus/Toil use the singleMachine batchSystem.

**Comment by oneillkza** [comment]
I believe @thiagogenez also has a GPU cluster at the EBI, and is interested in this functionality.

**Comment by thiagogenez** [comment]
thanks @oneillkza for letting me know about this issue.

Yes, I'm interested to see this functionality working with Cactus. 

So far, I have run Cactus on a Slrum cluster without Toil scheduling capabilities. I set Toil to use `singleMachine` approach and scheduled GPU jobs for GPU nodes using a script acting as an external scheduler.

**Comment by thiagogenez** [comment]
> And yep, I think it may just be as simple as throwing `--gres=gpu:<count>` into the submission commands.

Hi @adamnovak 
Same here with me. Just adding `--gres=gpu:4` to grab a GPU-enabled worker.

Ex: `srun --gres=gpu:4 --mem 200gb -t 30 --pty bash`

**Comment by thiagogenez** [comment]
thanks @adamnovak 

I'm interested to propose a PR to solve this issue. Will have a look. Cheers

**Comment by adamnovak** [comment]
We fixed this in #4350.
