### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by Hexotical** [DataBiosphere/toil#4318]
Support running toil with python 3.11

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1263)
┆Issue Number: TOIL-1263

**Comment by Hexotical** [comment]
Switch main from 3.9 to 3.11 too

**Comment by Hexotical** [comment]
https://github.com/benoitc/http-parser/issues/94 
Blocks 3.11, doesn't look like http-parser been's updated since 2020 either, might want to find some alternatives

**Comment by adamnovak** [comment]
This was fixed in #4646.
