### ISSUE TITLE
Python 3.10 release has incorrect version.py info; thinks it is on Python 3.9

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4339]
See https://github.com/ComparativeGenomicsToolkit/cactus/issues/911 where this is causing a problem running Cactus.

If you install Toil on Python 3.10 and look at its internal metadata:

```
docker run -ti --rm python:3.10-bullseye /bin/bash -c "pip install toil ; cat /usr/local/lib/python3.10/site-packages/toil/version.py"
```

It says it is a Python 3.9 Toil and wants to use a Python 3.9 appliance.

@DailyDreaming I think we need to re-run the release checklist for 3.10 and maybe publish a new version to fix this, making sure to regenerate `version.py` at the right point in the build process every time.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1273)
┆Issue Number: TOIL-1273

**Comment by DailyDreaming** [comment]
@adamnovak Ack, thanks for pointing it out.  Will do.
