### ISSUE TITLE
Can't `toil launch-cluster` because flatcar-linux.net is down

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4382]
Flatcar Linux has their main website on https://www.flatcar.org/ but links to release feeds hosted on flatcar-linux.net, which we fetch in Toil here:
https://github.com/DataBiosphere/toil/blob/1ccf68c8864f27670b877be980b5fde418a1f0bc/src/toil/lib/aws/ami.py#L67

Today. `flatcar-linux.net` doesn't exist in the DNS system, so trying to launch a cluster on AWS fails with an error. @Hexotical has the full log; it says something about a Socket `gaierror` because it can't resolve the domain.

We should fix Toil to better handle the inaccessibility of the Flatcar release feed; it should fail with a message saying that you need to set `TOIL_AMI_ID`, or else just skip the release feed source and try the Marketplace source, and complain at the end if nothing is found there either.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1290)
┆Issue Number: TOIL-1290

**Comment by adamnovak** [comment]
It looks like `TOIL_AWS_AMI=ami-085f581307a3a975d` in the environment should fix `toil launch-cluster` for amd64 nodes for now. I'm not sure what the right AMIs would be for ARM clusters since... the Flatcar feeds are down.

**Comment by larryns** [comment]
I tried this AMI, but it I get an error saying the image ID doesn't exist. AMI ```ami-08870dfc70c8d6fe4``` does work though, unless there's some reason not to use it?
