### ISSUE TITLE
Conda: TypeError: interpreted classes cannot inherit from compiled

### ISSUE THREAD

**Issue by weber8thomas** [DataBiosphere/toil#4394]
```
/g/korbel2/weber/miniconda3/envs/toil/lib/python3.10/site-packages/htcondor/__init__.py:49: UserWarning: Neither the environment variable CONDOR_CONFIG, /etc/condor/, /usr/local/etc/, nor ~condor/ contain a condor_config source. Therefore, we are using a null condor_config.
  _warnings.warn(message)
[2023-02-28T13:46:14+0100] [MainThread] [I] [cwltool] Resolved 'example.cwl' to 'file:///g/korbel2/weber/workspace/cwl-ashleys/example.cwl'
Traceback (most recent call last):
  File "/g/korbel2/weber/miniconda3/envs/toil/bin/toil-cwl-runner", line 10, in <module>
    sys.exit(main())
  File "/g/korbel2/weber/miniconda3/envs/toil/lib/python3.10/site-packages/toil/cwl/cwltoil.py", line 3651, in main
    tool = cwltool.load_tool.make_tool(uri, loading_context)
  File "cwltool/load_tool.py", line 620, in make_tool
  File "/g/korbel2/weber/miniconda3/envs/toil/lib/python3.10/site-packages/toil/cwl/cwltoil.py", line 989, in toil_make_tool
    return ToilCommandLineTool(toolpath_object, loadingContext)
TypeError: interpreted classes cannot inherit from compiled
```

Versions used:

* cwltool                   3.1.20221201130942 py310hb099472_1    conda-forge
* schema-salad              8.4.20230213094415 py310h1fa729e_0    conda-forge
* toil                      5.9.2              pyhdfd78af_0    bioconda

@mr-c

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1296)
┆Issue Number: TOIL-1296

**Comment by adamnovak** [comment]
The error doesn't say it, but this constraint and this error for breaking it is introduced by `mypyc`, which I think is used somewhere inside `schema-salad`. Hopefully @mr-c can figure out why it is doing this.

**Comment by mr-c** [comment]
Yep, I'm in person with @weber8thomas and I know the problem and the fix . A reminder for me to get back to this later. We have a workaround (install using pip, not conda)

**Comment by mr-c** [comment]
https://github.com/common-workflow-language/cwltool/commit/c5e2912863449934bd278c6a81dfc4aa27967221 addresses this issue and is part of the https://pypi.org/project/cwltool/3.1.20230302145532/ release but will take a bit for bioconda to build that version, which should fix this for users of `toil-cwl-runner` from conda.

I'll start releasing binary wheels for `cwltool` (compiled with `mypyc`) to PyPI, so future CI runs of Toil will catch any regressions. The cwltool fix includes a test, so fingers crossed for minimal/no regressions.
