### ISSUE TITLE
File to String conversion in toil-wdl-runner

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4516]
Currently, when toil-wdl-runner converts a File to a String, it returns it's own representation of the file rather than a filepath. The WDL [1.0](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#type-coercion) and [1.1](https://github.com/openwdl/wdl/edit/main/versions/1.1/SPEC.md#type-coercion) spec don't say anything regarding how an engine should convert a File to a String, but it may be better to use the filepath instead.

It also looks like the behavior is different when the file is defined in the workflow.
```wdl
workflow testWorkflow {
    input {
    }
    File f = "/home/heaucques/Documents/toil-examples/test.wdl"
    output {
        String out = f
    }
}
```
will output:
```
{"testWorkflow.out": "/home/heaucques/Documents/toil-examples/test.wdl"}
```
compared to when the file is defined in the JSON:
```
{"testWorkflow.out": "toilfile:225%3A0%3Afiles%2Fno-job%2Ffile-cad70245a27846c9abda3140567f8011%2Ftest.wdl/test.wdl"}
```
which is presumably because the file is not imported.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1361)
┆Issue Number: TOIL-1361

**Comment by adamnovak** [comment]
It looks like there might actually be two issues here:

* We aren't importing the file referenced directly by path in the workflow. I'm not sure if WDL actually allows the workflow to do this, but if we don't complain about it we should turn the file into an actual imported file.
* We aren't putting imported files at a sensible place and giving their paths when going from a file back to a string. In the output section of a workflow we might want to treat files-converted-to-strings as if they were actual output files. If this happens inside a task we probably need to drop the files somewhere on the node's filesystem and treat them as container inputs.
