### ISSUE TITLE
CI lint fails due to updated stub

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4534]
Mypy is complaining about a missing attribute:
```
src/toil/lib/aws/iam.py:10:1: error: Module "mypy_boto3_iam.type_defs" has no
attribute "AttachedPolicyOutputTypeDef"  [attr-defined]
    from mypy_boto3_iam.type_defs import AttachedPolicyOutputTypeDef
    ^
```
This is likely because an updated version of `mypy_boto3_iam` removed it.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1371)
┆Issue Number: TOIL-1371

**Comment by adamnovak** [comment]
I think I have a fix for this that I am glomming onto my PR.

**Comment by adamnovak** [comment]
This should be fixed in https://github.com/DataBiosphere/toil/pull/4523 now.
