### ISSUE TITLE
docker file not found error on slurm cluster

### ISSUE THREAD

**Issue by philge** [DataBiosphere/toil#4560]
Hi,

I am running Cactus tool on a slurm cluster (https://github.com/ComparativeGenomicsToolkit/cactus). Cactus uses Toil. I am getting the attached error. I have docker installed and docker is in PATH. It seems docker command is not in the PATH when Toil runs. Can you please help me to fix the issue.
[cactus_error.txt](https://github.com/DataBiosphere/toil/files/12328611/cactus_error.txt)

Thanks
Philge

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1382)
┆Issue Number: TOIL-1382

**Comment by DailyDreaming** [comment]
@philge I'm not sure that this is a Toil issue.  I'll reply in the [cactus issue thread](https://github.com/ComparativeGenomicsToolkit/cactus/issues/1129).
