### ISSUE TITLE
Feedback on CWL v1.2.1 release requested

### ISSUE THREAD

**Issue by acoleman2000** [DataBiosphere/toil#4564]
Hello,

We are asking for feedback for the CWL v1.2.1 release.

Changelogs for the release can be found below:

Workflow / ExpressionTool / Operation:
https://deploy-preview-115--cwl-v1-2-dev.netlify.app/workflow#Changelog_for_v1.2.1

CommandLineTool:
https://deploy-preview-115--cwl-v1-2-dev.netlify.app/commandlinetool#Changelog_for_v1.2.1

You can provide your feedback, as well as see a full summary of changes here: https://github.com/common-workflow-language/cwl-v1.2/pull/115.

We ask that all feedback be provided by August 31st.

Thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1384)
┆Issue Number: TOIL-1384

**Comment by DailyDreaming** [comment]
@acoleman2000 Will take a look, thanks.
