### ISSUE TITLE
Use fractions instead of floats for core requirements

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#457]
In SingleMachine, for example, three jobs with .2 and four with .1 will not fit into one core:

```
>>> .1 + .2 + .1 + .2 + .1 + .2 + .1 > 1.0
True
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-314)
┆Issue Number: TOIL-314

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
