### ISSUE TITLE
Mypy breaks with new boto update

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4576]
I think an update to mypy-boto3-iam broke mypy. It looks like certain functions now return/expect a new type `PolicyDocumentDictTypeDef`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1388)
┆Issue Number: TOIL-1388

**Comment by adamnovak** [comment]
This was fixed in #4577.
