### ISSUE TITLE
Removing the Parasol batch system has made Toil fail when parsing arguments if you have run it before

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4689]
If you ran Toil between when config files were added in #4569 and when the Parasol batch system was removed in #4678, it will now crash when parsing arguments with a message like:

```
wdltoil.py: error: unrecognized arguments: --parasol_command=parasol --parasol_max_batches=1000 --mesosName=toil
```

I'm not sure how Mesos got in there.

I think #4666 will solve this going forward, as it will make us make config files with everything commented out by default, to avoid this kind of problem.

So maybe #4666 will count as fixing this? Or maybe we want some kind of cleanup logic to handle old fully-populated config files and not fail?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1450)
┆Issue Number: TOIL-1450

**Comment by adamnovak** [comment]
The user-level fix is to `rm ~/.toil/default.yaml`.

**Comment by DailyDreaming** [comment]
This should be resolved.
