### ISSUE TITLE
toil-wdl-runner does not strip leading whitespace in an evaluated command template

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4695]
toil-wdl-runner returns IndentationError if common leading whitespace exists within a code block like so:
```wdl
version 1.1

workflow wf {
    input {}
    call t {}
    output {}
}

task t {
    input {}
    command <<<
    python <<CODE
    print("hello")  # indentation error
    CODE
    >>>
    output {}
    runtime {
        docker: "python"
    }
}
```
But the workflow will run if all leading indentation after the `<<CODE` specifier is removed:
```wdl
...
    command <<<
    python <<CODE
print("hello")
CODE
    >>>
...
```
I think the spec mentions a [similar case](https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#stripping-leading-whitespace). I'm not sure if that workflow is runnable or not as miniwdl doesn't seem to run it, but this seems to be the issue.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1453)
┆Issue Number: TOIL-1453

**Comment by adamnovak** [comment]
@stxue1 Can you open a bug against MiniWDL for this? Maybe Mike Lin will helpfully fix it for us.

**Comment by stxue1** [comment]
I think I phrased the miniwdl part wrong. Miniwdl is able to run the example I wrote, but not the example in the spec, which I don't think is a working example. I think the issue might be on Toil's side, but it could be possible for miniwdl to automatically strip whitespace when the command string is passed off to miniwdl.
