### ISSUE TITLE
Eliminate usage of threading.Event for thread termination

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#474]
The new caching code uses threading.Event to request Thread termination. There are two problems: One is that threading.Event is overkill unless you intend to block until the event is signalled. Thanks to GIL, a simple boolean flag suffices. Second problem is that threads raise a runtime error in order to bail out. This causes every thread to print a stacktrace which is noise distracting from the root cause. A simple `return` would be better.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-315)
┆Issue Number: TOIL-315

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

This will be fixed by #2691.

**Comment by DailyDreaming** [comment]
Fixed by #2691.
