### ISSUE TITLE
Removing whitespace in WDL doesn't work for overindented code blocks

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#4983]
The spec seems to want runners to support stripping whitespace from overindented python code blocks:
https://github.com/openwdl/wdl/blob/9c0b9cf4586508a9e6260cc5c5e562e21f625aac/SPEC.md?plain=1#L3590-L3624

The current issue is the amount of whitespace to remove is done at the first seen line:
https://github.com/DataBiosphere/toil/blob/4cb5bb3871ac21a9793f638b83775926ed94a226/src/toil/wdl/wdltoil.py#L241

In the spec example's case, it finds 2 spaces at `python <<CODE` but needs to remove 4 at `with open("~{infile}") as fp:`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1596)
┆Issue Number: TOIL-1596

**Comment by adamnovak** [comment]
Does Cromwell handle this somehow?

I would think the spec is wrong here; I don't think that that shell command with just its internal indentation can work. You might *want* to indent inside the heredoc, but if Bash doesn't make allowances for it, and Python doesn't let you indent the entire script, I don't know why it makes sense for the WDL interpreter to provide special logic to give you this feature.

**Comment by adamnovak** [comment]
The spec doesn't actually say that the given example *works*, just that it produces a particular Bash script:
```sh
python <<CODE
  with open("/path/to/file") as fp:
    for line in fp:
      if not line.startswith('#'):
        print(line.strip())
CODE
```
That Bash script runs Python with an input where the first line starts with two spaces. Python then raises an error.

**Comment by adamnovak** [comment]
I've reported a bug on the spec: https://github.com/openwdl/wdl/issues/668

**Comment by adamnovak** [comment]
The WDL spec is going to change with https://github.com/openwdl/wdl/pull/669 to no longer suggest over-indenting heredocs in its examples, so I am going to close this.
