### ISSUE TITLE
Processes hanging further down toil chain

### ISSUE THREAD

**Issue by scrowley-Datirium** [DataBiosphere/toil#5072]
Running into an issue where a workflow will get hung running the same software. 

# Background

 - toil-cwl-runner used to run cwl (with a single step)
 - that step is run on a docker image
 - that docker image is based off r-base, and uses a bash script to do preprocessing and stage data for hopach: [link to docker file](https://github.com/datirium/workflows/blob/master/dockerfiles/scidap-genelists-Dockerfile)
 - that bash script then calls an R script with processed data: [link to bash](https://github.com/datirium/workflows/blob/master/dockerfiles/scripts/run_genelists_rnaseq.sh#L215)
 - that r script will run up to the hopach call before getting hung indefinitely: [link to R](https://github.com/datirium/workflows/blob/master/dockerfiles/scripts/run_hopach_clustering.R#L29)

adding logs around all aspects of the bash/r script confirmed that the hopach call is where the process is getting hung.

Toil is being called like so:
```
 toil-cwl-runner \
    --logDebug \
    --stats \
    --bypass-file-store \
    --batchSystem single_machine \
    --retryCount 0 \
    --disableCaching \
    --defaultMemory 68719476736\
    --defaultCores 8 \
    --jobStore "/example/jobstore/dir" \
    --writeLogs "/example/log/dir" \
    --outdir "/example/out/dir" "/path/to/workflow.cwl" "/path/to/job.json"  > "example/out/dir/results.json"
```

# Why this is a toil problem

The use of [hopach](https://bioconductor.org/packages/release/bioc/html/hopach.html) causes the process to hang indefinitely. 
While that may imply that this is an issue for hopach, we've been able to run the workflow successfully in numerous ways (with the same data), where the only failures happen when the workflow is run through toil.

We've successfully run the workflow (with the same input data) by:
 - starting docker container and running just r script (with data processed by bash script, saved as tmp output by toil)
 - starting docker container and running entire bash script 
 - running entire cwl with cwltool

# More info on example runs
[docker image used](https://hub.docker.com/layers/robertplayer/scidap-genelists/dev/images/sha256-3ad61fbe1564867f03e3ba5142b21f31ef271cd96daf82656f646c1e8ddd1435?context=explore)

From the machine in question, this is how toil starts docker and that step
```bash
docker \
    run \
    -i \
    --mount=type=bind,source=/path/to/workdir,target=/sSEKzd \
    --mount=type=bind,source=/path/to/tmp/dir,target=/tmp \
    --mount=type=bind,source=/path/to/inputs/input1.tsv,target=/var/lib/cwl/RANDOM_STR1/input1.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input2.tsv,target=/var/lib/cwl/RANDOM_STR2/input2.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input3.tsv,target=/var/lib/cwl/RANDOM_STR3/input3.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input4.tsv,target=/var/lib/cwl/RANDOM_STR4/input4.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input5.tsv,target=/var/lib/cwl/RANDOM_STR5/input5.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input6.tsv,target=/var/lib/cwl/RANDOM_STR6/input6.tsv,readonly \
    --workdir=/sSEKzd \
    --read-only=true \
    --log-driver=none \
    --user=1001:1001 \
    --rm \
    --cidfile=/path/to/outdir/20240821123938-335117.cid \
    --env=TMPDIR=/tmp \
    --env=HOME=/sSEKzd \
    robertplayer/scidap-genelists:dev \
    /bin/sh \
    -c \
    run_genelists_rnaseq.sh -g /var/lib/cwl/RANDOM_STR1/input1.tsv,/var/lib/cwl/RANDOM_STR2/input2.tsv,/var/lib/cwl/RANDOM_STR3/input3.tsv,/var/lib/cwl/RANDOM_STR4/input4.tsv -b /var/lib/cwl/RANDOM_STR5/input5.tsv -c /var/lib/cwl/RANDOM_STR6/input6.tsv -a 'filtered deseq fdr01 l2fc2' -e 'SRR7475893 rep2,SRR7475894 rep1,SRR7475895 rep2,SRR7475892 rep1' -t 1 > /path/to/outdir/genelists_stdout.log 2> /path/to/outdir/genelists_stderr.log
```

## Test runs

This is how we started docker and ran the script for that step:
```
# the working dir here has 2 folders
# "manual_test": which is empty and considered the "outdir"
# "data_files": which has a copy of the inputs used
tmp_working_dir_var="/path/to/working/dir"
docker run -v $tmp_working_dir_var:/data/ --rm -ti robertplayer/scidap-genelists:dev /bin/bash
cd /data/manual_test
# param names here correlates to the flag in our script
t="1"
a="deseq genelist"
b="/data/data_files/deseq_report_features.tsv"
c="/data/data_files/deseq_report_filtered.tsv"
e="naive rep1,naive rep2,act5h rep1,act5h rep2"
g="/data/data_files/naive_rep1.genes.tsv,/data/data_files/naive_rep2.genes.tsv,/data/data_files/act5h_rep1.genes.tsv,/data/data_files/act5h_rep2.genes.tsv"
bash /usr/local/bin/run_genelists_rnaseq.sh -t $t -a "$a" -b $b -c $c -e "$e" -g $g 1> log.stdout 2> log.stderr
```

Which completed successfully. We also ran just the rscript by mounting the tmpdirs that toil created (during its failed run) and using the inputs created by our bash script before R was hung. That container/run also completed successfully.

Running with cwltool also completed successfully:
```
conda activate cwl #env with cwltool
cwl-runner --leave-tmpdir --tmpdir-prefix "cwl-tmpdir" /path/to/workflow.cwl /path/to/job.json
# where job.json references the same data that was manually mounted before
```

---

Not sure as to what might be causing this, but short of adding logs and manually building hopach, we're at loss as to how to troubleshoot further.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1636)
┆Issue Number: TOIL-1636

**Comment by adamnovak** [comment]
Are you able to replicate the hang by running the Docker command that Toil is generating (maybe with the input file paths changed)? Or is there something about having Toil itself in the loop as the parent process of that Docker command (like maybe forgetting to read from a stream) that is necessary to get the hang? If you weren't using `--bypass-file-store` you could fetch the input files out of the job store with [toil debug-job](https://toil.readthedocs.io/en/latest/running/debugging.html#fetching-job-inputs). But since you are I think they might just be at the paths actually mounted into the Docker command after the workflow fails, so the command might run unmodified.

I noticed that the Toil Docker command is passing `--user=1001:1001` to run the container under a particular user ID, as well as `--read-only=true` to prevent writing to the base container image, while you don't provide those options when you run the Docker container successfully yourself. It is possible that the `hopatch` workload hangs under these conditions, and that `cwltool` isn't set up to run it this way.

It also looks like your Bash script is getting slightly different arguments under Toil (like `-a 'filtered deseq fdr01 l2fc2'`) than when you run it yourself (where you look like you end up with `-a 'deseq genelist'`). Though for the case where you fished out the Rscript process's inputs and ran it alone presumably you ended up matching exactly what it saw under Toil when it hung?

For CWL workflows, Toil calls into `cwltool` code to produce the Docker command and run the container. How did you capture the `docker run` command that Toil is using, and can the same process be used on `cwltool` to capture the Docker command that it runs which apparently works? If they differ at all, maybe that is the source of the problem?

I looked at `hopatch`, and it doesn't seem to do anything interesting like try and spin up a bunch of OMP threads or turn around and install more R packages or anything.

**Comment by scrowley-Datirium** [comment]
responding to each paragraph:

1.
when running docker as toil does, the docker run command is:
```
docker \
    run \
    -i \
    --mount=type=bind,source=/path/to/WORKDIR,target=/Orsrwl \
    --mount=type=bind,source=/path/to/TMPDIR,target=/tmp \
    --mount=type=bind,source=/path/to/inputs/input1.tsv,target=/var/lib/cwl/RANDOM_STR1/input1.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input2.tsv,target=/var/lib/cwl/RANDOM_STR2/input2.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input3.tsv,target=/var/lib/cwl/RANDOM_STR3/input3.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input4.tsv,target=/var/lib/cwl/RANDOM_STR4/input4.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input5.tsv,target=/var/lib/cwl/RANDOM_STR5/input5.tsv,readonly \
    --mount=type=bind,source=/path/to/inputs/input6.tsv,target=/var/lib/cwl/RANDOM_STR6/input6.tsv,readonly \
    --workdir=/Orsrwl \
    --read-only=true \
    --log-driver=none \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/Orsrwl \
    robertplayer/scidap-genelists:dev \
    /bin/sh \
    -c "run_genelists_rnaseq.sh -g /var/lib/cwl/RANDOM_STR1/input1.tsv,/var/lib/cwl/RANDOM_STR2/input2.tsv,/var/lib/cwl/RANDOM_STR3/input3.tsv,/var/lib/cwl/RANDOM_STR4/input4.tsv -b /var/lib/cwl/RANDOM_STR5/input5.tsv -c /var/lib/cwl/RANDOM_STR6/input6.tsv -a 'filtered deseq fdr01 l2fc2' -e 'SRR7475893 rep2,SRR7475894 rep1,SRR7475895 rep2,SRR7475892 rep1' -t 1" > /path/to/WORKDIR/genelists_stdout.log 2> /path/to/WORKDIR/genelists_stderr.log
```

This run is still currently processing, but it seems to also be hung. the hopach script has been running for 20 minutes, and there are no logs from its ```verbose``` outputs.


The ```--bypass-file-store``` flag can be removed from our toil command if that would make debugging easier, but using original file locations isn't a burden to us, especially since the inputs provided for this workflow are read-only. 
The flag is included by default because our toil run commands are built based on the system it runs on, and the default system our command builder was designed for is an ```lsf``` cluster with a shared filesystem. However, this machine is only running toil in ```single_machine``` mode.

If removing that flag would allow us to utilize ```toil job-debug``` to better understand whats happening, we can do so. But we currently have the jobstore and tmp files preserved on failed runs.


Would we be able to use job-debug with the preserved jobstore, but without the filestore? Within the jobstore dir are 3 folders, ```files, jobs, stats```, and within jobs is ```kind-CWLJob,  kind-CWLWorkflow,  kind-ResolveIndirect``` directories, each with ```instance-RAND_STR``` folders.

Is the ```jobId``` we give to ```toil job-debug``` based on the instance name that correlates to the job for that step? 

---

2.
The mounted inputs are read-only, but are only used by the initial bash script for preprocessing. The bash script generates the single file used as input by ```hopach```, and since that file is created and written to by the bash script, there shouldn't be any read/write permission errors. 

---

3.
The manual ```docker run``` command we sent does include a different value for the ```-a``` param, but we had run it with the same as well. This workflows' maintainer assures me that different values for the ```-a``` param wouldn't have any bearing on the hanging of the process, but invalid values would cause the bash to fail before getting to the ```hopach``` call.
Runs with toil using different values for ```-a``` were also attempted, but ended in the same hung process.

---

4.
The docker run command was capture via toil logs. running ```ls``` on the directory ```${--writeLogs}/logs``` gives these files
``` 
CWLWorkflow_workflow.json_000.log  
failed_CWLJob_workflow.json.data_integration.87c38390--8ca2--48c8--8ddd--a876a231eec6_000.log
```

Reading the failed file (with name correlating to CWL step), the final lines are the docker run command (until we kill the container after a couple of hours due to hung process)

We know which process is hung (without extra logs) from doing ```docker top``` on the container
```

UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
# main bash script
**user              PID             PPID             C                  DATE               ?                   22:07:10            /usr/lib/R/bin/exec/R --no-echo --no-restore --file=/usr/local/bin/run_hopach_clustering.R --args genelist_0-cluster_data.tmp VST**
```

---

5.
In regards to hopach, we would agree that it isn't doing anything extra intensive, and all R packages used would have been preinstalled on the docker image. We included the ```verbose=TRUE``` param for hopach, and in our test runs were able to get relevant logs. But when running from toil, we were unable to get any logs from hopach, even the first log that outputs "Searcing for main clusters..." before any real computations has started

**Comment by scrowley-Datirium** [comment]
This can be closed. 

We were running toil version 6.1.0
Upgrading to 7.0.0 didnt fix this issue, but updating our docker images base to use [r-ubuntu](https://hub.docker.com/r/rocker/r-ubuntu) instead of [r-base](https://hub.docker.com/_/r-base) seems to have fixed it

**Comment by scrowley-Datirium** [comment]
We were running toil version 6.1.0
Upgrading to 7.0.0 didnt fix this issue, but updating our docker images base to use [r-ubuntu](https://hub.docker.com/r/rocker/r-ubuntu) instead of [r-base](https://hub.docker.com/_/r-base) seems to have fixed it
