### ISSUE TITLE
toil partially incompatible with Python 3.13 due to removal of "pipes" from the standard library

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#5119]
https://github.com/DataBiosphere/toil/blob/9aeca838cc4ae313ee89fcfa7405740afdbffd0a/src/toil/provisioners/node.py#L282

Maybe try [`shlex.quote`](https://docs.python.org/3/library/shlex.html#shlex.quote) or switching to use [`subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run) at

https://github.com/DataBiosphere/toil/blob/9aeca838cc4ae313ee89fcfa7405740afdbffd0a/src/toil/provisioners/node.py#L285

xref https://bugs.debian.org/1084681

> Dear maintainer(s),
> 
> Python 3.13 removes a large amount of so called 'dead battery' libraries  from the standard library. As such, code that imports these libraries will no longer work in Python 3.13, which is the targeted version for [Debian]Trixie.
> 
> The following removed libraries were found in this package:
> 
> pipes: src/toil/provisioners/node.py:16
> 
> See this link for more details: 
> https://peps.python.org/pep-0594/#deprecated-modules
> 
> Cheers,

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1656)
┆Issue Number: TOIL-1656

**Comment by stxue1** [comment]
I think I remember replacing another usage of `pipes.quote` with `shlex.quote` as well. IIRC they are (or should be) interexchangeable.
