### ISSUE TITLE
Add FTP support to `AbstractJobStore._get_size`

### ISSUE THREAD

**Issue by stxue1** [DataBiosphere/toil#5134]
`_get_size` currently doesn't support FTP as it requires special [commands and wizardry](https://stackoverflow.com/questions/22090001/get-folder-size-using-ftplib/22093848#22093848).

This will also need to support extracting username/password from the URL and/or supporting environmental variables to override the username/password

This will allow FTP files to work with #5133

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1660)
┆Issue Number: TOIL-1660

**Comment by mr-c** [comment]
I implemented the equivalent of this in https://github.com/ohsu-comp-bio/cwl-tes/blob/03f0096f9fae8acd527687d3460a726e09190c3a/cwl_tes/ftp.py#L231
Feel free to steal!
