### ISSUE TITLE
Fix failing CWLWorkflowTest

### ISSUE THREAD

**Issue by gmloose** [DataBiosphere/toil#5150]
The test `CWLWorkflowTest.test_slurm_node_memory` is failing when Slurm doesn't enforce a memory limit. Reason is that it then returns the string "unlimited" instead of a string containing an integer value.

The fix is easy. I'll create a pull request.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1667)
┆Issue Number: TOIL-1667

**Comment by gmloose** [comment]
Fixed by https://github.com/DataBiosphere/toil/pull/5151

**Comment by mr-c** [comment]
fixed in https://github.com/DataBiosphere/toil/pull/5151
