### ISSUE TITLE
Python3.12 SyntaxWarning

### ISSUE THREAD

**Issue by tillea** [DataBiosphere/toil#5186]
Hi,
there is a [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087116) about a syntax warning  which I've fixed in a [patch](https://salsa.debian.org/med-team/toil/-/blob/master/debian/patches/python3.12-syntax.patch?ref_type=heads) in Debian's development platform.  Feel free to integrate this in your next release.
Kind regards, Andreas.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1692)
┆Issue Number: TOIL-1692

**Comment by mr-c** [comment]
Thank you @tillea ; looks like this got fixed already: https://github.com/DataBiosphere/toil/blob/8e0d84ae82b24c7e6244baae5ff5d6d5fb4377e8/src/toil/wdl/wdltoil.py#L5472-L5474
