### ISSUE TITLE
Add Sphinx doctest support to test run documentation examples

### ISSUE THREAD

**Issue by benedictpaten** [DataBiosphere/toil#525]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-318)
┆Issue Number: TOIL-318

**Comment by benedictpaten** [comment]
Oops, wish we could get this going. Not going to insist this is part of the docs milestone though.

**Comment by DailyDreaming** [comment]
Closed by https://github.com/DataBiosphere/toil/pull/2426.
