### ISSUE TITLE
Check that Toil version matches between leader, executor and worker

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#538]
Mesos scheduler should pass current version along in task structure. Mesos executor should compare agains own version and complain. Same with leader and worker.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-319)
┆Issue Number: TOIL-319

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still a problem.
