### ISSUE TITLE
Option handling is messy

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#560]
Inconsistently formatted help strings, convoluted language, job store parsing and validation is spread over setOptions and loadJobStore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-252)
┆Issue Number: TOIL-252

**Comment by cricketsloan** [comment]
➤ Hannes Schmidt commented:

Can you please not use me as the crash test dummy here? My inbox is full enough already. ;-)
