### ISSUE TITLE
Prioritize big jobs in single machine

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#563]
Single machine batch system is artificially enforcing FIFO semantics on the jobs submitted to it.

Consider a priority queue that orders jobs based on the jobs' requirements (either a weighted sum or just the number of cores) such that we can prioritize big jobs reducing the chance of small jobs preventing big jobs from running, leaving cores underutilized.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-320)
┆Issue Number: TOIL-320

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.
