### ISSUE TITLE
Multipart copy should compute MD5 checksums as file parts are uploaded

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#665]
As it stands the AWS multipart copy function does not compute an md5 hash. Amazon creates an etag which is computed by taking the hex digest of the byte digest of each file part concatenated in order of upload. The final etag is also appended with a dash and the number of parts uploaded. 

A thread with a corresponding queue (of max size 1-3) should run along side the main thread which conducts the uploads of the file. This way a checking mechanism can be implemented in the function without a second pass over the uploaded file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-324)
┆Issue Number: TOIL-324

**Comment by JakeNarkizian** [comment]
related to #655

**Comment by hannes-ucsc** [comment]
s3am needs this too.

**Comment by hannes-ucsc** [comment]
One caveat: For files encrypted with SSE or SSE-C, the etag uses the MD5's of the encrypted parts, not their clear text. On the client, you don't know the encrypted part, only the clear text.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.

**Comment by adamnovak** [comment]
We have a bunch of checksumming stuff in the AWS job store now, though I'm not sure if any of it comes into play when doing an import.
