### ISSUE TITLE
Investigate Mesos' dynamic reservation API to model disk, left-overs and cache

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#681]
In 0.25.0, Mesos introduced _dynamic reservations_ (http://mesos.apache.org/documentation/latest/reservation/). We could use it to handle the disk left-overs problem @arkal identified. 

Instead of using Mesos' built-in `disk` resource, we would introduce a custom resource, say `toil-disk`. It would be initialized to the amount of free disk when mesos-slave is started up. But when left-overs are detected during recovery from unsuccessful cache eviction, the `toil-disk` resource would be adjusted using the dynamic reservation API. This would require the introduction of a new, static batch system API method called `adjustFreeDisk(newTotal)` which initially only the Mesos batch system would implement.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-327)
┆Issue Number: TOIL-327

**Comment by arkal** [comment]
I'm working on this but I'm hitting a dead end right now.  Every 30s the executor conducts a statvfs on workDir and does a calculation to say exactly how much of the disk should be used for Toil. If the value has changed over the last 30s, the executor reports this to master. When the master receives an offer from the agent running that executor, it accepts the offer with a "reserve" operation to set the disk value to the updated value. However this is not working for some reason :( I'll show you the code tomorrow and hope you have some insight into this.

I think an option would be to specify roles='toil' in the invocation of mesos master and --default-roles='toil' in the agents. I might be wrong. I'm waiting on  replies from the mesos mailing list.

**Comment by hannes-ucsc** [comment]
@arkal talked about this and will be using an alternative way to make reservations (via HTTP REST request).

**Comment by arkal** [comment]
This will also fix the issue on singlemachine

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
