### ISSUE TITLE
Eliminate codependent options like --mesos and --mesosMaster

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#685]
Users typically need to provide `--mesosMaster` when they specify `--mesos`. If they forget to do so, they currently get a cryptic error message. We should improve the error message but we should also make the codependence more obvious in the CLI. We could use the same mechanism for batch systems that we use for job stores. IOW, it could be `--batchSystem "mesos:spark-master:5050"`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-328)
┆Issue Number: TOIL-328

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
