### ISSUE TITLE
Add ability to schedule a full node

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#717]
On Mesos this could be done using a synthetic resource like node=1. Every job will consume that  resource when accepting an offer. Single-node jobs, i.e. jobs with  cores=INFINITY requirement will only accept offers with node=1.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-329)
┆Issue Number: TOIL-329

**Comment by hannes-ucsc** [comment]
… or a fraction of a full node.

**Comment by hannes-ucsc** [comment]
@arkal and I brainstormed this a bit. 

cores=(min, max) with type(min) == int and isinstance(max, int, callable[int->int]) with callable argument being either number of nodes on the currently offered slave (me) or the number of nodes on the biggest node there is in the cluster (@arkal).

**Comment by hannes-ucsc** [comment]
BSs that don't support this mechanism will fallback to using min.

**Comment by arkal** [comment]
`s/nodes/cores/` ?

**Comment by hannes-ucsc** [comment]
Yes. Fixed. THX.

**Comment by hannes-ucsc** [comment]
I have another idea how we could implement this above the batch system layer. There could be cooperative mini-scheduler in worker.py based on a IPC semaphore. The batch system would schedule multiple jobs on a node as usual, but the semaphore enforces the nodes requirement, serializing these tasks as necessary.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
