### ISSUE TITLE
Add support for importing/exporting encrypted files

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#720]
An encrypted jobstore can import unencrypted files which will be encrypted on import. However A file that is already encrypted cannot be imported into an encrypted jobstore.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-330)
┆Issue Number: TOIL-330

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
