### ISSUE TITLE
Import/export job store tests sporadically fail against Azure

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#787]
Jake, can you take a look at this? It's totally possible that there is nothing we can do about downtimes or unreliability on the Azure side. I just want you to look at the stack traces and think about if there is something we can do about them,

http://jenkins.cgcloud.info/job/toil-pull-requests/1081/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-331)
┆Issue Number: TOIL-331

**Comment by cket** [comment]
Another case, caused by AzureMissingResourceHttpError: 
http://jenkins.cgcloud.info/job/toil-pull-requests/1191/

**Comment by arkal** [comment]
Another AzureMissingResourceError

http://jenkins.cgcloud.info/job/toil-pull-requests/1210/testReport/src.toil.test.src.jobCacheTest/AzureJobStoreCacheTest/testCacheEviction/

**Comment by arkal** [comment]
FYI, my issue was resolved by not using the same jobstore name for the tests even though the jobstore is cleaned after every test.
