### ISSUE TITLE
Refactor `restart` to `resume` in code and CLI

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#793]
As it stands Toil.restart() (pending on PR #769), toilRestart, and the --restart command line flag are semantically incorrect. A toil workflow is **never** restarted, it is **resumed** from the point of failure. These names ought to reflect this.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-259)
┆Issue Number: TOIL-259

**Comment by jvivian** [comment]
+1

**Comment by DailyDreaming** [comment]
I agree it's more accurate, but it's a major breaking change at this point.  Closing this.

**Comment by mr-c** [comment]
You can keep the old command line options and methods, but just hide them, so nothing  breaks.
