### ISSUE TITLE
Add batch system for Apache YARN

### ISSUE THREAD

**Issue by fnothaft** [DataBiosphere/toil#796]
[YARN](https://hadoop.apache.org/docs/r2.7.1/hadoop-yarn/hadoop-yarn-site/YARN.html) is the resource manager packaged with Hadoop 2.x. We use it on our internal cluster at Berkeley, as it is commonly installed by most Hadoop distros (e.g., CDH, HDP, etc).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-334)
┆Issue Number: TOIL-334

**Comment by DailyDreaming** [comment]
Stale, reopen if still relevant.
