### ISSUE TITLE
Parasol's shutdown() attempts to remove all running jobs on the cluster

### ISSUE THREAD

**Issue by joelarmstrong** [DataBiosphere/toil#809]
Even those started from other users or in different pipelines. This triggers when the shutdown method is called.

Parasol has an ACL system so it's not a huge deal, but if you are running multiple pipelines this causes problems.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-335)
┆Issue Number: TOIL-335

**Comment by adamnovak** [comment]
I'm going to close this out as not planned, unless we start using Parasol again.
