### ISSUE TITLE
Document import/export trade-offs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#875]
Mention that 
- per-sample files should be imported on a worker
- it may be more efficient to not import large files that are only used once, but rather download them directly
- it may matter whether an external file in S3 is in the same region as the job store

Point out that toil-scripts/lib has a common functionality for downloading URLs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-343)
┆Issue Number: TOIL-343

**Comment by hannes-ucsc** [comment]
Punting for next sprint.

**Comment by hannes-ucsc** [comment]
Won't make it into 3.3.0.

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
