### ISSUE TITLE
Import/Export tests don't use multithreaded upload for S3

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#883]
The import export tests import from every job store storage mechanism to every supported job store. For each import pair files of 5 sizes > 0 are imported. 

Let S be the set of supported job stores, there are `2^|S|` pairs `1/4` of which import from some bucket in S3 5 times. Thus there are 20 uploads of random bytes to S3 buckets.

 In the interest of cutting down build time these should be uploaded with a multithreaded approach.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-344)
┆Issue Number: TOIL-344

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
