### ISSUE TITLE
`Cannot retry failed request` when creating Google jobstore

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#913]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/162/testReport/junit/src.toil.test.jobStores.jobStoreTest/GoogleJobStoreTest/test_importExportFile__size_partsize__otherJobStore_azurejobstoretest/

Boto understandably fails to retry a request to upload an object from a stream (a file object that can't be seeked within).

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-266)
┆Issue Number: TOIL-266

**Comment by hannes-ucsc** [comment]
In light of this we may have to rethink whether we support streams at all. If we decide to do that, we need to change all of the streaming job store methods to use multipart requests with one full part buffered from the stream.

**Comment by DailyDreaming** [comment]
Link no longer works, I’m closing this.
