### ISSUE TITLE
`Read timed out` in AzureJobStoreTest

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#917]
http://jenkins.cgcloud.info/job/toil-pull-requests/1383/testReport/src.toil.test.jobStores.jobStoreTest/AzureJobStoreTest/test_importExportFile__size_onemib__otherJobStore_azurejobstoretest/

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-265)
┆Issue Number: TOIL-265

**Comment by cricketsloan** [comment]
➤ Lon commented:

Link no longer works and as there is no other information, I’m closing this.
