### ISSUE TITLE
Assertion error in GoogleJobStoreTest

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#920]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/165/testReport/junit/src.toil.test.jobStores.jobStoreTest/GoogleJobStoreTest/test_importExportFile__size_partsizeminusone__otherJobStore_awsjobstoretest/

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-264)
┆Issue Number: TOIL-264

**Comment by cricketsloan** [comment]
➤ Lon commented:

Link no longer works and as there is no other information, I’m closing this.

**Comment by DailyDreaming** [comment]
Link no longer works and as there is no other information, I’m closing this.
