### ISSUE TITLE
`IOError: close() called` in GoogleJobStoreTest

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#945]
http://jenkins.cgcloud.info/job/toil-pull-requests/1403/testReport/junit/src.toil.test.jobStores.jobStoreTest/GoogleJobStoreTest/test_importExportFile__size_partsize__otherJobStore_awsjobstoretest/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-349)
┆Issue Number: TOIL-349

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

All the information on this error has died with Jenkins.
