### ISSUE TITLE
Test parallelization garbles console output on Jenkins builds

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#951]
Due to test parallelization, the build's console is written to by multiple processes concurrently and therefore has to be taken with a grain of salt. In particular, it could be that the console says

fooTest: FAILED
barTest: PASS

but that in reality fooTest passed and barTest failed.

The console output that is captured and then listed per test will be correct and can be trusted. Only the overall console output will be bad.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-260)
┆Issue Number: TOIL-260

**Comment by cricketsloan** [comment]
➤ Lon commented:

Closing this as this is not currently an issue.
